(()=>{
const $=(s,el=document)=>el.querySelector(s);
const $$=(s,el=document)=>[...el.querySelectorAll(s)];
const ic=(n,st='')=>`<svg class="i" ${st?`style="${st}"`:''}><use href="#i-${n}"/></svg>`;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function ls(k,v){try{if(v===undefined){const x=localStorage.getItem('sangkarloka.'+k);return x?JSON.parse(x):null}localStorage.setItem('sangkarloka.'+k,JSON.stringify(v))}catch(e){return null}}
const WA='62895403828002';
const IG='sangkarloka_';
const PHOTO=k=>k?`photos/${k}.jpg`:null;
const ph=(key,fallback,alt='',pos='')=>`<div class="ph">${fallback||''}${key?`<img src="${PHOTO(key)}" alt="${esc(alt)}" loading="lazy" ${pos?`style="object-position:${pos}"`:''} onerror="this.remove()">`:''}</div>`;

/* ---------- i18n ---------- */
const S={lang:ls('lang')||'id',cart:ls('cart')||[],gift:ls('gift')||{wrap:'goni',card:false,to:'',from:'',msg:''},cat:'all',shop:{cats:new Set(),max:150000,easy:false,sort:'pop'},reviews:{},orders:[],co:{step:1,info:{},ship:'jne',pay:'bca'},quiz:{i:0,a:[]},careTab:0};
const L=()=>S.lang;
const T={
 id:{home:'Beranda',shop:'Katalog',story:'Cerita',faq:'FAQ',cart:'Keranjang',search:'Cari',kicker:'Mini plant house',giant:'tumbuh',hzA:'Hijau Kecil,',hzB:'Bahagia Besar',hzIg:'Lihat ide styling di Instagram',hzL:'Jenis succulent & kaktus mini, dipilih satu per satu',hzC:'Teman kecil untuk meja kerja & hadiah',hzCta:'Belanja sekarang',hzR:'Gratis ongkir Jabodetabek untuk belanja di atasnya',h1a:'Rumah kecil',h1b:'untuk',h1c:'tanaman kecil',hxQuiz:'Bantu aku memilih',pt1:'Diaklimatisasi seminggu',pt2:'Siap jadi hadiah',pt3:'Kirim se-Indonesia',lead:'Succulent & kaktus mini dari rumah tanam kami, dibungkus goni, lengkap dengan kartu ucapan, siap jadi teman meja kerja atau hadiah kecil yang berkesan.',stat:'Siap kirim ke seluruh Indonesia',statB:'Rawat mudah',cta:'Belanja succulent',ticker:['Echeveria','Haworthia Zebra','Kaktus Kelinci','Gasteria Mini','Aloe Mini','Jade Plant','Kaktus Tiang','Golden Barrel','Terarium Mini'],
  pickT:'Pilih teman', pickH:'hijau-mu',pickP:'Semua tanaman dipilih satu per satu, diaklimatisasi seminggu, lalu dikirim dengan media tanam porous siap pakai.',all:'Semua',succ:'Succulent',cact:'Kaktus',aloe:'Aloe & Jade',terr:'Terarium',gift:'Paket Hadiah',add:'Tambah',added:'Ditambahkan',easy:'Mudah',med:'Sedang',care:'Perawatan',viewAll:'Lihat semua katalog',
  quizT:'Bingung pilih yang mana?',pmT:'Ceritakan sedikit, kami pilihkan tanamannya.',pm0:'Favorit minggu ini',pmSoFar:'Cocok sejauh ini',pmDone:'Kalimatmu lengkap. Klik bagian hijau untuk mengubah jawaban.',pm:Object.assign([{pre:'Tanamanku akan tinggal',ask:'Di mana tanamannya akan tinggal?',o:[['dekat jendela terang','Matahari pagi 3–4 jam'],['di ruangan agak redup','Meja kerja, rak, kamar'],['di teras atau balkon','Panas dan terbuka']]},{pre:', aku',ask:'Seberapa sering kamu menyiram?',o:[['sering lupa menyiram','Kadang 2 minggu baru ingat'],['menyiram seminggu sekali','Rutin di akhir pekan'],['senang merawat tiap hari','Cek tanaman hampir tiap hari']]},{pre:', dan tanaman ini untuk',ask:'Untuk siapa tanaman ini?',o:[['diriku sendiri','Teman di meja kerja'],['hadiah','Ulang tahun, wisuda, terima kasih'],['kantor atau acara','Souvenir dan hampers']]}],{end:'.'}),why:{bright:'Suka cahaya terang',dim:'Tahan di cahaya redup',outdoor:'Kuat di luar ruangan',forget:'Tetap segar walau lupa disiram',week:'Cukup disiram seminggu sekali',care:'Senang dirawat rutin',self:'Pas untuk meja kerja',gift:'Cantik untuk hadiah',office:'Cocok untuk kantor dan acara'},quizP:'Jawab 3 pertanyaan singkat, kami carikan succulent yang paling cocok dengan ruangan dan kebiasaanmu.',q:[['Di mana tanamannya akan tinggal?',[['☀️','Dekat jendela terang','Kena matahari pagi 3–4 jam'],['🏠','Ruangan agak redup','Meja kerja, rak, kamar'],['🌤️','Teras / luar ruangan','Panas dan terbuka']]],['Seberapa sering kamu ingat menyiram?',[['😅','Sering lupa','Kadang 2 minggu baru ingat'],['🗓️','Seminggu sekali','Rutin di akhir pekan'],['🪴','Suka merawat','Cek tanaman hampir tiap hari']]],['Untuk siapa?',[['🙋','Untuk diri sendiri','Teman kerja di meja'],['🎁','Untuk hadiah','Ulang tahun, wisuda, terima kasih'],['🏢','Untuk kantor / acara','Souvenir, hampers']]]],quizRes:'Paling cocok untukmu',again:'Ulangi kuis',alt:'Alternatif lain',
  giftT:'Dibungkus seperti',giftH:'hadiah',giftP:'Ciri khas Sangkarloka: pot goni dengan pita, kartu "Just For You" tulisan tangan, dan box kraft gantung. Atur di sini, kami siapkan sebelum dikirim.',wrap:'Kemasan',card:'Kartu ucapan "Just For You"',to:'Untuk',from:'Dari',msg:'Pesan singkat (opsional)',saveGift:'Simpan untuk pesanan ini',
  careT:'Panduan rawat',careH:'anti layu',careTabs:[['💧','Menyiram'],['☀️','Cahaya'],['🪨','Media tanam'],['🪴','Pot & ganti pot']],
  bulkT:'Souvenir & hampers',bulkP:'Pernikahan, seminar, ulang tahun kantor. Pesan mulai 25 pcs dengan kartu dan pita custom warna acaramu.',qty:'Jumlah',est:'Estimasi total',perPc:'per pcs',askWA:'Minta penawaran via WhatsApp',
  ideaTag:'Ide styling',momentT:'Inspirasi',momentH:'sudut hijau',momentP:'Ide menata tanaman mini di rumah dan kantor. Sudah punya sudut hijau sendiri? Tag @'+IG+' di Instagram.',
  faqT:'Pertanyaan yang sering',faqH:'ditanya',
  checkout:'Checkout',empty:'Keranjangmu masih kosong',emptyP:'Mulai dari succulent paling gampang dirawat.',subtotal:'Subtotal',shipping:'Ongkir',total:'Total',freeShip:'Gratis ongkir Jabodetabek di atas',freeOK:'Gratis ongkir Jabodetabek aktif',orderWA:'Pesan via WhatsApp',remove:'Hapus',giftAdd:'Kemasan & kartu',pot:'Pot',qtyL:'Jumlah',addCart:'Tambah ke keranjang',buyNow:'Beli sekarang',light:'Cahaya',water:'Siram',size:'Ukuran',latin:'Nama latin',details:'Detail tanaman',careGuide:'Cara rawat',shipInfo:'Pengiriman & garansi',related:'Cocok dipadukan dengan',reviews:'Ulasan',noRev:'Belum ada ulasan untuk tanaman ini. Jadilah yang pertama.',writeRev:'Tulis ulasan',postRev:'Kirim ulasan',name:'Nama',city:'Kota',yourRev:'Ulasanmu',
  filters:'Filter',category:'Kategori',maxPrice:'Harga maks',easyOnly:'Hanya yang mudah dirawat',sortPop:'Terpopuler',sortLow:'Termurah',sortHigh:'Termahal',sortAZ:'Nama A–Z',items:'tanaman',clear:'Reset filter',
  step1:'Data penerima',step2:'Pengiriman',step3:'Pembayaran',fullName:'Nama lengkap',waNo:'No. WhatsApp',address:'Alamat lengkap',cityL:'Kota / kabupaten',postal:'Kode pos',cont:'Lanjut',back:'Kembali',placeOrder:'Buat pesanan',thanks:'Terima kasih',orderOK:'Pesananmu sudah kami terima.',payTo:'Selesaikan pembayaran ke',confirmWA:'Konfirmasi via WhatsApp',keepShop:'Lanjut belanja',demo:'Website demo. Tidak ada pembayaran sungguhan.',
  storyT:'Cerita di balik',storyH:'sangkar kecil',storyP:'Sangkarloka lahir dari kebiasaan sederhana: memberi tanaman kecil sebagai tanda terima kasih. "Sangkar" adalah rumah, "loka" adalah tempat. Kami ingin setiap succulent punya rumah yang layak, dari pot goni yang kami ikat sendiri sampai kartu yang ditulis tangan.',
  steps:[['Dipilih','Setiap tanaman dicek akar, warna dan hamanya sebelum masuk katalog.'],['Diaklimatisasi','Seminggu di rumah tanam supaya kuat menempuh perjalanan.'],['Dikemas','Dibungkus goni atau box kraft, diberi kartu, lalu dikirim dengan bubble wrap.']],
  footerP:'Mini plant house. Succulent & kaktus mini untuk meja kerja dan hadiah kecil.',made:'Website oleh Organoo Studio'},
 en:{home:'Home',shop:'Shop',story:'Story',faq:'FAQ',cart:'Cart',search:'Search',kicker:'Mini plant house',giant:'grow',hzA:'Little Green,',hzB:'Big Happiness',hzIg:'Styling ideas on Instagram',hzL:'Mini succulents & cacti, each one hand-picked',hzC:'Little companions for desks & gifts',hzCta:'Shop now',hzR:'Free Greater Jakarta shipping on orders above this',h1a:'A little house',h1b:'for',h1c:'little plants',hxQuiz:'Help me choose',pt1:'Acclimatised for a week',pt2:'Gift-ready',pt3:'Ships across Indonesia',lead:'Mini succulents and cacti from our little greenhouse, wrapped in burlap with a handwritten card, ready to live on your desk or become a small gift that sticks.',stat:'Shipping across Indonesia',statB:'Easy care',cta:'Shop succulents',ticker:['Echeveria','Zebra Haworthia','Bunny Ears Cactus','Gasteria Mini','Mini Aloe','Jade Plant','Column Cactus','Golden Barrel','Mini Terrarium'],
  pickT:'Pick your',pickH:'green buddy',pickP:'Every plant is hand-picked, acclimatised for a week and shipped in porous, ready-to-use potting mix.',all:'All',succ:'Succulents',cact:'Cacti',aloe:'Aloe & Jade',terr:'Terrariums',gift:'Gift sets',add:'Add',added:'Added',easy:'Easy',med:'Medium',care:'Care',viewAll:'See the full catalogue',
  quizT:'Not sure which one?',pmT:'Tell us a little, we pick the plant.',pm0:'Favourite this week',pmSoFar:'Best match so far',pmDone:'Your sentence is complete. Tap a green part to change an answer.',pm:Object.assign([{pre:'My plant will live',ask:'Where will it live?',o:[['by a bright window','3–4 hours of morning sun'],['in a dimmer room','Desk, shelf or bedroom'],['on a balcony','Hot and open']]},{pre:', I',ask:'How often do you water?',o:[['often forget to water','Sometimes two weeks go by'],['water once a week','A weekend routine'],['love daily plant care','I check on plants daily']]},{pre:', and it is for',ask:'Who is it for?',o:[['myself','A desk companion'],['a gift','Birthday, graduation, thank you'],['the office or an event','Souvenirs and hampers']]}],{end:'.'}),why:{bright:'Loves bright light',dim:'Copes with low light',outdoor:'Tough enough for outdoors',forget:'Forgives forgotten waterings',week:'Happy with weekly watering',care:'Enjoys regular care',self:'Made for your desk',gift:'Lovely as a gift',office:'Great for offices and events'},quizP:'Answer 3 quick questions and we will match you with the succulent that suits your space and habits.',q:[['Where will it live?',[['☀️','By a bright window','3–4 hours of morning sun'],['🏠','A dimmer room','Desk, shelf or bedroom'],['🌤️','Balcony / outdoors','Hot and open']]],['How often do you remember to water?',[['😅','I often forget','Sometimes two weeks go by'],['🗓️','Once a week','A weekend routine'],['🪴','I love plant care','I check on plants daily']]],['Who is it for?',[['🙋','Myself','A desk companion'],['🎁','A gift','Birthday, graduation, thank you'],['🏢','Office / event','Souvenirs and hampers']]]],quizRes:'Your best match',again:'Retake quiz',alt:'Also a good fit',
  giftT:'Wrapped like a',giftH:'present',giftP:'The Sangkarloka signature: a burlap pot with a bow, a handwritten "Just For You" card and a hanging kraft box. Set it up here and we prepare it before shipping.',wrap:'Wrapping',card:'"Just For You" card',to:'To',from:'From',msg:'Short message (optional)',saveGift:'Save for this order',
  careT:'Care guide',careH:'no wilting',careTabs:[['💧','Watering'],['☀️','Light'],['🪨','Soil mix'],['🪴','Pots & repotting']],
  bulkT:'Souvenirs & hampers',bulkP:'Weddings, seminars, company birthdays. Order from 25 pieces with custom cards and ribbons in your event colours.',qty:'Quantity',est:'Estimated total',perPc:'per piece',askWA:'Request a quote on WhatsApp',
  ideaTag:'Styling idea',momentT:'Green corner',momentH:'ideas',momentP:'Ideas for styling mini plants at home and at work. Got your own green corner? Tag @'+IG+' on Instagram.',
  faqT:'Frequently',faqH:'asked',
  checkout:'Checkout',empty:'Your cart is empty',emptyP:'Start with the easiest succulents to care for.',subtotal:'Subtotal',shipping:'Shipping',total:'Total',freeShip:'Free Greater Jakarta shipping over',freeOK:'Free Greater Jakarta shipping unlocked',orderWA:'Order via WhatsApp',remove:'Remove',giftAdd:'Wrapping & card',pot:'Pot',qtyL:'Quantity',addCart:'Add to cart',buyNow:'Buy now',light:'Light',water:'Water',size:'Size',latin:'Latin name',details:'Plant details',careGuide:'How to care',shipInfo:'Shipping & guarantee',related:'Pairs well with',reviews:'Reviews',noRev:'No reviews for this plant yet. Be the first.',writeRev:'Write a review',postRev:'Post review',name:'Name',city:'City',yourRev:'Your review',
  filters:'Filters',category:'Category',maxPrice:'Max price',easyOnly:'Easy care only',sortPop:'Most popular',sortLow:'Price: low to high',sortHigh:'Price: high to low',sortAZ:'Name A–Z',items:'plants',clear:'Reset filters',
  step1:'Recipient',step2:'Shipping',step3:'Payment',fullName:'Full name',waNo:'WhatsApp number',address:'Full address',cityL:'City',postal:'Postcode',cont:'Continue',back:'Back',placeOrder:'Place order',thanks:'Thank you',orderOK:'We have received your order.',payTo:'Complete your payment to',confirmWA:'Confirm on WhatsApp',keepShop:'Keep shopping',demo:'Demo website. No real payment is taken.',
  storyT:'The story behind',storyH:'the little house',storyP:'Sangkarloka began with a simple habit: giving a tiny plant as a thank-you. "Sangkar" means home and "loka" means place. We want every succulent to have a proper home, from the burlap pots we tie ourselves to cards written by hand.',
  steps:[['Picked','Every plant is checked for roots, colour and pests before it joins the catalogue.'],['Acclimatised','A week in our greenhouse so it is strong enough for the journey.'],['Packed','Wrapped in burlap or a kraft box, given a card, then shipped in bubble wrap.']],
  footerP:'Mini plant house. Mini succulents and cacti for desks and small gifts.',made:'Website by Organoo Studio'}
};
const t=k=>T[L()][k]??T.id[k]??k;
const tx=o=>typeof o==='string'?o:(o[L()]||o.id);
const RATE=16300;
const money=n=>L()==='en'?'$'+(n/RATE).toFixed(2):'Rp'+Math.round(n).toLocaleString('id-ID');

/* ---------- catalogue ---------- */
const POTS=[{k:'goni',n:{id:'Goni + pita',en:'Burlap + bow'},p:0},{k:'white',n:{id:'Keramik putih',en:'White ceramic'},p:8000},{k:'terracotta',n:{id:'Terakota',en:'Terracotta'},p:6000},{k:'box',n:{id:'Box kraft gantung',en:'Hanging kraft box'},p:10000}];
const potDraw={goni:'burlap',white:'white',terracotta:'terracotta',box:'box'};
const P=[
 {slug:'echeveria-lola',name:'Echeveria Lola',latin:'Echeveria lilacina × derenbergii',kind:'rosette',cat:'succ',price:35000,pop:98,care:1,light:{id:'Terang, matahari pagi',en:'Bright, morning sun'},water:{id:'7–10 hari sekali',en:'Every 7–10 days'},size:'8–10 cm',tags:['bright','forget','self','gift'],desc:{id:'Roset mungil berwarna hijau pastel dengan ujung merah muda saat kena matahari pagi. Favorit untuk meja kerja dekat jendela.',en:'A tiny pastel rosette whose tips blush pink in morning sun. A favourite for desks near a window.'}},
 {slug:'haworthia-zebra',name:'Haworthia Zebra',latin:'Haworthiopsis attenuata',kind:'zebra',cat:'succ',price:30000,pop:95,care:1,light:{id:'Tahan agak redup',en:'Tolerates lower light'},water:{id:'10–14 hari sekali',en:'Every 10–14 days'},size:'7–9 cm',tags:['dim','forget','self','office'],desc:{id:'Daun runcing bergaris putih seperti zebra. Paling tahan di ruangan ber-AC dan cahaya tidak langsung.',en:'Pointed leaves with white zebra stripes. The toughest pick for air-conditioned rooms with indirect light.'}},
 {slug:'gasteria-mini',name:'Gasteria Mini',latin:'Gasteria bicolor var. liliputana',kind:'aloe',cat:'succ',price:40000,pop:90,care:1,light:{id:'Terang tidak langsung',en:'Bright, indirect'},water:{id:'7–10 hari sekali',en:'Every 7–10 days'},size:'10–12 cm',tags:['bright','week','gift','self'],desc:{id:'Daun tebal bertotol putih yang tumbuh berlapis seperti lidah. Sangat tahan banting, cocok untuk pemula dan meja kerja.',en:'Thick, white-speckled leaves stacked like tongues. Extremely forgiving, great for beginners and desks.'}},
 {slug:'bunny-ears',name:{id:'Kaktus Kelinci',en:'Bunny Ears Cactus'},latin:'Opuntia microdasys',kind:'bunny',cat:'cact',price:35000,pop:92,care:1,light:{id:'Terang, matahari langsung',en:'Bright, direct sun'},water:{id:'10–14 hari sekali',en:'Every 10–14 days'},size:'10–12 cm',tags:['bright','outdoor','forget','gift'],desc:{id:'Dua "telinga" hijau dengan bintik kuning halus. Lucu, fotogenik, dan jadi best seller untuk kado.',en:'Two green "ears" dotted with soft yellow glochids. Cute, photogenic and a best-selling gift.'}},
 {slug:'golden-barrel',name:'Golden Barrel Mini',latin:'Parodia leninghausii (juvenile)',kind:'barrel',cat:'cact',price:45000,pop:84,care:1,light:{id:'Matahari langsung',en:'Direct sun'},water:{id:'14 hari sekali',en:'Every 14 days'},size:'8–10 cm',tags:['bright','outdoor','forget','self'],desc:{id:'Kaktus bulat dengan duri kuning keemasan yang berkilau saat kena cahaya.',en:'A round cactus with golden spines that glow in the light.'}},
 {slug:'column-cactus',name:{id:'Kaktus Tiang Mini',en:'Mini Column Cactus'},latin:'Cereus sp. (juvenile)',kind:'barrel',cat:'cact',price:38000,pop:80,care:2,light:{id:'Terang tidak langsung',en:'Bright, indirect'},water:{id:'7–10 hari sekali',en:'Every 7–10 days'},size:'10–12 cm',tags:['bright','week','gift'],desc:{id:'Kaktus tegak berusuk dengan duri halus. Tumbuh pelan dan rapi, pas untuk rak sempit dan sudut meja.',en:'An upright ribbed cactus with fine spines. Slow and tidy, perfect for narrow shelves and desk corners.'}},
 {slug:'aloe-mini',name:'Aloe Mini',latin:'Aloe juvenna',kind:'aloe',cat:'aloe',price:32000,pop:78,care:1,light:{id:'Terang',en:'Bright'},water:{id:'7–10 hari sekali',en:'Every 7–10 days'},size:'10–12 cm',tags:['bright','week','self','office'],desc:{id:'Aloe bertubuh mungil dengan bintik putih. Tumbuh rapat dan cepat beranak.',en:'A compact aloe with white speckles. Grows tight and pups quickly.'}},
 {slug:'jade-plant',name:'Jade Plant',latin:'Crassula ovata',kind:'jade',cat:'aloe',price:45000,pop:82,care:1,light:{id:'Terang',en:'Bright'},water:{id:'10 hari sekali',en:'Every 10 days'},size:'12–15 cm',tags:['bright','week','gift','office'],desc:{id:'Dikenal sebagai tanaman keberuntungan. Batang kayu mungil dengan daun tebal hijau mengilap.',en:'Known as the lucky plant. A tiny woody trunk with thick, glossy green leaves.'}},
 {slug:'sedum-burrito',name:'Sedum Burrito',latin:'Sedum morganianum',kind:'burrito',cat:'succ',price:38000,pop:74,care:2,light:{id:'Terang tidak langsung',en:'Bright, indirect'},water:{id:'7 hari sekali',en:'Every 7 days'},size:'10 cm, menjuntai',tags:['bright','care','self'],desc:{id:'Butiran daun hijau muda yang menjuntai. Cantik di pot gantung atau tepi rak.',en:'Trailing strands of plump pale-green leaves. Beautiful in a hanging pot or on a shelf edge.'}},
 {slug:'terrarium-mini',name:{id:'Terarium Kaca Mini',en:'Mini Glass Terrarium'},latin:'Echeveria, Haworthia, Parodia',kind:'terrarium',cat:'terr',price:145000,pop:76,care:2,light:{id:'Terang tidak langsung',en:'Bright, indirect'},water:{id:'Semprot 2 minggu sekali',en:'Mist every 2 weeks'},size:'Ø 12 cm',tags:['dim','care','gift','office'],desc:{id:'Taman mini dalam bola kaca: tiga succulent, pasir berlapis dan batu hias. Siap jadi kado tanpa perlu dibungkus lagi.',en:'A miniature garden in a glass globe: three succulents, layered sand and decorative stones. Gift-ready as it is.'}},
 {slug:'trio-set',name:{id:'Paket Trio Succulent',en:'Succulent Trio Set'},latin:'Echeveria · Parodia · Haworthia',kind:'trio',cat:'gift',price:99000,pop:88,care:1,light:{id:'Terang',en:'Bright'},water:{id:'7–14 hari sekali',en:'Every 7–14 days'},size:'3 × 8 cm',tags:['bright','forget','gift','office'],desc:{id:'Tiga tanaman termudah kami dalam pot goni, lengkap dengan kartu "Just For You". Hemat Rp11.000 dibanding beli satuan.',en:'Our three easiest plants in burlap pots with a "Just For You" card. Save Rp11,000 versus buying them separately.'}},
 {slug:'hanging-box',name:{id:'Hampers Gantung',en:'Hanging Hamper'},latin:{id:'Succulent pilihan (bergantian)',en:'Rotating succulent pick'},kind:'rosette',cat:'gift',price:55000,pop:86,care:1,defPot:'box',light:{id:'Terang tidak langsung',en:'Bright, indirect'},water:{id:'7–10 hari sekali',en:'Every 7–10 days'},size:'Box 10 × 10 cm',tags:['bright','week','gift'],desc:{id:'Succulent pilihan yang siap digantung di jendela atau dinding. Standarnya dalam box kraft bertali rami, lengkap dengan tag nama penerima dan pengirim.',en:'A hand-picked succulent ready to hang by a window or on a wall. Comes in a kraft box with jute hangers and a name tag for recipient and sender.'}}
];
const IMG={'echeveria-lola':['succulent-white-pot','50% 40%'],'haworthia-zebra':['aloe-white','50% 60%'],'gasteria-mini':['white-pot-plant','50% 50%'],'bunny-ears':['bunny-ears-1','50% 50%'],'golden-barrel':['cactus-shallow','60% 40%'],'column-cactus':['cactus-brown-pot','50% 60%'],'aloe-mini':['aloe-blue','55% 50%'],'jade-plant':['succulent-table','35% 45%'],'sedum-burrito':['succulent-topview','55% 50%'],'terrarium-mini':['terrarium','50% 55%'],'trio-set':['succulents-variety','50% 55%'],'hanging-box':['hook-plant','50% 45%']};
P.forEach(p=>{const m=IMG[p.slug];if(m){p.img=m[0];p.pos=m[1]}});
const byslug=s=>P.find(p=>p.slug===s);
const nm=p=>tx(p.name);
const CATS=['all','succ','cact','aloe','terr','gift'];
const art=(p,pot)=>PArt.plant(p.kind,potDraw[pot||p.defPot||'goni']);
const pimg=(p,pot)=>ph(!pot||pot===(p.defPot||'goni')?p.img:null,art(p,pot),nm(p),p.pos);
const potP=k=>(POTS.find(x=>x.k===k)||{p:0}).p;
const priceOf=p=>p.price+potP(p.defPot||'goni');
const lineUnit=l=>byslug(l.s).price+potP(l.pot);
const GIFTW={goni:0,box:10000,plain:0};
const giftCost=()=>(S.gift.card?3000:0);
function save(){ls('cart',S.cart);ls('gift',S.gift);badge()}
const count=()=>S.cart.reduce((a,l)=>a+l.q,0);
const subtotal=()=>S.cart.reduce((a,l)=>a+lineUnit(l)*l.q,0)+(S.cart.length?giftCost():0);
function toast(msg,action){const el=document.createElement('div');el.className='toast';el.innerHTML=`<span>${esc(msg)}</span>${action?`<button type="button">${esc(action.t)}</button>`:''}`;$('#toasts').appendChild(el);if(action)$('button',el).onclick=()=>{el.remove();action.run()};setTimeout(()=>{el.style.transition='opacity .3s';el.style.opacity=0;setTimeout(()=>el.remove(),300)},3200)}
function add(slug,q=1,pot){const p=byslug(slug);pot=pot||p.defPot||'goni';const l=S.cart.find(x=>x.s===slug&&x.pot===pot);if(l)l.q+=q;else S.cart.push({s:slug,q,pot});save();toast(`${nm(p)} · ${t('added').toLowerCase()}`,{t:t('cart'),run:openCart})}
function badge(){$$('.cartn').forEach(b=>{b.textContent=count();b.hidden=!count()})}
const careDots=n=>`<span class="care">${[1,2,3].map(i=>`<i class="d ${i<=n?'on':''}"></i>`).join('')} ${n===1?t('easy'):t('med')}</span>`;
const waLink=txt=>`https://wa.me/${WA}?text=${encodeURIComponent(txt)}`;

/* ---------- chrome ---------- */
function navPills(cur,compact){const A=(h,k)=>`<a class="gp" href="#${h}" ${cur===h?'aria-current="page"':''}>${t(k)}</a>`;
 return `<div class="gnav"><a class="brand" href="#home" aria-label="Sangkarloka"><span class="mark"><img src="${LOGO}" alt=""></span><span><b>SANGKARLOKA</b><small>MINI PLANT HOUSE</small></span></a>
 ${A('home','home')}${A('shop','shop')}${A('story','story')}<span class="sp"></span>
 <button class="gp icon" id="srchBtn" aria-label="${t('search')}">${ic('search')}</button><button class="gp icon" id="cartBtn" aria-label="${t('cart')}">${ic('bag')}<span class="cartn num" hidden>0</span></button>
 <div class="lang" role="group" aria-label="Language">${['id','en'].map(l=>`<button type="button" data-lang="${l}" aria-pressed="${L()===l}">${l==='id'?'ID · Rp':'EN · $'}</button>`).join('')}</div>
 <button class="gp icon burger" id="burger" aria-label="Menu" aria-expanded="false">${ic('menu')}</button></div>
 <nav class="mmenu" id="mmenu"><a href="#home">${t('home')}</a><a href="#shop">${t('shop')}</a><a href="#story">${t('story')}</a><div class="lang" role="group" aria-label="Language">${['id','en'].map(l=>`<button type="button" data-lang="${l}" aria-pressed="${L()===l}">${l==='id'?'ID · Rp':'EN · $'}</button>`).join('')}</div></nav>`}
function footer(){return `<footer class="f"><div class="wrap"><div class="fg">
 <div><div class="fbrand"><img src="${LOGO_W}" alt=""><div><b>SANGKARLOKA</b><small>MINI PLANT HOUSE</small></div></div><p style="margin-top:14px;max-width:34ch">${t('footerP')}</p></div>
 <div><h4>${t('shop')}</h4>${CATS.slice(1).map(c=>`<a href="#shop" data-fcat="${c}">${t(c)}</a>`).join('')}</div>
 <div><h4>Info</h4><a href="#story">${t('story')}</a><a href="#home" data-jump="faq">FAQ</a><a href="#home" data-jump="care">${t('careT')}</a><a href="#home" data-jump="bulk">${t('bulkT')}</a></div>
 <div><h4>Kontak</h4><a href="${waLink('Halo Sangkarloka!')}" target="_blank" rel="noopener">${ic('wa','width:16px;height:16px;vertical-align:-3px')} 0895-4038-28002</a><a href="https://instagram.com/${IG}" target="_blank" rel="noopener">${ic('ig','width:16px;height:16px;vertical-align:-3px')} @${IG}</a></div></div>
 <div class="fbig" aria-hidden="true">sangkarloka</div>
 <div class="fbot"><span>© 2026 Sangkarloka · Mini Plant House</span><span>${t('made')}</span></div></div></footer>`}
function mount(cur,body,isHome){document.documentElement.lang=L();
 $('#root').innerHTML=`<header class="topbar">${navPills(cur)}</header>`+`<main id="main">${body}</main>`+footer();
 bindNav($('#root'));badge();reveal();
 $$('[data-fcat]').forEach(a=>a.onclick=()=>{S.shop.cats=new Set([a.dataset.fcat])});
 $$('[data-jump]').forEach(a=>a.addEventListener('click',()=>S.jump=a.dataset.jump))}
function bindNav(root){$$('#cartBtn',root).forEach(b=>b.onclick=openCart);$$('#srchBtn',root).forEach(b=>b.onclick=openSearch);
 $$('[data-lang]',root).forEach(b=>b.onclick=()=>{S.lang=b.dataset.lang;ls('lang',S.lang);const y=scrollY;route();scrollTo(0,y)});
 const bg=$('#burger',root);if(bg)bg.onclick=()=>{const m=$('#mmenu',root);m.classList.toggle('open');bg.setAttribute('aria-expanded',m.classList.contains('open'))}}
function reveal(){const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.remove('pre');io.unobserve(e.target)}}),{rootMargin:'0px 0px -8% 0px'});$$('.reveal').forEach(el=>{if(el.getBoundingClientRect().top>innerHeight){el.classList.add('pre');io.observe(el)}})}

/* ---------- product card ---------- */
function card(p){return `<article class="card reveal"><div class="imgw"><a class="img" href="#p-${p.slug}" aria-label="${esc(nm(p))}">${pimg(p)}</a>
 <div class="badges">${p.cat==='gift'?`<span class="pill-tag">${ic('gift','width:13px;height:13px')}${t('gift')}</span>`:''}${p.pop>=92?'<span class="pill-tag dark">Best seller</span>':''}</div>
 <button class="circle add" data-add="${p.slug}" aria-label="${t('add')} ${esc(nm(p))}">${ic('plus')}</button></div>
 <div class="meta"><a href="#p-${p.slug}">${esc(nm(p))}</a><i>${esc(tx(p.latin))}</i><div class="row"><span class="price num">${money(priceOf(p))}</span>${careDots(p.care)}</div></div></article>`}
function bindCards(root=document){$$('[data-add]',root).forEach(b=>b.onclick=e=>{e.preventDefault();add(b.dataset.add);b.classList.add('ok');b.innerHTML=ic('check');setTimeout(()=>{b.classList.remove('ok');b.innerHTML=ic('plus')},1300)})}

/* ---------- HOME ---------- */
function pageHome(){const word=t('giant');
 const grid=P.filter(p=>S.cat==='all'||p.cat===S.cat).sort((a,b)=>b.pop-a.pop).slice(0,8);
 return `<section class="wrap hz"><div class="hz-in">
  <h1 class="hz-h" aria-label="${t('hzA')} ${t('hzB')}"><span class="w1">${t('hzA')}</span><span class="w2">${t('hzB')}</span></h1>
  <a class="hz-prod" href="#p-column-cactus"><span class="im"><img src="photos/cut/cactus-brown-pot.webp" alt="" onerror="this.remove()"></span><span class="go">${ic('arrow')}</span><span class="nm">${esc(nm(byslug('column-cactus')))}</span><b class="num">${money(priceOf(byslug('column-cactus')))}</b></a>
  <a class="hz-ig" href="https://instagram.com/${IG}" target="_blank" rel="noopener">${ph('window-shelf','',t('hzIg'),'40% 50%')}<span class="pl">${ic('ig')}</span><span class="tx">${t('hzIg')}</span></a>
  <div class="hz-row">
   <div class="shelf l"><img class="pl" src="photos/cut/pink-succulent.webp" alt="" onerror="this.remove()"><div class="pan"><div class="big"><b class="num">${P.length}</b><a class="add-c" href="#shop" aria-label="${t('shop')}">${ic('plus')}</a></div><p>${t('hzL')}</p></div></div>
   <div class="shelf c"><img class="pl" src="photos/cut/cactus-beige-pot.webp" alt="" onerror="this.remove()"><div class="pan"><p class="t">${t('hzC')}</p><a class="hz-cta" href="#shop">${t('hzCta')}<span>${ic('arrow')}</span></a></div></div>
   <div class="shelf r"><img class="pl" src="photos/cut/white-pot-plant.webp" alt="" onerror="this.remove()"><div class="pan"><div class="big"><b class="num">${L()==='id'?'Rp150rb':money(150000)}</b><span class="tk">${ic('truck')}</span></div><p>${t('hzR')}</p></div></div>
  </div>
 </div></section>
 <div class="ticker" aria-hidden="true"><div class="track">${Array(2).fill(t('ticker')).flat().map(x=>`<span>${x}</span>`).join('')}</div></div>
 <section class="s wrap" id="pick"><div class="sh"><h2>${t('pickT')} <span class="hand">${t('pickH')}</span></h2><p>${t('pickP')}</p></div>
  <div class="chips" role="group" aria-label="${t('category')}" style="margin-bottom:26px">${CATS.map(c=>`<button class="chip" type="button" data-hc="${c}" aria-pressed="${c===S.cat}">${t(c)}</button>`).join('')}</div>
  <div class="grid" id="homeGrid">${grid.map(card).join('')}</div><div style="text-align:center;margin-top:36px"><a class="btn lg" href="#shop">${t('viewAll')} ${ic('arrow')}</a></div></section>
 <section class="s wrap reveal" id="quiz"><div class="pm"><div class="pm-l"><span class="eyebrow">Plant match</span><h2 class="pm-h">${t('pmT')}</h2><p class="pm-sent" id="pmSent"></p><div class="pm-q" id="pmQ"></div><div class="pm-opts" id="pmOpts"></div></div><aside class="pm-r" id="pmRes" aria-live="polite"></aside></div></section>
 <section class="s wrap" id="gift"><div class="gift"><div class="gift-photos reveal">${ph('gift-box-plant','','Tanaman dan kado','50% 50%')}${ph('nice-day-sign','','Succulent dengan kartu ucapan','60% 50%')}${ph('hedgehog-pots','','Tiga succulent dalam pot mungil','40% 50%')}${ph('hand-cactus','','Kaktus dengan tag hadiah','60% 50%')}</div>
  <div><div class="sh" style="margin-bottom:18px"><h2>${t('giftT')} <span class="hand">${t('giftH')}</span></h2></div><p class="muted" style="margin-bottom:20px">${t('giftP')}</p>
  <div class="opt-list" role="radiogroup" aria-label="${t('wrap')}">${[['goni',{id:'Pot goni + pita hitam',en:'Burlap pot + black bow'},{id:'Standar Sangkarloka',en:'The Sangkarloka standard'},0],['box',{id:'Box kraft gantung + tali rami',en:'Hanging kraft box + jute'},{id:'Siap digantung di jendela',en:'Ready to hang by a window'},10000],['plain',{id:'Tanpa bungkus hadiah',en:'No gift wrap'},{id:'Untuk dipakai sendiri',en:'For your own desk'},0]].map(o=>`<label class="gopt"><input type="radio" name="wrap" value="${o[0]}" ${S.gift.wrap===o[0]?'checked':''}><span><b>${tx(o[1])}</b><small>${tx(o[2])}</small></span><b class="num">${o[3]?'+'+money(o[3]):'Gratis'}</b></label>`).join('')}
   <label class="gopt"><input type="checkbox" id="gCard" ${S.gift.card?'checked':''}><span><b>${t('card')}</b><small>${L()==='id'?'Ditulis tangan oleh tim kami':'Handwritten by our team'}</small></span><b class="num">+${money(3000)}</b></label></div>
  <div id="cardFields" ${S.gift.card?'':'hidden'} style="margin-top:16px;display:grid;grid-template-columns:1fr 230px;gap:18px;align-items:center"><div style="display:grid;gap:10px"><div class="field"><label for="gTo">${t('to')}</label><input class="input" id="gTo" maxlength="18" value="${esc(S.gift.to)}"></div><div class="field"><label for="gFrom">${t('from')}</label><input class="input" id="gFrom" maxlength="18" value="${esc(S.gift.from)}"></div><div class="field"><label for="gMsg">${t('msg')}</label><input class="input" id="gMsg" maxlength="60" value="${esc(S.gift.msg)}"></div></div>
   <div class="tag-prev" aria-label="Preview"><div><b>Just For<br>You</b><div class="ln" id="pTo">To : ${esc(S.gift.to||'…')}</div><div class="ln" id="pFrom">From : ${esc(S.gift.from||'…')}</div></div></div></div>
  <button class="btn leaf lg" id="saveGift" style="margin-top:18px">${ic('gift')} ${t('saveGift')}</button></div></div></section>
 <section class="s wrap" id="care"><div class="sh"><h2>${t('careT')} <span class="hand">${t('careH')}</span></h2></div><div class="care-g reveal"><div class="care-tabs" role="tablist">${t('careTabs').map((c,i)=>`<button role="tab" data-ct="${i}" aria-selected="${i===S.careTab}"><span class="ic">${c[0]}</span>${c[1]}</button>`).join('')}</div><div id="careBody"></div></div></section>
 <section class="s wrap" id="moments"><div class="sh"><h2>${t('momentT')} <span class="hand">${t('momentH')}</span></h2><p>${t('momentP')}</p></div><div class="revs">${[['hand-small-plant',{id:'Hadiah kecil untuk teman satu tim',en:'A small gift for a teammate'}],['window-shelf',{id:'Deretan succulent di jendela kamar',en:'A row of succulents on a bedroom sill'}],['hands-small-plants',{id:'Tiga pot kecil, tiga sahabat',en:'Three small pots for three friends'}]].map(r=>`<figure class="rev reveal" style="margin:0">${ph(r[0],PArt.plant('rosette','burlap'),tx(r[1]))}<figcaption class="b"><b>${tx(r[1])}</b><span class="muted" style="font-size:13px">${t('ideaTag')}</span></figcaption></figure>`).join('')}</div></section>
 <section class="s wrap reveal" id="bulk"><div class="bulk">${ph('succulents-top','','Succulent untuk souvenir')}<div class="in"><span class="eyebrow" style="color:#E4F2D3">B2B</span><h2>${t('bulkT')}</h2><p style="opacity:.9">${t('bulkP')}</p>
  <div class="seg" role="group" aria-label="Acara">${(L()==='id'?['Pernikahan','Kantor','Ulang tahun','Seminar']:['Wedding','Office','Birthday','Seminar']).map((e,i)=>`<button type="button" data-ev="${e}" aria-pressed="${i===0}">${e}</button>`).join('')}</div>
  <div class="field"><label for="bQty" style="color:#fff">${t('qty')}: <b class="num" id="bQtyV"></b> pcs</label><input type="range" id="bQty" min="25" max="500" step="5" value="100"></div>
  <div class="est"><span>${t('est')}</span><b class="num" id="bTot"></b><span class="num" id="bPer" style="opacity:.85"></span></div><a class="btn wa lg" id="bWA" href="#" target="_blank" rel="noopener">${ic('wa')} ${t('askWA')}</a></div></div></section>
 <section class="s wrap" id="faq"><div class="sh"><h2>${t('faqT')} <span class="hand">${t('faqH')}</span></h2></div><div class="faq">${FAQ().map((f,i)=>`<details ${i?'':'open'}><summary>${f[0]}</summary><p>${f[1]}</p></details>`).join('')}</div></section>`}
const FAQ=()=>L()==='id'?[['Apakah tanaman aman dikirim ke luar pulau?','Aman. Tanaman dikirim dengan media tanam kering, dibungkus kertas dan bubble wrap, lalu dimasukkan ke box berlubang. Untuk luar Jawa kami sarankan JNE REG atau SiCepat BEST.'],['Bagaimana kalau tanaman rusak saat sampai?','Kirim video unboxing ke WhatsApp kami maksimal 1×24 jam setelah paket diterima. Kami ganti tanaman baru tanpa biaya.'],['Bisa pakai kartu ucapan custom?','Bisa. Centang "Kartu ucapan Just For You" dan isi nama penerima, pengirim dan pesan singkat. Kami tulis tangan sebelum dikirim.'],['Berapa lama pesanan diproses?','Pesanan sebelum jam 14.00 WIB dikirim di hari yang sama (Senin–Sabtu). GoSend same day tersedia untuk Jabodetabek.'],['Bisa pesan untuk souvenir dalam jumlah banyak?','Bisa, mulai 25 pcs. Gunakan kalkulator souvenir di atas lalu kirim permintaan penawaran via WhatsApp.']]:[['Can plants be shipped across islands?','Yes. Plants travel in dry potting mix, wrapped in paper and bubble wrap inside a ventilated box. Outside Java we recommend JNE REG or SiCepat BEST.'],['What if a plant arrives damaged?','Send an unboxing video to our WhatsApp within 24 hours of delivery and we will replace the plant for free.'],['Can I add a custom card?','Yes. Tick the "Just For You" card and fill in the recipient, sender and a short message. We write it by hand before shipping.'],['How fast are orders processed?','Orders before 2 pm WIB ship the same day (Mon–Sat). GoSend same-day delivery is available in Greater Jakarta.'],['Do you take bulk souvenir orders?','Yes, from 25 pieces. Use the souvenir calculator above, then send us a quote request on WhatsApp.']];
const CARE=()=>L()==='id'?[['Menyiram','Succulent lebih cepat mati karena kebanyakan air daripada kekeringan. Siram hanya saat media tanam benar-benar kering.',['Tusuk media dengan tusuk gigi. Jika keluar bersih dan kering, saatnya menyiram.','Siram sampai air keluar dari lubang pot, lalu buang sisa air di tatakan.','Jangan menyemprot daun roset; air yang menggenang di tengah bisa membuat busuk.']],['Cahaya','Kebanyakan succulent butuh 3–4 jam cahaya terang per hari. Tanda kurang cahaya: batang memanjang dan warna memudar.',['Taruh dekat jendela timur untuk matahari pagi yang lembut.','Putar pot seperempat putaran tiap minggu agar tumbuh simetris.','Haworthia dan terarium paling tahan cahaya tidak langsung.']],['Media tanam','Media harus porous supaya air cepat turun. Semua tanaman kami dikirim dengan campuran siap pakai.',['Campuran kami: sekam bakar, pasir malang, pumice dan sedikit kompos.','Hindari tanah kebun biasa yang padat dan menahan air.','Tambahkan pupuk slow release sedikit setiap 3 bulan.']],['Pot & ganti pot','Pot goni kami sudah dilapisi pot plastik berlubang di dalamnya, jadi aman disiram langsung.',['Ganti pot setiap 12–18 bulan atau saat akar keluar dari lubang.','Pilih pot 1–2 cm lebih besar, jangan terlalu jauh.','Diamkan 2–3 hari tanpa disiram setelah ganti pot agar akar pulih.']]]:[['Watering','Succulents die from too much water far more often than from drought. Only water when the mix is completely dry.',['Poke the mix with a toothpick. If it comes out clean and dry, it is time to water.','Water until it drains from the pot, then empty the saucer.','Do not mist rosettes; water sitting in the centre can cause rot.']],['Light','Most succulents want 3–4 hours of bright light a day. Signs of too little: stretched stems and faded colour.',['Place near an east-facing window for gentle morning sun.','Turn the pot a quarter turn each week so it grows evenly.','Haworthia and terrariums cope best with indirect light.']],['Soil mix','The mix must be porous so water drains fast. Every plant ships in our ready-to-use blend.',['Our blend: burnt rice husk, volcanic sand, pumice and a little compost.','Avoid regular garden soil, which is dense and holds water.','Add a pinch of slow-release fertiliser every 3 months.']],['Pots & repotting','Our burlap pots have a perforated plastic liner inside, so you can water them directly.',['Repot every 12–18 months or when roots poke out of the drainage hole.','Choose a pot only 1–2 cm larger.','Wait 2–3 days before watering after repotting so the roots can heal.']]];
function bindHome(){
 $$('[data-hc]').forEach(b=>b.onclick=()=>{S.cat=b.dataset.hc;$$('[data-hc]').forEach(x=>x.setAttribute('aria-pressed',x===b));const g=$('#homeGrid');const l=P.filter(p=>S.cat==='all'||p.cat===S.cat).sort((a,c)=>c.pop-a.pop).slice(0,8);g.innerHTML=l.map(card).join('');g.animate([{opacity:0,transform:'translateY(12px)'},{opacity:1,transform:'none'}],{duration:420,easing:'ease-out'});bindCards(g)});
 const hz=$('.hz-in');if(hz&&matchMedia('(pointer:fine)').matches&&!matchMedia('(prefers-reduced-motion:reduce)').matches){hz.addEventListener('mousemove',e=>{const r=hz.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;$$('.hz .pl').forEach((el,k)=>{const d=[10,18,10][k]||10;el.style.translate=`${-x*d}px ${-y*d*.4}px`})});hz.addEventListener('mouseleave',()=>$$('.hz .pl').forEach(el=>el.style.translate=''))}

 quiz();
 const g=S.gift;$$('[name=wrap]').forEach(r=>r.onchange=()=>{g.wrap=r.value});
 $('#gCard').onchange=e=>{g.card=e.target.checked;$('#cardFields').hidden=!g.card};
 const upd=()=>{g.to=$('#gTo').value;g.from=$('#gFrom').value;g.msg=$('#gMsg').value;$('#pTo').textContent='To : '+(g.to||'…');$('#pFrom').textContent='From : '+(g.from||'…')};['gTo','gFrom','gMsg'].forEach(id=>$('#'+id).oninput=upd);
 $('#saveGift').onclick=()=>{save();toast(L()==='id'?'Kemasan hadiah disimpan untuk pesananmu':'Gift wrapping saved for your order',{t:t('cart'),run:openCart})};
 const drawCare=()=>{const c=CARE()[S.careTab];$('#careBody').innerHTML=`<div class="care-body"><div><h3>${c[0]}</h3><p style="color:var(--fg-2)">${c[1]}</p><ul>${c[2].map(x=>`<li>${x}</li>`).join('')}</ul></div>
  <div class="water"><b style="font-size:14px">${L()==='id'?'Kalkulator siram':'Watering calculator'}</b><label class="sr" for="wPot">Pot</label><select class="sel" id="wPot"><option value="8">Pot 8 cm</option><option value="10" selected>Pot 10 cm</option><option value="12">Pot 12 cm</option></select><label class="sr" for="wSeason">Season</label><select class="sel" id="wSeason"><option value="dry">${L()==='id'?'Musim kemarau':'Dry season'}</option><option value="wet">${L()==='id'?'Musim hujan':'Rainy season'}</option></select><label class="sr" for="wRoom">Room</label><select class="sel" id="wRoom"><option value="ac">${L()==='id'?'Ruang ber-AC':'Air-conditioned'}</option><option value="open">${L()==='id'?'Ruang terbuka':'Open room'}</option></select><div id="wOut"></div></div></div>`;
  const calc=()=>{const s=+$('#wPot').value;const days=Math.round((s===8?7:s===10?9:11)*($('#wSeason').value==='wet'?1.6:1)*($('#wRoom').value==='ac'?1.2:1));const ml=Math.round(s*s*.45);$('#wOut').innerHTML=`<b class="big num">${days} ${L()==='id'?'hari':'days'}</b><span class="muted" style="font-size:13px">${L()==='id'?`sekali siram, ±${ml} ml air`:`between waterings, about ${ml} ml each time`}</span>`};['wPot','wSeason','wRoom'].forEach(id=>$('#'+id).onchange=calc);calc()};
 drawCare();$$('[data-ct]').forEach(b=>b.onclick=()=>{S.careTab=+b.dataset.ct;$$('[data-ct]').forEach(x=>x.setAttribute('aria-selected',x===b));drawCare()});
 let ev=$('[data-ev]').dataset.ev;const bcalc=()=>{const q=+$('#bQty').value;const unit=q>=250?18000:q>=100?20000:22000;$('#bQtyV').textContent=q;$('#bTot').textContent=money(unit*q);$('#bPer').textContent=`${money(unit)} ${t('perPc')} · ${L()==='id'?'termasuk pot goni, pita & kartu':'incl. burlap pot, ribbon & card'}`;
  $('#bWA').href=waLink(L()==='id'?`Halo Sangkarloka! Saya ingin minta penawaran souvenir succulent untuk acara ${ev}, jumlah ${q} pcs (estimasi ${money(unit*q)}). Terima kasih.`:`Hi Sangkarloka! I'd like a quote for succulent souvenirs for a ${ev} event, ${q} pieces (estimate ${money(unit*q)}). Thank you.`)};
 $('#bQty').oninput=bcalc;$$('[data-ev]').forEach(b=>b.onclick=()=>{ev=b.dataset.ev;$$('[data-ev]').forEach(x=>x.setAttribute('aria-pressed',x===b));bcalc()});bcalc();
}
const PMIMG=[['window-shelf','succulent-table','plants-table'],null,['hand-white-bg','gift-box-plant','succulents-variety']];
const drops=n=>`<svg viewBox="0 0 96 64" aria-hidden="true">${[0,1,2].map(k=>`<path d="M${20+k*28} 12c7 10 12 17 12 24a12 12 0 0 1-24 0c0-7 5-14 12-24z" fill="${k<n?'var(--leaf-2)':'none'}" stroke="var(--leaf)" stroke-width="2.4" stroke-linejoin="round"/>`).join('')}</svg>`;
function quiz(){const st=S.quiz;if(!Array.isArray(st.a)||st.a.length!==3)st.a=[null,null,null];const Q=t('pm');
 $('#pmSent').innerHTML=Q.map((q,i)=>`${q.pre} <button type="button" class="blank ${st.a[i]!=null?'on':''} ${st.i===i?'cur':''}" data-qb="${i}" aria-label="${esc(q.ask)}">${st.a[i]!=null?esc(q.o[st.a[i]][0]):'<span>&nbsp;</span>'}</button>`).join('')+Q.end;
 const done=st.a.every(v=>v!=null);
 if(done&&!st.edit){$('#pmQ').innerHTML=`<span class="pm-n">✓</span><span>${t('pmDone')}</span><button class="link" type="button" id="qAgain">${t('again')}</button>`;$('#pmOpts').innerHTML='';$('#pmOpts').classList.add('done')}
 else{$('#pmOpts').classList.remove('done');const q=Q[st.i];$('#pmQ').innerHTML=`<span class="pm-n num">${st.i+1}/3</span><span>${esc(q.ask)}</span>`;
  $('#pmOpts').innerHTML=q.o.map((o,k)=>`<button type="button" class="pm-t ${st.a[st.i]===k?'sel':''}" data-qa="${k}" style="--d:${k*70}ms">${PMIMG[st.i]?ph(PMIMG[st.i][k],'',''):`<div class="ph dr">${drops(k+1)}</div>`}<span class="lb"><b>${esc(o[0])}</b><small>${esc(o[1])}</small></span></button>`).join('')}
 const want=[['bright','dim','outdoor'],['forget','week','care'],['self','gift','office']].map((w,i)=>st.a[i]!=null?w[st.a[i]]:null);
 const ranked=P.map(p=>({p,s:want.reduce((a,w,i)=>a+(w&&p.tags.includes(w)?(i===0?3:2):0),0)+(st.a[1]===0&&p.care===1?1:0)+p.pop/100})).sort((a,b)=>b.s-a.s);const best=ranked[0].p,n=st.a.filter(v=>v!=null).length;
 const why=want.filter(w=>w&&best.tags.includes(w)).map(w=>t('why')[w]);
 $('#pmRes').innerHTML=`<div class="tag"><span class="hole" aria-hidden="true"></span><span class="lbl">${n===0?t('pm0'):done?t('quizRes'):t('pmSoFar')+` · ${n}/3`}</span><a class="im" href="#p-${best.slug}">${pimg(best)}</a><a class="nm" href="#p-${best.slug}">${esc(nm(best))}</a><i>${esc(tx(best.latin))}</i>
  ${why.length?`<ul>${why.map(w=>`<li>${ic('check')}${w}</li>`).join('')}</ul>`:`<p class="muted">${esc(tx(best.desc))}</p>`}
  <div class="ft"><b class="num">${money(priceOf(best))}</b><button class="btn leaf sm" data-add="${best.slug}">${ic('plus','width:15px;height:15px')}${t('add')}</button></div>
  ${done?`<div class="alt"><small>${t('alt')}</small>${ranked.slice(1,3).map(r=>`<a href="#p-${r.p.slug}">${esc(nm(r.p))} <span class="num">${money(priceOf(r.p))}</span></a>`).join('')}</div>`:''}</div>`;
 const tg=$('#pmRes .tag');tg.animate([{transform:'rotate(-2deg) translateY(8px)',opacity:.4},{transform:'rotate(-1deg)',opacity:1}],{duration:420,easing:'cubic-bezier(.3,1.3,.5,1)'});
 bindCards($('#pmRes'));
 $$('[data-qb]').forEach(b=>b.onclick=()=>{st.i=+b.dataset.qb;st.edit=true;quiz();$('#pmOpts').scrollIntoView({behavior:'smooth',block:'nearest'})});
 $$('[data-qa]').forEach(b=>b.onclick=()=>{st.a[st.i]=+b.dataset.qa;st.edit=false;const nx=[0,1,2].find(i=>st.a[i]==null);st.i=nx==null?st.i:nx;quiz()});
 $('#qAgain')?.addEventListener('click',()=>{S.quiz={i:0,a:[null,null,null]};quiz()})}

/* ---------- SHOP ---------- */
function pageShop(){return `<div class="wrap page-h"><div class="crumbs"><a href="#home">${t('home')}</a>/<span>${t('shop')}</span></div><h1>${t('shop')}</h1></div>
 <div class="wrap shop"><aside class="filters" aria-label="${t('filters')}"><div><h4>${t('category')}</h4>${CATS.slice(1).map(c=>`<label class="ck"><input type="checkbox" data-fc="${c}" ${S.shop.cats.has(c)?'checked':''}> ${t(c)} <span class="muted num" style="margin-left:auto">${P.filter(p=>p.cat===c).length}</span></label>`).join('')}</div>
 <div><h4>${t('maxPrice')} · <span class="num" id="mxV">${money(S.shop.max)}</span></h4><input type="range" id="mx" min="30000" max="150000" step="5000" value="${S.shop.max}" aria-label="${t('maxPrice')}"></div>
 <label class="ck"><input type="checkbox" id="easyOnly" ${S.shop.easy?'checked':''}> ${t('easyOnly')}</label><button class="link" id="clr" type="button">${t('clear')}</button></aside>
 <div><div class="shop-top"><span class="muted" id="cnt"></span><label class="sr" for="sort">Sort</label><select class="sel" id="sort">${[['pop','sortPop'],['low','sortLow'],['high','sortHigh'],['az','sortAZ']].map(o=>`<option value="${o[0]}" ${o[0]===S.shop.sort?'selected':''}>${t(o[1])}</option>`).join('')}</select></div><div class="grid" id="shopGrid" style="grid-template-columns:repeat(auto-fill,minmax(220px,1fr))"></div></div></div>`}
function bindShop(){const draw=()=>{const f=S.shop;let l=P.filter(p=>(!f.cats.size||f.cats.has(p.cat))&&priceOf(p)<=f.max&&(!f.easy||p.care===1));const so={pop:(a,b)=>b.pop-a.pop,low:(a,b)=>priceOf(a)-priceOf(b),high:(a,b)=>priceOf(b)-priceOf(a),az:(a,b)=>nm(a).localeCompare(nm(b))}[f.sort];l=[...l].sort(so);
 $('#cnt').textContent=`${l.length} ${t('items')}`;$('#shopGrid').innerHTML=l.length?l.map(card).join(''):`<div class="empty" style="grid-column:1/-1">${L()==='id'?'Tidak ada tanaman yang cocok.':'No plants match.'} <button class="btn sm" id="clr2">${t('clear')}</button></div>`;bindCards($('#shopGrid'));$('#clr2')?.addEventListener('click',clear)};
 const clear=()=>{S.shop={cats:new Set(),max:150000,easy:false,sort:S.shop.sort};route()};
 $$('[data-fc]').forEach(c=>c.onchange=()=>{c.checked?S.shop.cats.add(c.dataset.fc):S.shop.cats.delete(c.dataset.fc);draw()});$('#mx').oninput=e=>{S.shop.max=+e.target.value;$('#mxV').textContent=money(S.shop.max);draw()};$('#easyOnly').onchange=e=>{S.shop.easy=e.target.checked;draw()};$('#sort').onchange=e=>{S.shop.sort=e.target.value;draw()};$('#clr').onclick=clear;draw()}

/* ---------- PRODUCT ---------- */
function pageProduct(p){const pot=S.pp&&S.pp.s===p.slug?S.pp.pot:(p.defPot||'goni');const revs=S.reviews[p.slug]||[];
 return `<div class="wrap page-h" style="padding-bottom:16px"><div class="crumbs"><a href="#home">${t('home')}</a>/<a href="#shop">${t('shop')}</a>/<span>${t(p.cat)}</span></div></div>
 <div class="wrap pdp"><div class="gal"><div class="main" id="gMain">${pimg(p,pot)}</div><div class="thumbs" role="group" aria-label="Views">${(p.img?[['photo',ph(p.img,art(p),nm(p),p.pos)]]:[]).concat(POTS.map(o=>[o.k,`<div class="ph">${art(p,o.k)}</div>`])).map((v,i)=>`<button type="button" data-g="${v[0]}" aria-pressed="${i===0}" aria-label="${v[0]}">${v[1]}</button>`).join('')}</div></div>
 <div class="info"><div style="display:flex;gap:8px;flex-wrap:wrap">${careDots(p.care)}${p.cat==='gift'?`<span class="pill-tag">${ic('gift','width:13px;height:13px')}${t('gift')}</span>`:''}</div><h1>${esc(nm(p))}</h1><p class="latin">${esc(tx(p.latin))}</p>
  <div class="price-big num" id="pPrice"></div><p style="color:var(--fg-2)">${esc(tx(p.desc))}</p>
  <div class="facts"><div>${ic('sun')}<b>${t('light')}</b>${esc(tx(p.light))}</div><div>${ic('drop')}<b>${t('water')}</b>${esc(tx(p.water))}</div><div>${ic('leaf')}<b>${t('size')}</b>${esc(p.size)}</div></div>
  <div><b style="font-size:14px">${t('pot')}</b><div class="opts" style="margin-top:10px" role="radiogroup" aria-label="${t('pot')}">${POTS.map(o=>`<button type="button" class="opt" data-pot="${o.k}" aria-pressed="${o.k===pot}"><div class="ph">${art(p,o.k)}</div>${tx(o.n)}<small>${o.p?'+'+money(o.p):'Gratis'}</small></button>`).join('')}</div></div>
  <div style="display:flex;gap:10px;flex-wrap:wrap"><div class="qty"><button type="button" id="qm" aria-label="-">−</button><input id="qv" value="1" inputmode="numeric" aria-label="${t('qtyL')}"><button type="button" id="qp" aria-label="+">+</button></div><button class="btn dark lg" id="addBtn" style="flex:1">${ic('bag')} ${t('addCart')}</button></div>
  <div style="display:flex;gap:10px;flex-wrap:wrap"><button class="btn lg" id="buyNow" style="flex:1">${t('buyNow')}</button><a class="btn wa lg" id="waBtn" href="#" target="_blank" rel="noopener" style="flex:1">${ic('wa')} ${t('orderWA')}</a></div>
  <div class="acc">${[[t('careGuide'),`${esc(tx(p.water))}. ${L()==='id'?'Pastikan media benar-benar kering sebelum disiram lagi. Letakkan di tempat':'Make sure the mix is fully dry before watering again. Keep it in'} ${esc(tx(p.light)).toLowerCase()}.`],[t('shipInfo'),L()==='id'?'Dikirim Senin–Sabtu. Pesanan sebelum 14.00 WIB dikirim hari yang sama. Garansi tanaman hidup: kirim video unboxing maksimal 1×24 jam jika ada kerusakan.':'Ships Monday to Saturday. Orders before 2 pm WIB ship the same day. Live-arrival guarantee: send an unboxing video within 24 hours if anything is damaged.']].map((a,i)=>`<details ${i?'':'open'}><summary>${a[0]}</summary><div>${a[1]}</div></details>`).join('')}</div></div></div>
 <section class="wrap" style="padding-top:40px"><div class="sh"><h2>${t('related')}</h2></div><div class="grid">${P.filter(x=>x.slug!==p.slug).sort((a,b)=>(b.cat!==p.cat)-(a.cat!==p.cat)||b.pop-a.pop).slice(0,4).map(card).join('')}</div></section>
 <section class="wrap" id="reviews" style="padding-top:70px"><div class="sh"><h2>${t('reviews')}</h2><button class="btn" id="writeRev">${t('writeRev')}</button></div>
  <form id="revForm" hidden novalidate style="display:grid;gap:12px;background:var(--paper);border:1.5px solid var(--line);border-radius:24px;padding:20px;margin-bottom:16px"><div class="two"><div class="field"><label for="rN">${t('name')}</label><input class="input" id="rN"></div><div class="field"><label for="rC">${t('city')}</label><input class="input" id="rC"></div></div><div class="field"><label for="rB">${t('yourRev')}</label><textarea class="input" id="rB"></textarea></div><p class="err-t" id="rErr" hidden>${L()==='id'?'Isi nama dan ulasan.':'Add your name and a review.'}</p><button class="btn leaf">${t('postRev')}</button></form>
  <div id="revList">${revs.length?revs.map(r=>`<div style="padding:16px 0;border-bottom:1.5px solid var(--line)"><b>${esc(r.n)}</b> <span class="muted" style="font-size:13px">· ${esc(r.c)} · ${r.d}</span><p style="margin-top:6px">${esc(r.b)}</p></div>`).join(''):`<p class="muted">${t('noRev')}</p>`}</div></section>`}
function bindProduct(p){let pot=S.pp&&S.pp.s===p.slug?S.pp.pot:(p.defPot||'goni');const q=()=>Math.max(1,Math.min(50,parseInt($('#qv').value)||1));
 const upd=()=>{const unit=p.price+POTS.find(o=>o.k===pot).p;$('#pPrice').textContent=money(unit*q());$('#waBtn').href=waLink(L()==='id'?`Halo Sangkarloka! Saya mau pesan ${q()}× ${nm(p)} (${tx(POTS.find(o=>o.k===pot).n)}), total ${money(unit*q())}.`:`Hi Sangkarloka! I'd like to order ${q()}× ${nm(p)} (${tx(POTS.find(o=>o.k===pot).n)}), total ${money(unit*q())}.`)};upd();
 $$('[data-pot]').forEach(b=>b.onclick=()=>{pot=b.dataset.pot;S.pp={s:p.slug,pot};$$('[data-pot]').forEach(x=>x.setAttribute('aria-pressed',x===b));$('#gMain').innerHTML=pimg(p,pot);$$('[data-g]').forEach(x=>x.setAttribute('aria-pressed',x.dataset.g===pot||(x.dataset.g==='photo'&&pot===(p.defPot||'goni')&&!!p.img)));$('#gMain').animate([{opacity:.3,transform:'scale(.98)'},{opacity:1,transform:'none'}],{duration:350});upd()});
 $$('[data-g]').forEach(b=>b.onclick=()=>{const g=b.dataset.g;$$('[data-g]').forEach(x=>x.setAttribute('aria-pressed',x===b));$('#gMain').innerHTML=g==='photo'?ph(p.img,art(p),nm(p),p.pos):`<div class="ph">${art(p,g)}</div>`;if(g!=='photo'){pot=g;S.pp={s:p.slug,pot};$$('[data-pot]').forEach(x=>x.setAttribute('aria-pressed',x.dataset.pot===g));upd()}});
 $('#qm').onclick=()=>{$('#qv').value=Math.max(1,q()-1);upd()};$('#qp').onclick=()=>{$('#qv').value=Math.min(50,q()+1);upd()};$('#qv').oninput=upd;
 $('#addBtn').onclick=()=>add(p.slug,q(),pot);$('#buyNow').onclick=()=>{const l=S.cart.find(x=>x.s===p.slug&&x.pot===pot);if(l)l.q+=q();else S.cart.push({s:p.slug,q:q(),pot});save();location.hash='checkout'};
 $('#writeRev').onclick=()=>{$('#revForm').hidden=!$('#revForm').hidden};
 $('#revForm').onsubmit=e=>{e.preventDefault();const n=$('#rN').value.trim(),b=$('#rB').value.trim();if(!n||!b){$('#rErr').hidden=false;return}(S.reviews[p.slug]=S.reviews[p.slug]||[]).unshift({n,c:$('#rC').value.trim()||'—',b,d:new Date().toLocaleDateString(L()==='id'?'id-ID':'en-US',{day:'numeric',month:'short',year:'numeric'})});S.jump='reviews';route();toast(L()==='id'?'Terima kasih atas ulasannya!':'Thanks for your review!')}}

/* ---------- CART ---------- */
const FREE=150000;const JABO=['Jakarta','Bogor','Depok','Tangerang','Bekasi'];
function openCart(){closeAll();const ov=document.createElement('div');ov.className='ov';const d=document.createElement('aside');d.className='drawer';d.setAttribute('role','dialog');d.setAttribute('aria-label',t('cart'));document.body.append(ov,d);
 const close=()=>{ov.remove();d.remove();document.removeEventListener('keydown',k)};const k=e=>{if(e.key==='Escape')close()};document.addEventListener('keydown',k);ov.onclick=close;
 const draw=()=>{const sub=subtotal();const left=Math.max(0,FREE-sub);
  d.innerHTML=`<div class="dr-h"><h3>${t('cart')} <span class="muted num" style="font-size:15px">(${count()})</span></h3><button class="iconbtn" data-close aria-label="Close">${ic('x')}</button></div>
  ${S.cart.length?`<div class="dr-b"><div class="ship-bar"><span>${left?`${t('freeShip')} <b class="num">${money(FREE)}</b> · ${L()==='id'?'kurang':'add'} <b class="num">${money(left)}</b>`:`${ic('check','width:15px;height:15px;vertical-align:-3px')} ${t('freeOK')}`}</span><span class="t"><i style="width:${Math.min(100,sub/FREE*100)}%"></i></span></div>
  ${S.cart.map((l,i)=>{const p=byslug(l.s);return `<div class="line"><a class="th" href="#p-${p.slug}" data-close>${pimg(p,l.pot)}</a><div><div class="t1"><span>${esc(nm(p))}</span><span class="num">${money(lineUnit(l)*l.q)}</span></div><small>${t('pot')}: ${tx(POTS.find(o=>o.k===l.pot).n)}</small><div class="ctl"><div class="qty sm"><button type="button" data-dq="${i}" aria-label="-">−</button><input class="num" value="${l.q}" readonly aria-label="${t('qtyL')}"><button type="button" data-iq="${i}" aria-label="+">+</button></div><button class="link" data-rm="${i}">${t('remove')}</button></div></div></div>`}).join('')}
  <div style="background:var(--paper);border:1.5px solid var(--line);border-radius:18px;padding:12px 14px;font-size:13.5px;display:flex;gap:10px;align-items:center">${ic('gift')}<div style="flex:1"><b>${t('giftAdd')}</b><div class="muted">${S.gift.wrap==='box'?(L()==='id'?'Box kraft gantung':'Hanging kraft box'):S.gift.wrap==='plain'?(L()==='id'?'Tanpa bungkus':'No gift wrap'):(L()==='id'?'Goni + pita':'Burlap + bow')}${S.gift.card?` · Kartu untuk ${esc(S.gift.to||'…')}`:''}</div></div><a class="link" href="#home" data-jump="gift" data-close>${L()==='id'?'Ubah':'Edit'}</a></div></div>
  <div class="dr-f"><div class="sum"><span>${t('subtotal')}</span><span class="num">${money(sub)}</span></div><a class="btn dark lg block" href="#checkout" data-close>${t('checkout')}</a><a class="btn wa block" target="_blank" rel="noopener" href="${waLink(cartText())}">${ic('wa')} ${t('orderWA')}</a></div>`
  :`<div class="dr-b" style="text-align:center;padding-top:40px"><div style="width:120px;height:120px;margin:0 auto">${PArt.plant('rosette','burlap')}</div><h3 style="font-size:20px;margin-top:10px">${t('empty')}</h3><p class="muted">${t('emptyP')}</p><div style="display:grid;gap:12px;margin-top:18px;text-align:left">${P.filter(p=>p.care===1).sort((a,b)=>b.pop-a.pop).slice(0,3).map(p=>`<div class="line"><a class="th" href="#p-${p.slug}" data-close>${pimg(p)}</a><div><div class="t1"><span>${esc(nm(p))}</span><span class="num">${money(p.price)}</span></div><button class="btn sm" data-qa="${p.slug}" style="margin-top:8px">${t('add')}</button></div></div>`).join('')}</div></div>`}`;
  $$('[data-close]',d).forEach(a=>a.addEventListener('click',()=>{if(a.dataset.jump)S.jump=a.dataset.jump;close()}));
  $$('[data-dq]',d).forEach(b=>b.onclick=()=>{const l=S.cart[+b.dataset.dq];l.q--;if(!l.q)S.cart.splice(+b.dataset.dq,1);save();draw()});
  $$('[data-iq]',d).forEach(b=>b.onclick=()=>{S.cart[+b.dataset.iq].q++;save();draw()});
  $$('[data-rm]',d).forEach(b=>b.onclick=()=>{const l=S.cart.splice(+b.dataset.rm,1)[0];save();draw();toast(nm(byslug(l.s))+' '+(L()==='id'?'dihapus':'removed'),{t:'Undo',run:()=>{S.cart.push(l);save();openCart()}})});
  $$('[data-qa]',d).forEach(b=>b.onclick=()=>{const p=byslug(b.dataset.qa);S.cart.push({s:p.slug,q:1,pot:'goni'});save();draw()})};
 draw()}
function cartText(extra){const lines=S.cart.map(l=>`• ${l.q}× ${nm(byslug(l.s))} (${tx(POTS.find(o=>o.k===l.pot).n)}) – ${money(lineUnit(l)*l.q)}`).join('\n');const g=S.gift;
 return (L()==='id'?'Halo Sangkarloka! Saya mau pesan:\n':'Hi Sangkarloka! I would like to order:\n')+lines+(g.card?`\n• ${L()==='id'?'Kartu':'Card'} Just For You – To: ${g.to||'-'} / From: ${g.from||'-'}${g.msg?` / "${g.msg}"`:''}`:'')+`\n${t('subtotal')}: ${money(subtotal())}`+(extra||'')}
function closeAll(){$$('.ov,.drawer,.modal-ov').forEach(x=>x.remove())}
function openSearch(){closeAll();const ov=document.createElement('div');ov.className='modal-ov';ov.innerHTML=`<div class="modal" role="dialog" aria-label="${t('search')}" style="width:min(640px,100%)"><div class="modal-h"><h3>${t('search')}</h3><button class="iconbtn" data-x aria-label="Close">${ic('x')}</button></div><div class="modal-b"><input class="input" id="sq" placeholder="${L()==='id'?'Cari echeveria, kaktus, hadiah…':'Search echeveria, cactus, gifts…'}" autocomplete="off"><div id="sr" style="display:grid;gap:10px"></div></div></div>`;document.body.appendChild(ov);
 const close=()=>ov.remove();ov.addEventListener('click',e=>{if(e.target===ov||e.target.closest('[data-x]')||e.target.closest('a'))close()});
 const draw=()=>{const q=$('#sq').value.trim().toLowerCase();const l=P.filter(p=>!q||(nm(p)+' '+tx(p.latin)+' '+tx(p.desc)+' '+t(p.cat)).toLowerCase().includes(q)).slice(0,6);$('#sr').innerHTML=l.length?l.map(p=>`<a class="line" href="#p-${p.slug}" style="text-decoration:none"><span class="th">${pimg(p)}</span><span><span class="t1"><span>${esc(nm(p))}</span><span class="num">${money(p.price)}</span></span><small>${esc(tx(p.latin))}</small></span></a>`).join(''):`<p class="muted">${L()==='id'?'Tidak ditemukan':'No results'} “${esc(q)}”.</p>`};
 $('#sq').oninput=draw;draw();setTimeout(()=>$('#sq')?.focus(),30);document.addEventListener('keydown',function k(e){if(e.key==='Escape'){close();document.removeEventListener('keydown',k)}})}

/* ---------- CHECKOUT ---------- */
const CITIES=[['Jakarta',12000],['Bogor',15000],['Depok',15000],['Tangerang',15000],['Bekasi',15000],['Bandung',18000],['Yogyakarta',20000],['Semarang',20000],['Surabaya',22000],['Malang',22000],['Denpasar',28000],['Medan',32000],['Makassar',35000],['Lainnya',30000]];
function shipCost(){const c=S.co.info.city||'Jakarta';const base=(CITIES.find(x=>x[0]===c)||[0,30000])[1];const jabo=JABO.includes(c);let s=S.co.ship==='gosend'?25000:base+(S.co.ship==='sicepat'?5000:0);if(jabo&&subtotal()>=FREE&&S.co.ship!=='gosend')s=0;return s}
function pageCheckout(){if(!S.cart.length)return `<div class="wrap done"><h1 style="font-size:34px">${t('empty')}</h1><a class="btn dark lg" href="#shop">${t('shop')}</a></div>`;
 return `<div class="wrap page-h" style="padding-bottom:0"><div class="crumbs"><a href="#home">${t('home')}</a>/<span>${t('checkout')}</span></div><h1 style="font-size:clamp(30px,4vw,48px)">${t('checkout')}</h1></div><div class="wrap co"><div id="coM"></div><aside id="coS"></aside></div>`}
function bindCheckout(){if(!S.cart.length)return;const C=S.co,I=C.info;
 const sum=()=>{const sub=subtotal(),sh=shipCost();$('#coS').innerHTML=`<b style="font-family:var(--f-display);font-size:18px">${L()==='id'?'Ringkasan':'Summary'}</b>${S.cart.map(l=>{const p=byslug(l.s);return `<div class="line" style="grid-template-columns:60px 1fr"><span class="th" style="width:60px;height:60px">${pimg(p,l.pot)}</span><span><span class="t1"><span style="font-size:14px">${l.q}× ${esc(nm(p))}</span><span class="num">${money(lineUnit(l)*l.q)}</span></span><small>${tx(POTS.find(o=>o.k===l.pot).n)}</small></span></div>`}).join('')}${S.gift.card?`<div class="sum"><span>${t('card')}</span><span class="num">${money(3000)}</span></div>`:''}
  <div style="border-top:1.5px solid var(--line);padding-top:12px;display:grid;gap:8px"><div class="sum"><span>${t('subtotal')}</span><span class="num">${money(sub)}</span></div><div class="sum"><span>${t('shipping')}${I.city?` (${I.city})`:''}</span><span class="num">${sh?money(sh):'Gratis'}</span></div><div class="sum total"><span>${t('total')}</span><span class="num">${money(sub+sh)}</span></div></div><p class="muted" style="font-size:12.5px">${t('demo')}</p>`};
 const steps=()=>`<div style="display:flex;gap:8px;margin-bottom:22px;flex-wrap:wrap">${[t('step1'),t('step2'),t('step3')].map((s,i)=>`<span class="pill-tag ${C.step===i+1?'dark':''}" style="${C.step>i+1?'background:var(--leaf-soft)':''}">${C.step>i+1?'✓':i+1} · ${s}</span>`).join('')}</div>`;
 const draw=()=>{const M=$('#coM');
  if(C.step===1){M.innerHTML=steps()+`<form id="f1" novalidate><div class="two"><div class="field"><label for="nm">${t('fullName')}</label><input class="input" id="nm" autocomplete="name" value="${esc(I.nm||'')}"></div><div class="field"><label for="wa">${t('waNo')}</label><input class="input" id="wa" inputmode="tel" placeholder="08xx-xxxx-xxxx" value="${esc(I.wa||'')}"></div></div>
   <div class="field"><label for="ad">${t('address')}</label><textarea class="input" id="ad" autocomplete="street-address">${esc(I.ad||'')}</textarea></div><div class="two"><div class="field"><label for="ct">${t('cityL')}</label><select class="sel" id="ct" style="width:100%;border-radius:14px;height:48px">${CITIES.map(c=>`<option ${c[0]===(I.city||'Jakarta')?'selected':''}>${c[0]}</option>`).join('')}</select></div><div class="field"><label for="pc">${t('postal')}</label><input class="input" id="pc" inputmode="numeric" maxlength="5" value="${esc(I.pc||'')}"></div></div>
   <p class="err-t" id="e1" hidden></p><button class="btn dark lg">${t('cont')}</button></form>`;
   $('#ct').onchange=e=>{I.city=e.target.value;sum()};
   $('#f1').onsubmit=e=>{e.preventDefault();const v=id=>$('#'+id).value.trim();const bad=[];if(!v('nm'))bad.push('nm');if(!/^(\+?62|0)8\d{7,12}$/.test(v('wa').replace(/[\s-]/g,'')))bad.push('wa');if(v('ad').length<10)bad.push('ad');if(!/^\d{5}$/.test(v('pc')))bad.push('pc');
    $$('#f1 .input').forEach(i=>i.classList.toggle('err',bad.includes(i.id)));if(bad.length){$('#e1').hidden=false;$('#e1').textContent=bad.includes('wa')?(L()==='id'?'Nomor WhatsApp harus diawali 08 atau 62.':'WhatsApp number must start with 08 or 62.'):bad.includes('pc')?(L()==='id'?'Kode pos harus 5 angka.':'Postcode must be 5 digits.'):(L()==='id'?'Lengkapi kolom yang ditandai.':'Fill in the highlighted fields.');return}
    Object.assign(I,{nm:v('nm'),wa:v('wa'),ad:v('ad'),city:v('ct'),pc:v('pc')});C.step=2;draw();scrollTo({top:0,behavior:'smooth'})}}
  if(C.step===2){const jabo=JABO.includes(I.city);if(C.ship==='gosend'&&!jabo)C.ship='jne';M.innerHTML=steps()+`<form id="f2" style="display:grid;gap:10px">${[['jne','JNE REG',L()==='id'?'2–4 hari':'2–4 days',true],['sicepat','SiCepat BEST',L()==='id'?'1–2 hari · +Rp5.000':'1–2 days · +Rp5,000',true],['gosend','GoSend Same Day',jabo?(L()==='id'?'Hari ini, khusus Jabodetabek':'Today, Greater Jakarta only'):(L()==='id'?'Tidak tersedia untuk '+I.city:'Not available for '+I.city),jabo]].map(o=>`<label class="rc" style="${o[3]?'':'opacity:.5'}"><input type="radio" name="sh" value="${o[0]}" ${C.ship===o[0]?'checked':''} ${o[3]?'':'disabled'}><div><b>${o[1]}</b><small>${o[2]}</small></div></label>`).join('')}<button class="btn dark lg">${t('cont')}</button><button type="button" class="link" id="b1">← ${t('back')}</button></form>`;
   $$('[name=sh]').forEach(r=>r.onchange=()=>{C.ship=r.value;sum()});$('#b1').onclick=()=>{C.step=1;draw()};$('#f2').onsubmit=e=>{e.preventDefault();C.step=3;draw()}}
  if(C.step===3){M.innerHTML=steps()+`<form id="f3" style="display:grid;gap:10px">${[['bca','Transfer BCA Virtual Account',L()==='id'?'Dicek otomatis':'Verified automatically'],['qris','QRIS','GoPay, OVO, DANA, ShopeePay'],['cod','COD',JABO.includes(I.city)?(L()==='id'?'Bayar di tempat, Jabodetabek':'Cash on delivery, Greater Jakarta'):(L()==='id'?'Hanya Jabodetabek':'Greater Jakarta only')]].map(o=>`<label class="rc" style="${o[0]==='cod'&&!JABO.includes(I.city)?'opacity:.5':''}"><input type="radio" name="py" value="${o[0]}" ${C.pay===o[0]?'checked':''} ${o[0]==='cod'&&!JABO.includes(I.city)?'disabled':''}><div><b>${o[1]}</b><small>${o[2]}</small></div></label>`).join('')}<button class="btn leaf lg" id="place">${t('placeOrder')} · <span class="num">${money(subtotal()+shipCost())}</span></button><button type="button" class="link" id="b2">← ${t('back')}</button></form>`;
   $$('[name=py]').forEach(r=>r.onchange=()=>C.pay=r.value);if(C.pay==='cod'&&!JABO.includes(I.city)){C.pay='bca';$('[name=py][value=bca]').checked=true}$('#b2').onclick=()=>{C.step=2;draw()};
   $('#f3').onsubmit=e=>{e.preventDefault();const b=$('#place');b.disabled=true;b.textContent='…';setTimeout(()=>{const no='SKL-'+(2610+S.orders.length);const total=subtotal()+shipCost();S.last={no,total,pay:C.pay,info:{...I},text:cartText(`\n${t('shipping')}: ${money(shipCost())}\n${t('total')}: ${money(total)}\nNo. order: ${no}\n${I.nm}, ${I.city}`)};S.orders.unshift(S.last);S.cart=[];S.gift={wrap:'goni',card:false,to:'',from:'',msg:''};C.step=1;save();location.hash='order'},1000)}}
  sum()};draw()}
function pageOrder(){const o=S.last;if(!o)return `<div class="wrap done"><a class="btn dark lg" href="#shop">${t('shop')}</a></div>`;
 const pay=o.pay==='bca'?`<span class="muted">BCA Virtual Account</span><b class="code num">8808 0000 ${o.no.slice(4)}</b><span class="pill-tag" style="justify-self:center">DEMO</span><span class="muted">a.n. Sangkarloka · ${money(o.total)}</span>`:o.pay==='qris'?`<span class="muted">QRIS</span><div style="width:150px;height:150px;background:repeating-conic-gradient(var(--ink) 0 25%,#fff 0 50%) 0 0/18px 18px;border-radius:12px;border:8px solid #fff;box-shadow:0 0 0 1.5px var(--line)"></div><span class="muted">${money(o.total)}</span>`:`<span class="muted">COD</span><b>${L()==='id'?'Bayar ke kurir saat paket tiba':'Pay the courier on delivery'}</b>`;
 return `<div class="wrap done"><div class="ok">${ic('check')}</div><span class="eyebrow">${o.no}</span><h1 style="font-size:clamp(30px,5vw,54px)">${t('thanks')}, ${esc(o.info.nm.split(' ')[0])}!</h1><p class="muted">${t('orderOK')}</p><div class="va"><b style="font-size:14px">${t('payTo')}</b>${pay}</div><div style="display:flex;gap:10px;flex-wrap:wrap;justify-content:center"><a class="btn wa lg" href="${waLink(o.text)}" target="_blank" rel="noopener">${ic('wa')} ${t('confirmWA')}</a><a class="btn lg" href="#shop">${t('keepShop')}</a></div><p class="muted" style="font-size:12.5px">${t('demo')}</p></div>`}

/* ---------- STORY ---------- */
function pageStory(){return `<div class="wrap page-h"><div class="crumbs"><a href="#home">${t('home')}</a>/<span>${t('story')}</span></div></div>
 <section class="wrap story"><div><h1 style="font-size:clamp(34px,5vw,62px);letter-spacing:-.05em">${t('storyT')} <span style="font-family:var(--f-hand);color:var(--leaf);font-weight:600;letter-spacing:0">${t('storyH')}</span></h1><p style="font-size:18px;color:var(--fg-2);margin-top:20px;max-width:52ch">${t('storyP')}</p><div style="display:flex;gap:10px;margin-top:24px;flex-wrap:wrap"><a class="btn dark lg" href="#shop">${t('cta')}</a><a class="btn lg" href="https://instagram.com/${IG}" target="_blank" rel="noopener">${ic('ig')} @${IG}</a></div></div>${ph('hand-white-bg','','Tangan memegang tanaman','40% 50%')}</section>
 <section class="s wrap"><div class="steps3">${t('steps').map((s,i)=>`<div class="reveal"><b class="n">0${i+1}</b><h3 style="font-size:20px">${s[0]}</h3><p class="muted">${s[1]}</p></div>`).join('')}</div></section>
 <section class="s wrap"><div class="gift-photos" style="grid-template-columns:repeat(3,1fr)">${['hands-plants','pink-succulent','succulent-green'].map(k=>ph(k,'','Succulent')).join('')}</div></section>`}

/* ---------- router ---------- */
let LOGO='',LOGO_W='';
function route(){clearInterval(S.lensT);closeAll();const h=(location.hash||'#home').slice(1)||'home';let body,bind,cur=h,isHome=false,title='Sangkarloka · Mini Plant House';
 if(h.startsWith('p-')&&byslug(h.slice(2))){const p=byslug(h.slice(2));body=pageProduct(p);bind=()=>bindProduct(p);cur='shop';title=nm(p)+' · Sangkarloka'}
 else if(h==='shop'){body=pageShop();bind=bindShop;title=t('shop')+' · Sangkarloka'}
 else if(h==='story'){body=pageStory();title=t('story')+' · Sangkarloka'}
 else if(h==='checkout'){body=pageCheckout();bind=bindCheckout;title=t('checkout')+' · Sangkarloka'}
 else if(h==='order'){body=pageOrder();title='Order · Sangkarloka'}
 else{cur='home';isHome=true;body=pageHome();bind=bindHome}
 document.title=title;mount(cur,body,isHome);bind&&bind();
 if(S.jump){const j=S.jump;S.jump=null;setTimeout(()=>document.getElementById(j)?.scrollIntoView(),60)}else if(!h.startsWith('#'))scrollTo(0,0)}
addEventListener('hashchange',()=>{const h=location.hash.slice(1);if(['pick','quiz','gift','care','moments','bulk','faq'].includes(h)){document.getElementById(h)?.scrollIntoView({behavior:'smooth'});return}route()});
window.__boot=(logo,logoW)=>{LOGO=logo;LOGO_W=logoW;route()};
})();
