(()=>{
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const ic=(n,st='')=>`<svg class="i"${st?` style="${st}"`:''}><use href="#i-${n}"/></svg>`;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ls=(k,v)=>{try{if(v===undefined)return JSON.parse(localStorage.getItem('hr_'+k));localStorage.setItem('hr_'+k,JSON.stringify(v))}catch(e){return null}};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const ph=(k,alt='',pos='',ini='')=>`<div class="ph">${ini?`<span class="ini">${esc(ini)}</span>`:''}${k?`<img src="photos/${k}.jpg" alt="${esc(alt)}" loading="lazy"${pos?` style="object-position:${pos}"`:''} onerror="this.remove()">`:''}</div>`;
const hash=s=>{let h=2166136261;for(const c of s)h=Math.imul(h^c.charCodeAt(0),16777619);return h>>>0};
const RM=matchMedia('(prefers-reduced-motion:reduce)').matches;

/* ---------- currency ---------- */
const CUR={USD:{r:1,loc:'en-US'},EUR:{r:.92,loc:'en-IE'},AUD:{r:1.52,loc:'en-AU'}};
const money=(usd,o={})=>{const c=CUR[S.cur];const v=usd*(o.raw?1:c.r);return new Intl.NumberFormat(c.loc,{style:'currency',currency:S.cur,maximumFractionDigits:0,notation:o.compact?'compact':'standard'}).format(v)};
const curSel=id=>`<label class="sr" for="${id}">Currency</label><select class="cur-sel" id="${id}" data-cur>${Object.keys(CUR).map(k=>`<option ${k===S.cur?'selected':''}>${k}</option>`).join('')}</select>`;

/* ---------- data ---------- */
const OFF=[
 {k:'ny',city:'New York',tz:'America/New_York',ab:'ET',addr:'118 Hudson Street, 9th Floor · New York, NY 10013',tel:'+1 (212) 555-0148',mail:'newyork@haldenrowe.example',img:'office-glass'},
 {k:'ldn',city:'London',tz:'Europe/London',ab:'UK',addr:'4 Carlisle Yard, 3rd Floor · London EC2A 4NS',tel:'+44 20 7946 0321',mail:'london@haldenrowe.example',img:'open-office'},
 {k:'syd',city:'Sydney',tz:'Australia/Sydney',ab:'AET',addr:'Level 18, 60 Margaret Street · Sydney NSW 2000',tel:'+61 2 5550 1874',mail:'sydney@haldenrowe.example',img:'office-work'}];
const off=k=>OFF.find(o=>o.k===k);
const SV=[
 {s:'wealth-planning',t:'Wealth Planning',cat:'wealth',ic:'chart',img:'advisor-client',pos:'50% 40%',from:2400,unit:'one-time plan',dur:'4–6 weeks',sh:'One living plan for cash flow, investments, protection and the big goals in between.',tags:['Cash flow','Investments','Protection'],
  body:['Most people do not need more financial products. They need someone to connect the ones they already have. Wealth planning starts with where your money goes today and ends with a written plan that tells you what to do next month, next year and in ten years.','We model your income, spending, savings, investments and insurance together, stress-test the plan against a bad market or a lost job, and then stay with you to put it into action.'],
  inc:[['Net-worth & cash-flow map','Every account, debt and commitment in one clear picture.'],['Goal modelling','Home, education, sabbatical or early retirement, priced and scheduled.'],['Investment review','Fees, risk and allocation checked against your goals.'],['Protection audit','Life, income and property cover sized to what you actually need.']],who:['Professionals with growing income and scattered accounts','Couples planning a big life change','Anyone who wants a second opinion on their current plan']},
 {s:'tax-strategy',t:'Tax Strategy',cat:'tax',ic:'scale',img:'calc-paper',pos:'50% 50%',from:1800,unit:'per engagement',dur:'2–4 weeks',sh:'Year-round planning that keeps more of what you earn, within the rules.',tags:['Personal tax','Business tax','Cross-border'],
  body:['Good tax work happens before the year ends, not after. We look at how income is earned, held and withdrawn and find the legitimate ways to reduce what you owe.','For clients with income in more than one country we coordinate with local accountants in the US, UK, EU and Australia so nothing falls through the gaps.'],
  inc:[['Annual tax roadmap','Key dates and decisions for the year ahead.'],['Structure review','Sole trader, company, trust or partnership: what fits now.'],['Investment tax efficiency','Account types, timing and loss harvesting.'],['Cross-border coordination','Residency, treaties and reporting obligations.']],who:['Business owners and contractors','Employees with equity or bonuses','Expats and globally mobile families']},
 {s:'business-advisory',t:'Business Advisory',cat:'business',ic:'brief',img:'meet-2',pos:'50% 40%',from:4800,unit:'per month',dur:'Ongoing',sh:'Fractional CFO support: forecasts, pricing, funding and the board pack.',tags:['Forecasting','Pricing','Funding'],
  body:['Growing companies often reach a point where the founder is still the finance team. Our advisors step in as a fractional CFO, building the forecasts, reporting and discipline a larger business needs.','We sit in on leadership meetings, prepare investors and lenders, and help you make decisions with numbers you trust.'],
  inc:[['13-week cash forecast','Updated weekly so surprises arrive early.'],['Monthly management pack','KPIs, margins and variance explained in plain language.'],['Pricing & unit economics','Where you make money and where you do not.'],['Funding readiness','Debt, equity or grants, with the model to back it.']],who:['Founder-led companies from $2M to $50M revenue','Teams preparing for a raise or a loan','Boards that want clearer reporting']},
 {s:'retirement-planning',t:'Retirement Planning',cat:'retire',ic:'ret',img:'advisor-tablet',pos:'50% 50%',from:2400,unit:'one-time plan',dur:'3–5 weeks',sh:'Turn savings into a dependable income you will not outlive.',tags:['Pensions','Income','Timing'],
  body:['Retirement is less about a number and more about a paycheck. We work out when you can stop working, which accounts to draw from first and how to keep a steady income through good and bad markets.','Pensions, 401(k)s, SIPPs and superannuation all have their own rules. We bring them into one plan and review it with you every year.'],
  inc:[['Retirement date analysis','Three scenarios: early, planned and cautious.'],['Withdrawal sequencing','Which account to draw from, and when.'],['Pension & super consolidation','Fewer accounts, lower fees, one view.'],['Annual income review','Adjustments as markets and life change.']],who:['People within 15 years of retirement','Recent retirees building an income plan','Anyone with pensions in more than one country']},
 {s:'estate-coordination',t:'Estate Coordination',cat:'estate',ic:'shield',img:'handshake',pos:'40% 50%',from:1500,unit:'per engagement',dur:'3–6 weeks',sh:'Make sure what you have built goes where you want, with the paperwork to prove it.',tags:['Wills & trusts','Succession','Gifting'],
  body:['We are not a law firm, but we make sure the financial side of your estate is ready for your lawyer. That means knowing what you own, who inherits it and how it will be taxed.','We work alongside your solicitor or attorney, prepare the numbers they need and check that beneficiaries, titles and trusts actually match your wishes.'],
  inc:[['Estate inventory','Assets, titles and beneficiaries in one register.'],['Inheritance tax estimate','What your estate could owe today and later.'],['Gifting strategy','Helping family now, tax-efficiently.'],['Lawyer coordination','A brief your legal advisor can act on.']],who:['Families with property in more than one place','Parents planning to help children buy a home','Business owners thinking about succession']},
 {s:'exit-planning',t:'Exit & Succession',cat:'business',ic:'ne',img:'meet-6',pos:'50% 50%',from:25000,unit:'project, from',dur:'6–18 months',sh:'Prepare your company, and your finances, for a sale or handover.',tags:['Valuation','Buyer prep','After the sale'],
  body:['A successful exit starts two or three years before the sale. We help you understand what the business is worth, what buyers will look for and what you need to fix first.','We also plan the personal side: what the proceeds need to do for you, how they will be taxed and what life looks like the day after.'],
  inc:[['Valuation range','Based on comparable deals and your numbers.'],['Readiness scorecard','The 20 things buyers check, graded.'],['Data room preparation','Clean financials before due diligence starts.'],['Post-sale wealth plan','Turning proceeds into long-term security.']],who:['Owners planning to sell in the next 1–3 years','Family businesses passing to the next generation','Founders weighing an offer']}];
const svc=s=>SV.find(x=>x.s===s);
const CATN={wealth:'Wealth',tax:'Tax',business:'Business',retire:'Retirement',estate:'Estate'};
const ADV=[
 {id:'maya',n:'Maya Lindqvist',r:'Partner, Wealth Planning',cat:'wealth',off:'ny',img:'p-w1',pos:'50% 18%',cred:['CFP®','CFA'],yrs:16,lang:'English, Swedish',bio:'Maya leads our wealth practice in New York. She spent eight years at a global private bank before co-founding Halden & Rowe to offer the same depth of advice without the product sales.',focus:['Dual-income families','Equity compensation','Education funding']},
 {id:'daniel',n:'Daniel Okafor',r:'Partner, Business Advisory',cat:'business',off:'ldn',img:'p-m5',pos:'50% 15%',cred:['ACA','MBA'],yrs:14,lang:'English, Yoruba',bio:'Daniel runs our fractional CFO team. A chartered accountant by training, he has helped more than forty founder-led businesses build forecasting and reporting that boards trust.',focus:['Fractional CFO','Fundraising','Pricing strategy']},
 {id:'sophie',n:'Sophie Marchetti',r:'Head of Tax Strategy',cat:'tax',off:'ldn',img:'p-w2',pos:'50% 18%',cred:['CTA','ACCA'],yrs:12,lang:'English, Italian, French',bio:'Sophie specialises in cross-border tax for families and business owners with ties to the UK, EU and US. She coordinates with local accountants so clients get one joined-up answer.',focus:['Cross-border tax','Business structures','Residency changes']},
 {id:'james',n:'James Whitfield',r:'Senior Advisor, Retirement',cat:'retire',off:'ny',img:'p-m1',pos:'50% 20%',cred:['CFP®','RICP®'],yrs:19,lang:'English',bio:'James has spent almost two decades helping clients move from saving to spending. He is known for patient meetings and very clear income plans.',focus:['Retirement income','Pension decisions','Social Security timing']},
 {id:'leila',n:'Leila Haddad',r:'Estate & Succession Advisor',cat:'estate',off:'syd',img:'p-w3',pos:'50% 25%',cred:['CFP®','TEP'],yrs:11,lang:'English, Arabic',bio:'Leila works with families and business owners on the financial side of estate and succession planning, working closely with their lawyers in Australia and abroad.',focus:['Family succession','Trust structures','Gifting plans']},
 {id:'lucas',n:'Lucas Brenner',r:'Director, Exit Planning',cat:'business',off:'ldn',img:'p-m3',pos:'50% 25%',cred:['CFA','CF'],yrs:15,lang:'English, German',bio:'Lucas advised on mid-market deals for a decade before joining us. He now prepares owners for a sale two to three years ahead, on both the business and the personal side.',focus:['Exit readiness','Valuation','Post-sale planning']},
 {id:'hannah',n:'Hannah Kerr',r:'Wealth Advisor',cat:'wealth',off:'syd',img:'p-w4',pos:'50% 20%',cred:['CFP®'],yrs:8,lang:'English',bio:'Hannah helps young professionals and families in Sydney build their first real plan, from superannuation to buying a home.',focus:['First home planning','Superannuation','Young families']},
 {id:'samuel',n:'Samuel Adeyemi',r:'Tax & Business Advisor',cat:'tax',off:'ny',img:'p-m4',pos:'50% 25%',cred:['CPA'],yrs:9,lang:'English, French',bio:'Samuel works with contractors, small business owners and startup employees on tax planning and structure, keeping the paperwork simple and the savings real.',focus:['Small business tax','Stock options','Contractor income']}];
const adv=id=>ADV.find(a=>a.id===id);
const TM=[
 {q:'For the first time we have one plan that covers the house, the kids’ schooling and our pensions. The quarterly reviews keep us honest.',n:'Rachel & Tom Ellison',r:'Clients since 2019 · New York',img:'p-w6',pos:'50% 30%'},
 {q:'Daniel’s team rebuilt our forecasting in six weeks. When we went to the bank for a facility, they said it was the clearest pack they had seen all year.',n:'Marcus Hale',r:'Founder, Parcel & Pine · London',img:'p-m6',pos:'50% 30%'},
 {q:'Sophie untangled three countries’ worth of tax for our move to Sydney. We knew exactly what to file and when.',n:'Elena Rossi',r:'Relocated client · Sydney',img:'p-w5',pos:'55% 30%'},
 {q:'We sold the company eighteen months after the first meeting. The readiness scorecard made due diligence almost boring.',n:'Arjun Mehta',r:'Former CEO, Kestrel Labs',img:'p-m2',pos:'50% 25%'}];
const ARTS=[
 {s:'year-end-tax-checklist',t:'The year-end tax checklist we give every client',cat:'Tax',min:6,date:'Sep 18, 2026',img:'meet-1',ex:'Twelve decisions worth making before December 31, from pension top-ups to realising losses.',
  body:['Every autumn we sit down with clients and run through the same short list. None of it is complicated, but most of it only works if you do it before the tax year closes.',{h:'Start with contributions'},'Retirement accounts are still the simplest way to reduce this year’s bill. Check how much allowance you have left and whether carry-forward rules let you use earlier years.','If you run a company, compare the cost of paying yourself a bonus with an employer pension contribution. The difference is often larger than people expect.',{h:'Then look at your investments'},'Losses can be useful. Selling a position that has fallen and buying something similar lets you bank the loss against gains elsewhere, as long as you respect the local wash-sale or bed-and-breakfast rules.','Finally, write down what changed this year: a new job, a move, a child, a sale. Most tax surprises start with a life event nobody mentioned to their accountant.']},
 {s:'fractional-cfo-signs',t:'Five signs your business needs a fractional CFO',cat:'Business',min:5,date:'Sep 4, 2026',img:'meet-3',ex:'Growth hides problems. Here is how to tell when the founder should stop being the finance team.',
  body:['The first finance hire is often an accountant who records the past. What many growing businesses need first is someone who plans the future.',{h:'You cannot answer the cash question quickly'},'If “how much runway do we have?” takes a week to answer, forecasting is overdue. A 13-week cash view is the simplest fix.',{h:'Margins are a guess'},'When pricing decisions are based on feel, profitable customers subsidise unprofitable ones. Unit economics make the trade-offs visible.','Other signs: the board pack arrives late, lenders ask questions you cannot answer, and the founder spends Sunday nights in spreadsheets. A fractional CFO gives you senior judgement for a few days a month, without a full-time salary.']},
 {s:'retirement-income-order',t:'Which account should you draw from first in retirement?',cat:'Retirement',min:7,date:'Aug 21, 2026',img:'office-work',ex:'The order you spend your savings in can matter as much as how much you saved.',
  body:['Retirement savers spend decades thinking about how much to put away and very little time on how to take it out. Yet the order of withdrawals can change how long the money lasts by years.',{h:'The conventional order'},'A common starting point is taxable accounts first, then tax-deferred pensions, then tax-free accounts last. It lets the tax-advantaged money grow for longer.',{h:'Why the rule of thumb breaks'},'In practice, drawing a little from pensions in low-income years can fill lower tax bands that would otherwise go unused. Couples, state pension timing and inheritance plans all change the answer.','That is why we model withdrawal sequencing for each client, year by year, and revisit it every annual review.']},
 {s:'cross-border-move',t:'Moving countries? Sort these money questions first',cat:'Wealth',min:6,date:'Aug 7, 2026',img:'meet-8',ex:'Residency, pensions and bank accounts: a practical order of operations for a smooth move.',
  body:['An international move is exciting and administratively brutal. The financial side goes much better when it is handled in the right order.',{h:'Before you go'},'Understand when you stop being tax resident where you live now and when you become resident in the new country. The dates are rarely the same, and the gap matters.','Decide what happens to pensions and investment accounts. Some can stay, some should move and some will become expensive or difficult to manage from abroad.',{h:'In your first year'},'Open local accounts early, keep records of exchange rates on large transfers and book a review with an advisor who understands both systems before your first tax return is due.']}];
const art=s=>ARTS.find(a=>a.s===s);
const FAQ=[
 ['Are you fee-only?','Yes. We are paid by clients only: fixed fees or a transparent percentage of assets for Private Wealth. We do not receive commissions from product providers.'],
 ['What happens in the free intro call?','A 20-minute conversation with an advisor to understand what you need. You leave with an honest view of whether we are the right fit and what an engagement would cost.'],
 ['Can you work with clients in more than one country?','Yes. Our offices in New York, London and Sydney work together, and we coordinate with local accountants and lawyers where needed.'],
 ['Do I have to move my investments to you?','No. Planning and tax work are independent of where your money is held. Private Wealth clients can choose to have us manage portfolios, but it is never required.'],
 ['How often will we meet?','Plan clients have a delivery meeting and a 90-day check-in. Ongoing clients meet quarterly, with email and video access to their advisor in between.'],
 ['Is my data secure?','Documents are shared through an encrypted client portal with two-factor sign-in. We never ask for passwords to your bank or investment accounts.']];
const PLANS={
 ind:[{n:'Financial Plan',p:2400,u:'one-time',d:'A complete written plan with 90 days of follow-up.',f:['Discovery & data gathering','Written plan with action list','Delivery meeting + 90-day check-in','Email support during setup']},
      {n:'Ongoing Advice',p:450,u:'/ month',d:'Your advisor on call, with quarterly reviews.',feat:1,f:['Everything in Financial Plan','Quarterly review meetings','Unlimited email & video access','Annual tax roadmap']},
      {n:'Private Wealth',pct:'0.75%',u:'of assets / year',d:'For households with investable assets above ',min:1e6,f:['Everything in Ongoing Advice','Discretionary portfolio management','Estate & gifting coordination','Dedicated two-person team']}],
 biz:[{n:'Health Check',p:3900,u:'one-time',d:'A two-week review of your numbers and finance function.',f:['Cash, margin & pricing review','Finance process audit','Priorities for the next 12 months','Board-ready summary']},
      {n:'Fractional CFO',p:4800,u:'/ month',d:'Senior finance leadership, two to four days a month.',feat:1,f:['13-week cash forecast','Monthly management pack','Board & investor meetings','Funding readiness']},
      {n:'Exit Readiness',p:25000,u:'project, from',d:'Prepare the business and your finances for a sale.',f:['Valuation range','Readiness scorecard','Data room preparation','Post-sale wealth plan']}]};
const LOGOS=[['Kestrel Labs','M4 18 12 4l8 14z'],['Parcel & Pine','M12 3v18M5 10l7-7 7 7'],['Ovalis','M12 4a8 8 0 1 0 0 16 8 8 0 1 0 0-16'],['Brightline','M3 12h18M12 3v18'],['Asterfield','M12 3l2.6 6.4L21 12l-6.4 2.6L12 21l-2.6-6.4L3 12l6.4-2.6z'],['Monoline','M4 20V4l16 16V4'],['Veloa','M4 5l8 14 8-14']];

/* ---------- state ---------- */
const S={cur:ls('cur')||'USD',bookings:ls('bookings')||[],page:'',timers:[],
 bk:{step:1,svc:null,adv:null,fmt:null,date:null,time:null,info:{},local:false,resched:null,month:null},
 calc:{start:50000,monthly:1500,years:20,prof:'bal'},prA:'ind',advF:'all',insF:'All',tmI:0,off:'ny',jump:null,sent:null};
if(!CUR[S.cur])S.cur='USD';
const saveBk=()=>{ls('bookings',S.bookings);$$('.bkn').forEach(b=>{b.textContent=S.bookings.length;b.hidden=!S.bookings.length})};
const timer=(fn,ms)=>{const t=setInterval(fn,ms);S.timers.push(t);return t};

/* ---------- time zones & availability ---------- */
const USER_TZ=(()=>{try{return Intl.DateTimeFormat().resolvedOptions().timeZone||'UTC'}catch(e){return 'UTC'}})();
const tzParts=(tz,d)=>{const p={};new Intl.DateTimeFormat('en-US',{timeZone:tz,hourCycle:'h23',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',weekday:'short'}).formatToParts(d).forEach(x=>p[x.type]=x.value);return p};
const tzOff=(tz,d)=>{const p=tzParts(tz,d);return (Date.UTC(+p.year,+p.month-1,+p.day,+p.hour%24,+p.minute,+p.second)-d.getTime())/6e4};
const toUTC=(ds,tm,tz)=>{const [y,m,d]=ds.split('-').map(Number),[h,mi]=tm.split(':').map(Number);const g=Date.UTC(y,m-1,d,h,mi);return new Date(g-tzOff(tz,new Date(g))*6e4)};
const officeToday=tz=>{const p=tzParts(tz,new Date());return {ds:`${p.year}-${p.month}-${p.day}`,hm:`${p.hour%24}`.padStart(2,'0')+':'+p.minute}};
const TIMES=['09:00','09:30','10:00','10:30','11:00','11:30','13:00','13:30','14:00','14:30','15:00','15:30','16:00','16:30'];
const isWeekend=ds=>{const d=new Date(ds+'T12:00:00Z').getUTCDay();return d===0||d===6};
function slots(aid,ds){const a=adv(aid);if(!a||isWeekend(ds))return [];const tz=off(a.off).tz,now=officeToday(tz);if(ds<now.ds)return [];
 return TIMES.map(t=>({t,free:(hash(aid+ds+t)%100)>40&&!(ds===now.ds&&t<=now.hm)&&!S.bookings.some(b=>b.adv===aid&&b.date===ds&&b.time===t&&b.id!==S.bk.resched)}))}
const addDays=(ds,n)=>{const d=new Date(ds+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10)};
function nextSlot(aid){const tz=off(adv(aid).off).tz;let ds=officeToday(tz).ds;for(let i=0;i<30;i++){const f=slots(aid,ds).find(x=>x.free);if(f)return {ds,t:f.t};ds=addDays(ds,1)}return null}
const fmtDate=(ds,o={weekday:'short',month:'short',day:'numeric'})=>new Date(ds+'T12:00:00Z').toLocaleDateString('en-US',{...o,timeZone:'UTC'});
const fmtTime=t=>{const [h,m]=t.split(':').map(Number);return `${(h%12)||12}:${String(m).padStart(2,'0')} ${h<12?'AM':'PM'}`};
const localTime=(ds,t,tz)=>toUTC(ds,t,tz).toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit',timeZone:USER_TZ});
const localDate=(ds,t,tz)=>toUTC(ds,t,tz).toLocaleDateString('en-US',{weekday:'short',month:'short',day:'numeric',timeZone:USER_TZ});

/* ---------- shell ---------- */
function nav(cur){const L=(h,t)=>`<a href="#${h}" ${cur===h?'aria-current="page"':''}>${t}</a>`;
 return `<header class="nav" id="nav"><div class="bar"><a class="logo" href="#home" aria-label="Halden & Rowe home"><span class="m"><svg viewBox="0 0 24 24" fill="none" stroke="#fff" stroke-width="2.2" stroke-linecap="round"><path d="M6 4v16M18 4v16M6 12h12"/></svg></span><span><b>Halden &amp; Rowe</b><small>Wealth · Business</small></span></a>
 <nav class="nl" aria-label="Main">${L('services','Services')}${L('advisors','Advisors')}${L('insights','Insights')}<a href="#pricing">Pricing</a><a href="#contact">Contact</a></nav><span class="sp"></span>
 <a class="ib" href="#book" aria-label="My consultations" title="My consultations">${ic('cal')}<span class="n num bkn" ${S.bookings.length?'':'hidden'}>${S.bookings.length}</span></a>
 <a class="btn cit bk" href="#book" style="margin-left:8px">Book a consultation<span class="go">${ic('ne','width:15px;height:15px')}</span></a>
 <button class="ib burger" id="burger" aria-label="Menu" aria-expanded="false">${ic('menu')}</button></div></header>
 <nav class="mm" id="mm" aria-label="Mobile">${['services:Services','advisors:Advisors','insights:Insights','pricing:Pricing','contact:Contact'].map(x=>{const [h,t]=x.split(':');return `<a href="#${h}">${t}</a>`}).join('')}<a class="btn" href="#book">Book a consultation</a></nav>`}
function footer(){return `<footer class="f"><div class="wrap"><div class="fg">
 <div><a class="logo" href="#home"><span class="m"><svg viewBox="0 0 24 24" fill="none" stroke="#fff" stroke-width="2.2" stroke-linecap="round"><path d="M6 4v16M18 4v16M6 12h12"/></svg></span><span><b>Halden &amp; Rowe</b><small style="color:#8C98C0">Wealth · Business</small></span></a><p style="margin-top:16px;max-width:36ch">Independent, fee-only advice for families, founders and finance teams. New York · London · Sydney.</p></div>
 <div><h4>Services</h4>${SV.slice(0,5).map(s=>`<a href="#service-${s.s}">${s.t}</a>`).join('')}</div>
 <div><h4>Firm</h4><a href="#advisors">Advisors</a><a href="#insights">Insights</a><a href="#pricing">Pricing</a><a href="#book">Book a consultation</a><a href="#contact">Contact</a></div>
 <div><h4>Monthly insights</h4><p style="font-size:14.5px">One email a month. Practical, no product pitches.</p><form class="nlf" id="nlf" novalidate><label class="sr" for="nle">Email</label><input class="input" id="nle" type="email" placeholder="you@company.com" autocomplete="email"><button class="btn cit" type="submit">Join</button></form><p class="err-t" id="nlerr" hidden style="margin-top:6px;color:#FF8A8D">Enter a valid email address.</p><div style="margin-top:18px">${curSel('fcur')}</div></div></div>
 <div class="fbig">Halden &amp; Rowe</div>
 <div class="fbot"><span>© 2026 Halden &amp; Rowe (fictional firm). Illustrations only, not financial advice.</span><span>Demo website by Organoo Studio</span></div></div></footer>`}
function mount(cur,body){$('#root').innerHTML=nav(cur)+`<main id="main">${body}</main>`+footer()+(S.demoOff?'':`<div class="demo" id="demo">Demo<span class="x3">&nbsp;· Organoo Studio</span><button type="button" aria-label="Hide demo label">${ic('x','width:12px;height:12px')}</button></div>`);
 $('#burger').onclick=()=>{const m=$('#mm');m.classList.toggle('open');$('#burger').setAttribute('aria-expanded',m.classList.contains('open'))};
 $$('#mm a').forEach(a=>a.addEventListener('click',()=>$('#mm').classList.remove('open')));
 $('#demo button')?.addEventListener('click',()=>{S.demoOff=1;$('#demo').remove()});
 $('#nlf').onsubmit=e=>{e.preventDefault();const v=$('#nle').value.trim();const ok=/^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test(v);$('#nlerr').hidden=ok;$('#nle').classList.toggle('err',!ok);if(ok){$('#nle').value='';toast('Subscribed. First issue arrives next month.')}};
 bindCur(document)}
function bindCur(root){$$('[data-cur]',root).forEach(s=>s.onchange=()=>{S.cur=s.value;ls('cur',S.cur);$$('[data-cur]').forEach(x=>x.value=S.cur);document.dispatchEvent(new Event('cur'))})}
function toast(msg){const t=document.createElement('div');t.className='toast';t.innerHTML=ic('check')+esc(msg);$('#toasts').appendChild(t);setTimeout(()=>{t.style.transition='opacity .3s';t.style.opacity=0;setTimeout(()=>t.remove(),300)},3200)}
const sh=(eb,h,p='',extra='')=>`<div class="sh"><div><span class="eyebrow rv">${eb}</span><h2 class="rv" style="--dl:.08s">${h}</h2></div>${p||extra?`<div class="rv" style="--dl:.16s;display:grid;gap:16px;justify-items:start">${p?`<p>${p}</p>`:''}${extra}</div>`:''}</div>`;

/* ---------- HOME ---------- */
const HW=['Clear','advice','for','@','the','decisions','that','shape','your','<em>future.</em>'];
function pageHome(){const nx=nextSlot('maya');
 return `<section class="hero"><div class="wrap"><div class="h-top">
  <span class="h-badge"><b><i></i>Taking new clients</b><span class="x2">Fee-only · Fiduciary · Since 2008</span></span>
  <h1 class="h-title">${HW.map((w,i)=>w==='@'?`<span class="pill" aria-hidden="true">${['handshake','advisor-client','pair-laptop'].map((k,j)=>`<span class="ph ${j?'':'on'}"><img src="photos/${k}.jpg" alt="" onerror="this.remove()"></span>`).join('')}</span> `:`<span class="w"><span style="--i:${i}">${w}</span></span> `).join('')}</h1>
  <p class="h-lead">Halden &amp; Rowe helps families, founders and finance teams make confident money decisions, with one advisor who knows your whole picture and a written plan you can actually follow.</p>
  <div class="h-cta"><a class="btn pri lg" href="#book">Book a free intro call<span class="go">${ic('ne','width:15px;height:15px')}</span></a><a class="btn ghost lg" href="#services">Explore services</a></div>
  <div class="h-proof"><span class="avs">${['p-w6','p-m6','p-w5','p-m2'].map(k=>ph(k,'','50% 25%')).join('')}</span><span><span class="stars">★★★★★</span> 4.9 from 640+ client reviews</span></div></div>
  <div class="bento">
   <div class="col" data-speed=".05" data-desk>
    <div class="bx cob rv" data-io="spark"><span class="big num" data-count="2.4" data-dec="1" data-pre="$" data-suf="B">$0B</span><div class="lb">Assets under advice</div>
     <svg class="spark" viewBox="0 0 200 70" preserveAspectRatio="none"><defs><linearGradient id="spk" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#FFC83D" stop-opacity=".45"/><stop offset="1" stop-color="#FFC83D" stop-opacity="0"/></linearGradient></defs><path class="a" d="M0 62 L22 55 L44 58 L66 44 L88 47 L110 34 L132 36 L154 22 L176 18 L200 6 L200 70 L0 70Z"/><path class="l" d="M0 62 L22 55 L44 58 L66 44 L88 47 L110 34 L132 36 L154 22 L176 18 L200 6"/></svg></div>
    <div class="bx cit rv" style="--dl:.1s"><span class="big num" data-count="96" data-suf="%">0%</span><div class="lb" style="opacity:1">Clients still with us after five years</div></div></div>
   <div class="col c2"><div class="bmain rv clip">${ph('group-table','Advisors meeting clients','50% 30%')}
    <div class="slot"><span style="width:44px;height:44px;border-radius:12px;background:var(--mint-soft);color:#08775D;display:grid;place-items:center">${ic('cal')}</span><div class="dt"><small>Next free intro call</small><b>${nx?`${fmtDate(nx.ds)} · ${fmtTime(nx.t)} ET`:'This week'}</b></div><a class="btn pri sm" href="#book" data-quick="maya">Book</a></div></div></div>
   <div class="col" data-speed="-.04" data-desk>
    <div class="bx bport rv" style="--dl:.15s">${ph('p-w1','Maya Lindqvist','50% 18%')}<div class="cap"><div><b>Talk to Maya</b><span>Partner · CFP®, CFA</span></div><button class="circ" data-adv="maya" aria-label="View Maya’s profile">${ic('ne','width:16px;height:16px')}</button></div></div>
    <div class="bx rv" style="--dl:.2s"><span class="muted" style="font-size:13.5px;font-weight:700">We help with</span><div class="rot" id="rot">${['Tax strategy','Retirement income','Exit planning','Cash flow','Estate plans'].map((w,i)=>`<span class="${i?'nx':''}">${w}</span>`).join('')}</div></div></div>
  </div></div></section>
 <section class="logos"><p>Advisors to founders and teams at</p><div class="mq"><div class="tr" id="mqt">${[...LOGOS,...LOGOS].map(l=>`<span class="lg"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linejoin="round"><path d="${l[1]}"/></svg>${l[0]}</span>`).join('')}</div></div></section>
 <section class="s wrap" id="about"><div class="intro"><div><span class="eyebrow rv">About the firm</span><p class="fill" id="fill">${'We are an independent, fee-only advisory firm. For eighteen years we have helped families, founders and finance teams turn complicated money questions into clear, confident decisions, with advice that is fiduciary by design and plans that keep working long after the first meeting.'.split(' ').map(w=>`<span class="wd${/independent|fee-only|fiduciary|clear,|confident/.test(w)?' hl':''}">${w}</span>`).join(' ')}</p>
  <div class="rv" style="margin-top:28px;display:flex;gap:10px;flex-wrap:wrap"><a class="btn" href="#advisors">Meet the advisors</a><a class="link" href="#process" style="align-self:center">How we work</a></div></div>
  <div class="im rv clip" style="position:relative">${ph('pair-laptop','Advisor reviewing a plan with a client','35% 50%')}</div></div>
  <div class="stats">${[['18','','yrs','Years advising clients'],['2.4','$','B','Assets under advice',1],['1200','','+','Households & businesses'],['96','','%','Five-year client retention']].map((s,i)=>`<div class="st rv ${i===1?'hi':''}" style="--dl:${i*.08}s"><b class="num" data-count="${s[0]}" ${s[4]?'data-dec="1"':''} data-pre="${s[1]}" data-suf="${s[2]}">0</b><span>${s[3]}</span></div>`).join('')}</div></section>
 <section class="hs" id="hs"><div class="hs-st"><div class="wrap hs-head"><div><span class="eyebrow">What we do</span><h2>Six ways we <em>help</em></h2></div><div class="hs-ctr"><span class="num" id="hsN">01</span><span class="hs-bar"><i id="hsBar"></i></span><span class="num">0${SV.length}</span></div></div>
  <div class="hs-track" id="hsT">${SV.map((s,i)=>`<a class="sv" href="#service-${s.s}">${ph(s.img,s.t,s.pos)}<div class="bd"><span class="no">0${i+1}</span><h3>${s.t}</h3><p>${s.sh}</p><ul>${s.tags.map(t=>`<li>${t}</li>`).join('')}</ul><div class="more">Learn more<span>${ic('ne','width:16px;height:16px')}</span></div></div></a>`).join('')}
   <div class="sv end"><span class="eyebrow">Not sure yet?</span><h3>Start with a free 20-minute intro call.</h3><p>Tell us what is on your mind. We will point you to the right advisor, or tell you honestly if we are not the right fit.</p><a class="btn" href="#book">Book the intro call</a></div></div></div></section>
 <section class="s wrap" id="process"><div class="proc"><div class="proc-l"><span class="eyebrow">How we work</span><h2>Four steps from <em>question</em> to plan</h2><p>Every engagement follows the same rhythm, so you always know what happens next and what it costs.</p><a class="btn pri" href="#book" style="margin-top:24px">Start with step one</a></div>
  <div class="steps" id="steps"><svg class="ln" preserveAspectRatio="none" viewBox="0 0 4 100"><line x1="2" y1="0" x2="2" y2="100"/><line class="f" id="lnF" x1="2" y1="0" x2="2" y2="100" pathLength="1" style="stroke-dasharray:1;stroke-dashoffset:1"/></svg>
  ${[['Discover','A free 20-minute call to understand your situation and goals. No forms, no sales pitch.',['Free','20 min','Video or phone']],['Diagnose','We gather documents through the secure portal and map your full picture: accounts, tax, cover and cash flow.',['1–2 weeks','Secure portal']],['Design','You receive a written plan with prioritised actions, costs and dates, walked through in a delivery meeting.',['Written plan','Delivery meeting']],['Deliver & review','We help you put it into action, then meet quarterly or yearly to keep it on track as life changes.',['Quarterly reviews','Annual tax roadmap']]].map((s,i)=>`<div class="step"><span class="dot">${i+1}</span><h3>${s[0]}</h3><p>${s[1]}</p><div class="meta">${s[2].map(m=>`<span class="tag">${m}</span>`).join('')}</div></div>`).join('')}</div></div></section>
 <section class="s wrap" id="calculator">${sh('Planning calculator','See what a plan could <em>grow into</em>','Move the sliders to see an illustrative projection. Your advisor builds the real version with your numbers, taxes and goals.',curSel('ccur'))}
  <div class="calc rv"><div class="calc-l">
   ${[['start','Starting amount',0,1000000,5000],['monthly','Monthly contribution',0,20000,100],['years','Years invested',1,40,1]].map(r=>`<div class="rg"><div class="t"><label for="c-${r[0]}">${r[1]}</label><b class="num" id="cv-${r[0]}"></b></div><input type="range" id="c-${r[0]}" min="${r[2]}" max="${r[3]}" step="${r[4]}" value="${S.calc[r[0]]}"></div>`).join('')}
   <div class="rg"><div class="t"><span>Investment profile</span></div><div class="seg" role="group" aria-label="Investment profile">${[['con','Cautious'],['bal','Balanced'],['gro','Growth']].map(p=>`<button type="button" data-prof="${p[0]}" aria-pressed="${S.calc.prof===p[0]}">${p[1]}</button>`).join('')}</div><span class="disc" id="c-rate"></span></div>
   <a class="btn pri" href="#book">Build my real plan</a></div>
  <div class="calc-r"><div class="res"><div><small>Projected value</small><b class="num" id="c-out">–</b></div><div class="legend"><span><i style="background:var(--cobalt)"></i>Projected</span><span><i style="background:var(--citrus)"></i>You contribute</span></div></div>
   <svg class="chart" id="chart" viewBox="0 0 600 260" role="img" aria-label="Projection chart"></svg>
   <div class="brk"><div><small>You contribute</small><b class="num" id="c-in">–</b></div><div><small>Growth</small><b class="num" id="c-gr">–</b></div><div><small>Growth share</small><b class="num" id="c-sh">–</b></div></div>
   <p class="disc">Illustrative only. Assumes a steady annual return of 4% (cautious), 6% (balanced) or 8% (growth), compounded monthly, before fees, taxes and inflation. Not financial advice.</p></div></div></section>
 <section class="s wrap" id="why">${sh('Why clients stay','Advice built around <em>you</em>, not products')}
  <div class="stack" id="stack">${[['Fiduciary, always','We are legally and contractually bound to act in your best interest. No commissions, no in-house funds, no sales targets.',['Fee-only since 2008','No product commissions','Written conflicts policy'],'meet-7'],['Fixed, visible fees','You see the full price before any work begins. Plans are fixed fee; ongoing advice is a flat monthly amount.',['Quote before you commit','No hidden percentages','Cancel ongoing advice any time'],'desk-laptop'],['One advisor who knows you','You work with the same named advisor, backed by specialists in tax, estate and business finance when you need them.',['Named lead advisor','Specialist team behind them','Reply within one business day'],'meet-5'],['Plans that keep working','A plan is only useful if it survives real life. We review it on a schedule and whenever something big changes.',['Quarterly or annual reviews','Life-event check-ins','Secure client portal'],'meeting-room']].map((c,i)=>`<article class="sc" style="--k:${i}"><div><span class="n">0${i+1} / 04</span><h3>${c[0]}</h3><p>${c[1]}</p><ul>${c[2].map(x=>`<li>${ic('check')}${x}</li>`).join('')}</ul></div>${ph(c[3],c[0],'50% 50%')}</article>`).join('')}</div></section>
 <section class="s wrap" id="team">${sh('The advisors','Senior people, <em>not</em> call centres','',`<div style="display:flex;gap:8px;flex-wrap:wrap" role="group" aria-label="Filter advisors">${advTabs()}</div>`)}<div class="adv" id="advGrid"></div><div style="text-align:center;margin-top:30px"><a class="btn" href="#advisors">See the full team</a></div></section>
 <section class="s wrap" id="stories"><div class="tm"><div class="tm-side rv"><span class="eyebrow">Client stories</span><h2>Trusted for the <em>long</em> run</h2><p class="muted" style="margin-top:14px;max-width:40ch">What clients say after a year or more of working with us.</p><div class="score"><div><b class="num" data-count="4.9" data-dec="1">0</b><span>Average rating</span></div><div><b class="num" data-count="640" data-suf="+">0</b><span>Verified reviews</span></div></div></div>
  <div class="tm-card rv" id="tmCard"><span class="q" aria-hidden="true">“</span><div class="tm-sl" id="tmSl">${TM.map((t,i)=>`<div class="tm-it ${i===S.tmI?'on':''}" aria-hidden="${i!==S.tmI}"><blockquote>${t.q}</blockquote><div class="who">${ph(t.img,t.n,t.pos)}<div><b>${t.n}</b><span>${t.r}</span></div></div></div>`).join('')}</div>
   <div class="tm-nav"><div class="tm-dots" id="tmD">${TM.map((_,i)=>`<button type="button" aria-label="Story ${i+1}" aria-current="${i===S.tmI}"></button>`).join('')}</div><button class="rbtn" id="tmP" aria-label="Previous">${ic('left')}</button><button class="rbtn" id="tmN" aria-label="Next">${ic('arrow')}</button></div></div></div></section>
 <section class="s wrap" id="pricing">${sh('Pricing','Straightforward <em>fees</em>','Every engagement starts with a free intro call and a written quote.',`<div class="pr-top"><div class="seg" style="width:260px" role="group" aria-label="Audience">${[['ind','Individuals'],['biz','Businesses']].map(a=>`<button type="button" data-pa="${a[0]}" aria-pressed="${S.prA===a[0]}">${a[1]}</button>`).join('')}</div>${curSel('pcur')}</div>`)}<div class="pr" id="prGrid"></div></section>
 <div class="band rv" id="band">${ph('city-1','City skyline','50% 60%')}<div class="in"><span class="eyebrow" style="color:#fff">Offices in New York · London · Sydney</span><h2>Let’s make your next decision a <em>clear</em> one.</h2><p>Book a free 20-minute intro call with a senior advisor. No obligation, no product pitch.</p><div style="display:flex;gap:10px;flex-wrap:wrap;justify-content:center"><a class="btn cit lg" href="#book">Book the intro call<span class="go">${ic('ne','width:15px;height:15px')}</span></a><a class="btn white lg" href="#contact">Send a message</a></div></div></div>
 <section class="s wrap" id="faq"><div class="faq"><div><span class="eyebrow rv">FAQ</span><h2 class="rv">Questions, <em style="color:var(--cobalt)">answered</em></h2><p class="muted rv" style="margin-top:14px">Still curious? <a class="link" href="#contact">Ask us directly</a>.</p></div><div>${FAQ.map((f,i)=>`<div class="qa rv" style="--dl:${i*.05}s"><button type="button" aria-expanded="${i===0}" aria-controls="qa${i}">${f[0]}<i>${ic('plus','width:16px;height:16px')}</i></button><div class="a" id="qa${i}"><div><p>${f[1]}</p></div></div></div>`).join('')}</div></div></section>
 <section class="s wrap" id="latest">${sh('Insights','Practical notes from our <em>advisors</em>','',`<a class="btn" href="#insights">All insights</a>`)}<div class="ins">${ARTS.slice(0,3).map(artCard).join('')}</div></section>
 <section class="s wrap" id="contact">${contactBlock()}</section>`}
const advTabs=()=>[['all','All'],['wealth','Wealth'],['tax','Tax'],['business','Business'],['retire','Retirement & estate']].map(t=>`<button class="chip" type="button" data-af="${t[0]}" aria-pressed="${S.advF===t[0]}">${t[1]}</button>`).join('');
const advCard=(a,i)=>`<button class="ad" type="button" data-adv="${a.id}" style="--d:${i*.06}s">${ph(a.img,a.n,a.pos)}<div class="cap"><div><b>${a.n}</b><span>${a.r}</span></div><i>${ic('ne','width:15px;height:15px')}</i></div></button>`.replace('</div><div class="cap">',`<span class="ov">${off(a.off).city} · ${a.cred.join(', ')} · ${a.yrs} yrs</span></div><div class="cap">`);
const advFilter=f=>ADV.filter(a=>f==='all'||a.cat===f||(f==='retire'&&a.cat==='estate'));
const artCard=(a,i=0)=>`<a class="ar" href="#article-${a.s}" style="--d:${i*.07}s">${ph(a.img,a.t,'50% 50%')}<div class="mt"><span class="tag">${a.cat}</span>${a.date} · ${a.min} min read</div><h3>${a.t}</h3><p>${a.ex}</p></a>`;
function contactBlock(){const o=off(S.off);
 return `<div class="ct rv"><div class="ct-f" id="ctF">${S.sent?sentBox():`<span class="eyebrow">Contact</span><h2>Let’s start a <em style="color:var(--cobalt)">conversation</em></h2><p class="muted">Tell us a little about what you need. An advisor replies within one business day.</p>
  <form id="cf" novalidate style="display:grid;gap:14px"><div class="two"><div class="field"><label for="cn">Full name</label><input class="input" id="cn" autocomplete="name"></div><div class="field"><label for="ce">Email</label><input class="input" id="ce" type="email" autocomplete="email"></div></div>
  <div class="two"><div class="field"><label for="ctp">Topic</label><select class="sel" id="ctp"><option value="">Choose a topic</option>${SV.map(s=>`<option>${s.t}</option>`).join('')}<option>Something else</option></select></div><div class="field"><label for="cof">Nearest office</label><select class="sel" id="cof">${OFF.map(x=>`<option value="${x.k}" ${x.k===S.off?'selected':''}>${x.city}</option>`).join('')}</select></div></div>
  <div class="field"><label for="cm">Message</label><textarea class="input" id="cm" placeholder="A sentence or two is plenty."></textarea></div>
  <label style="display:flex;gap:10px;font-size:14px;color:var(--fg-2);align-items:flex-start"><input type="checkbox" id="cok" style="margin-top:3px;accent-color:var(--cobalt);width:18px;height:18px"> I agree to be contacted about my enquiry. We never share your details.</label>
  <p class="err-t" id="cerr" hidden></p><button class="btn pri lg" type="submit" style="justify-self:start">Send message<span class="go">${ic('arrow','width:15px;height:15px')}</span></button></form>`}</div>
 <div class="ct-r"><div class="off-tabs" role="group" aria-label="Offices">${OFF.map(x=>`<button type="button" data-off="${x.k}" aria-pressed="${x.k===S.off}">${x.city}</button>`).join('')}</div>
  <div id="offBody">${offBody(o)}</div></div></div>`}
function offBody(o){return `<div style="display:flex;justify-content:space-between;align-items:flex-end;gap:12px;flex-wrap:wrap"><div><span style="font-size:13px;color:#9FB2FF;font-weight:700;letter-spacing:.1em;text-transform:uppercase">Local time</span><div class="clock num" id="clock">--:--</div></div><span class="open" id="open"><i></i>…</span></div>
 <div class="off-img" style="margin-top:14px">${ph(o.img,o.city+' office','50% 50%')}</div>
 <div class="off-d" style="margin-top:14px"><span>${ic('pin','width:16px;height:16px;vertical-align:-3px')} ${o.addr}</span><a href="tel:${o.tel.replace(/[^+\d]/g,'')}">${ic('phone','width:16px;height:16px;vertical-align:-3px')} ${o.tel}</a><a href="mailto:${o.mail}">${ic('mail','width:16px;height:16px;vertical-align:-3px')} ${o.mail}</a><span>Mon–Fri · 9:00–18:00 local time</span></div>`}
const sentBox=()=>`<div class="ok-box"><span class="eyebrow">Message sent</span><b>Thanks, ${esc(S.sent.n.split(' ')[0])}. We’ve got it.</b><p>Reference <b class="num">${S.sent.ref}</b>. An advisor from our ${off(S.sent.o).city} office will reply to ${esc(S.sent.e)} within one business day.</p><div style="display:flex;gap:10px;flex-wrap:wrap;margin-top:6px"><a class="btn pri" href="#book">Book a call instead</a><button class="btn ghost" type="button" id="newMsg">Send another message</button></div></div>`;

function bindHome(){
 // hero pill + rotating words
 let pi=0;timer(()=>{if(document.hidden)return;const p=$$('.pill .ph');if(!p.length)return;p[pi].classList.remove('on');pi=(pi+1)%p.length;p[pi].classList.add('on')},2600);
 let ri=0;timer(()=>{if(document.hidden)return;const w=$$('#rot span');if(!w.length)return;const c=w[ri];ri=(ri+1)%w.length;const n=w[ri];c.className='out';n.className='';setTimeout(()=>{if(c.className==='out')c.className='nx'},650)},2200);
 $$('[data-quick]').forEach(a=>a.addEventListener('click',()=>{resetBk();S.bk.adv=a.dataset.quick;S.bk.svc='intro'}));
 // advisors
 const drawAdv=()=>{$('#advGrid').innerHTML=advFilter(S.advF).slice(0,4).map(advCard).join('');bindAdv($('#advGrid'))};
 $$('[data-af]').forEach(b=>b.onclick=()=>{S.advF=b.dataset.af;$$('[data-af]').forEach(x=>x.setAttribute('aria-pressed',x===b));drawAdv()});drawAdv();
 // testimonials
 const card=$('#tmCard');let paused=false;const go=i=>{S.tmI=(i+TM.length)%TM.length;$$('.tm-it').forEach((e,k)=>{e.classList.toggle('on',k===S.tmI);e.setAttribute('aria-hidden',k!==S.tmI)});$$('#tmD button').forEach((b,k)=>{b.setAttribute('aria-current',k===S.tmI);if(k===S.tmI){b.style.display='none';b.offsetWidth;b.style.display=''}})};
 $$('#tmD button').forEach((b,k)=>b.onclick=()=>{go(k);tmT=restart()});$('#tmP').onclick=()=>{go(S.tmI-1);tmT=restart()};$('#tmN').onclick=()=>{go(S.tmI+1);tmT=restart()};
 let tmT=null;const restart=()=>{clearInterval(tmT);return timer(()=>{if(!paused&&!document.hidden)go(S.tmI+1)},6000)};tmT=restart();
 card.onmouseenter=()=>{paused=true;card.classList.add('paused')};card.onmouseleave=()=>{paused=false;card.classList.remove('paused')};
 let sx=null;card.addEventListener('pointerdown',e=>sx=e.clientX);card.addEventListener('pointerup',e=>{if(sx!=null&&Math.abs(e.clientX-sx)>50){go(S.tmI+(e.clientX<sx?1:-1));tmT=restart()}sx=null});
 // pricing
 const drawPr=()=>{$('#prGrid').innerHTML=PLANS[S.prA].map((p,i)=>`<div class="pc ${p.feat?'feat':''}" style="animation:rise .5s ${i*.07}s var(--ease) both">${p.feat?'<span class="tag">Most chosen</span>':''}<h3>${p.n}</h3><div class="pp num">${p.pct?p.pct:money(p.p)}<small>${p.u}</small></div><p class="ds">${p.d}${p.min?money(p.min,{compact:1}):''}</p><ul>${p.f.map(f=>`<li>${ic('check')}${f}</li>`).join('')}</ul><a class="btn ${p.feat?'cit':'pri'}" href="#book">Get started</a></div>`).join('')};
 $$('[data-pa]').forEach(b=>b.onclick=()=>{S.prA=b.dataset.pa;$$('[data-pa]').forEach(x=>x.setAttribute('aria-pressed',x===b));drawPr()});drawPr();
 // faq
 $$('.qa button').forEach(b=>b.onclick=()=>b.setAttribute('aria-expanded',b.getAttribute('aria-expanded')!=='true'));
 // calculator
 const RATE={con:.04,bal:.06,gro:.08};
 const calc=()=>{const c=S.calc;['start','monthly','years'].forEach(k=>{const el=$('#c-'+k);c[k]=+el.value;el.style.setProperty('--p',((el.value-el.min)/(el.max-el.min)*100)+'%');$('#cv-'+k).textContent=k==='years'?`${c.years} yrs`:money(c[k],{raw:1})});
  $('#c-rate').textContent=`Assumed return ${RATE[c.prof]*100}% a year`;
  const i=RATE[c.prof]/12;let bal=c.start,inv=c.start;const pts=[[0,bal,inv]];for(let y=1;y<=c.years;y++){for(let m=0;m<12;m++){bal=bal*(1+i)+c.monthly;inv+=c.monthly}pts.push([y,bal,inv])}
  $('#c-out').textContent=money(bal,{raw:1});$('#c-in').textContent=money(inv,{raw:1});$('#c-gr').textContent=money(bal-inv,{raw:1});$('#c-sh').textContent=bal>0?Math.round((bal-inv)/bal*100)+'%':'0%';
  const W=600,H=260,x0=46,x1=590,y0=18,y1=226,max=Math.max(...pts.map(p=>p[1]),1);const nice=(()=>{const e=Math.pow(10,Math.floor(Math.log10(max)));const f=max/e;return (f<=2?2:f<=5?5:10)*e})();
  const X=y=>x0+(x1-x0)*y/Math.max(c.years,1),Y=v=>y1-(y1-y0)*v/nice;
  const line=k=>pts.map((p,j)=>`${j?'L':'M'}${X(p[0]).toFixed(1)} ${Y(p[k]).toFixed(1)}`).join(' ');
  const area=k=>line(k)+` L${X(c.years)} ${y1} L${x0} ${y1} Z`;
  let g='';for(let t=0;t<=4;t++){const v=nice*t/4,yy=Y(v);g+=`<line class="gl" x1="${x0}" x2="${x1}" y1="${yy}" y2="${yy}"/><text x="${x0-8}" y="${yy+4}" text-anchor="end">${money(v,{raw:1,compact:1})}</text>`}
  const step=c.years>20?10:c.years>8?5:c.years>3?2:1;for(let y=0;y<=c.years;y+=step)g+=`<text x="${X(y)}" y="${H-12}" text-anchor="middle">${y===0?'Now':'Yr '+y}</text>`;
  $('#chart').innerHTML=`<defs><linearGradient id="ga" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#2F5BFF" stop-opacity=".32"/><stop offset="1" stop-color="#2F5BFF" stop-opacity="0"/></linearGradient></defs>${g}<path d="${area(1)}" fill="url(#ga)"/><path d="${area(2)}" fill="#FFC83D" fill-opacity=".35"/><path d="${line(2)}" fill="none" stroke="#F2B416" stroke-width="2"/><path id="pl" d="${line(1)}" fill="none" stroke="#2F5BFF" stroke-width="3" stroke-linecap="round"/><g class="tip" id="tip" style="opacity:0"><line id="tl" y1="${y0}" y2="${y1}" stroke="#0D1A3A" stroke-dasharray="3 4"/><circle id="tc" r="6" fill="#fff" stroke="#2F5BFF" stroke-width="3"/><rect id="tr" rx="8" height="44" width="132" fill="#0D1A3A"/><text id="tt1" fill="#fff" style="fill:#fff;font-weight:700;font-size:12px"></text><text id="tt2" style="fill:#B7C3F0;font-size:11px"></text></g>`;
  const svg=$('#chart');svg.onmousemove=e=>{const r=svg.getBoundingClientRect();const sx=(e.clientX-r.left)/r.width*W;const y=clamp(Math.round((sx-x0)/(x1-x0)*c.years),0,c.years);const p=pts[y];const px=X(y),py=Y(p[1]);$('#tip').style.opacity=1;$('#tl').setAttribute('x1',px);$('#tl').setAttribute('x2',px);$('#tc').setAttribute('cx',px);$('#tc').setAttribute('cy',py);const bx=px>W-150?px-142:px+10;$('#tr').setAttribute('x',bx);$('#tr').setAttribute('y',Math.max(y0,py-50));$('#tt1').setAttribute('x',bx+10);$('#tt1').setAttribute('y',Math.max(y0,py-50)+19);$('#tt1').textContent=money(p[1],{raw:1});$('#tt2').setAttribute('x',bx+10);$('#tt2').setAttribute('y',Math.max(y0,py-50)+35);$('#tt2').textContent=y?`Year ${y} · in ${money(p[2],{raw:1,compact:1})}`:'Today'};svg.onmouseleave=()=>$('#tip').style.opacity=0;
  if(!RM){const pl=$('#pl'),L=pl.getTotalLength();pl.style.strokeDasharray=L;pl.style.strokeDashoffset=S.calcDrawn?0:L;if(!S.calcDrawn){pl.getBoundingClientRect();pl.style.transition='stroke-dashoffset 1.2s cubic-bezier(.2,.8,.2,1)';pl.style.strokeDashoffset=0;S.calcDrawn=1}}};
 ['start','monthly','years'].forEach(k=>$('#c-'+k).oninput=calc);$$('[data-prof]').forEach(b=>b.onclick=()=>{S.calc.prof=b.dataset.prof;$$('[data-prof]').forEach(x=>x.setAttribute('aria-pressed',x===b));calc()});S.calcDrawn=0;calc();
 document.addEventListener('cur',S.onCur=()=>{calc();drawPr()});
 bindContact()}
function bindContact(){
 const tick=()=>{const o=off(S.off);const el=$('#clock');if(!el)return;const p=tzParts(o.tz,new Date());el.textContent=`${p.hour%24}`.padStart(2,'0')+':'+p.minute;const h=+p.hour%24,wd=p.weekday;const open=!['Sat','Sun'].includes(wd)&&h>=9&&h<18;const oe=$('#open');oe.className='open'+(open?'':' cl');oe.innerHTML=`<i></i>${open?'Open now':'Closed now'} · ${p.weekday} ${o.ab}`};tick();timer(tick,1000);
 $$('[data-off]').forEach(b=>b.onclick=()=>{S.off=b.dataset.off;$$('[data-off]').forEach(x=>x.setAttribute('aria-pressed',x===b));$('#offBody').innerHTML=offBody(off(S.off));const cof=$('#cof');if(cof)cof.value=S.off;tick()});
 const f=$('#cf');if(f){$('#cof').onchange=e=>{S.off=e.target.value;$$('[data-off]').forEach(x=>x.setAttribute('aria-pressed',x.dataset.off===S.off));$('#offBody').innerHTML=offBody(off(S.off));tick()};
  f.onsubmit=e=>{e.preventDefault();const v=id=>$('#'+id).value.trim();const bad=[];if(v('cn').length<2)bad.push('cn');if(!/^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test(v('ce')))bad.push('ce');if(!v('ctp'))bad.push('ctp');if(v('cm').length<10)bad.push('cm');
   ['cn','ce','ctp','cm'].forEach(id=>$('#'+id).classList.toggle('err',bad.includes(id)));const ok=$('#cok').checked;const er=$('#cerr');
   if(bad.length||!ok){er.hidden=false;er.textContent=bad.includes('ce')?'Please enter a valid email address.':bad.includes('cm')?'Please add a short message (10+ characters).':bad.length?'Please complete the highlighted fields.':'Please tick the consent box so we can reply.';return}
   S.sent={n:v('cn'),e:v('ce'),o:v('cof'),ref:'HR-'+String(hash(v('ce')+Date.now())%900000+100000)};$('#ctF').innerHTML=sentBox();bindSent()}}else bindSent()}
function bindSent(){$('#newMsg')?.addEventListener('click',()=>{S.sent=null;const w=$('#contact');w.innerHTML=contactBlock();w.querySelector('.rv').classList.add('in');bindContact()})}
function bindAdv(root=document){$$('[data-adv]',root).forEach(b=>b.onclick=()=>openAdv(b.dataset.adv))}
function openAdv(id){const a=adv(id);const o=off(a.off);const n=nextSlot(id);closeModal();
 const m=document.createElement('div');m.className='mdl';m.setAttribute('role','dialog');m.setAttribute('aria-modal','true');m.setAttribute('aria-label',a.n);
 m.innerHTML=`<div class="bx2">${ph(a.img,a.n,a.pos)}<div class="in"><button class="x" aria-label="Close">${ic('x')}</button><span class="eyebrow">${CATN[a.cat]} · ${o.city}</span><h3>${a.n}</h3><span class="muted" style="font-weight:600">${a.r}</span><div class="cred">${a.cred.map(c=>`<span class="tag">${c}</span>`).join('')}<span class="tag cit">${a.yrs} years</span></div><p>${a.bio}</p>
  <div class="kv"><span>Office</span><b>${o.city} (${o.ab})</b><span>Languages</span><b>${a.lang}</b><span>Focus</span><b>${a.focus.join(' · ')}</b><span>Next free slot</span><b>${n?`${fmtDate(n.ds)}, ${fmtTime(n.t)} ${o.ab}`:'Next week'}</b></div>
  <div style="display:flex;gap:10px;flex-wrap:wrap;margin-top:8px"><a class="btn pri" href="#book" id="mBook">Book with ${a.n.split(' ')[0]}</a><button class="btn ghost" type="button" id="mCopy">${ic('copy','width:16px;height:16px')}Copy email</button></div></div></div>`;
 document.body.appendChild(m);S.lastFocus=document.activeElement;m.querySelector('.x').focus();
 m.onclick=e=>{if(e.target===m)closeModal()};m.querySelector('.x').onclick=closeModal;
 $('#mBook').onclick=()=>{resetBk();S.bk.adv=id;closeModal()};
 $('#mCopy').onclick=()=>{const em=a.n.split(' ')[0].toLowerCase()+'@haldenrowe.example';(navigator.clipboard?.writeText(em)||Promise.reject()).then(()=>toast('Copied '+em)).catch(()=>toast(em))}}
function closeModal(){const m=$('.mdl');if(m){m.remove();S.lastFocus?.focus?.()}}
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});

/* ---------- SERVICES ---------- */
function pageServices(){return `<section class="wrap ph-h"><div class="crumbs"><a href="#home">Home</a>/<span>Services</span></div><h1 class="rv">Advice for every <em>stage</em> of life and business</h1><p class="rv" style="--dl:.1s">Six practice areas, one joined-up team. Start with the one that matters most today; we will connect the rest.</p></section>
 <section class="wrap"><div class="svg-grid">${SV.map((s,i)=>`<a class="sg" href="#service-${s.s}" style="--d:${i*.06}s">${ph(s.img,s.t,s.pos)}<div class="bd"><span class="tag" style="justify-self:start">${ic(s.ic,'width:14px;height:14px')}${CATN[s.cat]}</span><h3>${s.t}</h3><p>${s.sh}</p><span style="display:flex;justify-content:space-between;align-items:center;margin-top:6px;font-weight:700">From ${money(s.from)}<span class="circ" style="width:38px;height:38px">${ic('ne','width:15px;height:15px')}</span></span></div></a>`).join('')}</div></section>
 <div class="band rv" style="min-height:380px">${ph('city-1','','50% 60%')}<div class="in"><h2>Not sure which one you <em>need</em>?</h2><p>A free 20-minute intro call will tell you.</p><a class="btn cit lg" href="#book">Book the intro call</a></div></div>`}
function pageService(s){const i=SV.indexOf(s),nx=SV[(i+1)%SV.length];const team=ADV.filter(a=>a.cat===s.cat);
 return `<section class="wrap ph-h"><div class="crumbs"><a href="#home">Home</a>/<a href="#services">Services</a>/<span>${s.t}</span></div><h1 class="rv">${s.t}</h1><p class="rv" style="--dl:.1s">${s.sh}</p></section>
 <section class="wrap"><div class="sd-hero rv clip" style="position:relative;overflow:hidden" data-speed-img>${ph(s.img,s.t,s.pos)}</div>
 <div class="sd"><div class="body">${s.body.map(p=>`<p class="rv">${p}</p>`).join('')}
  <h2 class="rv">What’s included</h2><div class="inc">${s.inc.map((x,k)=>`<div class="rv" style="--dl:${k*.06}s"><b>${x[0]}</b><span>${x[1]}</span></div>`).join('')}</div>
  <h2 class="rv">Who it’s for</h2><ul style="padding:0;list-style:none;display:grid;gap:10px">${s.who.map(w=>`<li class="rv" style="display:flex;gap:10px;align-items:center;font-size:16.5px">${ic('check','color:var(--mint)')}${w}</li>`).join('')}</ul>
  <a class="btn" href="#service-${nx.s}" style="margin-top:40px">Next: ${nx.t} ${ic('arrow','width:16px;height:16px')}</a></div>
 <aside class="aside"><span class="muted" style="font-weight:700;font-size:13.5px">Fees</span><div class="pp num">${money(s.from)}</div><span class="muted" style="font-size:14px;margin-top:-6px">${s.unit}</span>
  <div><div class="row"><span class="muted">Typical timeline</span><b>${s.dur}</b></div><div class="row"><span class="muted">Meetings</span><b>Video or in person</b></div><div class="row"><span class="muted">Offices</span><b>NY · London · Sydney</b></div></div>
  <a class="btn pri" href="#book" id="bkSvc">Book this service</a>${curSel('scur')}
  ${team.length?`<span class="muted" style="font-weight:700;font-size:13.5px;margin-top:8px">Advisors</span>${team.map(a=>`<button class="mini-adv" type="button" data-adv="${a.id}">${ph(a.img,a.n,a.pos)}<div><b>${a.n}</b><span>${a.r}</span></div></button>`).join('')}`:''}</aside></div></section>`}
function bindService(s){$('#bkSvc').addEventListener('click',()=>{resetBk();S.bk.svc=s.s});bindAdv();document.addEventListener('cur',S.onCur=()=>{const y=scrollY;route();scrollTo(0,y)})}

/* ---------- ADVISORS ---------- */
function pageAdvisors(){return `<section class="wrap ph-h"><div class="crumbs"><a href="#home">Home</a>/<span>Advisors</span></div><h1 class="rv">The people behind the <em>advice</em></h1><p class="rv" style="--dl:.1s">${ADV.length} senior advisors across New York, London and Sydney. Every client has one named lead advisor and access to the whole team.</p>
 <div class="rv" style="--dl:.15s;display:flex;gap:8px;flex-wrap:wrap;margin-top:26px">${advTabs()}<span style="flex:1"></span><label class="sr" for="aoff">Office</label><select class="cur-sel" id="aoff"><option value="">All offices</option>${OFF.map(o=>`<option value="${o.k}">${o.city}</option>`).join('')}</select></div></section>
 <section class="wrap"><div class="adv" id="advAll"></div><p class="muted" id="advEmpty" hidden style="text-align:center;padding:40px">No advisors match that filter.</p></section>`}
function bindAdvisors(){const draw=()=>{const o=$('#aoff').value;const l=advFilter(S.advF).filter(a=>!o||a.off===o);$('#advAll').innerHTML=l.map(advCard).join('');$('#advEmpty').hidden=!!l.length;bindAdv($('#advAll'))};
 $$('[data-af]').forEach(b=>b.onclick=()=>{S.advF=b.dataset.af;$$('[data-af]').forEach(x=>x.setAttribute('aria-pressed',x===b));draw()});$('#aoff').onchange=draw;draw()}

/* ---------- INSIGHTS ---------- */
function pageInsights(){const cats=['All',...new Set(ARTS.map(a=>a.cat))];return `<section class="wrap ph-h"><div class="crumbs"><a href="#home">Home</a>/<span>Insights</span></div><h1 class="rv">Insights</h1><p class="rv" style="--dl:.1s">Practical notes on tax, wealth, retirement and running a business, written by our advisors.</p>
 <div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:26px" role="group" aria-label="Category">${cats.map(c=>`<button class="chip" type="button" data-ic="${c}" aria-pressed="${S.insF===c}">${c}</button>`).join('')}</div></section><section class="wrap"><div class="ins" id="insG"></div></section>`}
function bindInsights(){const draw=()=>{$('#insG').innerHTML=ARTS.filter(a=>S.insF==='All'||a.cat===S.insF).map(artCard).join('')};$$('[data-ic]').forEach(b=>b.onclick=()=>{S.insF=b.dataset.ic;$$('[data-ic]').forEach(x=>x.setAttribute('aria-pressed',x===b));draw()});draw()}
function pageArticle(a){const rel=ARTS.filter(x=>x!==a).slice(0,3);return `<div class="rprog" id="rprog"></div><section class="wrap ph-h art"><div class="crumbs"><a href="#home">Home</a>/<a href="#insights">Insights</a>/<span>${a.cat}</span></div><h1 class="rv" style="font-size:clamp(36px,5vw,62px)">${a.t}</h1><div class="mt rv" style="display:flex;gap:10px;align-items:center;margin-top:18px;color:var(--muted);font-weight:600;font-size:14px"><span class="tag">${a.cat}</span>${a.date} · ${a.min} min read</div>
 <div class="cover rv clip" style="position:relative;overflow:hidden">${ph(a.img,a.t,'50% 50%')}</div><div class="body" id="artBody">${a.body.map(p=>typeof p==='string'?`<p>${p}</p>`:`<h3>${p.h}</h3>`).join('')}</div>
 <div class="share"><span class="muted" style="font-weight:700">Share</span><button class="btn ghost sm" type="button" id="cpl">${ic('copy','width:15px;height:15px')}Copy link</button><a class="btn ghost sm" href="mailto:?subject=${encodeURIComponent(a.t)}&body=${encodeURIComponent(a.ex)}">${ic('mail','width:15px;height:15px')}Email</a><span style="flex:1"></span><a class="btn pri sm" href="#book">Talk to an advisor</a></div>
 <p class="disc" style="margin-top:18px">General information only, not personal financial, tax or legal advice.</p></section>
 <section class="wrap" style="margin-top:80px"><h2 style="font-size:36px;margin-bottom:24px">Keep reading</h2><div class="ins">${rel.map(artCard).join('')}</div></section>`}
function bindArticle(){$('#cpl').onclick=()=>{(navigator.clipboard?.writeText(location.href)||Promise.reject()).then(()=>toast('Link copied')).catch(()=>toast(location.href))}}

/* ---------- BOOKING ---------- */
const FMT=[['video','Video call','Secure video link by email','video'],['phone','Phone call','We call the number you give us','phone'],['office','In person','At your advisor’s office','pin']];
function resetBk(){S.bk={step:1,svc:null,adv:null,fmt:null,date:null,time:null,info:S.bk.info||{},local:S.bk.local,resched:null,month:null}}
const bkSvcName=k=>k==='intro'?'Free intro call':svc(k)?.t;
function pageBook(){return `<section class="wrap ph-h" style="padding-bottom:10px"><div class="crumbs"><a href="#home">Home</a>/<span>Book a consultation</span></div><h1 class="rv" style="font-size:clamp(38px,5vw,64px)">Book a <em>consultation</em></h1><p class="rv" style="--dl:.1s">Five quick steps. You will get a confirmation, a calendar file and a reference number straight away.</p><div class="mybk" id="myBk"></div></section><section class="wrap"><div class="bk" id="bk"></div></section>`}
function drawMyBk(){const el=$('#myBk');if(!el)return;const l=[...S.bookings].sort((a,b)=>a.utc-b.utc);
 el.innerHTML=l.length?`<b style="font-size:15px">Your upcoming consultations</b>`+l.map(b=>{const a=adv(b.adv),o=off(a.off);return `<div class="mb"><div class="d"><small>${fmtDate(b.date,{month:'short'})}</small><b>${+b.date.slice(8)}</b></div><div class="t"><b>${bkSvcName(b.svc)} with ${a.n}</b><span>${fmtDate(b.date,{weekday:'long'})} · ${fmtTime(b.time)} ${o.ab} · ${FMT.find(f=>f[0]===b.fmt)[1]} · Ref ${b.id}</span></div>${calLinks(b,1)}<button class="btn ghost sm" data-rs="${b.id}">Reschedule</button><button class="btn ghost sm" data-cx="${b.id}" style="color:var(--bad)">Cancel</button></div>`}).join(''):'';
 $$('[data-ics]',el).forEach(b=>b.onclick=()=>ics(S.bookings.find(x=>x.id===b.dataset.ics)));
 $$('[data-cx]',el).forEach(b=>b.onclick=()=>{if(b.dataset.sure){S.bookings=S.bookings.filter(x=>x.id!==b.dataset.cx);saveBk();drawMyBk();drawBk();toast('Consultation cancelled')}else{b.dataset.sure=1;b.textContent='Confirm cancel'}});
 $$('[data-rs]',el).forEach(b=>b.onclick=()=>{const x=S.bookings.find(y=>y.id===b.dataset.rs);S.bk={...S.bk,step:4,svc:x.svc,adv:x.adv,fmt:x.fmt,date:null,time:null,info:{...x.info},resched:x.id,month:null};drawBk();$('#bk').scrollIntoView({behavior:'smooth',block:'start'})})}
function drawBk(){const B=S.bk,el=$('#bk');if(!el)return;const STEPS=[['Service',bkSvcName(B.svc)],['Advisor',B.adv&&adv(B.adv).n],['Format',B.fmt&&FMT.find(f=>f[0]===B.fmt)[1]],['Date & time',B.date&&B.time&&`${fmtDate(B.date)} · ${fmtTime(B.time)}`],['Your details',B.info.n]];
 const done=B.step===6;
 const side=`<div class="bk-side">${STEPS.map((s,i)=>`<button type="button" class="bk-s ${B.step===i+1?'on':''} ${(B.step>i+1||done)?'dn':''}" data-gs="${i+1}" ${i+1>B.step||done?'disabled':''}><i>${B.step>i+1||done?'✓':i+1}</i><span>${s[0]}<small>${esc(s[1]||'')}</small></span></button>`).join('')}</div>`;
 let m='';
 if(B.step===1){m=`<h2>What would you like to discuss?</h2><p>Pick a service, or start with a free intro call if you are not sure.</p><div class="opts">${[['intro','Free intro call','20 minutes · no cost','cal'],...SV.map(s=>[s.s,s.t,'From '+money(s.from),s.ic])].map((o,i)=>`<button type="button" class="op" data-v="${o[0]}" aria-pressed="${B.svc===o[0]}" style="--d:${i*.04}s"><span class="ic">${ic(o[3])}</span><b>${o[1]}</b><span>${o[2]}</span></button>`).join('')}</div>`}
 if(B.step===2){const cat=svc(B.svc)?.cat;const rec=ADV.filter(a=>!cat||a.cat===cat),oth=ADV.filter(a=>!rec.includes(a));const card=(a,i)=>{const n=nextSlot(a.id),o=off(a.off);return `<button type="button" class="op" data-v="${a.id}" aria-pressed="${B.adv===a.id}" style="--d:${i*.04}s">${ph(a.img,a.n,a.pos)}<b>${a.n}</b><span>${a.r}</span><span>${o.city} · next ${n?fmtDate(n.ds)+', '+fmtTime(n.t):'next week'}</span></button>`};
  m=`<h2>Choose your advisor</h2><p>${cat?`Recommended for ${bkSvcName(B.svc)}.`:'Any advisor can run your intro call.'}</p><div class="opts">${rec.map(card).join('')}</div>${oth.length?`<p style="margin-top:22px;font-weight:700">Also available</p><div class="opts" style="margin-top:10px">${oth.map((a,i)=>card(a,i+rec.length)).join('')}</div>`:''}`}
 if(B.step===3){const o=off(adv(B.adv).off);m=`<h2>How would you like to meet?</h2><p>All formats are the same length and price.</p><div class="opts">${FMT.map((f,i)=>`<button type="button" class="op" data-v="${f[0]}" aria-pressed="${B.fmt===f[0]}" style="--d:${i*.05}s"><span class="ic">${ic(f[3])}</span><b>${f[1]}</b><span>${f[0]==='office'?o.addr:f[2]}</span></button>`).join('')}</div>`}
 if(B.step===4){const a=adv(B.adv),o=off(a.off),today=officeToday(o.tz).ds;if(!B.month)B.month=today.slice(0,7);const [yy,mm]=B.month.split('-').map(Number);const first=new Date(Date.UTC(yy,mm-1,1)),days=new Date(Date.UTC(yy,mm,0)).getUTCDate(),lead=(first.getUTCDay()+6)%7;const limit=addDays(today,60);
  let cells='';for(let i=0;i<lead;i++)cells+='<span></span>';for(let d=1;d<=days;d++){const ds=`${B.month}-${String(d).padStart(2,'0')}`;const any=ds>=today&&ds<=limit&&slots(a.id,ds).some(x=>x.free);cells+=`<button type="button" data-d="${ds}" ${any?'':'disabled'} aria-pressed="${B.date===ds}" aria-label="${fmtDate(ds,{weekday:'long',month:'long',day:'numeric'})}${any?'':' unavailable'}">${d}${any?'<i class="av"></i>':''}</button>`}
  const prevOk=B.month>today.slice(0,7),nextOk=`${B.month}-01`<limit.slice(0,7)+'-01';
  const sl=B.date?slots(a.id,B.date):[];
  m=`<h2>Pick a date and time</h2><p>${a.n} · ${FMT.find(f=>f[0]===B.fmt)[1]} · 45 minutes</p><div class="cal"><div><div class="cal-h"><button class="rbtn" type="button" id="pm" ${prevOk?'':'disabled'} aria-label="Previous month">${ic('left')}</button><b>${first.toLocaleDateString('en-US',{month:'long',year:'numeric',timeZone:'UTC'})}</b><button class="rbtn" type="button" id="nm" ${nextOk?'':'disabled'} aria-label="Next month">${ic('arrow')}</button></div><div class="cal-g">${['Mo','Tu','We','Th','Fr','Sa','Su'].map(d=>`<span class="dw">${d}</span>`).join('')}${cells}</div></div>
   <div><b style="display:block;margin-bottom:12px">${B.date?fmtDate(B.date,{weekday:'long',month:'long',day:'numeric'}):'Choose a date first'}</b><div class="times">${sl.map(x=>`<button type="button" data-t="${x.t}" ${x.free?'':'disabled'} aria-pressed="${B.time===x.t}">${B.local?localTime(B.date,x.t,o.tz):fmtTime(x.t)}</button>`).join('')}</div>
   <div class="tzb">${ic('ret','width:15px;height:15px')}<span>Times shown in ${B.local?`your time zone (${USER_TZ})`:`${o.city} time (${o.ab})`}</span><button class="link" type="button" id="tzT">${B.local?'Show office time':'Show my time'}</button></div>
   ${B.date&&B.time&&!B.local&&o.tz!==USER_TZ?`<p class="disc" style="margin-top:8px">That is ${localDate(B.date,B.time,o.tz)}, ${localTime(B.date,B.time,o.tz)} where you are.</p>`:''}</div></div>`}
 if(B.step===5){const I=B.info;m=`<h2>Your details</h2><p>We only use these to confirm and prepare for your consultation.</p><form id="bf" novalidate style="display:grid;gap:14px;margin-top:22px"><div class="two"><div class="field"><label for="bn">Full name</label><input class="input" id="bn" autocomplete="name" value="${esc(I.n||'')}"></div><div class="field"><label for="be">Email</label><input class="input" id="be" type="email" autocomplete="email" value="${esc(I.e||'')}"></div></div>
  <div class="two"><div class="field"><label for="bp">Phone ${B.fmt==='phone'?'':'<span class="muted">(optional)</span>'}</label><input class="input" id="bp" type="tel" autocomplete="tel" placeholder="+1 212 555 0100" value="${esc(I.p||'')}"></div><div class="field"><label for="bw">You are</label><select class="sel" id="bw">${['An individual or family','A business owner','A finance lead at a company'].map(x=>`<option ${I.w===x?'selected':''}>${x}</option>`).join('')}</select></div></div>
  <div class="field"><label for="bno">Anything we should know? <span class="muted">(optional)</span></label><textarea class="input" id="bno">${esc(I.no||'')}</textarea></div><p class="err-t" id="berr" hidden></p></form>`}
 if(done&&!S.bookings.find(x=>x.id===B.last)){resetBk();return drawBk()}
 if(done){const b=S.bookings.find(x=>x.id===B.last);const a=adv(b.adv),o=off(a.off);m=`<div class="conf"><span class="ok"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"><path d="m5 12.5 4.5 4.5L19 7.5"/></svg></span><h2>You’re booked, ${esc(b.info.n.split(' ')[0])}.</h2><p class="muted">A confirmation is on its way to ${esc(b.info.e)}. This is a demo, so no email is actually sent.</p>
  <div class="sum"><div><span>Reference</span><b class="num">${b.id}</b></div><div><span>Service</span><b>${bkSvcName(b.svc)}</b></div><div><span>Advisor</span><b>${a.n}</b></div><div><span>When</span><b>${fmtDate(b.date,{weekday:'long',month:'long',day:'numeric'})}, ${fmtTime(b.time)} ${o.ab}</b></div><div><span>Your time</span><b>${localDate(b.date,b.time,o.tz)}, ${localTime(b.date,b.time,o.tz)}</b></div><div><span>Format</span><b>${b.fmt==='office'?'In person · '+o.city:FMT.find(f=>f[0]===b.fmt)[1]}</b></div></div>
  <div style="display:flex;gap:10px;flex-wrap:wrap;justify-content:center">${calLinks(b)}<button class="btn ghost" type="button" id="again">Book another</button><a class="btn ghost" href="#home">Back to home</a></div></div>`}
 const can=[0,!!B.svc,!!B.adv,!!B.fmt,!!(B.date&&B.time),true][B.step];
 el.innerHTML=side+`<div class="bk-main" id="bkm">${m}${done?'':`<div class="bk-foot"><button class="btn ghost" type="button" id="bkBack" ${B.step===1?'style="visibility:hidden"':''}>${ic('left','width:16px;height:16px')}Back</button><button class="btn pri" type="button" id="bkNext" ${can?'':'disabled'}>${B.step===5?(B.resched?'Confirm new time':'Confirm booking'):'Continue'}${ic('arrow','width:16px;height:16px')}</button></div>`}</div>`;
 // bindings
 $$('[data-gs]',el).forEach(b=>b.onclick=()=>{B.step=+b.dataset.gs;drawBk()});
 const key=['svc','adv','fmt'][B.step-1];if(key)$$('.op',el).forEach(b=>b.onclick=()=>{if(B[key]!==b.dataset.v){B[key]=b.dataset.v;if(key==='svc'&&B.adv&&svc(B.svc)&&adv(B.adv).cat!==svc(B.svc).cat){}if(key!=='fmt'){B.date=null;B.time=null;B.month=null}}$$('.op',el).forEach(x=>x.setAttribute('aria-pressed',x===b));$('#bkNext').disabled=false});
 $$('.op',el).forEach(b=>b.addEventListener('dblclick',()=>$('#bkNext').click()));
 if(B.step===4){$$('[data-d]',el).forEach(b=>b.onclick=()=>{B.date=b.dataset.d;B.time=null;drawBk()});$$('[data-t]',el).forEach(b=>b.onclick=()=>{B.time=b.dataset.t;drawBk()});
  $('#pm').onclick=()=>{const [y,m]=B.month.split('-').map(Number);const d=new Date(Date.UTC(y,m-2,1));B.month=d.toISOString().slice(0,7);drawBk()};$('#nm').onclick=()=>{const [y,m]=B.month.split('-').map(Number);const d=new Date(Date.UTC(y,m,1));B.month=d.toISOString().slice(0,7);drawBk()};$('#tzT').onclick=()=>{B.local=!B.local;drawBk()}}
 $('#bkBack')?.addEventListener('click',()=>{B.step--;drawBk()});
 $('#bkNext')?.addEventListener('click',()=>{if(B.step<5){B.step++;drawBk();if(innerWidth<900)$('#bk').scrollIntoView({behavior:'smooth'});return}
  const v=id=>$('#'+id).value.trim();const bad=[];if(v('bn').length<2)bad.push('bn');if(!/^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test(v('be')))bad.push('be');const pd=v('bp').replace(/[^\d]/g,'');if((B.fmt==='phone'||v('bp'))&&(pd.length<7||pd.length>15))bad.push('bp');
  ['bn','be','bp'].forEach(id=>$('#'+id).classList.toggle('err',bad.includes(id)));if(bad.length){const e=$('#berr');e.hidden=false;e.textContent=bad.includes('be')?'Please enter a valid email address.':bad.includes('bp')?'Please enter a valid phone number with country code.':'Please enter your name.';return}
  B.info={n:v('bn'),e:v('be'),p:v('bp'),w:v('bw'),no:v('bno')};
  if(!slots(B.adv,B.date).find(x=>x.t===B.time&&x.free)){B.step=4;B.time=null;drawBk();toast('That slot was just taken. Please pick another time.');return}
  const a=adv(B.adv);const id=B.resched||('HR-'+(hash(B.adv+B.date+B.time+B.info.e)%900000+100000));
  const rec={id,svc:B.svc,adv:B.adv,fmt:B.fmt,date:B.date,time:B.time,info:{...B.info},utc:toUTC(B.date,B.time,off(a.off).tz).getTime()};
  S.bookings=S.bookings.filter(x=>x.id!==id);S.bookings.push(rec);saveBk();const wasR=!!B.resched;B.last=id;B.step=6;B.resched=null;drawMyBk();drawBk();toast(wasR?'Consultation rescheduled':'Consultation booked');scrollTo({top:$('#bk').getBoundingClientRect().top+scrollY-100,behavior:'smooth'})});
 if(done){$$('[data-ics]',el).forEach(x=>x.onclick=()=>ics(S.bookings.find(y=>y.id===x.dataset.ics)));$('#again').onclick=()=>{resetBk();drawBk()}}}
const IN_VIEWER=!!window.claude;
function calLinks(b,sm){const a=adv(b.adv),o=off(a.off);const st=new Date(b.utc),en=new Date(b.utc+45*6e4);const f=d=>d.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'');const t=`${bkSvcName(b.svc)} with ${a.n} (Halden & Rowe)`,loc=b.fmt==='office'?o.addr:FMT.find(x=>x[0]===b.fmt)[1],det=`Reference ${b.id}. Demo booking made on a portfolio website.`;
 const g=`https://calendar.google.com/calendar/render?action=TEMPLATE&text=${encodeURIComponent(t)}&dates=${f(st)}/${f(en)}&details=${encodeURIComponent(det)}&location=${encodeURIComponent(loc)}`;
 const ol=`https://outlook.live.com/calendar/0/deeplink/compose?path=%2Fcalendar%2Faction%2Fcompose&rru=addevent&subject=${encodeURIComponent(t)}&startdt=${st.toISOString()}&enddt=${en.toISOString()}&body=${encodeURIComponent(det)}&location=${encodeURIComponent(loc)}`;
 const c=sm?'btn ghost sm':'btn ghost';return `<a class="${sm?c:'btn pri'}" href="${g}" target="_blank" rel="noopener">${ic('cal','width:15px;height:15px')}Google Calendar</a><a class="${c}" href="${ol}" target="_blank" rel="noopener">Outlook</a>${IN_VIEWER?'':`<button class="${c}" type="button" data-ics="${b.id}">${ic('dl','width:15px;height:15px')}.ics</button>`}`}
function ics(b){if(!b)return;const a=adv(b.adv),o=off(a.off);const st=new Date(b.utc),en=new Date(b.utc+45*6e4);const f=d=>d.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'');
 const txt=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Halden & Rowe demo//EN','BEGIN:VEVENT',`UID:${b.id}@haldenrowe.example`,`DTSTAMP:${f(new Date())}`,`DTSTART:${f(st)}`,`DTEND:${f(en)}`,`SUMMARY:${bkSvcName(b.svc)} with ${a.n} (Halden & Rowe)`,`LOCATION:${b.fmt==='office'?o.addr.replace(/,/g,'\\,'):FMT.find(x=>x[0]===b.fmt)[1]}`,`DESCRIPTION:Reference ${b.id}. Demo booking created on a portfolio website.`,'END:VEVENT','END:VCALENDAR'].join('\r\n');
 const url=URL.createObjectURL(new Blob([txt],{type:'text/calendar'}));const l=document.createElement('a');l.href=url;l.download=`halden-rowe-${b.id}.ics`;document.body.appendChild(l);l.click();l.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Calendar file downloaded')}
function bindBook(){drawMyBk();drawBk();document.addEventListener('cur',S.onCur=drawBk)}

/* ---------- motion engine ---------- */
let io;
function initReveal(){io?.disconnect();io=new IntersectionObserver(es=>es.forEach(e=>{if(!e.isIntersecting)return;const t=e.target;t.classList.add('in');io.unobserve(t);$$('[data-count]',t).forEach(countUp);if(t.dataset.count)countUp(t)}),{threshold:.15,rootMargin:'0px 0px -6% 0px'});
 $$('.rv,.st,[data-count]').forEach(el=>{if(RM){el.classList.add('in');countUp(el,true);return}io.observe(el)})}
function countUp(el,now){if(!el.dataset.count||el.dataset.done)return;el.dataset.done=1;const to=+el.dataset.count,dec=+(el.dataset.dec||0),pre=el.dataset.pre||'',suf=el.dataset.suf||'';const fmt=v=>pre+(dec?v.toFixed(dec):Math.round(v).toLocaleString('en-US'))+suf;if(now||RM){el.textContent=fmt(to);return}
 const t0=performance.now(),D=1600;const f=t=>{const p=Math.min(1,(t-t0)/D),e=1-Math.pow(1-p,4);el.textContent=fmt(to*e);if(p<1)requestAnimationFrame(f)};requestAnimationFrame(f)}
let ticking=false,lastY=scrollY,vel=0;
function measure(){const hs=$('#hs'),tr=$('#hsT');if(hs&&tr){if(innerWidth<=900){hs.style.height='';S.hsDist=0;return}S.hsDist=Math.max(0,tr.scrollWidth-innerWidth);hs.style.height=(innerHeight+S.hsDist)+'px'}}
function frame(){ticking=false;const y=scrollY,vh=innerHeight,H=document.documentElement.scrollHeight;
 $('#prog').style.transform=`scaleX(${clamp(y/Math.max(1,H-vh),0,1)})`;$('#nav')?.classList.toggle('small',y>30);
 if(RM)return;
 const desk=innerWidth>980;
 $$('[data-speed]').forEach(el=>{if(el.hasAttribute('data-desk')&&!desk){el.style.transform='';return}const r=el.getBoundingClientRect();const c=r.top+r.height/2-vh/2;el.style.transform=`translate3d(0,${(-c*+el.dataset.speed).toFixed(1)}px,0)`});
 const band=$('#band .ph')||$('.band .ph');if(band){const r=band.parentElement.getBoundingClientRect();if(r.bottom>0&&r.top<vh)band.style.transform=`translate3d(0,${((r.top+r.height/2-vh/2)*-.12).toFixed(1)}px,0)`}
 const hs=$('#hs');if(hs&&S.hsDist){const r=hs.getBoundingClientRect(),p=clamp(-r.top/(hs.offsetHeight-vh),0,1);$('#hsT').style.transform=`translate3d(${(-p*S.hsDist).toFixed(1)}px,0,0)`;$('#hsBar').style.transform=`scaleX(${p})`;$('#hsN').textContent='0'+Math.min(SV.length,1+Math.floor(p*SV.length))}
 const st=$('#steps');if(st){const r=st.getBoundingClientRect(),p=clamp((vh*.6-r.top)/r.height,0,1);$('#lnF').style.strokeDashoffset=1-p;$$('.step',st).forEach(s=>s.classList.toggle('on',s.getBoundingClientRect().top<vh*.6))}
 const cards=$$('#stack .sc');cards.forEach((c,i)=>{const nx=cards[i+1];if(!nx){c.style.transform='';c.style.filter='';return}const top=parseFloat(getComputedStyle(nx).top)||0;const d=nx.getBoundingClientRect().top-top;const p=clamp(1-d/(vh*.8),0,1);c.style.transform=`scale(${(1-p*.06).toFixed(4)})`;c.style.filter=`brightness(${(1-p*.12).toFixed(3)})`});
 const fl=$('#fill');if(fl){const r=fl.getBoundingClientRect(),p=clamp((vh*.85-r.top)/(r.height+vh*.35),0,1);const w=fl._w||(fl._w=$$('.wd',fl));const n=Math.round(p*w.length);w.forEach((s,i)=>s.classList.toggle('on',i<n))}
 const rp=$('#rprog');if(rp){const b=$('#artBody').getBoundingClientRect();rp.style.transform=`scaleX(${clamp((vh*.5-b.top)/b.height,0,1)})`}
 vel=vel*.8+Math.abs(y-lastY)*.2;lastY=y;const mq=$('#mqt');if(mq){const an=mq.getAnimations()[0];if(an)an.playbackRate=1+Math.min(vel/6,5)}
 if(vel>.3&&!S.velT){S.velT=setTimeout(()=>{S.velT=null;onScroll()},60)}}
function onScroll(){if(!ticking){ticking=true;requestAnimationFrame(frame)}}
addEventListener('scroll',onScroll,{passive:true});addEventListener('resize',()=>{measure();onScroll()});

/* ---------- router ---------- */
const JUMPS=['pricing','contact','calculator','faq','process','about','team'];
function route(){const h=(location.hash||'#home').slice(1)||'home';closeModal();$('#mm')?.classList.remove('open');
 if(JUMPS.includes(h)){const wasHome=S.page==='home';if(!wasHome)render('home');const t=document.getElementById(h);if(t){t.scrollIntoView({behavior:wasHome?'smooth':'instant',block:'start'})}return}
 render(h);scrollTo(0,0)}
function render(h){S.timers.forEach(clearInterval);S.timers=[];if(S.onCur){document.removeEventListener('cur',S.onCur);S.onCur=null}
 let body,bind,cur=h,title='Halden & Rowe · Wealth & Business Advisory';
 if(h==='services'){body=pageServices();title='Services · Halden & Rowe'}
 else if(h.startsWith('service-')&&svc(h.slice(8))){const s=svc(h.slice(8));body=pageService(s);bind=()=>bindService(s);cur='services';title=s.t+' · Halden & Rowe'}
 else if(h==='advisors'){body=pageAdvisors();bind=bindAdvisors;title='Advisors · Halden & Rowe'}
 else if(h==='insights'){body=pageInsights();bind=bindInsights;title='Insights · Halden & Rowe'}
 else if(h.startsWith('article-')&&art(h.slice(8))){const a=art(h.slice(8));body=pageArticle(a);bind=bindArticle;cur='insights';title=a.t+' · Halden & Rowe'}
 else if(h==='book'){body=pageBook();bind=bindBook;title='Book a consultation · Halden & Rowe'}
 else{h='home';cur='home';body=pageHome();bind=bindHome}
 S.page=h;document.title=title;mount(cur,body);bind&&bind();bindAdv($('.hero')||document.createElement('div'));
 if(h!=='home'&&h!=='advisors'&&h!=='book'&&!h.startsWith('service-'))bindAdv();
 measure();initReveal();S.rendered=1;onScroll()}
addEventListener('hashchange',route);
document.addEventListener('click',e=>{const a=e.target.closest('a[href^="#"]');if(!a)return;const h=a.getAttribute('href').slice(1);if(JUMPS.includes(h)&&location.hash==='#'+h){e.preventDefault();route()}});
route();
})();
