(()=>{
const $=(s,el=document)=>el.querySelector(s);
const $$=(s,el=document)=>[...el.querySelectorAll(s)];
const ic=(n,st='')=>`<svg class="i" ${st?`style="${st}"`:''}><use href="#i-${n}"/></svg>`;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmtN=(n,d=0)=>Number(n).toLocaleString('en-US',{minimumFractionDigits:d,maximumFractionDigits:d});
const AVC=['#7C9BBB','#C08A55','#8FAE7E','#D07A6A','#6F7FA8','#B79348'];
const av=n=>`<span class="av" style="background:${AVC[[...n].reduce((a,c)=>a+c.charCodeAt(0),0)%AVC.length]}">${esc(n.split(' ').map(w=>w[0]).join('').slice(0,2))}</span>`;
function ls(k,v){try{if(v===undefined){const x=localStorage.getItem('arbor.'+k);return x?JSON.parse(x):null}localStorage.setItem('arbor.'+k,JSON.stringify(v))}catch(e){return null}}
function toast(msg,action){const t=document.createElement('div');t.className='toast';t.innerHTML=`<span>${esc(msg)}</span>${action?`<button type="button">${esc(action.t)}</button>`:''}`;$('#toasts').appendChild(t);if(action)$('button',t).onclick=()=>{t.remove();action.run()};setTimeout(()=>{t.style.transition='opacity .3s';t.style.opacity=0;setTimeout(()=>t.remove(),300)},3200)}
const stars=r=>`<span class="stars" aria-label="${r} out of 5 stars">${[1,2,3,4,5].map(i=>`<svg class="${r>=i-.25?'':'off'}"><use href="#i-star"/></svg>`).join('')}</span>`;

/* ---------- catalogue ---------- */
const P=[
 {slug:'solve-sofa',img:'room-blue-windows',pos:'50% 70%',name:'Sölve 3-Seat Sofa',type:'sofa',cat:'Sofa',price:1249,compare:1449,rating:4.8,count:212,tag:'Bestseller',v:[['Dusty Blue','#8FA9C4','#C49060'],['Oat','#D9CBB4','#B98B5E'],['Charcoal','#6B6E73','#8A5A34']],desc:'A deep, low-slung sofa with feather-wrapped cushions and a solid FSC oak base. Built to be sat on every day and reupholstered, not replaced.',dims:[['Width','214 cm / 84"'],['Depth','96 cm / 38"'],['Height','78 cm / 31"'],['Seat height','44 cm / 17"']],mat:'Recycled polyester-linen blend, FSC-certified oak legs, feather and foam cushions with removable covers.'},
 {slug:'muffin-lounge',img:'room-green-chair',pos:'40% 75%',name:'Muffin Lounge Chair',type:'lounge',cat:'Chair',price:426,rating:4.9,count:148,v:[['Sage','#8FB5A4','#B98B5E'],['Blush','#E3B8AE','#B98B5E'],['Mist Blue','#9DB4C9','#A87A4F']],desc:'A channel-tufted shell that hugs your shoulders, on slim oak legs. Small enough for a reading corner, generous enough to nap in.',dims:[['Width','78 cm / 31"'],['Depth','80 cm / 31"'],['Height','92 cm / 36"'],['Seat height','42 cm / 16.5"']],mat:'Performance velvet (OEKO-TEX), solid oak legs, high-resilience foam.'},
 {slug:'elio-easy',name:'Elio Easy Chair',type:'easy',cat:'Chair',price:350,rating:4.7,count:96,tag:'New',v:[['Stone Grey','#A5A7A6','#B07A4C'],['Oat','#D8CCB8','#B07A4C'],['Forest','#6F8A74','#8A5A34']],desc:'A mid-century frame in solid ash with loose cushions you can flip, wash and replace. The armrests are wide enough for a cup of coffee.',dims:[['Width','70 cm / 27.5"'],['Depth','78 cm / 31"'],['Height','80 cm / 31.5"'],['Seat height','40 cm / 16"']],mat:'Solid ash frame with water-based oil, wool-blend cushion covers.'},
 {slug:'rumi-rattan',img:'chair-rattan-door',pos:'50% 60%',name:'Rumi Rattan Chair',type:'rattan',cat:'Chair',price:180,rating:4.6,count:74,v:[['Sage','#9DBAA5','#8A5A34'],['Sky','#9CB8CF','#8A5A34'],['Sand','#D9C7A8','#8A5A34']],desc:'Hand-woven rattan on a steam-bent walnut-stained frame, with a plump round cushion. Light enough to carry to the balcony.',dims:[['Width','62 cm / 24.5"'],['Depth','58 cm / 23"'],['Height','76 cm / 30"'],['Seat height','45 cm / 17.5"']],mat:'Natural rattan, beech frame, cotton canvas cushion.'},
 {slug:'romp-pouf',img:'ottoman-striped',pos:'62% 60%',name:'Romp Storage Ottoman',type:'pouf',cat:'Chair',price:86,rating:4.8,count:131,v:[['Cream','#EFE8DC','#C08A55'],['Stone','#CFC7BA','#9C6B42']],desc:'A woven storage ottoman with a lift-off lid. Footrest, extra seat and a hiding place for throws and board games.',dims:[['Width','56 cm / 22"'],['Depth','40 cm / 16"'],['Height','44 cm / 17"']],mat:'Recycled bouclé, solid oak cradle.'},
 {slug:'alma-wardrobe',img:'sideboard-modern',pos:'60% 82%',name:'Alma Sideboard',type:'sideboard',cat:'Cabinet',price:622,rating:4.7,count:58,v:[['Powder Blue','#A9C9D6','#D8B891'],['Chalk','#EDEAE3','#D8B891'],['Sage','#AFC4B0','#D8B891']],desc:'Two soft-close doors, an open oak bay and adjustable shelves, finished in a low-VOC matte lacquer. Arrives fully assembled.',dims:[['Width','160 cm / 63"'],['Depth','42 cm / 16.5"'],['Height','75 cm / 29.5"']],mat:'FSC birch plywood, low-VOC lacquer, oak legs.'},
 {slug:'teo-nightstand',img:'nightstand-wood',pos:'40% 65%',name:'Teo Nightstand',type:'nightstand',cat:'Cabinet',price:166,compare:195,rating:4.8,count:201,v:[['Oak & Cream','#F2EBDD','#C0874E'],['Walnut & Sage','#D5E0D2','#8E5B34']],desc:'A two-drawer bedside table on splayed legs, with a routed pull so there is no hardware to catch.',dims:[['Width','50 cm / 19.5"'],['Depth','40 cm / 16"'],['Height','55 cm / 21.5"']],mat:'Solid oak or walnut, lacquered MDF drawer fronts.'},
 {slug:'oda-bed',img:'bed-wood-linen',pos:'50% 60%',name:'Oda Upholstered Bed',type:'bed',cat:'Bed',price:1090,rating:4.9,count:87,v:[['Mist Blue','#A7BCD0','#B4875C'],['Oat','#D6C8B2','#B4875C'],['Charcoal','#6D7075','#7A5236']],desc:'A channel-stitched headboard and a slatted base that needs no box spring. Queen and King sizes, tool-free assembly in 15 minutes.',dims:[['Width (Queen)','168 cm / 66"'],['Length','218 cm / 86"'],['Headboard height','110 cm / 43"']],mat:'Recycled linen-look fabric, FSC pine frame, oak feet.'},
 {slug:'haru-table',name:'Haru Oval Coffee Table',type:'table',cat:'Table',price:289,rating:4.7,count:112,v:[['Natural Oak','#9DB4C9','#C99A66'],['Smoked Oak','#D6B4A0','#7E5537']],desc:'A soft oval top that is kind to shins, on four turned legs. Sized for a three-seat sofa.',dims:[['Width','120 cm / 47"'],['Depth','62 cm / 24"'],['Height','40 cm / 16"']],mat:'Solid oak with hard-wax oil finish.'},
 {slug:'arc-lamp',img:'lamp-floor-brown',pos:'40% 55%',name:'Halo Floor Lamp',type:'lamp',cat:'Lighting',price:219,rating:4.6,count:64,tag:'New',v:[['Linen','#EFE6D6','#C08A55'],['Sage','#B7CBB5','#C08A55'],['Terracotta','#D69A7B','#C08A55']],desc:'A slim brass stem with a soft matte shade and a warm-dimming bulb included. Fits beside a sofa or a reading chair.',dims:[['Height','150 cm / 59"'],['Base','25 cm / 10"'],['Shade','18 cm / 7"']],mat:'Powder-coated steel, linen shade, oak switch collar.'},
 {slug:'nook-sofa',img:'room-blue-sofa',pos:'58% 70%',name:'Nook 2-Seat Sofa',type:'sofa',cat:'Sofa',price:899,rating:4.7,count:77,v:[['Sage','#A3BBA6','#B98B5E'],['Blush','#E0BCB2','#B98B5E'],['Oat','#D9CBB4','#B98B5E']],desc:'The Sölve, scaled for apartments. Fits through a 76 cm doorway without removing the legs.',dims:[['Width','168 cm / 66"'],['Depth','92 cm / 36"'],['Height','78 cm / 31"']],mat:'Recycled polyester-linen blend, FSC oak legs.'},
 {slug:'brio-dining',img:'dining-upholstered',pos:'35% 60%',name:'Brio Dining Chair',type:'dining',cat:'Chair',price:140,rating:4.8,count:189,v:[['Oak & Oat','#D9CBB4','#C99A66'],['Walnut & Charcoal','#6D7075','#7E5537']],desc:'A light, stackable dining chair with a padded seat. Sold individually, 10% off in sets of four at checkout.',dims:[['Width','46 cm / 18"'],['Depth','50 cm / 19.5"'],['Height','80 cm / 31.5"'],['Seat height','46 cm / 18"']],mat:'Solid oak or walnut-stained beech, wool-blend seat pad.'}
];
const CATS=['All','Chair','Sofa','Cabinet','Table','Bed','Lighting'];
const byslug=s=>P.find(p=>p.slug===s);
const PHOTO=k=>k?`photos/${k}.jpg`:null;
const ph=(key,fallback,alt='',cls='',pos='')=>`<div class="ph ${cls}">${fallback}${key?`<img src="${PHOTO(key)}" alt="${esc(alt)}" loading="lazy" ${pos?`style="object-position:${pos}"`:''} onerror="this.remove()">`:''}</div>`;
const art=(p,vi=0,view)=>{const v=p.v[vi]||p.v[0];if(view==='photo')return ph(p.img,Art.product(p.type,v[1],v[2],'front'),p.name,'',p.pos);return Art.product(p.type,v[1],v[2],view||'front')};
const pimg=(p,vi=0)=>ph(vi===0?p.img:null,Art.product(p.type,p.v[vi][1],p.v[vi][2],'front'),p.name,'',p.pos);
const REV_TXT=[['Worth every cent','Arrived with white-glove delivery two days early. The fabric feels far more expensive than it was.','Hannah P.','Austin, TX'],['Solid and beautiful','Assembly took ten minutes. Sturdy, no wobble, and the colour matches the photos exactly.','Liam O.','Melbourne, VIC'],['Our favourite piece','We compared five brands. This one had the best build quality and the most honest delivery estimate.','Priya S.','Brooklyn, NY'],['Great with kids and a dog','Six months in and the fabric still looks new. Spills wipe straight off.','Tom W.','Brisbane, QLD']];
const S={cart:ls('cart')||[],wish:new Set(ls('wish')||[]),cur:'USD',disc:null,cat:'All',shop:{cats:new Set(),max:1500,colors:new Set(),sale:false,sort:'featured'},user:ls('user'),orders:[],appts:[],reviews:{},newsCode:null,co:{step:1,info:{},ship:'standard'}};
const CUR={USD:['$',1],AUD:['A$',1.52],EUR:['€',.92]};
const money=(usd,d=0)=>{const [s,r]=CUR[S.cur];const v=usd*r;return s+fmtN(d?v:Math.round(v),d)};
const DISC={WELCOME30:{pct:30,label:'30% off your first order'},ARBOR10:{pct:10,label:'10% off'}};
const FREE=500;
function saveCart(){ls('cart',S.cart);ls('wish',[...S.wish]);updateBadges()}
const cartCount=()=>S.cart.reduce((a,l)=>a+l.q,0);
const subtotal=()=>S.cart.reduce((a,l)=>a+byslug(l.s).price*l.q,0);
function totals(ship='standard'){const sub=subtotal();const dsc=S.disc?Math.round(sub*DISC[S.disc].pct)/100:0;const after=sub-dsc;let sh=after>=FREE||!sub?0:49;if(ship==='white')sh+=79;if(ship==='express')sh+=129;const tax=Math.round((after+sh)*0.0825*100)/100;return {sub,dsc,sh,tax,total:after+sh+tax}}
function addToCart(slug,vi=0,q=1,silent){const l=S.cart.find(x=>x.s===slug&&x.v===vi);if(l)l.q+=q;else S.cart.push({s:slug,v:vi,q});saveCart();const b=$('#cartN');if(b){b.classList.remove('pop');void b.offsetWidth;b.classList.add('pop')}
 if(!silent)toast(`${byslug(slug).name} added to cart`,{t:'View cart',run:openCart})}
function updateBadges(){const n=cartCount();const b=$('#cartN');if(b){b.textContent=n;b.hidden=!n}const w=$('#wishN');if(w){w.textContent=S.wish.size;w.hidden=!S.wish.size}}
function toggleWish(slug,btn){if(S.wish.has(slug)){S.wish.delete(slug);toast('Removed from wishlist')}else{S.wish.add(slug);toast('Saved to wishlist',{t:'View',run:()=>location.hash='wishlist'})}saveCart();$$(`[data-wish="${slug}"]`).forEach(b=>b.setAttribute('aria-pressed',S.wish.has(slug)))}

/* ---------- layout ---------- */
function nav(cur){const L=(h,t)=>`<a href="#${h}" ${cur===h?'aria-current="page"':''}>${t}</a>`;
 return `<div class="announce"><span>Free white-glove delivery on orders over <b>${money(FREE)}</b> in the US &amp; Australia</span><span>·</span><span>100-night home trial</span></div>
 <header class="nav" id="nav"><div class="wrap"><a class="logo" href="#home"><svg><use href="#logo"/></svg>Arbor&amp;Co.</a>
 <nav class="links" aria-label="Main">${L('shop','Products')}${L('story','About Us')}${L('stores','Our Store')}${L('delivery','Delivery')}</nav>
 <div class="nav-r"><label class="sr" for="cur">Currency</label><select class="cur" id="cur">${Object.keys(CUR).map(c=>`<option ${c===S.cur?'selected':''}>${c}</option>`).join('')}</select>
  <button class="iconbtn" id="srchBtn" aria-label="Search">${ic('search')}</button><a class="iconbtn hide-s" href="#wishlist" aria-label="Wishlist">${ic('heart')}<span class="badge-n num" id="wishN" hidden></span></a>
  <button class="iconbtn" id="cartBtn" aria-label="Cart">${ic('bag')}<span class="badge-n num" id="cartN" hidden></span></button><button class="iconbtn hide-s" id="acctBtn" aria-label="Account">${ic('user')}</button>
  <button class="iconbtn burger" id="burger" aria-label="Menu" aria-expanded="false">${ic('menu')}</button></div></div>
 <nav class="mmenu" id="mmenu"><a href="#shop">Products</a><a href="#story">About Us</a><a href="#stores">Our Store</a><a href="#delivery">Delivery</a><a href="#wishlist">Wishlist</a><a href="#" id="mAcct">Account</a></nav></header>`}
function footer(){return `<footer class="site"><div class="wrap"><div class="fgrid">
 <div><h4>Service</h4><a href="#delivery">Delivery &amp; returns</a><a href="#delivery">100-night trial</a><a href="#story">Legal notice</a><a href="#story">Data protection</a></div>
 <div><h4>Shop</h4>${CATS.slice(1,6).map(c=>`<a href="#shop" data-fcat="${c}">${c}s</a>`).join('')}</div>
 <a class="logo" href="#home"><svg><use href="#logo"/></svg>Arbor&amp;Co.</a>
 <div><h4>Connect</h4><a href="#home">Instagram</a><a href="#home">Pinterest</a><a href="#home">Journal</a></div>
 <div><h4>Contact</h4><a href="#stores">88 Wythe Ave, Brooklyn NY</a><a href="#stores">21 Smith St, Collingwood VIC</a><a href="#stores">hello@arborandco.com</a></div></div>
 <div class="fbot"><span>© 2026 Arbor &amp; Co. All rights reserved. Fictional brand · Demo by Organoo Studio.</span><span style="display:flex;align-items:center;gap:6px;flex-wrap:wrap"><span class="shopify"><i></i>Built on Shopify · Online Store 2.0</span><a href="#delivery">Terms of service</a><a href="#story">Privacy policy</a></span></div></div></footer>`}
function mountChrome(cur,body){document.getElementById('root').innerHTML=nav(cur)+`<main id="main">${body}</main>`+footer();
 $('#cur').onchange=e=>{S.cur=e.target.value;route();toast('Prices shown in '+S.cur)};
 $('#cartBtn').onclick=openCart;$('#srchBtn').onclick=openSearch;$('#acctBtn').onclick=openAccount;
 $('#mAcct').onclick=e=>{e.preventDefault();openAccount()};$('#burger').onclick=e=>{const m=$('#mmenu');m.classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',m.classList.contains('open'))};
 $$('[data-fcat]').forEach(a=>a.onclick=()=>{S.shop.cats=new Set([a.dataset.fcat])});
 const n=$('#nav');const onS=()=>n.classList.toggle('scrolled',scrollY>10);addEventListener('scroll',onS,{passive:true});onS();
 updateBadges();bindCards();reveal()}
function reveal(){const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.remove('pre');io.unobserve(e.target)}}),{rootMargin:'0px 0px -8% 0px'});
 $$('.reveal').forEach(el=>{if(el.getBoundingClientRect().top>innerHeight){el.classList.add('pre');io.observe(el)}})}

/* ---------- product card ---------- */
function card(p){return `<article class="pcard reveal"><a class="plinth" href="#product-${p.slug}" aria-label="${esc(p.name)}">${art(p)}</a>
 ${p.tag||p.compare?`<span class="tag ${p.compare?'sale':''}">${p.compare?'Sale':p.tag}</span>`:''}
 <button class="iconbtn heart" data-wish="${p.slug}" aria-pressed="${S.wish.has(p.slug)}" aria-label="Save ${esc(p.name)}" style="background:#fff">${ic('heart')}</button>
 <div class="label"><div class="txt"><span>${esc(p.name)}</span><b class="num">${money(p.price)}</b></div><div class="tab br" style="position:relative"><button class="circ" data-add="${p.slug}" aria-label="Add ${esc(p.name)} to cart">${ic('arrow')}</button></div></div></article>`}
function bindCards(root=document){$$('[data-add]',root).forEach(b=>b.onclick=e=>{e.preventDefault();addToCart(b.dataset.add);b.classList.add('added');b.innerHTML=ic('check');setTimeout(()=>{b.classList.remove('added');b.innerHTML=ic('arrow')},1400)});
 $$('[data-wish]',root).forEach(b=>b.onclick=e=>{e.preventDefault();toggleWish(b.dataset.wish,b)})}

/* ---------- HOME ---------- */
function pageHome(){
 const sofa=byslug('solve-sofa'),m1=byslug('muffin-lounge'),m2=byslug('elio-easy');
 const words=(t,d0)=>t.split(' ').map((w,i)=>`<span class="w" style="animation-delay:${d0+i*.07}s">${w}</span>`).join(' ');
 const best=P.filter(p=>S.cat==='All'||p.cat===S.cat).slice(0,6);
 return `<section class="hero wrap"><h1>${words('Slow-made',0)} <span class="pill-img w" style="animation-delay:.1s">${Art.pill('lounge','#8FB5A4','#B98B5E')}</span> ${words('furniture for',.14)}<br><span class="pill-img wide w" style="animation-delay:.3s">${Art.pill('sofa','#8FA9C4','#C49060')}</span> ${words('everyday living',.36)}</h1>
 <div class="hero-grid"><div class="stage" id="stage">${Art.heroRoom()}
  <a class="tab tl" href="#product-solve-sofa" data-jump="reviews" style="text-decoration:none"><span class="avs">${['Hannah P','Liam O','Priya S'].map((n,i)=>`<span style="background:${AVC[i]}">${n.split(' ').map(x=>x[0]).join('')}</span>`).join('')}<span style="background:#151515">12k</span></span><small>4.9 from<br>12,480 reviews</small></a>
  <div class="tab br"><a class="btn dark" href="#shop">Shop now <span class="go">${ic('arrow','width:15px;height:15px')}</span></a></div></div>
  <div class="minis">${[m1,m2].map(p=>`<a class="mini" href="#product-${p.slug}"><div class="pic">${art(p)}<div class="sws">${p.v.map(v=>`<i style="background:${v[1]}"></i>`).join('')}</div></div><div class="meta"><div>${esc(p.name.split(' ').slice(0,2).join(' '))}<div>${stars(p.rating)}</div></div><span class="num">${money(p.price)}</span></div></a>`).join('')}</div></div></section>
 <section class="wrap stats reveal">${[[24,'K+','Homes furnished across the US and Australia since 2016'],[120,'+','Pieces designed in-house and built by partner workshops'],[96,'%','Customers who come back for their next piece']].map(s=>`<div><b class="num" data-count="${s[0]}" data-suf="${s[1]}">${s[0]}${s[1]}</b><span>${s[2]}</span></div>`).join('')}</section>
 <div class="marquee" aria-hidden="true"><div class="track">${Array(2).fill(['FSC-certified oak','Recycled bouclé','Water-based finishes','Carbon-neutral delivery','100-night trial','10-year frame warranty','Made to be repaired']).flat().map(t=>`<span>${t}</span>`).join('')}</div></div>
 <section class="s wrap"><div class="sh"><h2>Our Best Quality Products</h2></div><div class="chips" role="group" aria-label="Filter by category">${CATS.slice(0,6).map(c=>`<button class="chip" type="button" data-hc="${c}" aria-pressed="${c===S.cat}">${c}</button>`).join('')}</div>
  <div class="grid" id="bestGrid">${best.map(card).join('')}</div><div style="text-align:center;margin-top:48px"><a class="btn lg" href="#shop">View all ${P.length} pieces <span class="go" style="background:var(--ink);color:#fff">${ic('arrow','width:15px;height:15px')}</span></a></div></section>
 <section class="s wrap"><div class="why"><div class="reveal"><button class="vid" id="playFilm" aria-label="Play the Arbor & Co. film">${Art.videoScene()}<span class="tab br play"><span class="circ">${ic('play')}</span></span></button><p style="margin-top:14px;font-weight:600;max-width:30ch">Watch the 16-second film and meet the workshop behind every piece</p></div>
  <div class="reveal"><h2 style="font-size:clamp(30px,3.6vw,44px)">Why Choose Us</h2><p class="muted" style="margin:10px 0 24px;max-width:48ch">Four reasons 24,000 homes chose furniture that is built to be kept, not replaced.</p>
  <div class="acc">${[['Sustainability','Every frame uses FSC-certified or reclaimed wood, fabrics are made from recycled fibres, and deliveries are carbon-neutral. We publish the footprint of each piece on its product page.'],['Unrivaled quality','Solid-wood frames, kiln-dried for 21 days, joined with dowels instead of staples. Every frame carries a 10-year warranty and every cover can be removed and washed.'],['Unmatched variety','120+ pieces in 40 fabrics and 3 wood tones, designed to mix across collections so rooms grow over time.'],['Legacy of craft','We work with six family-run workshops in Portugal, Vietnam and Victoria, Australia. Most of our makers have been building furniture for more than 25 years.']].map((a,i)=>`<details ${i===1?'open':''}><summary>${a[0]}</summary><p>${a[1]}</p></details>`).join('')}</div></div></div></section>
 <section class="s wrap reveal"><div class="banner">${Art.bannerScene()}<div class="copy"><h2>Every piece is made to be sat on, lived with and handed down.</h2><a class="btn" href="#shop" style="background:#fff">See products <span class="go" style="background:var(--ink);color:#fff">${ic('arrow','width:14px;height:14px')}</span></a></div><div class="tab tr"><button class="btn dark sm" id="bookBtn" style="height:40px">Book a showroom visit <span class="go" style="width:26px;height:26px">${ic('arrow','width:13px;height:13px')}</span></button></div></div></section>
 <section class="s wrap"><div class="rev-wrap"><div class="reveal"><span class="eyebrow">From real homes</span><h2 style="font-size:clamp(28px,3.4vw,40px);margin-top:10px">Rated 4.9 by 12,480 customers</h2><p class="muted" style="margin-top:10px">Verified reviews from customers in the US and Australia.</p><div style="display:flex;gap:8px;margin-top:20px"><button class="circ" id="revL" aria-label="Previous review" style="background:#fff;color:var(--ink);border:1px solid var(--ink)">${ic('left')}</button><button class="circ" id="revR" aria-label="Next review">${ic('right')}</button></div></div>
  <div class="rev-track" id="revTrack">${REV_TXT.concat([['Delivery team were brilliant','They carried the bed up four flights, assembled it and took all the packaging away.','Grace K.','Sydney, NSW']]).map(r=>`<figure class="rev" style="margin:0">${stars(5)}<blockquote><b style="display:block;margin-bottom:6px;font-family:var(--f-display);font-size:18px">${r[0]}</b>${r[1]}</blockquote><figcaption class="who">${av(r[2])}<div><b>${r[2]}</b>${r[3]} · Verified buyer</div></figcaption></figure>`).join('')}</div></div></section>
 <section class="news wrap reveal"><h2>Subscribe to our newsletter and<br>grab <b>30% OFF</b> your first order</h2><form id="newsF" novalidate><span style="color:var(--blue-deep)">${ic('send','width:26px;height:26px')}</span><label class="sr" for="newsE">Email</label><input class="input" id="newsE" type="email" placeholder="Your email"><button class="btn dark">Subscribe</button></form><p class="err-t" id="newsErr" hidden>Enter a valid email address.</p><div id="newsCode"></div></section>`}

function bindHero(){const fr=$('#heroFrame');if(!fr)return;const L=LOOKS[S.look];
 const place=()=>{const img=$('.ph>img',fr);const W=fr.clientWidth,H=fr.clientHeight;let dw=W,dh=H,ox=0,oy=0;if(img){const ar=L.ar;if(W/H>ar){dw=W;dh=W/ar}else{dh=H;dw=H*ar}ox=(W-dw)*L.pos[0]/100;oy=(H-dh)*L.pos[1]/100}
  $$('.spot',fr).forEach(b=>{const x=ox+dw*b.dataset.x/100,y=oy+dh*b.dataset.y/100;b.style.left=x+'px';b.style.top=y+'px';const fb=fr.getBoundingClientRect();const block=[...$$('.copy>*',fr),$('.side-card',fr),$('.slides',fr)].filter(e=>e&&e.offsetParent).map(e=>{const r=e.getBoundingClientRect();return [r.left-fb.left-18,r.top-fb.top-18,r.left-fb.left+Math.min(r.width,e.scrollWidth||r.width)+18,r.bottom-fb.top+18]});b.hidden=x<24||x>W-24||y<24||y>H-24||block.some(r=>x>r[0]&&x<r[2]&&y>r[1]&&y<r[3])})};
 place();const im=$('.ph>img',fr);if(im)im.addEventListener('error',()=>setTimeout(place,0));S.heroRO&&S.heroRO.disconnect();S.heroRO=new ResizeObserver(place);S.heroRO.observe(fr);
 $$('[data-spot]',fr).forEach(b=>b.onclick=e=>{e.stopPropagation();$$('.spot-card').forEach(c=>c.remove());const sp=L.spots[+b.dataset.spot];const p=byslug(sp[2]);const c=document.createElement('div');c.className='spot-card';
  c.innerHTML=`<a href="#product-${p.slug}" class="ph" style="position:relative">${pimg(p)}</a><div><b>${esc(p.name)}</b>${stars(p.rating)}<div class="row"><span class="num" style="font-weight:700">${money(p.price)}</span><button class="btn dark sm" data-add="${p.slug}">Add</button></div></div>`;
  const bx=parseFloat(b.style.left),by=parseFloat(b.style.top);c.style.left=(bx>fr.clientWidth*.6?bx-270:bx+26)+'px';c.style.top=Math.max(12,Math.min(fr.clientHeight-110,by-40))+'px';if(innerWidth<600){c.style.left='16px';c.style.top='70px'}fr.appendChild(c);bindCards(c);
  setTimeout(()=>document.addEventListener('click',function h(ev){if(!c.contains(ev.target)){c.remove();document.removeEventListener('click',h)}}),0)});
 $('#addLook',fr).onclick=()=>{L.spots.forEach(sp=>addToCart(sp[2],0,1,true));toast(`${L.spots.length} pieces added to cart`,{t:'View cart',run:openCart})};
 $$('[data-look]',fr).forEach(b=>b.onclick=()=>setLook(+b.dataset.look));
 const hs=$('.ph>img',fr)||$('.ph>svg',fr);if(hs&&matchMedia('(pointer:fine)').matches){fr.onmousemove=e=>{const r=fr.getBoundingClientRect();const cur=$('.ph>img',fr)||$('.ph>svg',fr);cur.style.transform=`scale(1.05) translate(${-((e.clientX-r.left)/r.width-.5)*14}px,${-((e.clientY-r.top)/r.height-.5)*10}px)`};fr.onmouseleave=()=>{const cur=$('.ph>img',fr)||$('.ph>svg',fr);cur.style.transform=''}}
 clearInterval(S.lookTimer);if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;let el=0;
 S.lookTimer=setInterval(()=>{const line=$('#lookLine');if(!line){clearInterval(S.lookTimer);return}const busy=fr.matches(':hover')||$('.spot-card')||$('.modal-ov,.drawer,.search-ov')||document.hidden||fr.getBoundingClientRect().bottom<0;if(busy)return;el+=100;const k=el/9000;line.style.width=Math.min(100,k*100)+'%';if(k>=1)setLook((S.look+1)%LOOKS.length)},100)}
function setLook(i){const fr=$('#heroFrame');if(!fr)return;S.look=i;clearInterval(S.lookTimer);fr.innerHTML=heroInner();fr.animate([{opacity:.4},{opacity:1}],{duration:600,easing:'ease-out'});$$('.w',fr).forEach(()=>{});bindHero()}
function bindHome(){
 const st=$('#stage');if(st&&matchMedia('(pointer:fine)').matches){st.addEventListener('mousemove',e=>{const r=st.getBoundingClientRect();const x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;$('svg',st).style.transform=`scale(1.04) translate(${-x*14}px,${-y*10}px)`});st.addEventListener('mouseleave',()=>$('svg',st).style.transform='')}
 $$('[data-hc]').forEach(b=>b.onclick=()=>{S.cat=b.dataset.hc;$$('[data-hc]').forEach(x=>x.setAttribute('aria-pressed',x===b));const g=$('#bestGrid');const l=P.filter(p=>S.cat==='All'||p.cat===S.cat).slice(0,6);g.innerHTML=l.length?l.map(card).join(''):`<div class="empty" style="grid-column:1/-1">No ${S.cat.toLowerCase()} pieces right now.</div>`;g.animate([{opacity:0,transform:'translateY(14px)'},{opacity:1,transform:'none'}],{duration:450,easing:'ease-out'});bindCards(g)});
 $$('[data-count]').forEach(el=>{if(el.getBoundingClientRect().top<innerHeight)return;const io=new IntersectionObserver(es=>{if(es[0].isIntersecting){io.disconnect();const t=+el.dataset.count,suf=el.dataset.suf;const t0=performance.now();const step=now=>{const k=Math.min(1,(now-t0)/1200);el.textContent=Math.round(t*(1-Math.pow(1-k,3)))+suf;if(k<1)requestAnimationFrame(step)};requestAnimationFrame(step)}});io.observe(el)});
 $('#playFilm').onclick=openFilm;$('#bookBtn').onclick=()=>openBooking();
 const tr=$('#revTrack');$('#revL').onclick=()=>tr.scrollBy({left:-380,behavior:'smooth'});$('#revR').onclick=()=>tr.scrollBy({left:380,behavior:'smooth'});
 $('#newsF').onsubmit=e=>{e.preventDefault();const v=$('#newsE').value.trim();const ok=/^\S+@\S+\.\S+$/.test(v);$('#newsE').classList.toggle('err',!ok);$('#newsErr').hidden=ok;if(!ok)return;S.newsCode='WELCOME30';
  $('#newsCode').innerHTML=`<p style="margin-top:18px">You're in. Your code for 30% off:</p><div class="code-box"><span>WELCOME30</span><button class="btn dark sm" type="button" id="applyCode">Apply to cart</button><button class="iconbtn" type="button" id="copyCode" aria-label="Copy code">${ic('copy')}</button></div>`;$('#newsE').value='';
  $('#applyCode').onclick=()=>{S.disc='WELCOME30';toast('WELCOME30 applied: 30% off',{t:'View cart',run:openCart})};$('#copyCode').onclick=()=>{try{navigator.clipboard.writeText('WELCOME30').then(()=>toast('Code copied'),()=>toast('Code: WELCOME30'))}catch(_){toast('Code: WELCOME30')}}};
 $$('[data-jump]').forEach(a=>a.addEventListener('click',()=>S.jump=a.dataset.jump));
}

/* ---------- SHOP ---------- */
function pageShop(){const colors=[['Blue','#8FA9C4'],['Green','#9DBAA5'],['Neutral','#D9CBB4'],['Pink','#E3B8AE'],['Grey','#6B6E73']];
 return `<div class="wrap page-h"><div class="crumbs"><a href="#home">Home</a>/<span>Products</span></div><h1>All furniture</h1></div>
 <div class="wrap shop"><aside class="filters" aria-label="Filters"><div><h4>Category</h4>${CATS.slice(1).map(c=>`<label class="ck"><input type="checkbox" data-fc="${c}" ${S.shop.cats.has(c)?'checked':''}> ${c} <span class="muted num" style="margin-left:auto">${P.filter(p=>p.cat===c).length}</span></label>`).join('')}</div>
  <div><h4>Max price · <span class="num" id="maxV">${money(S.shop.max)}</span></h4><input type="range" id="maxR" min="100" max="1500" step="50" value="${S.shop.max}" aria-label="Maximum price"></div>
  <div><h4>Colour</h4><div class="sws">${colors.map(c=>`<button type="button" class="dot-sw" data-col="${c[0]}" aria-pressed="${S.shop.colors.has(c[0])}" title="${c[0]}" aria-label="${c[0]}" style="background:${c[1]}"></button>`).join('')}</div></div>
  <div><label class="ck"><input type="checkbox" id="saleOnly" ${S.shop.sale?'checked':''}> On sale only</label></div><button class="link" id="clrF" type="button">Clear all filters</button></aside>
  <div><div class="shop-top"><span class="muted" id="cnt"></span><label class="sr" for="sort">Sort</label><select class="sel" id="sort">${[['featured','Featured'],['low','Price: low to high'],['high','Price: high to low'],['rating','Top rated'],['az','Name A–Z']].map(o=>`<option value="${o[0]}" ${o[0]===S.shop.sort?'selected':''}>${o[1]}</option>`).join('')}</select></div><div class="grid" id="shopGrid"></div></div></div>`}
const colorGroup=hex=>{const n=parseInt(hex.slice(1),16),r=n>>16,g=(n>>8)&255,b=n&255;if(r<130&&g<130&&b<130)return 'Grey';if(b>r+10&&b>=g)return 'Blue';if(g>r&&g>b)return 'Green';if(r>g+18&&r>b+18)return 'Pink';return 'Neutral'};
function bindShop(){const draw=()=>{const f=S.shop;let l=P.filter(p=>(!f.cats.size||f.cats.has(p.cat))&&p.price<=f.max&&(!f.sale||p.compare)&&(!f.colors.size||p.v.some(v=>f.colors.has(colorGroup(v[1])))));
  const so={low:(a,b)=>a.price-b.price,high:(a,b)=>b.price-a.price,rating:(a,b)=>b.rating-a.rating,az:(a,b)=>a.name.localeCompare(b.name)}[f.sort];if(so)l=[...l].sort(so);
  $('#cnt').textContent=`${l.length} of ${P.length} pieces`;$('#shopGrid').innerHTML=l.length?l.map(card).join(''):`<div class="empty" style="grid-column:1/-1">Nothing matches these filters. <button class="btn sm" id="clr2" style="margin-left:8px">Clear filters</button></div>`;bindCards($('#shopGrid'));$('#clr2')?.addEventListener('click',clear)};
 const clear=()=>{S.shop={cats:new Set(),max:1500,colors:new Set(),sale:false,sort:S.shop.sort};route()};
 $$('[data-fc]').forEach(c=>c.onchange=()=>{c.checked?S.shop.cats.add(c.dataset.fc):S.shop.cats.delete(c.dataset.fc);draw()});
 $('#maxR').oninput=e=>{S.shop.max=+e.target.value;$('#maxV').textContent=money(S.shop.max);draw()};
 $$('[data-col]').forEach(b=>b.onclick=()=>{const c=b.dataset.col;S.shop.colors.has(c)?S.shop.colors.delete(c):S.shop.colors.add(c);b.setAttribute('aria-pressed',S.shop.colors.has(c));draw()});
 $('#saleOnly').onchange=e=>{S.shop.sale=e.target.checked;draw()};$('#sort').onchange=e=>{S.shop.sort=e.target.value;draw()};$('#clrF').onclick=clear;draw()}

/* ---------- PRODUCT ---------- */
const VIEWS=(p,vi)=>(p.img&&!vi?['photo']:[]).concat(['front','detail','room']);
function pageProduct(p){const vi=S.pv&&S.pv.s===p.slug?S.pv.i:0;const v=p.v[vi];
 const revs=(S.reviews[p.slug]||[]).concat(REV_TXT.map((r,i)=>({t:r[0],b:r[1],n:r[2],loc:r[3],r:i===2?4:5,d:['Sep 12, 2026','Aug 30, 2026','Aug 18, 2026','Jul 29, 2026'][i]})));
 return `<div class="wrap page-h" style="padding-bottom:18px"><div class="crumbs"><a href="#home">Home</a>/<a href="#shop">Products</a>/<span>${p.cat}</span></div></div>
 <div class="wrap pdp"><div class="gallery"><div class="thumbs" role="group" aria-label="Views">${VIEWS(p,vi).map((vw,i)=>`<button type="button" data-view="${vw}" aria-pressed="${i===0}" aria-label="${vw==='photo'?'Photo':vw+' view'}">${art(p,vi,vw)}</button>`).join('')}</div><div class="main-img" id="mainImg" role="img" aria-label="${esc(p.name)} in ${v[0]}">${art(p,vi,VIEWS(p,vi)[0])}</div></div>
 <div class="info"><div style="display:flex;gap:8px;align-items:center">${p.tag?`<span class="chip" style="height:26px;padding:0 10px;font-size:12px">${p.tag}</span>`:''}<a href="#" data-to="reviews" style="display:flex;gap:6px;align-items:center;font-size:13px;text-decoration:none">${stars(p.rating)}<span class="muted">${p.rating} · ${p.count+(S.reviews[p.slug]||[]).length} reviews</span></a></div>
  <h1>${esc(p.name)}</h1><div class="price-row"><b class="num">${money(p.price)}</b>${p.compare?`<s class="num">${money(p.compare)}</s><span class="chip" style="height:26px;padding:0 10px;font-size:12px;background:var(--ink);color:#fff">Save ${money(p.compare-p.price)}</span>`:''}</div>
  <p class="muted" style="font-size:13px;margin-top:-10px">or 4 interest-free payments of ${money(p.price/4,2)} with Shop Pay Installments</p>
  <p style="color:var(--fg-2)">${esc(p.desc)}</p>
  <div><div class="opt-h">Colour <span id="vName">${v[0]}</span></div><div class="sw-row">${p.v.map((x,i)=>`<button type="button" class="dot-sw" data-vi="${i}" aria-pressed="${i===vi}" aria-label="${x[0]}" title="${x[0]}" style="background:linear-gradient(135deg,${x[1]} 55%,${x[2]} 55%)"></button>`).join('')}</div></div>
  <div class="buy"><div class="qty"><button type="button" id="qm" aria-label="Decrease quantity">−</button><input id="qv" value="1" inputmode="numeric" aria-label="Quantity"><button type="button" id="qp" aria-label="Increase quantity">+</button></div><button class="btn dark lg" id="addBtn" style="flex:1">Add to cart · <span class="num" id="addPrice">${money(p.price)}</span></button><button class="iconbtn heart" data-wish="${p.slug}" aria-pressed="${S.wish.has(p.slug)}" aria-label="Save to wishlist" style="width:52px;height:52px;border:1px solid var(--line-2)">${ic('heart')}</button></div>
  <button class="btn lg block" id="buyNow">Buy it now</button>
  <div class="eta"><label class="sr" for="zip">ZIP or postcode</label><input class="input" id="zip" placeholder="ZIP / postcode for delivery date" inputmode="numeric"><button class="btn" id="etaBtn" type="button">Check</button></div><p id="etaOut" class="muted" style="font-size:13.5px;margin-top:-8px">Enter a US ZIP or Australian postcode.</p>
  <div class="usp"><div>${ic('truck')}<b>White-glove delivery</b>Free over ${money(FREE)}</div><div>${ic('return')}<b>100-night trial</b>Free returns</div><div>${ic('shield')}<b>10-year warranty</b>On every frame</div></div>
  <div class="acc">${[['Details',`<p>${esc(p.desc)} Ships in ${p.type==='sofa'||p.type==='bed'?'2–3':'1–2'} boxes.</p>`],['Dimensions',`<table class="dims">${p.dims.map(d=>`<tr><td>${d[0]}</td><td>${d[1]}</td></tr>`).join('')}</table>`],['Materials & care',`<p>${esc(p.mat)} Vacuum weekly, blot spills with a damp cloth, keep out of direct sun.</p>`],['Shipping & returns','<p>White-glove delivery includes room placement, assembly and packaging removal. Not in love? Return within 100 nights for a full refund, and we collect it for free.</p>']].map((a,i)=>`<details ${i===0?'open':''}><summary>${a[0]}</summary>${a[1].replace('<p>','<p style="padding:0 4px 18px;color:var(--muted);font-size:14.5px">').replace('<table','<div style="padding:0 4px 18px"><table').replace('</table>','</table></div>')}</details>`).join('')}</div></div></div>
 <section class="wrap" style="padding-block:40px 0"><div class="sh" style="text-align:left"><h2>Complete the look</h2></div><div class="grid">${P.filter(x=>x.slug!==p.slug&&x.cat!==p.cat).slice(0,3).map(card).join('')}</div></section>
 <section class="wrap" id="reviews" style="padding-block:80px 90px"><div class="revs"><div><h2 style="font-size:34px">Reviews</h2><div style="display:flex;align-items:center;gap:12px;margin:14px 0"><b style="font-family:var(--f-display);font-size:48px;font-weight:600">${p.rating}</b><div>${stars(p.rating)}<div class="muted" style="font-size:13px">${p.count+(S.reviews[p.slug]||[]).length} verified reviews</div></div></div>
  <div class="dist">${[[5,82],[4,13],[3,3],[2,1],[1,1]].map(d=>`<div><span>${d[0]} ★</span><span class="t"><i style="width:${d[1]}%"></i></span><span class="muted num">${d[1]}%</span></div>`).join('')}</div><button class="btn block" id="writeRev" style="margin-top:20px">Write a review</button></div>
  <div><form id="revForm" hidden novalidate style="display:grid;gap:12px;background:var(--soft);padding:20px;border-radius:20px;margin-bottom:10px"><div class="field"><label>Your rating</label><div class="star-in" id="starIn">${[1,2,3,4,5].map(i=>`<button type="button" data-st="${i}" aria-label="${i} stars"><svg><use href="#i-star"/></svg></button>`).join('')}</div></div><div class="two"><div class="field"><label for="rvN">Name</label><input class="input" id="rvN"></div><div class="field"><label for="rvL">City</label><input class="input" id="rvL" placeholder="Portland, OR"></div></div><div class="field"><label for="rvT">Title</label><input class="input" id="rvT"></div><div class="field"><label for="rvB">Review</label><textarea class="input" id="rvB"></textarea></div><p class="err-t" id="rvErr" hidden>Add a rating, your name and a review.</p><button class="btn dark">Post review</button></form>
  <div id="revList">${revs.map(r=>`<div class="rv"><div class="top">${stars(r.r)}<span class="muted">${r.d}</span></div><b>${esc(r.t)}</b><p style="color:var(--fg-2)">${esc(r.b)}</p><span class="muted" style="font-size:13px">${esc(r.n)} · ${esc(r.loc)} · Verified buyer</span></div>`).join('')}</div></div></div></section>
 <div class="sticky-buy" id="sticky"><div class="th" id="stTh">${pimg(p,vi)}</div><div style="flex:1;min-width:0"><b style="font-size:14px">${esc(p.name)}</b><div class="muted" style="font-size:12.5px" id="stV">${v[0]} · ${money(p.price)}</div></div><button class="btn dark" id="stAdd">Add to cart</button></div>`}
function bindProduct(p){let vi=S.pv&&S.pv.s===p.slug?S.pv.i:0,view=VIEWS(p,vi)[0];
 const q=()=>Math.max(1,Math.min(20,parseInt($('#qv').value)||1));const upd=()=>{$('#addPrice').textContent=money(p.price*q())};
 const drawMain=()=>{$('#mainImg').innerHTML=art(p,vi,view);$('#mainImg').setAttribute('aria-label',`${p.name} in ${p.v[vi][0]}`)};
 $$('[data-vi]').forEach(b=>b.onclick=()=>{vi=+b.dataset.vi;S.pv={s:p.slug,i:vi};$$('[data-vi]').forEach(x=>x.setAttribute('aria-pressed',x===b));$('#vName').textContent=p.v[vi][0];const vs=VIEWS(p,vi);if(!vs.includes(view))view=vs[0];$('.thumbs').innerHTML=vs.map(vw=>`<button type="button" data-view="${vw}" aria-pressed="${vw===view}" aria-label="${vw==='photo'?'Photo':vw+' view'}">${art(p,vi,vw)}</button>`).join('');bindViews();drawMain();$('#stTh').innerHTML=pimg(p,vi);$('#stV').textContent=`${p.v[vi][0]} · ${money(p.price)}`;$('#mainImg').animate([{opacity:.3},{opacity:1}],{duration:350})});
 const bindViews=()=>$$('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;$$('[data-view]').forEach(x=>x.setAttribute('aria-pressed',x===b));drawMain()});bindViews();
 $('#mainImg').onclick=e=>{const m=e.currentTarget;m.classList.toggle('zoom');if(m.classList.contains('zoom')){const r=m.getBoundingClientRect();$('svg',m).style.transformOrigin=`${(e.clientX-r.left)/r.width*100}% ${(e.clientY-r.top)/r.height*100}%`}};
 $('#qm').onclick=()=>{$('#qv').value=Math.max(1,q()-1);upd()};$('#qp').onclick=()=>{$('#qv').value=Math.min(20,q()+1);upd()};$('#qv').oninput=upd;$('#qv').onblur=()=>{$('#qv').value=q();upd()};
 $('#addBtn').onclick=()=>{addToCart(p.slug,vi,q());const b=$('#addBtn');b.innerHTML=ic('check')+' Added to cart';setTimeout(()=>{if(!document.body.contains(b)||!$('#qv'))return;b.innerHTML=`Add to cart · <span class="num" id="addPrice">${money(p.price*q())}</span>`},1500)};
 $('#stAdd').onclick=()=>addToCart(p.slug,vi,1);
 $('#buyNow').onclick=()=>{addToCart(p.slug,vi,q(),true);location.hash='checkout'};
 const eta=()=>{const z=$('#zip').value.trim();const d=(a,b)=>{const x=new Date(2026,8,29);x.setDate(x.getDate()+a);const y=new Date(2026,8,29);y.setDate(y.getDate()+b);const f=t=>t.toLocaleDateString('en-US',{month:'short',day:'numeric'});return f(x)+'–'+f(y)};
  if(/^\d{5}$/.test(z)){$('#etaOut').innerHTML=`${ic('truck','width:15px;height:15px;vertical-align:-3px')} Arrives <b>${d(7,11)}</b> to ${z}, from our New Jersey warehouse.`;$('#zip').classList.remove('err')}
  else if(/^\d{4}$/.test(z)){const metro=/^(2|3|4)/.test(z);$('#etaOut').innerHTML=`${ic('truck','width:15px;height:15px;vertical-align:-3px')} Arrives <b>${metro?d(5,8):d(9,14)}</b> to ${z}, from our Melbourne warehouse.`;$('#zip').classList.remove('err')}
  else{$('#etaOut').textContent='Enter a 5-digit US ZIP or a 4-digit Australian postcode.';$('#zip').classList.add('err')}};
 $('#etaBtn').onclick=eta;$('#zip').onkeydown=e=>{if(e.key==='Enter')eta()};
 $$('[data-to]').forEach(a=>a.onclick=e=>{e.preventDefault();document.getElementById(a.dataset.to).scrollIntoView({behavior:'smooth'})});
 let rating=0;$('#writeRev').onclick=()=>{$('#revForm').hidden=!$('#revForm').hidden;if(!$('#revForm').hidden)$('#rvN').focus()};
 $$('[data-st]').forEach(b=>b.onclick=()=>{rating=+b.dataset.st;$$('[data-st]').forEach(x=>x.classList.toggle('on',+x.dataset.st<=rating))});
 $('#revForm').onsubmit=e=>{e.preventDefault();const n=$('#rvN').value.trim(),bd=$('#rvB').value.trim();if(!rating||!n||!bd){$('#rvErr').hidden=false;return}(S.reviews[p.slug]=S.reviews[p.slug]||[]).unshift({t:$('#rvT').value.trim()||'Review',b:bd,n,loc:$('#rvL').value.trim()||'—',r:rating,d:'Just now'});S.jump='reviews';route();toast('Thanks! Your review is live.')};
 const sticky=$('#sticky');const onS=()=>{const r=$('#addBtn').getBoundingClientRect();sticky.classList.toggle('show',r.bottom<0&&$('#reviews').getBoundingClientRect().top>innerHeight*.6)};addEventListener('scroll',onS,{passive:true});S.cleanup=()=>removeEventListener('scroll',onS);
}

/* ---------- CART ---------- */
function openCart(){closeAll();const ov=document.createElement('div');ov.className='ov';const d=document.createElement('aside');d.className='drawer';d.setAttribute('role','dialog');d.setAttribute('aria-label','Cart');document.body.append(ov,d);
 const close=()=>{ov.remove();d.remove();document.removeEventListener('keydown',k)};const k=e=>{if(e.key==='Escape')close()};document.addEventListener('keydown',k);ov.onclick=close;
 const draw=()=>{const t=totals();const left=Math.max(0,FREE-(t.sub-t.dsc));
  d.innerHTML=`<div class="dr-h"><h3>Your cart <span class="muted num" style="font-size:16px">(${cartCount()})</span></h3><button class="iconbtn" data-close aria-label="Close cart">${ic('x')}</button></div>
  ${S.cart.length?`<div class="dr-b"><div class="ship-bar"><span>${left?`You're <b class="num">${money(left)}</b> away from free white-glove delivery`:`${ic('check','width:15px;height:15px;vertical-align:-3px;color:var(--good)')} You've unlocked free white-glove delivery`}</span><span class="t"><i style="width:${Math.min(100,(t.sub-t.dsc)/FREE*100)}%"></i></span></div>
   ${S.cart.map((l,i)=>{const p=byslug(l.s);return `<div class="line"><a class="th" href="#product-${p.slug}" data-close>${pimg(p,l.v)}</a><div><div class="t1"><a href="#product-${p.slug}" data-close style="text-decoration:none">${esc(p.name)}</a><span class="num">${money(p.price*l.q)}</span></div><small>${p.v[l.v][0]}</small><div class="ctl"><div class="qty sm"><button type="button" data-dq="${i}" aria-label="Decrease">−</button><input value="${l.q}" readonly aria-label="Quantity" class="num"><button type="button" data-iq="${i}" aria-label="Increase">+</button></div><button class="link" data-rm="${i}">Remove</button></div></div></div>`}).join('')}
   <details><summary style="cursor:pointer;font-size:13.5px;font-weight:600">Add an order note</summary><textarea class="input" id="note" style="margin-top:8px" placeholder="Gate code, delivery instructions…">${esc(S.note||'')}</textarea></details></div>
   <div class="dr-f"><form class="promo" id="promoF" novalidate><label class="sr" for="promo">Discount code</label><input class="input" id="promo" placeholder="Discount code" value="${S.disc||''}"><button class="btn sm" style="height:42px">${S.disc?'Remove':'Apply'}</button></form><p class="err-t" id="promoErr" hidden>That code isn't valid. Try WELCOME30.</p>
   <div class="sum-row"><span>Subtotal</span><span class="num">${money(t.sub)}</span></div>${t.dsc?`<div class="sum-row" style="color:var(--good)"><span>${S.disc} · ${DISC[S.disc].label}</span><span class="num">−${money(t.dsc)}</span></div>`:''}<div class="sum-row"><span>Delivery</span><span>${t.sh?money(t.sh):'Free'}</span></div><div class="sum-row total"><span>Estimated total</span><span class="num">${money(t.sub-t.dsc+t.sh)}</span></div>
   <a class="btn dark lg block" href="#checkout" data-close>${ic('lock','width:16px;height:16px')} Checkout</a><p class="muted" style="font-size:12px;text-align:center">Taxes calculated at checkout · Shop Pay, Apple Pay, Afterpay accepted</p></div>`
  :`<div class="dr-b" style="text-align:center;padding-top:50px"><div style="width:84px;height:84px;border-radius:50%;background:var(--soft);display:grid;place-items:center;margin:0 auto">${ic('bag','width:32px;height:32px')}</div><h3 style="font-size:22px;margin-top:16px">Your cart is empty</h3><p class="muted">Start with our most-loved pieces.</p><div style="display:grid;gap:12px;margin-top:18px;text-align:left">${P.slice(0,3).map(p=>`<div class="line"><a class="th" href="#product-${p.slug}" data-close>${pimg(p)}</a><div><div class="t1"><span>${esc(p.name)}</span><span class="num">${money(p.price)}</span></div><button class="btn sm" data-qa="${p.slug}" style="margin-top:8px">Add to cart</button></div></div>`).join('')}</div></div>`}`;
  $$('[data-close]',d).forEach(a=>a.addEventListener('click',close));
  $$('[data-dq]',d).forEach(b=>b.onclick=()=>{const l=S.cart[+b.dataset.dq];l.q--;if(!l.q)S.cart.splice(+b.dataset.dq,1);saveCart();draw()});
  $$('[data-iq]',d).forEach(b=>b.onclick=()=>{S.cart[+b.dataset.iq].q++;saveCart();draw()});
  $$('[data-rm]',d).forEach(b=>b.onclick=()=>{const l=S.cart.splice(+b.dataset.rm,1)[0];saveCart();draw();toast(byslug(l.s).name+' removed',{t:'Undo',run:()=>{S.cart.push(l);saveCart();openCart()}})});
  $$('[data-qa]',d).forEach(b=>b.onclick=()=>{addToCart(b.dataset.qa,0,1,true);draw()});
  $('#note',d)?.addEventListener('input',e=>S.note=e.target.value);
  $('#promoF',d)?.addEventListener('submit',e=>{e.preventDefault();if(S.disc){S.disc=null;draw();return}const c=$('#promo',d).value.trim().toUpperCase();if(DISC[c]){S.disc=c;draw();toast(c+' applied')}else{$('#promoErr',d).hidden=false;$('#promo',d).classList.add('err')}})};
 draw();S.redrawCart=draw}
function closeAll(){$$('.ov,.drawer,.modal-ov,.search-ov').forEach(x=>x.remove())}

/* ---------- CHECKOUT ---------- */
function pageCheckout(){if(!S.cart.length)return `<div class="wrap confirm"><h1 style="font-size:40px">Your cart is empty</h1><p class="muted">Add something you love, then come back to check out.</p><a class="btn dark lg" href="#shop">Browse products</a></div>`;
 return `<div class="wrap page-h" style="padding-bottom:0"><div class="crumbs"><a href="#home">Home</a>/<a href="#" id="toCart">Cart</a>/<span>Checkout</span></div><h1 style="font-size:40px">Checkout</h1></div><div class="wrap co"><div id="coMain"></div><aside class="co-sum" id="coSum"></aside></div>`}
function bindCheckout(){if(!S.cart.length)return;$('#toCart').onclick=e=>{e.preventDefault();openCart()};
 const C=S.co;const sum=()=>{const t=totals(C.ship);$('#coSum').innerHTML=`<b style="font-family:var(--f-display);font-size:20px">Order summary</b>${S.cart.map(l=>{const p=byslug(l.s);return `<div class="line" style="grid-template-columns:64px 1fr"><span class="th" style="width:64px;height:64px;position:relative">${pimg(p,l.v)}<span class="badge-n" style="top:-6px;right:-6px">${l.q}</span></span><div><div class="t1"><span style="font-size:14px">${esc(p.name)}</span><span class="num">${money(p.price*l.q)}</span></div><small>${p.v[l.v][0]}</small></div></div>`}).join('')}
  <div style="border-top:1px solid var(--line-2);padding-top:12px;display:grid;gap:8px"><div class="sum-row"><span>Subtotal</span><span class="num">${money(t.sub)}</span></div>${t.dsc?`<div class="sum-row" style="color:var(--good)"><span>Discount (${S.disc})</span><span class="num">−${money(t.dsc)}</span></div>`:''}<div class="sum-row"><span>Delivery</span><span class="num">${t.sh?money(t.sh):'Free'}</span></div><div class="sum-row"><span>Estimated tax</span><span class="num">${money(t.tax,2)}</span></div><div class="sum-row total"><span>Total</span><span class="num">${money(t.total,2)} <small class="muted" style="font-size:12px;font-family:var(--f-ui)">${S.cur}</small></span></div></div>
  <div class="demo-note">${ic('lock','width:15px;height:15px')}Demo checkout. No payment is taken.</div>`};
 const steps=()=>`<div class="steps">${['Information','Delivery','Payment'].map((s,i)=>`<span class="${C.step===i+1?'on':C.step>i+1?'done':''}"><i>${C.step>i+1?'✓':i+1}</i>${s}</span>`).join('<span>—</span>')}</div>`;
 const draw=()=>{const M=$('#coMain');const I=C.info;
  if(C.step===1){M.innerHTML=steps()+`<form id="f1" novalidate><div style="display:flex;gap:10px;flex-wrap:wrap"><button type="button" class="btn dark" style="flex:1;background:#5A31F4;border-color:#5A31F4" id="expPay">Express checkout · Shop Pay</button></div><div class="muted" style="text-align:center;font-size:12.5px">or continue below</div>
   <div class="field"><label for="em">Email</label><input class="input" id="em" type="email" autocomplete="email" value="${esc(I.em||S.user?.email||'')}"></div>
   <div class="two"><div class="field"><label for="fn">First name</label><input class="input" id="fn" autocomplete="given-name" value="${esc(I.fn||'')}"></div><div class="field"><label for="ln">Last name</label><input class="input" id="ln" autocomplete="family-name" value="${esc(I.ln||'')}"></div></div>
   <div class="field"><label for="ad">Address</label><input class="input" id="ad" autocomplete="street-address" value="${esc(I.ad||'')}"></div>
   <div class="three"><div class="field"><label for="ci">City</label><input class="input" id="ci" value="${esc(I.ci||'')}"></div><div class="field"><label for="co">Country</label><select class="input" id="co"><option ${I.co==='United States'?'selected':''}>United States</option><option ${I.co==='Australia'?'selected':''}>Australia</option></select></div><div class="field"><label for="zp">ZIP / postcode</label><input class="input" id="zp" inputmode="numeric" value="${esc(I.zp||'')}"></div></div>
   <p class="err-t" id="e1" hidden></p><button class="btn dark lg">Continue to delivery</button></form>`;
   $('#expPay').onclick=()=>{Object.assign(I,{em:'jordan@example.com',fn:'Jordan',ln:'Lee',ad:'148 Bedford Ave',ci:'Brooklyn',co:'United States',zp:'11249'});C.step=2;draw();toast('Details filled from Shop Pay (demo)')};
   $('#f1').onsubmit=e=>{e.preventDefault();const v=id=>$('#'+id).value.trim();const bad=[];if(!/^\S+@\S+\.\S+$/.test(v('em')))bad.push('em');['fn','ln','ad','ci'].forEach(k=>{if(!v(k))bad.push(k)});const co=v('co');if(!(co==='United States'?/^\d{5}$/:/^\d{4}$/).test(v('zp')))bad.push('zp');
    $$('#f1 .input').forEach(i=>i.classList.toggle('err',bad.includes(i.id)));if(bad.length){$('#e1').hidden=false;$('#e1').textContent=bad.includes('zp')?`Enter a valid ${co==='United States'?'5-digit ZIP':'4-digit postcode'} and fill the highlighted fields.`:'Fill in the highlighted fields.';return}
    Object.assign(I,{em:v('em'),fn:v('fn'),ln:v('ln'),ad:v('ad'),ci:v('ci'),co,zp:v('zp')});C.step=2;draw();scrollTo({top:0,behavior:'smooth'})}}
  if(C.step===2){const t0=totals('standard');M.innerHTML=steps()+`<div class="demo-note" style="margin-bottom:14px;background:var(--soft)">Ship to <b style="margin-left:4px">${esc(I.fn)} ${esc(I.ln)}, ${esc(I.ad)}, ${esc(I.ci)} ${esc(I.zp)}</b><button class="link" id="chg" style="margin-left:auto">Change</button></div><form id="f2" style="display:grid;gap:12px">
   ${[['standard','Standard delivery',I.co==='Australia'?'5–10 business days':'7–11 business days',t0.sh?money(t0.sh):'Free'],['white','White-glove delivery','Room placement, assembly, packaging removed','+'+money(79)],['express','Express delivery','3–5 business days, curbside','+'+money(129)]].map(o=>`<label class="radio-card"><input type="radio" name="sh" value="${o[0]}" ${C.ship===o[0]?'checked':''}><div><b>${o[1]}</b><small>${o[2]}</small></div><b class="num">${o[3]}</b></label>`).join('')}
   <button class="btn dark lg">Continue to payment</button><button type="button" class="link" id="back1">← Back to information</button></form>`;
   $$('[name=sh]').forEach(r=>r.onchange=()=>{C.ship=r.value;sum()});$('#chg').onclick=$('#back1').onclick=()=>{C.step=1;draw()};$('#f2').onsubmit=e=>{e.preventDefault();C.step=3;draw()}}
  if(C.step===3){M.innerHTML=steps()+`<form id="f3" novalidate><div class="radio-card" style="cursor:default"><div><b>Credit or debit card</b><small>Visa, Mastercard, Amex · all transactions are secure and encrypted</small></div>${ic('lock')}</div>
   <div class="field"><label for="cn">Card number</label><input class="input num" id="cn" inputmode="numeric" autocomplete="cc-number" placeholder="4242 4242 4242 4242" maxlength="19"></div>
   <div class="three"><div class="field"><label for="nm">Name on card</label><input class="input" id="nm" value="${esc((I.fn||'')+' '+(I.ln||''))}"></div><div class="field"><label for="ex">Expiry (MM/YY)</label><input class="input num" id="ex" placeholder="12/28" maxlength="5"></div><div class="field"><label for="cv">CVC</label><input class="input num" id="cv" placeholder="123" maxlength="4" inputmode="numeric"></div></div>
   <label style="display:flex;gap:10px;align-items:center;font-size:14px"><input type="checkbox" id="mk" checked style="accent-color:var(--ink)"> Email me about new collections and offers</label>
   <p class="hint muted" style="font-size:12.5px">Demo tip: use 4242 4242 4242 4242, any future expiry and any 3 digits.</p><p class="err-t" id="e3" hidden></p>
   <button class="btn dark lg" id="payBtn">${ic('lock','width:16px;height:16px')} Pay ${money(totals(C.ship).total,2)}</button><button type="button" class="link" id="back2">← Back to delivery</button></form>`;
   $('#cn').oninput=e=>{const d=e.target.value.replace(/\D/g,'').slice(0,16);e.target.value=d.replace(/(.{4})/g,'$1 ').trim()};
   $('#ex').oninput=e=>{let d=e.target.value.replace(/\D/g,'').slice(0,4);if(d.length>2)d=d.slice(0,2)+'/'+d.slice(2);e.target.value=d};
   $('#back2').onclick=()=>{C.step=2;draw()};
   $('#f3').onsubmit=e=>{e.preventDefault();const cn=$('#cn').value.replace(/\s/g,'');const luhn=s=>{let t=0;[...s].reverse().forEach((c,i)=>{let d=+c;if(i%2){d*=2;if(d>9)d-=9}t+=d});return s.length>=13&&t%10===0};
    const [mm,yy]=$('#ex').value.split('/').map(Number);const expOk=mm>=1&&mm<=12&&yy&&(2000+yy>2026||(2000+yy===2026&&mm>=9));const bad=[];if(!luhn(cn))bad.push('cn');if(!expOk)bad.push('ex');if(!/^\d{3,4}$/.test($('#cv').value))bad.push('cv');if(!$('#nm').value.trim())bad.push('nm');
    $$('#f3 .input').forEach(i=>i.classList.toggle('err',bad.includes(i.id)));if(bad.length){$('#e3').hidden=false;$('#e3').textContent=bad.includes('cn')?'That card number is not valid. Check the digits.':bad.includes('ex')?'Enter an expiry date in the future.':'Fill in the highlighted fields.';return}
    const b=$('#payBtn');b.disabled=true;b.textContent='Processing…';setTimeout(()=>{const t=totals(C.ship);const no='AR-'+(48210+S.orders.length);S.lastOrder={no,lines:S.cart.map(l=>({...l})),t,ship:C.ship,info:{...I},cur:S.cur,card:cn.slice(-4)};S.orders.unshift(S.lastOrder);S.cart=[];S.disc=null;C.step=1;saveCart();location.hash='order'},1300)}}
  sum()};
 draw()}
function pageOrder(){const o=S.lastOrder;if(!o)return `<div class="wrap confirm"><h1 style="font-size:40px">No recent order</h1><a class="btn dark lg" href="#shop">Shop furniture</a></div>`;
 const eta=new Date(2026,8,29);eta.setDate(eta.getDate()+(o.ship==='express'?4:9));
 return `<div class="wrap confirm"><div class="ok">${ic('check')}</div><span class="eyebrow">Order ${o.no}</span><h1 style="font-size:clamp(34px,5vw,56px)">Thank you, ${esc(o.info.fn)}!</h1><p class="muted" style="max-width:52ch">Your order is confirmed. We've sent a receipt to <b>${esc(o.info.em)}</b>. Estimated delivery: <b>${eta.toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric'})}</b>.</p>
 <div class="co-sum" style="position:static;width:min(520px,100%);text-align:left">${o.lines.map(l=>{const p=byslug(l.s);return `<div class="line" style="grid-template-columns:64px 1fr"><span class="th" style="width:64px;height:64px">${pimg(p,l.v)}</span><div><div class="t1"><span>${l.q} × ${esc(p.name)}</span><span class="num">${money(p.price*l.q)}</span></div><small>${p.v[l.v][0]}</small></div></div>`}).join('')}<div class="sum-row total" style="border-top:1px solid var(--line-2);padding-top:12px"><span>Paid with card •••• ${o.card}</span><span class="num">${money(o.t.total,2)}</span></div></div>
 <div style="display:flex;gap:10px;flex-wrap:wrap;justify-content:center"><a class="btn dark lg" href="#shop">Continue shopping</a><button class="btn lg" id="trackBtn">Track order</button></div></div>`}

/* ---------- STORY / STORES / DELIVERY / WISHLIST ---------- */
function pageStory(){return `<div class="wrap"><div class="story-hero"><div><div class="crumbs"><a href="#home">Home</a>/<span>About us</span></div><h1 style="font-size:clamp(40px,6vw,76px);margin-top:14px;letter-spacing:-.04em">Furniture you keep for the next twenty years.</h1></div><p>Arbor &amp; Co. started in a shared Brooklyn workshop in 2016 with one sofa and a simple rule: if it can't be repaired, we don't make it. Today we design 120 pieces with six family-run workshops and deliver to homes across the US and Australia.</p></div>
 <div class="stage reveal" style="aspect-ratio:21/9">${ph('room-blue-windows',Art.videoScene(),'Sölve sofa in a bright living room','','50% 65%')}</div>
 <section class="s"><div class="sh" style="text-align:left"><span class="eyebrow">Our timeline</span><h2 style="margin-top:8px">A decade of slow furniture</h2></div><div class="timeline">${[['2016','Two designers build the first Sölve sofa in a Brooklyn co-op workshop and sell 40 before the frame is finished.'],['2018','First partner workshop in Porto. Removable, washable covers become standard on every piece.'],['2021','Launch in Australia with a Melbourne warehouse and a Collingwood showroom.'],['2024','Carbon-neutral delivery across both markets and a repair programme for any piece we have ever sold.']].map(t=>`<div class="reveal"><b>${t[0]}</b><p>${t[1]}</p></div>`).join('')}</div></section>
 <section class="s"><div class="sh" style="text-align:left"><span class="eyebrow">Materials</span><h2 style="margin-top:8px">What our furniture is made of</h2></div><div class="mat">${[['FSC-certified oak','linear-gradient(135deg,#D9AE7E,#B98553)','Every solid-wood frame comes from certified forests. We kiln-dry it for 21 days so it does not warp in humid summers.'],['Recycled bouclé & linen','radial-gradient(circle at 30% 30%,#F4EFE6 20%,#E3DBCD 70%)','Upholstery fabrics are woven from recycled polyester and linen offcuts. Each metre keeps 22 plastic bottles out of landfill.'],['Water-based finishes','linear-gradient(135deg,#A9C9D6,#8FAFC4)','Low-VOC lacquers and hard-wax oils that are safe for nurseries and easy to touch up at home.']].map(m=>`<div class="reveal"><div class="sw" style="background:${m[1]};position:relative;overflow:hidden">${m[0].startsWith('Recycled')?ph('chair-white-studio','','Recycled bouclé close-up','','50% 40%'):''}</div><h3 style="font-size:20px">${m[0]}</h3><p class="muted" style="font-size:14.5px">${m[2]}</p></div>`).join('')}</div></section>
 <section class="wrap stats" style="padding-inline:0">${[['38%','Lower carbon footprint than the industry average per piece'],['6','Family-run partner workshops'],['0','Pieces sent to landfill from our returns since 2022']].map(s=>`<div><b>${s[0]}</b><span>${s[1]}</span></div>`).join('')}</section>
 <div style="text-align:center;padding-bottom:90px"><a class="btn dark lg" href="#shop">Shop the collection</a></div></div>`}
const STORES=[['Brooklyn','88 Wythe Ave, Williamsburg, NY 11249','America/New_York','Mon–Sat 10:00–19:00 · Sun 11:00–18:00',10,19],['Los Angeles','1240 E 3rd St, Arts District, CA 90013','America/Los_Angeles','Mon–Sun 10:00–19:00',10,19],['Melbourne','21 Smith St, Collingwood VIC 3066','Australia/Melbourne','Tue–Sun 10:00–17:30',10,17.5],['Sydney','402 Crown St, Surry Hills NSW 2010','Australia/Sydney','Mon–Sat 10:00–18:00',10,18]];
function storeOpen(s){try{const h=new Date().toLocaleString('en-US',{timeZone:s[2],hour:'numeric',minute:'numeric',hour12:false});const [hh,mm]=h.split(':').map(Number);const t=hh+mm/60;return t>=s[4]&&t<s[5]}catch(e){return false}}
function pageStores(){return `<div class="wrap page-h"><div class="crumbs"><a href="#home">Home</a>/<span>Our store</span></div><h1>Visit a showroom</h1><p class="muted" style="margin-top:12px;max-width:56ch">Sit on everything, touch every fabric and take home free swatches. Book a 45-minute session with a designer, free of charge.</p></div>
 <div class="wrap stores" style="padding-bottom:90px">${STORES.map((s,i)=>{const o=storeOpen(s);const local=new Date().toLocaleTimeString('en-US',{timeZone:s[2],hour:'numeric',minute:'2-digit'});return `<div class="store reveal"><span class="open ${o?'':'closed'}">${o?'Open now':'Closed now'} · ${local} local</span><h3 style="font-size:28px">${s[0]}</h3><p style="display:flex;gap:8px">${ic('pin')}${s[1]}</p><p class="hrs">${s[3]}</p><div style="display:flex;gap:8px;flex-wrap:wrap"><button class="btn dark" data-book="${i}">Book an appointment</button><a class="btn" href="https://www.google.com/maps/search/${encodeURIComponent(s[1])}" target="_blank" rel="noopener">Directions</a></div></div>`}).join('')}</div>`}
function pageDelivery(){return `<div class="wrap page-h"><div class="crumbs"><a href="#home">Home</a>/<span>Delivery</span></div><h1>Delivery &amp; returns</h1></div>
 <div class="wrap" style="display:grid;grid-template-columns:minmax(0,1.3fr) minmax(0,1fr);gap:40px;padding-bottom:40px" id="delGrid"><div><div class="tbl-wrap"><table class="tbl"><thead><tr><th>Region</th><th>Standard</th><th>White-glove</th><th>Lead time</th></tr></thead><tbody>${[['US · East Coast','Free over $500, else $49','+$79','7–11 days'],['US · West Coast','Free over $500, else $49','+$79','8–12 days'],['Australia · Metro','Free over A$760, else A$75','+A$120','5–10 days'],['Australia · Regional','A$95','+A$140','9–14 days'],['Canada & UK','Calculated at checkout','Not available','12–18 days']].map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div>
 <div class="acc" style="margin-top:30px">${[['What is white-glove delivery?','A two-person team brings your furniture to the room of your choice, assembles it and takes all packaging away for recycling.'],['How does the 100-night trial work?','Live with it for up to 100 nights. If it is not right, we collect it for free and refund you in full. Returned pieces are refurbished and resold, never landfilled.'],['Can I change my delivery date?','Yes. Reply to your dispatch email or use the tracking page up to 48 hours before your slot.'],['Do you deliver to apartments without elevators?','Yes, up to the 4th floor at no extra cost. Let us know in the order note.']].map(a=>`<details><summary>${a[0]}</summary><p>${a[1]}</p></details>`).join('')}</div></div>
 <aside class="calc"><h3 style="font-size:22px">Delivery calculator</h3><div class="field"><label for="dcC">Deliver to</label><select class="input" id="dcC"><option value="us-e">US · East Coast</option><option value="us-w">US · West Coast</option><option value="au-m">Australia · Metro</option><option value="au-r">Australia · Regional</option></select></div>
 <div class="field"><label for="dcV">Order value (USD)</label><input class="input num" id="dcV" type="number" min="0" value="${subtotal()||650}"></div><label style="display:flex;gap:10px;align-items:center;font-size:14px"><input type="checkbox" id="dcW" style="accent-color:var(--ink)"> Add white-glove service</label><div class="res" id="dcR"></div></aside></div><div style="height:50px"></div>`}
function bindDelivery(){if(innerWidth<900)$('#delGrid').style.gridTemplateColumns='1fr';const calc=()=>{const r=$('#dcC').value,v=+$('#dcV').value||0,w=$('#dcW').checked;const au=r.startsWith('au');let fee=r==='au-r'?62:v>=FREE?0:au?49:49;if(w)fee+=au?79:79;const lead={'us-e':'7–11','us-w':'8–12','au-m':'5–10','au-r':'9–14'}[r];
 $('#dcR').innerHTML=`<div class="sum-row"><span>Delivery fee</span><b class="num">${fee?money(fee):'Free'}</b></div><div class="sum-row" style="margin-top:6px"><span>Arrives in</span><b>${lead} business days</b></div>${v<FREE&&r!=='au-r'?`<p class="muted" style="font-size:12.5px;margin-top:8px">Add ${money(FREE-v)} more for free standard delivery.</p>`:''}`};['dcC','dcV','dcW'].forEach(id=>$('#'+id).addEventListener('input',calc));calc()}
function pageWish(){const l=P.filter(p=>S.wish.has(p.slug));return `<div class="wrap page-h"><div class="crumbs"><a href="#home">Home</a>/<span>Wishlist</span></div><h1>Your wishlist</h1></div><div class="wrap" style="padding-bottom:90px">${l.length?`<div style="display:flex;justify-content:flex-end;margin-bottom:18px"><button class="btn dark" id="addAll">Add all ${l.length} to cart</button></div><div class="grid">${l.map(card).join('')}</div>`:`<div class="empty">Nothing saved yet. Tap the heart on any piece to keep it here.<div style="margin-top:14px"><a class="btn dark" href="#shop">Browse products</a></div></div>`}</div>`}

/* ---------- overlays: film, booking, search, account ---------- */
function modal(title,body,wide){closeAll();const ov=document.createElement('div');ov.className='modal-ov';ov.innerHTML=`<div class="modal ${wide?'wide':''}" role="dialog" aria-label="${esc(title)}"><div class="modal-h"><h3>${title}</h3><button class="iconbtn" data-x aria-label="Close">${ic('x')}</button></div><div class="modal-b">${body}</div></div>`;document.body.appendChild(ov);
 const close=()=>{ov.remove();document.removeEventListener('keydown',k);ov.onclose&&ov.onclose()};const k=e=>{if(e.key==='Escape')close()};document.addEventListener('keydown',k);ov.addEventListener('click',e=>{if(e.target===ov||e.target.closest('[data-x]'))close()});return {el:ov,close}}
function openFilm(){const caps=['Designed in Brooklyn, lived in everywhere.','Built by six family-run workshops.','Fabrics woven from recycled fibres.','Made to be repaired, not replaced.'];let i=0,t=0,playing=true,iv;
 const m=modal('The Arbor film',`<div class="film" id="film"><div id="fs"></div><div class="cap" id="fc"></div><div class="ctl"><button type="button" id="fp" aria-label="Pause">${ic('pause','width:14px;height:14px')}</button><span class="bar"><i id="fb"></i></span><span class="t num" id="ft">0:00 / 0:16</span></div></div><p class="muted" style="font-size:13.5px">A 16-second look at how every Arbor piece is made.</p>`,true);
 const FK=['room-blue-windows','workshop','chair-white-studio','bed-wood-linen'];const show=()=>{$('#fs').innerHTML=ph(FK[i],Art.slide(i),caps[i]);$('#fs .ph').style.cssText='position:absolute;inset:0';const sv=$('#fs img')||$('#fs svg');sv.animate([{transform:'scale(1)'},{transform:'scale(1.08)'}],{duration:4000,fill:'forwards'});$('#fc').textContent=caps[i];$('#fc').style.animation='none';void $('#fc').offsetWidth;$('#fc').style.animation=''};
 show();const tick=()=>{if(!playing)return;t+=.1;if(t>=16){t=16;playing=false;$('#fp').innerHTML=ic('play','width:14px;height:14px')}const ni=Math.min(3,Math.floor(t/4));if(ni!==i){i=ni;show()}$('#fb').style.width=(t/16*100)+'%';$('#ft').textContent=`0:${String(Math.floor(t)).padStart(2,'0')} / 0:16`};iv=setInterval(tick,100);
 $('#fp').onclick=()=>{if(t>=16){t=0;i=0;show()}playing=!playing;$('#fp').innerHTML=ic(playing?'pause':'play','width:14px;height:14px');$('#fp').setAttribute('aria-label',playing?'Pause':'Play')};m.el.onclose=()=>clearInterval(iv)}
function openBooking(si=0){const days=[];for(let k=1;k<=10;k++){const d=new Date(2026,8,29);d.setDate(d.getDate()+k);days.push(d)}let day=0,slot=null;
 const m=modal('Book a showroom visit',`<div class="field"><label for="bS">Showroom</label><select class="input" id="bS">${STORES.map((s,i)=>`<option value="${i}" ${i===si?'selected':''}>${s[0]} · ${s[1].split(',')[0]}</option>`).join('')}</select></div>
 <div class="field"><label>Day</label><div class="slots" id="bD" style="grid-template-columns:repeat(5,1fr)">${days.map((d,i)=>`<button type="button" data-d="${i}" aria-pressed="${i===0}">${d.toLocaleDateString('en-US',{weekday:'short'})}<br><span class="num">${d.getDate()}</span></button>`).join('')}</div></div>
 <div class="field"><label>Time</label><div class="slots" id="bT"></div></div><div class="two"><div class="field"><label for="bN">Name</label><input class="input" id="bN" value="${esc(S.user?.name||'')}"></div><div class="field"><label for="bE">Email</label><input class="input" id="bE" type="email" value="${esc(S.user?.email||'')}"></div></div>
 <div class="field"><label for="bI">What are you shopping for?</label><select class="input" id="bI"><option>Living room</option><option>Bedroom</option><option>Dining</option><option>Whole home</option></select></div><p class="err-t" id="bErr" hidden></p><button class="btn dark lg" id="bGo">Confirm appointment</button>`);
 $$('#bD [data-d]').forEach(b=>{b.style.height='54px';b.style.lineHeight='1.2'});
 const drawT=()=>{const times=['10:00','11:00','12:00','13:30','14:30','15:30','16:30','17:30'];$('#bT').innerHTML=times.map((t,i)=>`<button type="button" data-t="${t}" aria-pressed="${slot===t}" ${(i*3+day*7+ +$('#bS').value)%5===0?'disabled':''}>${t}</button>`).join('');$$('#bT [data-t]').forEach(b=>b.onclick=()=>{slot=b.dataset.t;drawT()})};drawT();
 $('#bS').onchange=()=>{slot=null;drawT()};$$('#bD [data-d]').forEach(b=>b.onclick=()=>{day=+b.dataset.d;slot=null;$$('#bD [data-d]').forEach(x=>x.setAttribute('aria-pressed',x===b));drawT()});
 $('#bGo').onclick=()=>{const n=$('#bN').value.trim(),e=$('#bE').value.trim();const err=!slot?'Pick a time slot.':!n?'Enter your name.':!/^\S+@\S+\.\S+$/.test(e)?'Enter a valid email.':'';$('#bErr').hidden=!err;$('#bErr').textContent=err;if(err)return;const s=STORES[+$('#bS').value];const d=days[day].toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric'});S.appts.unshift({store:s[0],when:d+' at '+slot,topic:$('#bI').value});
  $('.modal-b',m.el).innerHTML=`<div class="confirm" style="padding:10px 0 4px"><div class="ok">${ic('check')}</div><h3 style="font-size:26px">You're booked, ${esc(n.split(' ')[0])}</h3><p class="muted">${s[0]} showroom · ${d} at ${slot}<br>${s[1]}</p><p class="muted" style="font-size:13px">A calendar invite is on its way to ${esc(e)}.</p><button class="btn dark" data-x>Done</button></div>`}}
function openSearch(){closeAll();const ov=document.createElement('div');ov.className='search-ov';ov.innerHTML=`<div class="wrap"><div style="display:flex;justify-content:flex-end"><button class="iconbtn" id="sx" aria-label="Close search">${ic('x')}</button></div><label class="sr" for="sq">Search</label><input id="sq" placeholder="Search sofas, chairs, oak…" autocomplete="off"><div style="display:flex;gap:8px;flex-wrap:wrap;margin:16px 0 28px">${['Sofa','Bouclé','Oak','Bed','Lighting'].map(t=>`<button class="chip" type="button" data-sq="${t}">${t}</button>`).join('')}</div><div class="grid" id="sr"></div></div>`;document.body.appendChild(ov);
 const close=()=>{ov.remove();document.removeEventListener('keydown',k)};const k=e=>{if(e.key==='Escape')close()};document.addEventListener('keydown',k);$('#sx').onclick=close;
 const draw=()=>{const q=$('#sq').value.trim().toLowerCase();const l=q?P.filter(p=>(p.name+' '+p.cat+' '+p.mat+' '+p.v.map(v=>v[0]).join(' ')).toLowerCase().includes(q)):P.slice(0,3);$('#sr').innerHTML=l.length?l.map(card).join(''):`<div class="empty" style="grid-column:1/-1">No results for “${esc(q)}”.</div>`;bindCards($('#sr'));$$('#sr a').forEach(a=>a.addEventListener('click',close))};
 $('#sq').oninput=draw;$$('[data-sq]').forEach(b=>b.onclick=()=>{$('#sq').value=b.dataset.sq;draw()});draw();setTimeout(()=>$('#sq')?.focus(),30)}
function openAccount(){if(!S.user){const m=modal('Sign in',`<p class="muted" style="font-size:14px">Track orders, save your wishlist across devices and manage showroom visits.</p><div class="field"><label for="aE">Email</label><input class="input" id="aE" type="email" value=""></div><div class="field"><label for="aP">Password</label><input class="input" id="aP" type="password"></div><p class="err-t" id="aErr" hidden>Enter a valid email and a password of 6+ characters.</p><button class="btn dark lg" id="aGo">Sign in</button><p class="muted" style="font-size:13px;text-align:center">New here? Signing in creates your account automatically.</p>`);
  $('#aGo').onclick=()=>{const e=$('#aE').value.trim(),p=$('#aP').value;if(!/^\S+@\S+\.\S+$/.test(e)||p.length<6){$('#aErr').hidden=false;return}const name=e.split('@')[0].replace(/[._]/g,' ').replace(/\b\w/g,c=>c.toUpperCase());S.user={email:e,name};ls('user',S.user);m.close();toast('Signed in as '+name)};return}
 const m=modal('Hi, '+esc(S.user.name.split(' ')[0]),`<p class="muted" style="font-size:14px">${esc(S.user.email)}</p><h4 style="font-size:18px">Orders</h4>${S.orders.length?S.orders.map(o=>`<div class="sum-row" style="padding:10px 0;border-bottom:1px solid var(--line)"><span><b>${o.no}</b> · ${o.lines.reduce((a,l)=>a+l.q,0)} items</span><span class="num">${money(o.t.total,2)} · <span style="color:var(--good)">Processing</span></span></div>`).join(''):'<p class="muted" style="font-size:14px">No orders yet.</p>'}
 <h4 style="font-size:18px">Showroom visits</h4>${S.appts.length?S.appts.map(a=>`<div class="sum-row" style="padding:10px 0;border-bottom:1px solid var(--line)"><span><b>${a.store}</b> · ${a.topic}</span><span>${a.when}</span></div>`).join(''):'<p class="muted" style="font-size:14px">No visits booked. <button class="link" id="bk">Book one</button></p>'}<button class="btn" id="so">Sign out</button>`);
 $('#so').onclick=()=>{S.user=null;ls('user',null);m.close();toast('Signed out')};$('#bk')?.addEventListener('click',()=>openBooking())}

/* ---------- router ---------- */
function route(){clearInterval(S.lookTimer);S.cleanup&&S.cleanup();S.cleanup=null;closeAll();const h=(location.hash||'#home').slice(1)||'home';
 let cur=h,body,bind,title='Arbor & Co.';
 if(h.startsWith('product-')&&byslug(h.slice(8))){const p=byslug(h.slice(8));body=pageProduct(p);bind=()=>bindProduct(p);cur='shop';title=p.name+' · Arbor & Co.'}
 else if(h==='shop'){body=pageShop();bind=bindShop;title='Shop · Arbor & Co.'}
 else if(h==='story'){body=pageStory();title='About us · Arbor & Co.'}
 else if(h==='stores'){body=pageStores();bind=()=>$$('[data-book]').forEach(b=>b.onclick=()=>openBooking(+b.dataset.book));title='Showrooms · Arbor & Co.'}
 else if(h==='delivery'){body=pageDelivery();bind=bindDelivery;title='Delivery · Arbor & Co.'}
 else if(h==='wishlist'){body=pageWish();bind=()=>$('#addAll')?.addEventListener('click',()=>{P.filter(p=>S.wish.has(p.slug)).forEach(p=>addToCart(p.slug,0,1,true));toast('Wishlist added to cart',{t:'View cart',run:openCart})});title='Wishlist · Arbor & Co.'}
 else if(h==='checkout'){body=pageCheckout();bind=bindCheckout;title='Checkout · Arbor & Co.'}
 else if(h==='order'){body=pageOrder();bind=()=>$('#trackBtn')?.addEventListener('click',()=>toast('Tracking link sent to '+S.lastOrder.info.em));title='Order confirmed · Arbor & Co.'}
 else {cur='home';body=pageHome();bind=bindHome}
 document.title=title;mountChrome(cur,body);bind&&bind();
 if(S.jump){const j=S.jump;S.jump=null;setTimeout(()=>document.getElementById(j)?.scrollIntoView(),60)}else scrollTo(0,0)}

/* ===================== v2 editorial layout ===================== */
function nav(cur){const L=(h,t)=>`<a href="#${h}" ${cur===h?'aria-current="page"':''}>${t}</a>`;
 return `<div class="announce"><span>Free white-glove delivery over <b>${money(FREE)}</b> in the US &amp; Australia</span><span>·</span><span>100-night home trial</span><span>·</span><span>10-year frame warranty</span></div>
 <header class="nav nav2" id="nav"><div class="wrap"><nav class="links" aria-label="Main">${L('shop','Shop')}${L('story','Our story')}${L('stores','Showrooms')}${L('delivery','Delivery')}</nav>
 <a class="logo" href="#home" aria-label="Arbor & Co. home">Arbor<span style="color:var(--terra)">&amp;</span>Co.</a>
 <div class="nav-r"><label class="sr" for="cur">Currency</label><select class="cur" id="cur">${Object.keys(CUR).map(c=>`<option ${c===S.cur?'selected':''}>${c}</option>`).join('')}</select>
  <button class="iconbtn" id="srchBtn" aria-label="Search">${ic('search')}</button><a class="iconbtn hide-s" href="#wishlist" aria-label="Wishlist">${ic('heart')}<span class="badge-n num" id="wishN" hidden></span></a>
  <button class="iconbtn hide-s" id="acctBtn" aria-label="Account">${ic('user')}</button><button class="iconbtn" id="cartBtn" aria-label="Cart">${ic('bag')}<span class="badge-n num" id="cartN" hidden></span></button>
  <button class="iconbtn burger" id="burger" aria-label="Menu" aria-expanded="false">${ic('menu')}</button></div></div>
 <nav class="mmenu" id="mmenu"><a href="#shop">Shop</a><a href="#story">Our story</a><a href="#stores">Showrooms</a><a href="#delivery">Delivery</a><a href="#wishlist">Wishlist</a><a href="#" id="mAcct">Account</a></nav></header>`}
function footer(){return `<footer class="site2"><div class="wrap"><div class="f2grid">
 <div><p style="font-family:var(--f-display);font-size:26px;font-weight:600;letter-spacing:-.02em;max-width:18ch;color:var(--ink)">Furniture made to be kept, repaired and handed down.</p><p class="muted" style="margin-top:12px;font-size:14px">hello@arborandco.com · +1 (718) 555-0142</p></div>
 <div><h4>Shop</h4>${CATS.slice(1).map(c=>`<a href="#shop" data-fcat="${c}">${c==='Lighting'?c:c+'s'}</a>`).join('')}</div>
 <div><h4>Help</h4><a href="#delivery">Delivery</a><a href="#delivery">Returns &amp; trial</a><a href="#delivery">Warranty</a><a href="#stores">Book a visit</a></div>
 <div><h4>Company</h4><a href="#story">Our story</a><a href="#story">Materials</a><a href="#stores">Showrooms</a><a href="#home">Journal</a></div>
 <div><h4>Follow</h4><a href="#home">Instagram</a><a href="#home">Pinterest</a><a href="#home">TikTok</a></div></div>
 <div class="wordmark" aria-hidden="true">Arbor<span>&amp;</span>Co.</div>
 <div class="f2bot"><span>© 2026 Arbor &amp; Co. Fictional brand · Demo storefront by Organoo Studio.</span><span style="display:flex;align-items:center;flex-wrap:wrap;gap:4px"><span class="shopify2"><i></i>Built on Shopify · Online Store 2.0</span><a href="#delivery">Terms</a><a href="#story">Privacy</a></span></div></div></footer>`}
function card(p){const off=p.compare?Math.round((1-p.price/p.compare)*100):0;return `<article class="p2 reveal"><div class="imgw"><a class="img" href="#product-${p.slug}" aria-label="${esc(p.name)}">${pimg(p)}</a>
 ${p.tag||off?`<span class="tag ${off?'sale':''}">${off?`−${off}%`:p.tag}</span>`:''}<button class="iconbtn heart" data-wish="${p.slug}" aria-pressed="${S.wish.has(p.slug)}" aria-label="Save ${esc(p.name)}">${ic('heart')}</button>
 <button class="quick" data-add="${p.slug}" type="button">${ic('bag','width:16px;height:16px')}Quick add</button></div>
 <div class="meta"><div class="r1"><a href="#product-${p.slug}">${esc(p.name)}</a><span class="pr num">${p.compare?`<s>${money(p.compare)}</s>`:''}${money(p.price)}</span></div><div class="r2"><span class="dots">${p.v.map(v=>`<i style="background:${v[1]}" title="${v[0]}"></i>`).join('')}</span><span>${stars(p.rating)} ${p.count}</span></div></div></article>`}
function bindCards(root=document){$$('[data-add]',root).forEach(b=>b.onclick=e=>{e.preventDefault();addToCart(b.dataset.add);const h=b.innerHTML;b.classList.add('added');b.innerHTML=ic('check','width:16px;height:16px')+'Added';setTimeout(()=>{b.classList.remove('added');b.innerHTML=h},1400)});
 $$('[data-wish]',root).forEach(b=>b.onclick=e=>{e.preventDefault();toggleWish(b.dataset.wish,b)})}
const LOOKS=[{name:'Living room',img:'room-blue-sofa',ar:1.78,pos:[50,50],svg:()=>Art.heroRoom(),spots:[[58,66,'solve-sofa'],[37,79,'haru-table'],[88,66,'alma-wardrobe'],[12,66,'elio-easy']],t:'The Sölve living room'},
 {name:'Bedroom',img:'bed-wood-linen',ar:1,pos:[50,55],svg:()=>Art.product('bed','#A7BCD0','#B4875C','room'),spots:[[52,57,'oda-bed'],[73,60,'teo-nightstand'],[27,58,'arc-lamp']],t:'The Oda bedroom'},
 {name:'Reading nook',img:'room-green-chair',ar:.653,pos:[50,68],svg:()=>Art.bannerScene(),spots:[[42,72,'muffin-lounge'],[80,56,'alma-wardrobe'],[49,36,'arc-lamp']],t:'The Muffin reading nook'}];
function heroInner(){const L=LOOKS[S.look];return `${ph(L.img,L.svg(),L.t,'',L.pos[0]+'% '+L.pos[1]+'%')}
  <div class="slides" role="group" aria-label="Shop the look">${LOOKS.map((l,i)=>`<button type="button" data-look="${i}" aria-pressed="${i===S.look}">${l.name}</button>`).join('')}</div>
  ${L.spots.map((sp,i)=>`<button class="spot" data-spot="${i}" data-x="${sp[0]}" data-y="${sp[1]}" style="left:${sp[0]}%;top:${sp[1]}%" aria-label="View ${esc(byslug(sp[2]).name)}"><i></i></button>`).join('')}
  <div class="copy"><span class="eyebrow" style="color:#fff;opacity:.85">Autumn collection · 2026</span><h1>Slow-made furniture <em>for</em> everyday living.</h1><p class="lead">Solid oak, recycled fabrics and a 100-night trial. Tap the dots to shop this room.</p><div class="ctas"><a class="btn light lg" href="#shop">Shop the collection</a><a class="btn glass lg" href="#stores">Visit a showroom</a></div></div>
  <aside class="side-card"><div style="display:flex;justify-content:space-between;align-items:center"><b style="font-size:14px">${L.t}</b><span class="muted" style="font-size:12px">${L.spots.length} pieces</span></div><div class="thumbs2">${L.spots.map(sp=>{const p=byslug(sp[2]);return `<a href="#product-${p.slug}" class="ph" aria-label="${esc(p.name)}" style="position:relative">${pimg(p)}</a>`}).join('')}</div><button class="btn dark sm block" id="addLook">Add the look · ${money(L.spots.reduce((a,sp)=>a+byslug(sp[2]).price,0))}</button></aside>
  <div class="line"><i id="lookLine"></i></div>`}
function pageHome(){S.look=S.look||0;
 const rooms=[['Living','room-blue-sofa','Sofa',Art.product('sofa','#A3BBA6','#B98B5E','room')],['Bedroom','bed-wood-linen','Bed',Art.product('bed','#D6C8B2','#B4875C','room')],['Dining','dining-upholstered','Chair',Art.product('dining','#D9CBB4','#C99A66','room')],['Lighting','lamp-floor-brown','Lighting',Art.product('lamp','#EFE6D6','#C08A55','room')]];
 const byPhoto=l=>l.filter(p=>p.img).concat(l.filter(p=>!p.img));const newIn=byPhoto(P.filter(p=>p.tag==='New').concat(P.filter(p=>p.tag!=='New'))).slice(0,8);
 const feat=byslug('solve-sofa');
 return `<section class="hero2 wrap"><div class="frame" id="heroFrame">${heroInner()}</div></section>
 <div class="wrap trust2">${[['truck','Free white-glove delivery','On orders over '+money(FREE)],['return','100-night home trial','Free collection if it is not right'],['shield','10-year frame warranty','On every sofa, chair and bed'],['leaf','FSC oak & recycled fabric','Carbon-neutral delivery']].map(t=>`<div>${ic(t[0])}<span><b>${t[1]}</b><span class="muted">${t[2]}</span></span></div>`).join('')}</div>
 <section class="s wrap"><div class="sec-h"><h2>Shop by room</h2><p>Pieces designed to work together, so a room can grow one piece at a time.</p></div><div class="rooms">${rooms.map(r=>`<a class="room reveal" href="#shop" data-room="${r[2]}">${ph(r[1],r[3],r[0]+' furniture')}<span class="t"><span><b>${r[0]}</b><small>${P.filter(p=>p.cat===r[2]).length} pieces</small></span><span class="go2">${ic('right')}</span></span></a>`).join('')}</div></section>
 <section class="s wrap"><div class="sec-h"><div><span class="eyebrow">Just landed</span><h2 style="margin-top:8px">New this season</h2></div><div class="arrows"><button type="button" id="cL" aria-label="Previous">${ic('left')}</button><button type="button" id="cR" aria-label="Next">${ic('right')}</button></div></div><div class="carousel" id="car">${newIn.map(card).join('')}</div></section>
 <section class="s wrap"><div class="story2"><div class="stick reveal">${ph('workshop',Art.slide(3),'Arbor workshop')}<button class="play2" id="playFilm"><span>${ic('play')}</span>Watch the 16-second film</button></div>
  <div><span class="eyebrow">Made to last</span><h2 style="font-size:clamp(32px,4vw,52px);letter-spacing:-.035em;margin:10px 0 18px">Built in six family workshops, not a factory line.</h2><p class="muted" style="max-width:52ch;margin-bottom:20px">Every Arbor piece is designed in Brooklyn and built by makers in Portugal, Vietnam and Victoria who have been doing this for 25 years or more.</p>
  <div class="pillars">${[['21','days','Kiln-dried oak','Solid-wood frames are dried for three weeks so they will not warp, then joined with dowels instead of staples.'],['40','fabrics','Recycled textiles','Bouclé, linen-look and performance velvet woven from recycled fibres. Every cover zips off and goes in the wash.'],['100','nights','Trial at home','Live with it for 100 nights. If it is not right, we collect it for free and refurbish it. Nothing goes to landfill.'],['24K','homes','Across two continents','Delivered to homes in the US and Australia since 2016, with a 4.9 average rating.']].map(x=>`<div class="pillar reveal"><b class="n num" data-count="${parseInt(x[0])}" data-suf="${x[0].replace(/\d+/,'')}">${x[0]}</b><div><h3>${x[2]} <span class="muted" style="font-weight:400;font-size:16px">· ${x[0]} ${x[1]}</span></h3><p>${x[3]}</p></div></div>`).join('')}</div></div></div></section>
 <section class="s wrap"><div class="sec-h"><h2>Bestsellers</h2><div class="tabs2" role="group" aria-label="Filter bestsellers">${['All','Chair','Sofa','Cabinet','Bed'].map(c=>`<button type="button" data-hc="${c}" aria-pressed="${c===S.cat}">${c==='All'?'All':c+'s'}</button>`).join('')}</div></div>
  <div class="bento2" id="bestGrid"></div></section>
 <section class="s wrap reveal"><div class="showroom">${ph('room-white-sofa-table',Art.bannerScene(),'Arbor showroom')}<div class="book-card"><span class="eyebrow">Showrooms</span><h3>Sit on everything before you buy</h3><p class="muted" style="font-size:14px">Free 45-minute sessions with a designer, plus take-home fabric swatches.</p><div class="cities" role="group" aria-label="Choose a showroom">${STORES.map((st,i)=>`<button type="button" data-city="${i}" aria-pressed="${i===0}">${st[0]}</button>`).join('')}</div><button class="btn dark lg" id="bookBtn">Find a time</button></div></div></section>
 <section class="s wrap"><div class="sec-h"><div><span class="eyebrow">#ArborAtHome</span><h2 style="margin-top:8px">Real homes, real reviews</h2></div><p>4.9 average from 12,480 verified buyers in the US and Australia.</p></div>
  <div class="ugc">${[['room-blue-gallery','tall','Priya, Brooklyn · Sölve Sofa in Dusty Blue','solve-sofa'],['q','','“Arrived two days early and the delivery team took every bit of packaging away.”','Hannah P. · Austin, TX'],['table-coffee-door','wide','Liam, Melbourne · Alma console and bench','alma-wardrobe'],['chair-rattan-door','','Grace, Sydney · Rumi Rattan Chairs','rumi-rattan'],['dining-table-chairs','','Tom, Brisbane · Brio Dining Chairs','brio-dining'],['q','','“Six months in with a dog and two kids. The fabric still looks new.”','Tom W. · Brisbane, QLD'],['bed-white-frame','wide','Jo, Portland · Oda Bed in Oat','oda-bed']].map(u=>u[0]==='q'?`<figure class="quote reveal">${stars(5)}<blockquote>${u[2]}</blockquote><figcaption style="position:static;opacity:1;transform:none;background:none;color:var(--muted);padding:0">${u[3]}</figcaption></figure>`:`<figure class="${u[1]} reveal" tabindex="0">${ph(u[0],Art.product(byslug(u[3]).type,byslug(u[3]).v[0][1],byslug(u[3]).v[0][2],'room'),u[2])}<figcaption>${u[2]} · <a href="#product-${u[3]}" style="color:#fff;font-weight:700">Shop</a></figcaption></figure>`).join('')}</div></section>
 <section class="s wrap reveal"><div class="news2">${ph('room-plants-armchair',Art.product('pouf','#EFE8DC','#C08A55','room'),'Plants and armchair by the window')}<div class="in"><span class="eyebrow">Newsletter</span><h2>Join the list and take <b>30% off</b> your first piece.</h2><p class="muted">One email a month: new collections, care guides and early access to sample sales.</p><form id="newsF" novalidate><label class="sr" for="newsE">Email</label><input class="input" id="newsE" type="email" placeholder="you@email.com"><button class="btn dark">Subscribe</button></form><p class="err-t" id="newsErr" hidden>Enter a valid email address.</p><div id="newsCode"></div></div></div></section>`}
function bindHome(){
 const drawBest=()=>{const l=P.filter(p=>S.cat==='All'||p.cat===S.cat).sort((a,b)=>(!!b.img)-(!!a.img));const f=l[0];const rest=l.slice(1,5);const g=$('#bestGrid');
  g.innerHTML=f?`<article class="feat"><a class="img" href="#product-${f.slug}" aria-label="${esc(f.name)}">${pimg(f)}</a><div class="over"><div><span class="eyebrow">No. 1 in ${f.cat.toLowerCase()}s</span><b>${esc(f.name)}</b><span class="muted" style="font-size:13px">${stars(f.rating)} ${f.count} reviews</span></div><button class="btn dark" data-add="${f.slug}">${money(f.price)} · Add</button></div></article>${rest.map(card).join('')}`:`<div class="empty" style="grid-column:1/-1">Nothing here yet.</div>`;
  g.animate([{opacity:0,transform:'translateY(14px)'},{opacity:1,transform:'none'}],{duration:450,easing:'ease-out'});bindCards(g)};
 drawBest();$$('[data-hc]').forEach(b=>b.onclick=()=>{S.cat=b.dataset.hc;$$('[data-hc]').forEach(x=>x.setAttribute('aria-pressed',x===b));drawBest()});
 bindHero();
 const car=$('#car');$('#cL').onclick=()=>car.scrollBy({left:-car.clientWidth*.8,behavior:'smooth'});$('#cR').onclick=()=>car.scrollBy({left:car.clientWidth*.8,behavior:'smooth'});
 $$('[data-room]').forEach(a=>a.addEventListener('click',()=>{S.shop.cats=new Set([a.dataset.room])}));
 let city=0;$$('[data-city]').forEach(b=>b.onclick=()=>{city=+b.dataset.city;$$('[data-city]').forEach(x=>x.setAttribute('aria-pressed',x===b))});$('#bookBtn').onclick=()=>openBooking(city);
 $('#playFilm').onclick=openFilm;
 $$('[data-count]').forEach(el=>{if(el.getBoundingClientRect().top<innerHeight)return;const io=new IntersectionObserver(es=>{if(es[0].isIntersecting){io.disconnect();const t=+el.dataset.count,suf=el.dataset.suf;const t1=performance.now();const step=now=>{const k=Math.min(1,(now-t1)/1100);el.textContent=Math.round(t*(1-Math.pow(1-k,3)))+suf;if(k<1)requestAnimationFrame(step)};requestAnimationFrame(step)}});io.observe(el)});
 $('#newsF').onsubmit=e=>{e.preventDefault();const v=$('#newsE').value.trim();const ok=/^\S+@\S+\.\S+$/.test(v);$('#newsE').classList.toggle('err',!ok);$('#newsErr').hidden=ok;if(!ok)return;
  $('#newsCode').innerHTML=`<p>Welcome in. Your code for 30% off:</p><div class="code-box" style="margin-top:8px"><span>WELCOME30</span><button class="btn dark sm" type="button" id="applyCode">Apply to cart</button><button class="iconbtn" type="button" id="copyCode" aria-label="Copy code">${ic('copy')}</button></div>`;$('#newsE').value='';
  $('#applyCode').onclick=()=>{S.disc='WELCOME30';toast('WELCOME30 applied: 30% off',{t:'View cart',run:openCart})};$('#copyCode').onclick=()=>{try{navigator.clipboard.writeText('WELCOME30').then(()=>toast('Code copied'),()=>toast('Code: WELCOME30'))}catch(_){toast('Code: WELCOME30')}}};
}

addEventListener('hashchange',route);
$('#demoClose').onclick=()=>$('#demoBadge').remove();
route();
})();
