(()=>{
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const ic=(n,st='')=>`<svg class="i"${st?` style="${st}"`:''}><use href="#i-${n}"/></svg>`;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ls=(k,v)=>{try{if(v===undefined)return JSON.parse(localStorage.getItem('fm_'+k));localStorage.setItem('fm_'+k,JSON.stringify(v))}catch(e){return null}};
const ss=(k,v)=>{try{if(v===undefined)return sessionStorage.getItem('fm_'+k);sessionStorage.setItem('fm_'+k,v)}catch(e){return null}};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const hash=s=>{let h=2166136261;for(const c of String(s))h=Math.imul(h^c.charCodeAt(0),16777619);return h>>>0};
const rng=seed=>()=>{seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296};
const ph=(k,alt='',pos='')=>`<div class="ph">${k?`<img src="photos/${k}.jpg" alt="${esc(alt)}" loading="lazy"${pos?` style="object-position:${pos}"`:''} onerror="this.remove()">`:''}</div>`;
const RM=matchMedia('(prefers-reduced-motion:reduce)').matches;
const DAY=864e5;
const pad=n=>String(n).padStart(2,'0');
const dsOf=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const parseDs=ds=>{const [y,m,d]=ds.split('-').map(Number);return new Date(y,m-1,d)};
const addDs=(ds,n)=>{const d=parseDs(ds);d.setDate(d.getDate()+n);return dsOf(d)};
const today=()=>dsOf(new Date());
const diffDays=(a,b)=>Math.round((parseDs(a)-parseDs(b))/DAY);
const fmtD=(ds,o={month:'short',day:'numeric'})=>parseDs(ds).toLocaleDateString('en-US',o);
const fmtT=t=>new Date(t).toLocaleTimeString('en-US',{hour:'2-digit',minute:'2-digit',hour12:false});
const fmtDT=t=>new Date(t).toLocaleString('en-US',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit',hour12:false});

/* ---------- constants ---------- */
const CLUBS={nyc:{n:'Williamsburg',city:'Brooklyn, NY',cur:'USD',loc:'en-US',addr:'214 Kent Ave, Brooklyn, NY 11249'},syd:{n:'Surry Hills',city:'Sydney, NSW',cur:'AUD',loc:'en-AU',addr:'88 Foveaux St, Surry Hills NSW 2010'}};
const PLANS={offpeak:{n:'Off-Peak',p:{USD:59,AUD:89},d:'Weekdays 10:00–16:00',f:['Gym floor, weekdays 10:00–16:00','2 classes a week','Digital member card'],x:['Recovery suite']},
 unlimited:{n:'Unlimited',p:{USD:99,AUD:149},d:'Any time, every day',feat:1,f:['Gym floor, 06:00–22:00 daily','Unlimited classes','Digital member card','Bring a friend once a month'],x:['Recovery suite']},
 plus:{n:'Unlimited + Recovery',p:{USD:149,AUD:219},d:'Train and recover',f:['Everything in Unlimited','Sauna & cold plunge','1 sports massage a month','10% off physio sessions'],x:[]}};
const money=(v,cur)=>new Intl.NumberFormat(cur==='AUD'?'en-AU':'en-US',{style:'currency',currency:cur,maximumFractionDigits:0}).format(v);
const CT={pil:{n:'Reformer Pilates',ic:'pil',cap:10},yoga:{n:'Vinyasa Yoga',ic:'yoga',cap:18},hiit:{n:'HIIT Circuit',ic:'hiit',cap:16},str:{n:'Strength Lab',ic:'str',cap:12},mob:{n:'Stretch & Mobility',ic:'mob',cap:14},rec:{n:'Recovery & Breath',ic:'rec',cap:10}};
const CATF=[['all','All'],['yoga','Yoga'],['pil','Pilates'],['hiit','HIIT'],['str','Strength'],['mob','Stretching'],['rec','Recovery']];
const COACH=[
 {id:'theo',n:'Theo Grant',r:'Head of Strength',img:'p-m1',pos:'50% 20%',hrs:'7,200 hrs coached',k:['str','hiit'],cert:'NSCA-CSCS · 11 years',bio:'Theo builds progressive strength programs for beginners and returning athletes. His Strength Lab classes are small, technical and very welcoming.'},
 {id:'jade',n:'Jade Moreno',r:'Reformer Pilates Lead',img:'p-w2',pos:'50% 25%',hrs:'6,900 hrs coached',k:['pil'],cert:'BASI Comprehensive · 9 years',bio:'Jade trained in rehabilitation Pilates before leading our reformer studio. Expect slow, precise work and a lot of core.'},
 {id:'kai',n:'Kai Reyes',r:'HIIT & Conditioning',img:'p-m3',pos:'50% 30%',hrs:'4,100 hrs coached',k:['hiit','str'],cert:'ACE-CPT · 6 years',bio:'Kai designs our circuits so every level can scale up or down. His 45 minutes go by fast.'},
 {id:'priya',n:'Priya Das',r:'Yoga & Mobility',img:'p-w8',pos:'50% 25%',hrs:'5,600 hrs coached',k:['yoga','mob','rec'],cert:'E-RYT 500 · 10 years',bio:'Priya teaches vinyasa, mobility and breathwork, with a focus on moving well for a lifetime.'}];
const coach=id=>COACH.find(c=>c.id===id);
const ROWS=['07:00','09:00','12:15','17:30','18:30','19:45'];
const SECRET='forma-2026-demo';
const WIN=30000;

/* ---------- members ---------- */
const FIRST=['Ava','Leo','Grace','Daniel','Ruth','Mia','Nina','Omar','Chloe','Ethan','Isla','Noah','Zara','Lucas','Maya','Jack','Sofia','Liam','Aria','Ben','Ivy','Sam','Layla','Owen','Ella','Hugo','Ruby','Theo','Emma','Finn','Lily','Kian','Nora','Max','Hana','Jude','Aisha','Tom','Elsie','Rafi','Zoe','Arlo','Priya','Cole','Maeve','Luca','Tara','Jonah'];
const LAST=['Thompson','Martins','Park','Brooks','Bennett','Rossi','Alvarez','Haddad','Nguyen','Walsh','Carter','Ito','Khan','Silva','Reid','Fraser','Costa','O’Neill','Patel','Hughes','Moreau','Kaur','Lopez','Chen','Ward','Novak','Price','Abara','Quinn','Duarte','Lee','Morgan','Stone','Fischer','Sato','Adler','Rahman','Burke','Hale','Levi','Young','Kerr','Das','Byrne','Flynn','Romano','Shah','Webb'];
const PH={'FM-1001':['p-w6','50% 30%'],'FM-1002':['p-m4','50% 25%'],'FM-1003':['p-w7','50% 30%'],'FM-1004':['p-m5','40% 30%'],'FM-1005':['p-w5','55% 20%'],'FM-1006':['p-w1','50% 20%'],'FM-1007':['p-w3','50% 25%'],'FM-1008':['p-m2','50% 20%']};
function seedMembers(){const T=today(),R=rng(20260929),out=[];
 const fixed={'FM-1001':['unlimited','nyc',64],'FM-1002':['offpeak','nyc',40],'FM-1003':['plus','syd',3],'FM-1004':['unlimited','nyc',-5],'FM-1005':['unlimited','syd',38,1],'FM-1006':['plus','nyc',120],'FM-1007':['unlimited','syd',6],'FM-1008':['offpeak','syd',-18]};
 for(let i=0;i<48;i++){const id='FM-'+(1001+i);const f=fixed[id];const plan=f?f[0]:(R()<.25?'offpeak':R()<.67?'unlimited':'plus');const club=f?f[1]:(R()<.55?'nyc':'syd');
  const r=R();const left=f?f[2]:(r<.14?-Math.ceil(R()*40):r<.24?Math.ceil(R()*7):Math.ceil(8+R()*300));const term=[30,90,365][Math.floor(R()*3)];
  const fn=FIRST[i],ln=LAST[i];out.push({id,n:fn+' '+ln,e:(fn+'.'+ln).toLowerCase().replace(/[^a-z.]/g,'')+'@example.com',tel:club==='nyc'?`+1 718 555 0${100+i}`:`+61 400 555 ${100+i}`,plan,club,exp:addDs(T,left),joined:addDs(T,left-term-Math.floor(R()*400)),frozen:f&&f[3]?1:0,act:.18+R()*.5,img:PH[id]?.[0]||null,pos:PH[id]?.[1]||''})}
 return out}
let MEM=[];
function loadMembers(){const base=seedMembers();const patch=ls('mpatch')||{},added=ls('madded')||[];MEM=base.concat(added).map(m=>({...m,...(patch[m.id]||{})}))}
const mem=id=>MEM.find(m=>m.id===id);
function patchMember(id,obj){const added=ls('madded')||[];const ai=added.findIndex(m=>m.id===id);if(ai>=0){added[ai]={...added[ai],...obj};ls('madded',added)}else{const p=ls('mpatch')||{};p[id]={...(p[id]||{}),...obj};ls('mpatch',p)}loadMembers()}
function status(m){if(m.frozen)return 'frozen';const d=diffDays(m.exp,today());if(d<0)return 'expired';if(d<=7)return 'expiring';return 'active'}
const SLBL={active:['ok','Active'],expiring:['warn','Expiring'],expired:['bad','Expired'],frozen:['dark','Frozen']};
const sPill=m=>{const s=status(m),d=diffDays(m.exp,today());return `<span class="pill ${SLBL[s][0]}"><i></i>${SLBL[s][1]}${s==='expiring'?` · ${d}d`:s==='active'?` · ${d}d`:''}</span>`};
const avatar=(m,cls='')=>`<span class="av ${cls}">${m.photo?`<img src="${m.photo}" alt="">`:m.img?`<img src="photos/${m.img}.jpg" alt="" style="object-position:${m.pos}" onerror="this.remove()">`:''}${esc(m.n.split(' ').map(x=>x[0]).join('').slice(0,2))}</span>`;

/* ---------- check-ins ---------- */
let SEEDED=null;
function seedVisits(){if(SEEDED)return SEEDED;const out=[],T=today(),now=Date.now();
 seedMembers().forEach(m=>{for(let k=45;k>=0;k--){const ds=addDs(T,-k);const r=rng(hash(m.id+ds));if(r()>m.act)continue;if(diffDays(m.exp,ds)<0)continue;if(m.frozen&&k<10)continue;const d=parseDs(ds),dow=d.getDay();
  let h;if(m.plan==='offpeak'){if(dow===0||dow===6)continue;h=10+r()*5.8}else h=6+r()*15.5;const t=d.getTime()+h*36e5;if(t>now-5*6e4)continue;out.push({t,id:m.id,ok:1,lvl:'ok',club:m.club,seed:1})}});
 const fl=[['FM-1004','Membership expired',2],['FM-1008','Membership expired',6],['FM-1017','QR code expired (possible screenshot)',1],['FM-1023','Already checked in 38 min ago (possible card sharing)',3],['FM-1002','Off-peak plan used outside 10:00–16:00',4]];
 fl.forEach((f,i)=>{const d=parseDs(addDs(T,-f[2]));out.push({t:d.getTime()+(8+i*2.3)*36e5,id:f[0],ok:0,lvl:'bad',why:f[1],club:'nyc',seed:1,sid:'s'+i})});
 return SEEDED=out.sort((a,b)=>a.t-b.t)}
const scans=()=>ls('scans')||[];
function allScans(){return seedVisits().concat(scans()).sort((a,b)=>a.t-b.t)}
const visits=()=>allScans().filter(s=>s.ok);
function addScan(s){const l=scans();l.push(s);ls('scans',l.slice(-800))}

/* ---------- rotating token ---------- */
const win=(t=Date.now())=>Math.floor(t/WIN);
const code6=(id,w)=>String(hash(id+'|'+w+'|'+SECRET)%1000000).padStart(6,'0');
const payload=(id,w=win())=>`FORMA|${id}|${w}|${code6(id,w)}`;
const qrSvg=txt=>QR.svg(txt,{fg:'#1C1C1C'});

/* ---------- validation at the gate ---------- */
function validate(input,opt={}){const now=Date.now();let id,ok=false,stale=false;
 if(typeof input==='string'){const p=input.trim().split('|');if(p[0]!=='FORMA'||p.length!==4)return res('bad','Not a FORMA code','This QR code does not belong to FORMA.',null,'Unknown code');id=p[1];const w=+p[2];if(code6(id,w)!==p[3])return res('bad','Invalid code','The code signature does not match. It may have been edited.',mem(id),'Tampered QR code');
  const cw=win(now);if(w>cw+1||w<cw-1)stale=true;ok=true}
 else{id=(input.id||'').trim().toUpperCase();if(!/^FM-\d{4}$/.test(id))return res('bad','Unknown member ID','Check the ID on the member’s card, e.g. FM-1001.',null,'Unknown member ID');const cw=win(now);ok=[cw,cw-1].some(w=>code6(id,w)===String(input.code).trim());if(!ok)return res('bad','Wrong or expired code','The 6-digit code changes every 30 seconds. Ask the member to read the current one.',mem(id),'Wrong or expired 6-digit code')}
 const m=mem(id);if(!m)return res('bad','Member not found',`No member with ID ${esc(id)}.`,null,'Unknown member ID');
 if(stale)return res('bad','QR code expired','This code is more than 60 seconds old. It is probably a screenshot or photo of someone else’s phone. Ask the member to open the live card.',m,'QR code expired (possible screenshot)');
 const st=status(m);
 if(st==='frozen')return res('bad','Membership frozen','This membership is on hold. The member can unfreeze it in the app or at the desk.',m,'Frozen membership');
 if(st==='expired')return res('bad','Membership expired',`Expired on ${fmtD(m.exp,{month:'long',day:'numeric'})}. Renew at the desk before entry.`,m,'Membership expired');
 const d=new Date(now),h=d.getHours()+d.getMinutes()/60,dow=d.getDay();
 if(m.plan==='offpeak'&&(dow===0||dow===6||h<10||h>=16))return res('bad','Outside Off-Peak hours','Off-Peak members can enter on weekdays 10:00–16:00. Offer a day pass or an Unlimited upgrade.',m,'Off-peak plan used outside 10:00–16:00');
 const last=visits().filter(v=>v.id===id).pop();
 if(!opt.override&&last&&now-last.t<3*36e5){const mins=Math.round((now-last.t)/6e4);return res('bad','Already checked in',`This card was used ${mins<1?'moments':mins+' min'} ago at ${fmtT(last.t)}. One entry per 3 hours: the card may be shared. Compare the photo before overriding.`,m,`Already checked in ${mins} min ago (possible card sharing)`,true)}
 const dl=diffDays(m.exp,today());
 if(st==='expiring')return res('warn',`Welcome, ${esc(m.n.split(' ')[0])}`,`Entry allowed. Membership expires in ${dl} day${dl===1?'':'s'}: remind them to renew.`,m);
 return res('ok',`Welcome, ${esc(m.n.split(' ')[0])}`,'Entry allowed. Check the photo matches.',m);
 function res(lvl,title,why,m,flag,canOverride){return {lvl,title,why,m,flag,canOverride}}}
function record(r,src){const s={t:Date.now(),id:r.m?.id||'?',ok:r.lvl!=='bad'?1:0,lvl:r.lvl,why:r.flag||'',club:r.m?.club||'nyc',src,sid:'x'+Date.now().toString(36)};addScan(s);return s}

/* ---------- schedule ---------- */
const monday=(ds=today())=>{const d=parseDs(ds);const k=(d.getDay()+6)%7;d.setDate(d.getDate()-k);return dsOf(d)};
function classesFor(club,ds){const out=[];const d=parseDs(ds),dow=d.getDay();ROWS.forEach((t,ri)=>{const h=hash(club+ds+t);if(h%100<(dow===0||dow===6?38:16))return;if((dow===0||dow===6)&&ri>=4)return;
 const ks=Object.keys(CT);let k=ks[h%ks.length];if(ri===2&&k==='hiit')k='mob';const c=CT[k];const cands=COACH.filter(x=>x.k.includes(k));const co=cands[h%cands.length]||COACH[0];
 const id=`${club}-${ds}-${t}`;const base=(h>>>8)%(c.cap+1);const mine=bookings().filter(b=>b.cid===id).length;out.push({id,k,t,ds,club,co:co.id,cap:c.cap,taken:Math.min(c.cap,base+mine)})});return out}
const bookings=()=>ls('bookings')||[];
const classById=id=>{const [club,y,m,d,t]=id.split('-');return classesFor(club,`${y}-${m}-${d}`).find(c=>c.id===id)};
const clsStart=c=>{const [h,mi]=c.t.split(':').map(Number);const d=parseDs(c.ds);d.setHours(h,mi);return d.getTime()};

/* ---------- state ---------- */
const S={page:'',timers:[],club:ls('club')||'nyc',wk:0,fil:'all',dayI:null,bill:'m',sess:ls('sess'),planSel:'unlimited',jn:{step:1},admTab:'overview',memF:'all',simId:'FM-1001',jf:'All',demoOff:0};
if(!CLUBS[S.club])S.club='nyc';
const me=()=>S.sess?mem(S.sess):null;
const timer=(fn,ms)=>{const t=setInterval(fn,ms);S.timers.push(t);return t};
function toast(msg,icn='check'){const t=document.createElement('div');t.className='toast';t.innerHTML=ic(icn)+esc(msg);$('#toasts').appendChild(t);setTimeout(()=>{t.style.transition='opacity .3s';t.style.opacity=0;setTimeout(()=>t.remove(),300)},3200)}
async function saveFile(name,text){try{if(window.claude&&window.claude.use){const d=await window.claude.use('downloads');if(d){await d.save({filename:name,data:text});toast('File saved');return}}}catch(e){if(e&&e.code==='declined'){toast('Download cancelled','x');return}}
 try{const u=URL.createObjectURL(new Blob([text],{type:'text/csv'}));const a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1500);toast('CSV downloaded')}catch(e){toast('Download is not available here','x')}}
function beep(ok){try{const A=window.AudioContext||window.webkitAudioContext;const c=S.ac||(S.ac=new A());const o=c.createOscillator(),g=c.createGain();o.connect(g);g.connect(c.destination);o.frequency.value=ok?880:220;o.type=ok?'sine':'square';g.gain.setValueAtTime(.08,c.currentTime);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+(ok?.25:.45));o.start();o.stop(c.currentTime+(ok?.25:.45))}catch(e){}}

/* ---------- chrome ---------- */
const LOGO=`<a class="logo" href="#home" aria-label="FORMA home"><span class="m"><svg viewBox="0 0 24 24" width="22" height="22" fill="none" stroke="#1C1C1C" stroke-width="2.6" stroke-linecap="round"><path d="M6 20V4h12M6 12h9"/></svg></span><b>FORMA</b></a>`;
function nav(cur){const L=(h,t,jump)=>`<a href="#${h}" ${cur===h&&!jump?'aria-current="page"':''}>${t}</a>`;const u=me();
 return `<div class="ann">New: your phone is your key. <b>QR check-in</b> is live at both clubs. <a href="#member">Open my card →</a></div><header class="nav" id="nav"><div class="bar">${LOGO}
 <nav class="nl" aria-label="Main">${L('classes','Classes')}${L('coaches','Coaches',1)}${L('plans','Memberships',1)}${L('recovery','Recovery',1)}${L('journal','Journal')}</nav><span class="sp"></span>
 <a class="ib" href="#member" aria-label="Member area">${u?avatar(u):`<span class="av">${ic('user','width:16px;height:16px')}</span>`}<span class="t">${u?esc(u.n.split(' ')[0]):'Member login'}</span></a>
 <a class="btn lime jn" href="#join" style="margin-left:8px">Join FORMA<span class="go">${ic('ne','width:15px;height:15px')}</span></a>
 <button class="burger" id="burger" aria-label="Menu" aria-expanded="false">${ic('menu')}</button></div></header>
 <nav class="mm" id="mm" aria-label="Mobile"><a href="#classes">Classes</a><a href="#coaches">Coaches</a><a href="#plans">Memberships</a><a href="#recovery">Recovery</a><a href="#journal">Journal</a><a href="#member">Member area</a><a class="btn" href="#join">Join FORMA</a></nav>`}
function footer(){return `<footer class="f"><div class="wrap"><div class="fg">
 <div>${LOGO}<p style="margin-top:16px;max-width:34ch;color:var(--fg-2)">Fitness and recovery club in Brooklyn and Sydney. Strength, classes, physio and a phone that opens the door.</p></div>
 <div><h4>Club</h4><a href="#classes">Class schedule</a><a href="#plans">Memberships</a><a href="#recovery">Recovery & physio</a><a href="#journal">Journal</a><a href="#join">Join</a></div>
 <div><h4>Visit</h4>${Object.values(CLUBS).map(c=>`<p style="font-size:14.5px;margin-bottom:10px"><b>${c.n}</b><br><span class="muted">${c.addr}</span></p>`).join('')}<span class="muted" style="font-size:14px">Open daily 06:00–22:00</span></div>
 <div class="staff"><h4>Staff area</h4><a href="#scan">${ic('scan','width:16px;height:16px')}Front-desk scanner</a><a href="#admin">${ic('grid','width:16px;height:16px')}Admin dashboard</a><a href="#member">${ic('qr','width:16px;height:16px')}Member card</a><p class="muted" style="font-size:13px;margin-top:10px">Demo admin PIN: <b>2468</b></p></div></div>
 <div class="fbot"><span>© 2026 FORMA (fictional club). Demo data only.</span><span>Website by Organoo Studio</span></div></div></footer>`}
function staffBar(cur,dark){return `<header class="nav" id="nav" style="${dark?'background:var(--ink);color:#fff':''}"><div class="bar">${LOGO.replace('<b>FORMA</b>',`<b style="${dark?'color:#fff':''}">FORMA</b>`)}<span class="pill ${dark?'':'dark'}" style="${dark?'background:#333;color:#fff':''}">${cur==='scan'?'Front desk':'Admin'}</span><span class="sp"></span>
 <div class="nl" style="${dark?'background:#262626;border-color:#333':''}"><a href="#scan" ${cur==='scan'?'aria-current="page"':''} style="${dark&&cur!=='scan'?'color:#ddd':''}">Scanner</a><a href="#admin" ${cur==='admin'?'aria-current="page"':''} style="${dark?'color:#ddd':''}">Admin</a><a href="#home" style="${dark?'color:#ddd':''}">Website</a></div>
 <button class="burger" id="burger" aria-label="Menu" aria-expanded="false" style="${dark?'background:#262626;border-color:#333;color:#fff':''}">${ic('menu')}</button></div></header>
 <nav class="mm" id="mm"><a href="#scan">Scanner</a><a href="#admin">Admin</a><a href="#home">Website</a></nav>`}
function mount(cur,body,mode){const kiosk=mode==='scan',adm=mode==='admin';
 $('#root').innerHTML=(kiosk||adm?staffBar(cur,kiosk):nav(cur))+`<main id="main" class="${kiosk?'kiosk':''}">${body}</main>`+(kiosk?'':footer())+(S.demoOff?'':`<div class="demo" id="demo">Demo<span class="x3">&nbsp;· Organoo Studio</span><button type="button" aria-label="Hide demo label">${ic('x','width:12px;height:12px')}</button></div>`);
 document.body.style.background=kiosk?'var(--ink)':'';
 $('#burger').onclick=()=>{const m=$('#mm');m.classList.toggle('open');$('#burger').setAttribute('aria-expanded',m.classList.contains('open'))};
 $$('#mm a').forEach(a=>a.addEventListener('click',()=>$('#mm').classList.remove('open')));
 $('#demo button')?.addEventListener('click',()=>{S.demoOff=1;$('#demo').remove()})}
function modal(html,cls=''){closeModal();const m=document.createElement('div');m.className='mdl';m.setAttribute('role','dialog');m.setAttribute('aria-modal','true');m.innerHTML=`<div class="bx ${cls}"><button class="x" aria-label="Close">${ic('x')}</button>${html}</div>`;document.body.appendChild(m);S.lastFocus=document.activeElement;m.querySelector('.x').focus();m.onclick=e=>{if(e.target===m)closeModal()};m.querySelector('.x').onclick=closeModal;return m}
function closeModal(){$('.mdl')?.remove();$('.drawer')?.remove();$('.scrim')?.remove()}
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
const sh=(eb,h,p='',extra='')=>`<div class="sh"><div><span class="eyebrow rv">${eb}</span><h2 class="rv" style="--dl:.08s">${h}</h2></div>${p||extra?`<div class="rv" style="--dl:.16s;display:grid;gap:14px;justify-items:start">${p?`<p>${p}</p>`:''}${extra}</div>`:''}</div>`;

/* ---------- HOME ---------- */
function nextClass(){const now=Date.now();for(let i=0;i<3;i++){const ds=addDs(today(),i);const c=classesFor(S.club,ds).find(c=>clsStart(c)>now+10*6e4&&c.taken<c.cap);if(c)return c}return null}
const inToday=()=>{const T=today();return new Set(visits().filter(v=>dsOf(new Date(v.t))===T).map(v=>v.id)).size};
function pageHome(){const nc=nextClass();
 return `<section class="hero"><div class="wrap"><div class="hz">
  <div class="hz-l"><span class="hz-tag"><b>Fitness + Recovery</b> Brooklyn · Sydney</span>
   <h1><span class="ln"><span style="--i:0">Stronger</span></span><span class="ln"><span style="--i:1">body,</span></span><span class="ln"><span style="--i:2"><span class="hl">calmer</span> mind.</span></span></h1>
   <p class="lead">Strength floor, reformer Pilates, yoga and a recovery suite with licensed physios. One membership, one QR code on your phone.</p>
   <div class="hz-chips"><a href="#classes" data-f="str">Strength</a><a href="#classes" data-f="pil">Reformer Pilates</a><a href="#classes" data-f="yoga">Yoga</a><a href="#classes" data-f="hiit">HIIT</a><a href="#recovery">Physio & recovery</a></div>
   <div class="hz-cta"><a class="sq" href="#join" aria-label="Join FORMA">${ic('ne')}</a><div><b style="font-family:var(--f-d);font-size:22px;display:block">Your first week is free</b><span class="muted">No joining fee. Cancel any time.</span></div></div></div>
  <div class="hz-r"><div class="blob" aria-hidden="true"></div><img class="athlete" data-par=".04" src="photos/cut/h-jump.webp" alt="Athlete mid-jump" onerror="this.remove()">
   ${nc?`<div class="fc nx"><small>Next class · ${CLUBS[S.club].n}</small><b>${CT[nc.k].n}</b><div class="r"><span>${nc.ds===today()?'Today':fmtD(nc.ds,{weekday:'short'})} ${nc.t} · ${nc.cap-nc.taken} spots</span><a href="#classes" data-cls="${nc.id}" aria-label="Book ${CT[nc.k].n}">${ic('ne','width:16px;height:16px')}</a></div></div>`:''}
   <div class="fc ci"><span class="dot">${ic('qr')}</span><div><b class="num" id="hzIn">${inToday()}</b><span><i class="live"></i>members checked in today</span></div></div>
   <div class="fc qr" aria-hidden="true"><div class="code" id="hzQr"></div><small><span class="ring" id="hzRing"></span>Code refreshes every 30 s</small></div></div></div>
  <div class="stats rv">${[['2','clubs, 06:00–22:00'],['120+','classes a week'],['30+','coaches & physios'],['2 s','to check in']].map(s=>`<div><b>${s[0]}</b><span>${s[1]}</span></div>`).join('')}</div></div></section>
 <div class="mq" aria-hidden="true"><div class="tr">${Array(2).fill(['Move','Recover','Repeat','Lift','Breathe','Stretch']).flat().map(w=>`<span>${w}</span>`).join('')}</div></div>
 <section class="s wrap" id="programs">${sh('Programs','Train every <span class="t">way</span> you want','Six ways to move, all included in Unlimited. Pick one or mix them all.',`<a class="btn" href="#classes">See the schedule</a>`)}
  <div class="prg">${[['a','str','Strength','h-lift','Small-group barbell and dumbbell coaching.','50% 30%'],['b','pil','Reformer Pilates','c-pil2','Precise, low-impact, very effective.','50% 30%'],['c','hiit','HIIT','c-box','45 minutes, heart rate up.','50% 40%'],['d','yoga','Yoga','c-yoga1','Flow & breathe.','50% 50%'],['e','mob','Stretch & Mobility','c-stretch2','Move better, feel looser.','50% 50%'],['f','rec','Recovery','r-leg','Physio, massage, sauna.','50% 50%']].map((p,i)=>`<a class="pg ${p[0]} rv zoom" style="--dl:${i*.06}s" href="#classes" data-f="${p[1]}">${ph(p[3],p[2],p[5])}<span class="tg">${ic(CT[p[1]].ic,'width:13px;height:13px;vertical-align:-2px')} ${p[1]==='rec'?'Recovery suite':CT[p[1]].n}</span><span class="ar">${ic('ne')}</span><h3>${p[2]}</h3><p>${p[4]}</p></a>`).join('')}</div></section>
 <div class="coach-band" id="coaches"><div class="wrap">${sh('Coaches','People who <span class="t" style="color:#8A8A8A">know</span> their stuff','Certified coaches and licensed physios. Tap a coach to see their classes this week.')}
  <div class="cg">${COACH.map((c,i)=>`<button class="co ${i===0?'tall':''} rv" style="--dl:${i*.07}s" data-coach="${c.id}">${ph(c.img,c.n,c.pos)}<span class="hrs">${c.hrs}</span><span class="cap"><b>${c.n}</b><span>${c.r}</span></span></button>`).join('').replace(/(<\/button>)(?![\s\S]*<\/button>)/,'$1<div class="cstat rv"><b>30+</b><p>Coaches and physios across two clubs, over 120 classes a week.</p><a class="btn ink" href="#classes" style="align-self:flex-start">Find a class</a></div>')}</div></div></div>
 <section class="s wrap" id="schedule">${sh('Schedule','Find your <span class="t">routine</span>','Book a spot in a few taps. Members see their bookings highlighted.',clubSwitch())}${scheduleBlock()}</section>
 <section class="ck" id="checkin"><div class="wrap"><h2 class="rv">Your phone is your key.</h2><p class="sub rv">No plastic cards, no shared passes. Every member gets a live QR code that changes every 30 seconds, so screenshots and borrowed cards simply do not work.</p>
  <div class="ck-grid"><div class="ck-list">${[['Open your card','In the FORMA member area, on any phone.'],['Scan at the gate','The front desk sees your photo and plan instantly.'],['You are in','Your visit is logged. Streaks, history and renewals in one place.']].map((x,i)=>`<div class="ck-it rv" style="--dl:${i*.08}s"><span class="n">${i+1}</span><div><b>${x[0]}</b><span>${x[1]}</span></div></div>`).join('')}</div>
   <div class="phone rv" aria-hidden="true"><span class="notch"></span><div class="scr"><div class="mcard"><div class="who">${avatar(mem('FM-1001'))}<div><b>Ava Thompson</b><span>Unlimited · FM-1001</span></div></div></div><div class="qrbox" style="position:relative"><span class="scan-line"></span><div class="code" id="ckQr"></div><div class="t"><span class="ring" id="ckRing"></span><span id="ckS">30 s</span></div><div class="pin num" id="ckPin"></div></div></div></div>
   <div class="ck-list">${[['Screenshots are rejected','Codes older than 60 seconds are refused and flagged.'],['Shared cards are caught','A second entry within 3 hours needs staff approval.'],['Expiry is automatic','Expired, frozen and off-peak rules are checked at the gate.']].map((x,i)=>`<div class="ck-it rv" style="--dl:${i*.08}s"><span class="n">${ic('lock','width:18px;height:18px')}</span><div><b>${x[0]}</b><span>${x[1]}</span></div></div>`).join('')}
    <div style="display:flex;gap:10px;flex-wrap:wrap;margin-top:6px"><a class="btn lime" href="#member">Try the member card</a><a class="btn white" href="#scan">Open the scanner</a></div></div></div></div>
  <div class="bigtxt" id="big1" aria-hidden="true">Check in · Check in · Check in ·</div><div class="bigtxt o" id="big2" aria-hidden="true">Train · Recover · Train · Recover ·</div></section>
 <section class="s wrap" id="plans">${sh('Memberships','Simple plans, <span class="t">no</span> joining fee','Prices shown for your club. Switch clubs to see local pricing.',`<div class="pl-top"><div class="seg" role="group" aria-label="Billing"><button type="button" data-bill="m" aria-pressed="${S.bill==='m'}">Monthly</button><button type="button" data-bill="y" aria-pressed="${S.bill==='y'}">Yearly<small>2 months free</small></button></div>${clubSwitch('pl')}</div>`)}<div class="plans" id="plansG"></div></section>
 <section class="s wrap" id="recovery">${sh('Recovery & physio','Recover like it’s part of <span class="t">training</span>','Licensed physiotherapists and massage therapists on site, with itemised receipts you can submit to your insurer.')}
  <div class="recv"><div class="img rv zoom" style="border-radius:32px;overflow:hidden;position:relative">${ph('r-back','Physiotherapist treating a client','50% 40%').replace('class="ph"','class="ph" style="position:absolute;inset:0"')}</div>
  <div class="rl">${[['Physio assessment','45 min · licensed physiotherapist',95],['Sports massage','60 min · remedial therapist',85],['Mobility screening','30 min · movement assessment',45],['Sauna & cold plunge','Drop-in · included in Unlimited + Recovery',0]].map((r,i)=>`<div class="ri rv" style="--dl:${i*.06}s"><b>${r[0]}</b><span class="p num">${r[2]?money(r[2],CLUBS[S.club].cur):'Included'}</span><span>${r[1]}</span><a class="btn sm ink" href="#classes" data-f="rec">Book</a></div>`).join('')}
   <div class="trust">${['Licensed physios','Insurance receipts','Private treatment rooms'].map(t=>`<span class="pill ok">${ic('check','width:14px;height:14px')}${t}</span>`).join('')}</div></div></div></section>
 <section class="s wrap" id="journal-h">${sh('Journal','Read, then <span class="t">move</span>','',`<a class="btn ghost" href="#journal">Read the journal ${ic('arrow','width:16px;height:16px')}</a>`)}${journalBento()}</section>
 <section class="s wrap" id="faq"><div class="faq"><div><span class="eyebrow rv">FAQ</span><h2 class="rv" style="font-size:clamp(38px,4.6vw,64px);font-weight:900;margin-top:14px;letter-spacing:-.04em">Good questions</h2></div><div>${FAQ.map((f,i)=>`<div class="qa rv" style="--dl:${i*.04}s"><button type="button" aria-expanded="${i===0}" aria-controls="qa${i}">${f[0]}<i>${ic('plus','width:16px;height:16px')}</i></button><div class="a" id="qa${i}"><div><p>${f[1]}</p></div></div></div>`).join('')}</div></div></section>
 <section class="jn-band rv"><div class="ph"><img src="photos/cut/h-knee.webp" alt="" style="object-fit:contain;object-position:70% 100%" onerror="this.remove()"></div><div class="in"><h2>Join<br>the club</h2><p>First week free, then month to month. Your member card is ready the moment you sign up.</p><a class="btn ink lg" href="#join">Start my free week<span class="go">${ic('ne','width:15px;height:15px')}</span></a></div></section>`}
const FAQ=[['How does QR check-in work?','Open the member area on your phone and show your live code at the gate. The code changes every 30 seconds and is checked against your membership, so a screenshot or someone else’s phone will not get in.'],
 ['What if my phone is dead?','Give the desk your member ID and show photo ID. Staff can check you in manually; it is logged the same way.'],
 ['What are Off-Peak hours?','Monday to Friday, 10:00 to 16:00. Off-Peak members scanning outside these hours can buy a day pass or upgrade on the spot.'],
 ['Can I pause my membership?','Yes. Freeze for 7, 14 or 30 days from the member area. Your expiry date moves forward automatically.'],
 ['Is physio covered by insurance?','Many private health plans cover physiotherapy. We give you an itemised receipt with the provider number to submit to your insurer.'],
 ['How do I cancel?','Monthly plans cancel any time from the member area or the front desk. Your access continues to the end of the paid period.']];
function clubSwitch(k='s'){return `<div class="seg" role="group" aria-label="Club">${Object.entries(CLUBS).map(([id,c])=>`<button type="button" data-club="${id}" aria-pressed="${S.club===id}">${c.n}</button>`).join('')}</div>`}
function scheduleBlock(){return `<div class="sch rv"><div class="sch-top"><div class="sch-f" role="group" aria-label="Filter classes">${CATF.map(f=>`<button class="chip" type="button" data-fil="${f[0]}" aria-pressed="${S.fil===f[0]}">${f[1]}</button>`).join('')}</div><span class="muted" style="font-size:14px" id="schInfo"></span></div><div id="schBody"></div><p class="sch-note">Book in the member area, or <a class="link" href="#join">start a free week</a> to book your first class.</p></div>`}
function drawSchedule(){const b=$('#schBody');if(!b)return;const mon=addDs(monday(),S.wk*7),days=[...Array(7)].map((_,i)=>addDs(mon,i)),T=today(),now=Date.now(),mine=new Set(bookings().filter(x=>x.who===S.sess).map(x=>x.cid));
 const all=days.map(ds=>classesFor(S.club,ds));
 const cell=(c,k)=>{if(!c)return `<div class="cl emp"></div>`;const past=clsStart(c)<now,full=c.taken>=c.cap,hide=S.fil!=='all'&&c.k!==S.fil;if(hide)return `<div class="cl emp"></div>`;
  return `<button type="button" class="cl ${c.k} ${full?'full':''} ${past?'past':''} ${mine.has(c.id)?'mine':''}" data-cls="${c.id}" style="--d:${k*.015}s" ${past?'disabled':''}><span class="ic">${ic(CT[c.k].ic,'width:16px;height:16px')}</span><b>${CT[c.k].n}</b><span>${ic('users','width:13px;height:13px')}${full?'Class full':`${c.cap-c.taken}/${c.cap} spots left`}</span></button>`};
 let g='';ROWS.forEach((t,ri)=>{g+=`<div class="tm">${t}</div>`;days.forEach((ds,di)=>g+=cell(all[di].find(c=>c.t===t),ri*7+di))});
 if(S.dayI==null)S.dayI=Math.max(0,days.indexOf(T));
 const dl=all[S.dayI].filter(c=>S.fil==='all'||c.k===S.fil);
 b.innerHTML=`<div class="wk"><button class="rb" type="button" id="wkP" ${S.wk?'':'disabled'} aria-label="Previous week">${ic('left')}</button>${days.map(ds=>`<div class="d ${ds===T?'today':''}">${fmtD(ds,{weekday:'short'})}, ${+ds.slice(8)}</div>`).join('')}<button class="rb" type="button" id="wkN" ${S.wk<1?'':'disabled'} aria-label="Next week">${ic('arrow')}</button></div><div class="grid">${g}</div>
  <div class="dtabs" role="group" aria-label="Day">${days.map((ds,i)=>`<button type="button" data-di="${i}" aria-pressed="${i===S.dayI}">${fmtD(ds,{weekday:'short'})}<br>${+ds.slice(8)}</button>`).join('')}<button type="button" id="wkN2" style="width:auto;padding:0 14px" ${S.wk<1?'':'disabled'}>${S.wk?'This week':'Next week'} →</button></div>
  <div class="day-list">${dl.length?dl.map(c=>cell(c,0).replace('<span class="ic">',`<span class="tt">${c.t}</span><span class="ic">`).replace(/<b>(.*?)<\/b><span>(.*?)<\/span><\/button>/,'<div><b>$1</b><span>$2</span></div></button>')).join(''):'<p class="muted" style="padding:20px;text-align:center">No classes for this filter today.</p>'}</div>`;
 $('#schInfo').textContent=`${CLUBS[S.club].n} · week of ${fmtD(mon,{month:'long',day:'numeric'})}`;
 $('#wkP').onclick=()=>{S.wk=0;S.dayI=null;drawSchedule()};$('#wkN').onclick=()=>{S.wk=1;S.dayI=0;drawSchedule()};$('#wkN2').onclick=()=>{S.wk=S.wk?0:1;S.dayI=S.wk?0:null;drawSchedule()};
 $$('[data-di]',b).forEach(x=>x.onclick=()=>{S.dayI=+x.dataset.di;drawSchedule()});
 $$('.cl[data-cls]',b).forEach(x=>x.onclick=()=>openClass(x.dataset.cls))}
function openClass(id){const c=classById(id);if(!c)return;const co=coach(c.co),u=me(),bk=bookings().find(b=>b.cid===id&&b.who===S.sess),full=c.taken>=c.cap;
 const m=modal(`<span class="pill" style="background:var(--t-${c.k==='pil'?'pil':c.k})">${ic(CT[c.k].ic,'width:14px;height:14px')}${CT[c.k].n}</span><h3>${CT[c.k].n}</h3><p class="muted">${fmtD(c.ds,{weekday:'long',month:'long',day:'numeric'})} · ${c.t} · 45 min · FORMA ${CLUBS[c.club].n}</p>
 <div style="display:flex;align-items:center;gap:12px;padding:12px;border-radius:18px;background:var(--mist)">${`<span class="av" style="width:48px;height:48px">${`<img src="photos/${co.img}.jpg" alt="" style="object-position:${co.pos}">`}</span>`}<div><b>${co.n}</b><div class="muted" style="font-size:13.5px">${co.r}</div></div></div>
 <div style="display:flex;justify-content:space-between;font-weight:600"><span>${full?'Class full':`${c.cap-c.taken} of ${c.cap} spots left`}</span><span class="muted">Cancel up to 2 h before</span></div>
 <div style="height:8px;border-radius:9px;background:var(--mist);overflow:hidden"><i style="display:block;height:100%;width:${c.taken/c.cap*100}%;background:var(--ink)"></i></div>
 <div id="clsAct" style="display:flex;gap:10px;flex-wrap:wrap">${bk?`<span class="pill ok">${ic('check','width:14px;height:14px')}You’re booked</span><button class="btn ghost" id="cxB">Cancel booking</button>`:u?(full?`<button class="btn" id="wlB">Join waitlist</button>`:(status(u)==='expired'||status(u)==='frozen'?`<span class="pill bad">Membership ${status(u)}</span><a class="btn ink" href="#member" data-tab="plan">Renew</a>`:`<button class="btn ink" id="bkB">Book my spot as ${esc(u.n.split(' ')[0])}</button>`)):`<a class="btn ink" href="#member">Member login</a><a class="btn lime" href="#join">Start free week</a>`}</div>`);
 $('#bkB',m)?.addEventListener('click',()=>{const l=bookings();l.push({cid:id,who:S.sess,t:Date.now()});ls('bookings',l);closeModal();drawSchedule();toast(`Booked: ${CT[c.k].n}, ${fmtD(c.ds,{weekday:'short'})} ${c.t}`)});
 $('#cxB',m)?.addEventListener('click',()=>{ls('bookings',bookings().filter(b=>!(b.cid===id&&b.who===S.sess)));closeModal();drawSchedule();toast('Booking cancelled')});
 $('#wlB',m)?.addEventListener('click',()=>{closeModal();toast('Added to the waitlist. We will email you if a spot opens.')})}
function openCoach(id){const c=coach(id);const up=[];for(let i=0;i<7&&up.length<5;i++){const ds=addDs(today(),i);classesFor(S.club,ds).filter(x=>x.co===id&&clsStart(x)>Date.now()).forEach(x=>up.push(x))}
 const m=modal(`${ph(c.img,c.n,c.pos)}<div class="in"><span class="eyebrow">${c.r}</span><h3>${c.n}</h3><span class="pill ok" style="justify-self:start">${c.cert}</span><p style="color:var(--fg-2)">${c.bio}</p><b>Upcoming at ${CLUBS[S.club].n}</b><div style="display:grid;gap:6px">${up.slice(0,5).map(x=>`<button class="cl ${x.k}" data-cls="${x.id}" style="min-height:0;flex-direction:row;align-items:center;justify-content:space-between;animation:none"><b>${CT[x.k].n}</b><span>${fmtD(x.ds,{weekday:'short'})} ${x.t}</span></button>`).join('')||'<p class="muted">No classes this week at this club.</p>'}</div></div>`,'wide');
 $$('[data-cls]',m).forEach(b=>b.onclick=()=>openClass(b.dataset.cls))}
function drawPlans(){const g=$('#plansG');if(!g)return;const cur=CLUBS[S.club].cur;g.innerHTML=Object.entries(PLANS).map(([k,p])=>{const v=S.bill==='y'?p.p[cur]*10:p.p[cur];return `<div class="plan ${p.feat?'feat':''}"><div class="nm"><span>${p.n}</span>${p.feat?'<span class="pill dark">Most popular</span>':''}</div><div class="pr num">${money(v,cur)}<small> / ${S.bill==='y'?'year':'month'}</small></div><span class="muted" style="${p.feat?'color:var(--fg-2)':''}">${p.d}</span><ul>${p.f.map(f=>`<li>${ic('check')}${f}</li>`).join('')}${p.x.map(f=>`<li class="x">${ic('x')}${f}</li>`).join('')}</ul><a class="btn ${p.feat?'ink':''}" href="#join" data-plan="${k}">Choose ${p.n}</a></div>`}).join('');
 $$('[data-plan]',g).forEach(a=>a.addEventListener('click',()=>{S.planSel=a.dataset.plan;S.jn={step:2}}))}
function bindHome(){
 drawSchedule();drawPlans();
 $$('[data-club]').forEach(b=>b.onclick=()=>{S.club=b.dataset.club;ls('club',S.club);$$('[data-club]').forEach(x=>x.setAttribute('aria-pressed',x.dataset.club===S.club));S.dayI=null;drawSchedule();drawPlans();$$('.ri .p').forEach((p,i)=>{const v=[95,85,45,0][i];p.textContent=v?money(v,CLUBS[S.club].cur):'Included'})});
 $$('[data-fil]').forEach(b=>b.onclick=()=>{S.fil=b.dataset.fil;$$('[data-fil]').forEach(x=>x.setAttribute('aria-pressed',x===b));drawSchedule()});
 $$('[data-bill]').forEach(b=>b.onclick=()=>{S.bill=b.dataset.bill;$$('[data-bill]').forEach(x=>x.setAttribute('aria-pressed',x===b));drawPlans()});
 $$('[data-coach]').forEach(b=>b.onclick=()=>openCoach(b.dataset.coach));
 $$('.qa button').forEach(b=>b.onclick=()=>b.setAttribute('aria-expanded',b.getAttribute('aria-expanded')!=='true'));
 $('.fc.nx a')?.addEventListener('click',e=>{e.preventDefault();openClass(e.currentTarget.dataset.cls)});
 bindJournalBento();
 const tick=()=>{const w=win(),p=1-((Date.now()%WIN)/WIN);if(S.lastW!==w){S.lastW=w;const q=qrSvg(payload('FM-1001',w));['#hzQr','#ckQr'].forEach(s=>{const e=$(s);if(e)e.innerHTML=q});const pin=$('#ckPin');if(pin)pin.textContent=code6('FM-1001',w).replace(/(\d{3})/,'$1 ')}
  ['#hzRing','#ckRing'].forEach(s=>$(s)?.style.setProperty('--p',p.toFixed(3)));const t=$('#ckS');if(t)t.textContent=Math.ceil(p*30)+' s';const hi=$('#hzIn');if(hi)hi.textContent=inToday()};
 S.lastW=null;tick();timer(tick,1000)}

/* ---------- journal ---------- */
const ARTS=[
 {s:'full-body-at-home',t:'The best full-body session you can do at home',cat:'Strength',min:6,date:'Sep 22',img:'c-squat',pos:'50% 40%',ex:'No machines, 30 minutes, every major muscle group.',body:['You do not need a rack to get stronger. You need a plan that loads every major movement pattern: squat, hinge, push, pull and carry.',{h:'The session'},'Three rounds of goblet squats, single-leg hip hinges, push-ups, backpack rows and suitcase carries. Rest 60 seconds between exercises and write down what you did.',{h:'Make it harder over time'},'Add one rep a week until you reach 15, then slow the lowering phase to three seconds. Progress is the whole point.']},
 {s:'start-running',t:'Ready, set, go: how to start running and stay with it',cat:'Cardio',min:5,date:'Sep 15',img:'h-bra',pos:'50% 30%',ex:'Walking is a perfectly good place to start.',body:['Walking is a safe, effective way to begin. A daily brisk walk builds the base that running needs.',{h:'Run-walk intervals'},'Alternate one minute of easy running with two minutes of walking for twenty minutes. Each week, add thirty seconds to the running part.',{h:'Stay with it'},'Run at a pace where you could still talk. Most beginners quit because they run too fast, not too far.']},
 {s:'laziness-in-sport',t:'Overcoming the “can’t be bothered” days',cat:'Mindset',min:4,date:'Sep 9',img:'p-w8',pos:'50% 25%',ex:'Motivation follows action, not the other way round.',body:['Everyone has days when training feels impossible. The trick is to make starting smaller than the excuse.',{h:'The five-minute rule'},'Tell yourself you will do five minutes. If you still want to stop after five, stop. You usually won’t.',{h:'Book it'},'A booked class is a promise to someone else. That is why members who book train twice as often as those who drop in.']},
 {s:'soft-vs-hard-styles',t:'Soft and hard styles of training, explained',cat:'Pilates',min:5,date:'Sep 2',img:'c-pil1',pos:'50% 40%',ex:'Why Pilates and HIIT belong in the same week.',body:['High-intensity work builds fitness fast but asks a lot of your joints. Slow, controlled work builds the stability that keeps you training.',{h:'A balanced week'},'Two harder sessions, two slower sessions and one day of mobility is a simple template that suits most people.']},
 {s:'limited-space',t:'How to work out in a limited space',cat:'Strength',min:4,date:'Aug 26',img:'c-push',pos:'50% 50%',ex:'Two square metres is enough.',body:['A mat-sized space is enough for a complete session if you choose your exercises well.',{h:'Stay on the spot'},'Lunges in place, push-ups, planks, glute bridges and step-ups on a sturdy chair cover everything without moving around.']}];
const art=s=>ARTS.find(a=>a.s===s);
function journalBento(){const [a,b,c,d,e]=ARTS;return `<div class="jb">
 <a class="jc big rv" href="#article-${a.s}">${ph(a.img,a.t,a.pos)}<div class="cap"><div class="meta"><b>Category</b>· ${a.cat} | ${a.date}</div><h3>${a.t}</h3></div></a>
 <div class="jc lime rv" style="--dl:.06s"><a href="#article-${b.s}" style="text-decoration:none"><div class="meta"><b>Category</b>· ${b.cat}</div><h3>${b.t}</h3><p>${b.ex} ${b.body[0]}</p></a><div class="lst"><a href="#article-${e.s}">${e.t}${ic('arrow')}</a><a href="#article-${d.s}">${d.t}${ic('arrow')}</a></div></div>
 <a class="jc tall rv" style="--dl:.12s" href="#article-${c.s}"><div class="meta"><b>Category</b>· ${c.cat}</div><h3>${c.t}</h3>${ph(c.img,c.t,c.pos)}</a>
 <a class="jc vid rv" style="--dl:.08s" href="#article-${d.s}">${ph(d.img,d.t,d.pos)}<span class="play">${ic('play','width:22px;height:22px')}</span><div class="cap"><div class="meta" style="color:#fff">${d.min} min · ${d.date}</div><h3 style="font-size:20px">${d.t}</h3></div></a>
 <div class="jc cats rv" style="--dl:.14s"><div class="cw">${['All','Strength','Cardio','Pilates','Mindset'].map(x=>`<button type="button" data-jf="${x}" aria-pressed="${S.jf===x}">${x}</button>`).join('')}</div><a class="ft" href="#journal" style="text-decoration:none">View all articles<span>${ic('arrow')}</span></a></div></div>`}
function bindJournalBento(){$$('[data-jf]').forEach(b=>b.onclick=()=>{S.jf=b.dataset.jf;location.hash='journal'})}
function pageJournal(){const cats=['All',...new Set(ARTS.map(a=>a.cat))];return `<section class="wrap ph-h"><div class="crumbs"><a href="#home">Home</a>/<span>Journal</span></div><h1 class="xp rv">Journal</h1><p class="rv">Training notes from our coaches and physios.</p><div class="sch-f" style="margin-top:22px">${cats.map(c=>`<button class="chip" type="button" data-jc="${c}" aria-pressed="${S.jf===c}">${c}</button>`).join('')}</div></section><section class="wrap"><div class="prg" id="jl" style="grid-auto-rows:auto;grid-template-columns:repeat(3,1fr)"></div></section>`}
function bindJournal(){const draw=()=>{$('#jl').innerHTML=ARTS.filter(a=>S.jf==='All'||a.cat===S.jf).map(a=>`<a class="jc" href="#article-${a.s}" style="background:var(--mist);animation:rise .5s both"><div style="height:240px">${ph(a.img,a.t,a.pos).replace('class="ph"','class="ph" style="height:100%"')}</div><div style="padding:20px"><div class="meta"><b>${a.cat}</b>· ${a.date} · ${a.min} min</div><h3 style="font-size:22px">${a.t}</h3><p class="muted" style="margin-top:8px;font-size:14.5px">${a.ex}</p></div></a>`).join('')};$$('[data-jc]').forEach(b=>b.onclick=()=>{S.jf=b.dataset.jc;$$('[data-jc]').forEach(x=>x.setAttribute('aria-pressed',x===b));draw()});draw()}
function pageArticle(a){return `<section class="wrap ph-h art"><div class="crumbs"><a href="#home">Home</a>/<a href="#journal">Journal</a>/<span>${a.cat}</span></div><h1 class="rv" style="font-size:clamp(36px,5vw,62px)">${a.t}</h1><p class="muted" style="margin-top:14px">${a.cat} · ${a.date} · ${a.min} min read</p><div class="cover rv zoom" style="position:relative;overflow:hidden">${ph(a.img,a.t,a.pos).replace('class="ph"','class="ph" style="position:absolute;inset:0"')}</div><div class="body">${a.body.map(p=>typeof p==='string'?`<p>${p}</p>`:`<h3>${p.h}</h3>`).join('')}</div><div style="display:flex;gap:10px;margin-top:20px;flex-wrap:wrap"><a class="btn ink" href="#classes">Book a class</a><a class="btn ghost" href="#journal">More articles</a></div></section>`}

/* ---------- CLASSES page ---------- */
function pageClasses(){return `<section class="wrap ph-h"><div class="crumbs"><a href="#home">Home</a>/<span>Classes</span></div><h1 class="xp rv">Class schedule</h1><p class="rv">Pick a club, filter by style and book. Classes are 45 minutes; cancel up to two hours before.</p><div style="margin-top:20px">${clubSwitch()}</div></section><section class="wrap">${scheduleBlock()}</section>`}
function bindClasses(){drawSchedule();$$('[data-club]').forEach(b=>b.onclick=()=>{S.club=b.dataset.club;ls('club',S.club);$$('[data-club]').forEach(x=>x.setAttribute('aria-pressed',x.dataset.club===S.club));S.dayI=null;drawSchedule()});$$('[data-fil]').forEach(b=>b.onclick=()=>{S.fil=b.dataset.fil;$$('[data-fil]').forEach(x=>x.setAttribute('aria-pressed',x===b));drawSchedule()})}

/* ---------- JOIN ---------- */
const luhn=n=>{const d=n.replace(/\D/g,'');if(d.length<13)return false;let s=0;[...d].reverse().forEach((c,i)=>{let v=+c;if(i%2){v*=2;if(v>9)v-=9}s+=v});return s%10===0};
function pageJoin(){return `<section class="wrap ph-h"><div class="crumbs"><a href="#home">Home</a>/<span>Join</span></div><h1 class="xp rv">Join FORMA</h1><p class="rv">Three steps. Your digital member card is ready the moment you finish.</p></section><section class="wrap"><div class="panel" id="jnp"></div></section>`}
function drawJoin(){const J=S.jn,el=$('#jnp');const cur=CLUBS[S.club].cur;const steps=['Plan','Your details','Payment'];
 const bar=`<div class="steps-bar">${steps.map((s,i)=>`<span class="pill ${J.step===i+1?'dark':J.step>i+1?'ok':''}">${J.step>i+1?'✓':i+1} · ${s}</span>`).join('')}</div>`;
 if(J.step===1){el.innerHTML=bar+`<div style="display:flex;justify-content:space-between;gap:12px;flex-wrap:wrap;align-items:center;margin-bottom:16px"><h2 style="font-size:34px">Choose a plan</h2><div style="display:flex;gap:8px;flex-wrap:wrap">${clubSwitch()}<div class="seg"><button type="button" data-bill="m" aria-pressed="${S.bill==='m'}">Monthly</button><button type="button" data-bill="y" aria-pressed="${S.bill==='y'}">Yearly</button></div></div></div>
  <div class="opts">${Object.entries(PLANS).map(([k,p])=>`<button type="button" class="op" data-v="${k}" aria-pressed="${S.planSel===k}"><b>${p.n}</b><span class="pr num">${money(S.bill==='y'?p.p[cur]*10:p.p[cur],cur)}<small style="font-size:14px;font-weight:500"> / ${S.bill==='y'?'yr':'mo'}</small></span><span>${p.d}</span></button>`).join('')}</div><p class="muted" style="margin-top:14px">First 7 days free. You will not be charged until day 8.</p>
  <div style="display:flex;justify-content:flex-end;margin-top:20px"><button class="btn ink lg" id="j1">Continue ${ic('arrow','width:16px;height:16px')}</button></div>`;
  $$('.op',el).forEach(b=>b.onclick=()=>{S.planSel=b.dataset.v;$$('.op',el).forEach(x=>x.setAttribute('aria-pressed',x===b))});$$('[data-club]',el).forEach(b=>b.onclick=()=>{S.club=b.dataset.club;ls('club',S.club);drawJoin()});$$('[data-bill]',el).forEach(b=>b.onclick=()=>{S.bill=b.dataset.bill;drawJoin()});$('#j1').onclick=()=>{J.step=2;drawJoin()}}
 if(J.step===2){const I=J.info||{};el.innerHTML=bar+`<h2 style="font-size:34px;margin-bottom:6px">Your details</h2><p class="muted">Your photo appears on your member card so the front desk can verify you. It stays on this device in the demo.</p>
  <form id="jf" novalidate style="display:grid;gap:14px;margin-top:18px"><div class="upl"><span class="av" id="jav">${I.photo?`<img src="${I.photo}" alt="">`:ic('cam','width:26px;height:26px')}</span><div><label class="btn ghost sm" for="jph" style="cursor:pointer">Upload photo</label><input id="jph" type="file" accept="image/*" class="sr"><p class="muted" style="font-size:13px;margin-top:6px">JPG or PNG, face clearly visible.</p></div></div>
  <div class="two"><div class="field"><label for="jn">Full name</label><input class="input" id="jn" autocomplete="name" value="${esc(I.n||'')}"></div><div class="field"><label for="je">Email</label><input class="input" id="je" type="email" autocomplete="email" value="${esc(I.e||'')}"></div></div>
  <div class="two"><div class="field"><label for="jt">Mobile</label><input class="input" id="jt" type="tel" autocomplete="tel" placeholder="${S.club==='nyc'?'+1 718 555 0100':'+61 400 555 100'}" value="${esc(I.tel||'')}"></div><div class="field"><label for="jb">Date of birth</label><input class="input" id="jb" type="date" value="${esc(I.dob||'')}"></div></div>
  <label style="display:flex;gap:10px;font-size:14px;color:var(--fg-2)"><input type="checkbox" id="jok" style="accent-color:var(--ink);width:18px;height:18px" ${I.ok?'checked':''}> I agree to the club rules and the health declaration.</label><p class="err-t" id="jerr" hidden></p>
  <div style="display:flex;justify-content:space-between"><button class="btn ghost" type="button" id="jb1">${ic('left','width:16px;height:16px')}Back</button><button class="btn ink lg" type="submit">Continue ${ic('arrow','width:16px;height:16px')}</button></div></form>`;
  $('#jph').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{const img=new Image();img.onload=()=>{const c=document.createElement('canvas'),s=240,k=Math.min(img.width,img.height);c.width=c.height=s;c.getContext('2d').drawImage(img,(img.width-k)/2,(img.height-k)/2,k,k,0,0,s,s);J.info={...(J.info||{}),photo:c.toDataURL('image/jpeg',.82)};$('#jav').innerHTML=`<img src="${J.info.photo}" alt="">`};img.src=r.result};r.readAsDataURL(f)};
  $('#jb1').onclick=()=>{J.step=1;drawJoin()};
  $('#jf').onsubmit=e=>{e.preventDefault();const v=id=>$('#'+id).value.trim();const bad=[];if(v('jn').length<2)bad.push('jn');if(!/^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test(v('je')))bad.push('je');const td=v('jt').replace(/\D/g,'');if(td.length<8||td.length>15)bad.push('jt');const dob=v('jb');const age=dob?(Date.now()-new Date(dob))/(365.25*DAY):0;if(!dob||age<16||age>100)bad.push('jb');
   ['jn','je','jt','jb'].forEach(id=>$('#'+id).classList.toggle('err',bad.includes(id)));const er=$('#jerr');if(bad.length||!$('#jok').checked){er.hidden=false;er.textContent=bad.includes('jb')?'Members must be 16 or older. Please check your date of birth.':bad.includes('je')?'Please enter a valid email.':bad.includes('jt')?'Please enter a valid mobile number.':bad.length?'Please complete the highlighted fields.':'Please accept the club rules to continue.';return}
   J.info={...(J.info||{}),n:v('jn'),e:v('je'),tel:v('jt'),dob,ok:1};J.step=3;drawJoin()}}
 if(J.step===3){const p=PLANS[S.planSel],amt=S.bill==='y'?p.p[cur]*10:p.p[cur];el.innerHTML=bar+`<div class="two" style="gap:30px;align-items:start"><div><h2 style="font-size:34px">Payment</h2><p class="muted" style="margin-top:6px">Demo only. Use 4242 4242 4242 4242, any future date and any CVC.</p>
  <form id="pf" novalidate style="display:grid;gap:14px;margin-top:18px"><div class="field"><label for="cn">Card number</label><input class="input num" id="cn" inputmode="numeric" autocomplete="cc-number" placeholder="4242 4242 4242 4242"></div><div class="two"><div class="field"><label for="ce">Expiry (MM/YY)</label><input class="input num" id="ce" inputmode="numeric" placeholder="08/29" autocomplete="cc-exp"></div><div class="field"><label for="cc">CVC</label><input class="input num" id="cc" inputmode="numeric" placeholder="123" autocomplete="cc-csc"></div></div><p class="err-t" id="perr" hidden></p>
  <div style="display:flex;justify-content:space-between"><button class="btn ghost" type="button" id="jb2">${ic('left','width:16px;height:16px')}Back</button><button class="btn ink lg" type="submit" id="payB">Start my free week</button></div></form></div>
  <div class="panel" style="background:var(--mist);border:0"><b style="font-family:var(--f-d);font-size:22px">${p.n}</b><p class="muted">FORMA ${CLUBS[S.club].n} · ${S.bill==='y'?'Yearly':'Monthly'}</p><div style="display:grid;gap:8px;margin-top:14px;font-size:15px"><div style="display:flex;justify-content:space-between"><span>Due today</span><b>${money(0,cur)}</b></div><div style="display:flex;justify-content:space-between"><span>From ${fmtD(addDs(today(),7),{month:'long',day:'numeric'})}</span><b>${money(amt,cur)} / ${S.bill==='y'?'yr':'mo'}</b></div><div style="display:flex;justify-content:space-between"><span>Joining fee</span><b>${money(0,cur)}</b></div></div></div></div>`;
  $('#ce').oninput=e=>{let v=e.target.value.replace(/\D/g,'').slice(0,4);if(v.length>2)v=v.slice(0,2)+'/'+v.slice(2);e.target.value=v};$('#cn').oninput=e=>{e.target.value=e.target.value.replace(/\D/g,'').slice(0,19).replace(/(\d{4})(?=\d)/g,'$1 ')};
  $('#jb2').onclick=()=>{J.step=2;drawJoin()};
  $('#pf').onsubmit=e=>{e.preventDefault();const bad=[];if(!luhn($('#cn').value))bad.push('cn');const [mm,yy]=$('#ce').value.split('/').map(Number);const exp=new Date(2000+(yy||0),mm||0,1);if(!(mm>=1&&mm<=12)||exp<=new Date())bad.push('ce');if(!/^\d{3,4}$/.test($('#cc').value))bad.push('cc');['cn','ce','cc'].forEach(id=>$('#'+id).classList.toggle('err',bad.includes(id)));const er=$('#perr');if(bad.length){er.hidden=false;er.textContent=bad.includes('cn')?'That card number is not valid.':bad.includes('ce')?'The expiry date must be in the future (MM/YY).':'Please enter the 3–4 digit CVC.';return}
   const b=$('#payB');b.disabled=true;b.textContent='Processing…';setTimeout(()=>{const added=ls('madded')||[];const id='FM-'+(2001+added.length);const I=J.info;const m={id,n:I.n,e:I.e,tel:I.tel,plan:S.planSel,club:S.club,exp:addDs(today(),(S.bill==='y'?365:30)+7),joined:today(),frozen:0,act:0,photo:I.photo||null,img:null,pos:''};added.push(m);ls('madded',added);loadMembers();S.sess=id;ls('sess',id);J.step=4;J.newId=id;drawJoin();toast('Welcome to FORMA!')},900)}}
 if(J.step===4){const m=mem(J.newId);el.innerHTML=`<div class="welcome"><div class="phone" style="width:260px;height:520px"><span class="notch"></span><div class="scr"><div class="mcard"><div class="who">${avatar(m)}<div><b>${esc(m.n)}</b><span>${PLANS[m.plan].n} · ${m.id}</span></div></div></div><div class="qrbox"><div class="code">${qrSvg(payload(m.id))}</div><div class="pin num">${code6(m.id,win()).replace(/(\d{3})/,'$1 ')}</div></div></div></div>
  <div><span class="pill ok">${ic('check','width:14px;height:14px')}Membership active</span><h2 style="font-size:clamp(36px,4vw,56px);margin-top:14px">You’re in, ${esc(m.n.split(' ')[0])}.</h2><p style="margin-top:14px;color:var(--fg-2);max-width:48ch">Your member ID is <b>${m.id}</b>. Show the live QR code at the ${CLUBS[m.club].n} front desk. It refreshes every 30 seconds, so keep the member area open rather than taking a screenshot.</p><div style="display:flex;gap:10px;flex-wrap:wrap;margin-top:22px"><a class="btn ink lg" href="#member">Open my member card</a><a class="btn ghost lg" href="#classes">Book a first class</a></div></div></div>`}}
function bindJoin(){if(S.jn.step===4)S.jn={step:1};drawJoin()}

/* ---------- MEMBER ---------- */
function pageMember(){const u=me();if(!u)return `<section class="wrap ph-h"><div class="crumbs"><a href="#home">Home</a>/<span>Member area</span></div><h1 class="xp rv">Member area</h1><p class="rv">Log in to see your live check-in code, visits and bookings.</p></section>
 <section class="wrap"><div class="two" style="gap:18px;align-items:start"><div class="panel"><h3 style="font-size:24px">Log in</h3><p class="muted" style="margin:6px 0 16px">Demo: enter a member ID or email. No password needed.</p><form id="lf" novalidate style="display:grid;gap:12px"><div class="field"><label for="li">Member ID or email</label><input class="input" id="li" placeholder="FM-1001 or ava.thompson@example.com" autocomplete="username"></div><p class="err-t" id="lerr" hidden>We couldn’t find that member. Try FM-1001.</p><button class="btn ink lg" type="submit">Log in</button></form></div>
 <div class="panel" style="background:var(--mist);border:0"><h3 style="font-size:24px">Try a demo member</h3><p class="muted" style="margin:6px 0 16px">Each one shows a different situation at the gate.</p><div class="demo-users">${[['FM-1001','Active'],['FM-1003','Expiring in 3 days'],['FM-1004','Expired'],['FM-1005','Frozen'],['FM-1002','Off-Peak plan']].map(([id,l])=>{const m=mem(id);return `<button class="du" type="button" data-login="${id}">${avatar(m)}<span>${esc(m.n)}<br><small class="muted">${l}</small></span></button>`}).join('')}</div></div></div></section>`;
 return `<section class="wrap" style="padding-top:34px"><div class="mp"><aside class="mp-card"><div class="top">${avatar(u)}<div><b>${esc(u.n)}</b><span>${u.id} · ${PLANS[u.plan].n}</span></div></div>
  <div class="qrbox" style="color:var(--ink)"><div class="code" id="mQr"></div><div class="t"><span class="ring" id="mRing"></span><span id="mS">30 s</span>· live code</div><div class="pin num" id="mPin"></div></div>
  <div style="display:flex;justify-content:space-between;align-items:center">${sPill(u)}<span style="font-size:13px;color:#BDBDBD">Valid until ${fmtD(u.exp,{month:'short',day:'numeric',year:'numeric'})}</span></div>
  <div class="vbar"><i style="width:${clamp(diffDays(u.exp,today())/30*100,0,100)}%"></i></div>
  <div class="kv"><span>Club</span><b>${CLUBS[u.club].n}</b><span>Visits this month</span><b id="mVm">–</b><span>Streak</span><b id="mStr">–</b></div>
  <p style="font-size:12.5px;color:#9A9A9A">Turn your screen brightness up at the gate. Screenshots will not work.</p><button class="btn white sm" id="lo">${ic('out','width:15px;height:15px')}Log out</button></aside>
 <div><div class="tabs" role="tablist">${[['visits','Visits'],['classes','My classes'],['plan','Membership']].map(t=>`<button class="chip" type="button" data-mt="${t[0]}" aria-pressed="${(S.mt||'visits')===t[0]}">${t[1]}</button>`).join('')}</div><div id="mBody" class="panel"></div></div></div></section>`}
function drawMemberTab(){const u=me(),el=$('#mBody');if(!u||!el)return;const t=S.mt||'visits';const my=visits().filter(v=>v.id===u.id);
 if(t==='visits'){const T=today(),first=T.slice(0,8)+'01',start=addDs(first,-((parseDs(first).getDay()+6)%7));const byDay={};my.forEach(v=>{const d=dsOf(new Date(v.t));byDay[d]=(byDay[d]||0)+1});
  let cells=['M','T','W','T','F','S','S'].map(d=>`<i class="dw">${d}</i>`).join('');for(let i=0;i<42;i++){const ds=addDs(start,i);if(ds.slice(0,7)!==T.slice(0,7)&&i>27)break;const n=byDay[ds]||0;cells+=`<i class="${n>1?'two':n?'on':''} ${ds===T?'td':''}" title="${fmtD(ds)}${n?`: ${n} visit${n>1?'s':''}`:''}" style="${ds.slice(0,7)!==T.slice(0,7)?'opacity:.35':''}"></i>`}
  el.innerHTML=`<h3 style="font-size:24px">${parseDs(T).toLocaleDateString('en-US',{month:'long',year:'numeric'})}</h3><p class="muted" style="margin:4px 0 16px">Every check-in at the gate is logged here.</p><div class="heat">${cells}</div><h3 style="font-size:20px;margin:26px 0 12px">Recent check-ins</h3><div class="hist">${my.slice(-10).reverse().map(v=>`<div class="hr"><span class="d">${+dsOf(new Date(v.t)).slice(8)}<small>${new Date(v.t).toLocaleDateString('en-US',{month:'short'})}</small></span><span class="g"><b>FORMA ${CLUBS[v.club].n}</b><br><span class="muted">${new Date(v.t).toLocaleDateString('en-US',{weekday:'long'})}</span></span><b class="num">${fmtT(v.t)}</b></div>`).join('')||'<p class="muted">No visits yet. Your first check-in will appear here.</p>'}</div>`}
 if(t==='classes'){const l=bookings().filter(b=>b.who===u.id).map(b=>({b,c:classById(b.cid)})).filter(x=>x.c).sort((a,b)=>clsStart(a.c)-clsStart(b.c));
  el.innerHTML=`<h3 style="font-size:24px;margin-bottom:14px">My classes</h3><div class="hist">${l.map(({c})=>`<div class="hr"><span class="d">${+c.ds.slice(8)}<small>${fmtD(c.ds,{month:'short'})}</small></span><span class="g"><b>${CT[c.k].n}</b><br><span class="muted">${fmtD(c.ds,{weekday:'long'})} ${c.t} · ${coach(c.co).n}</span></span>${clsStart(c)>Date.now()?`<button class="btn ghost sm" data-cx="${c.id}">Cancel</button>`:'<span class="pill">Done</span>'}</div>`).join('')||`<p class="muted">No classes booked yet.</p>`}</div><a class="btn ink" href="#classes" style="margin-top:16px">Browse the schedule</a>`;
  $$('[data-cx]',el).forEach(b=>b.onclick=()=>{ls('bookings',bookings().filter(x=>!(x.cid===b.dataset.cx&&x.who===u.id)));drawMemberTab();toast('Booking cancelled')})}
 if(t==='plan'){const st=status(u),cur=CLUBS[u.club].cur,p=PLANS[u.plan];
  el.innerHTML=`<h3 style="font-size:24px">${p.n}</h3><p class="muted" style="margin:4px 0 16px">${p.d} · ${money(p.p[cur],cur)} / month</p><div style="display:flex;gap:10px;align-items:center;flex-wrap:wrap">${sPill(u)}<span class="muted">Expires ${fmtD(u.exp,{weekday:'short',month:'long',day:'numeric',year:'numeric'})}</span></div>
  <h3 style="font-size:20px;margin:26px 0 12px">Renew or extend</h3><div class="opts">${[[1,'1 month',p.p[cur]],[3,'3 months',p.p[cur]*3*.95],[12,'12 months',p.p[cur]*10]].map(o=>`<button class="op" type="button" data-ext="${o[0]}"><b>${o[1]}</b><span class="pr num" style="font-size:26px">${money(o[2],cur)}</span><span>${o[0]===3?'5% off':o[0]===12?'2 months free':'Pay as you go'}</span></button>`).join('')}</div>
  <h3 style="font-size:20px;margin:26px 0 12px">Freeze</h3>${u.frozen?`<p style="margin-bottom:12px">Your membership is frozen. Unfreeze to use your card again.</p><button class="btn ink" id="unf">Unfreeze now</button>`:`<p class="muted" style="margin-bottom:12px">Travelling or injured? Pause and your expiry date moves forward.</p><div style="display:flex;gap:8px;flex-wrap:wrap">${[7,14,30].map(d=>`<button class="btn ghost" data-frz="${d}">${ic('snow','width:15px;height:15px')}${d} days</button>`).join('')}</div>`}`;
  $$('[data-ext]',el).forEach(b=>b.onclick=()=>{const n=+b.dataset.ext;const base=st==='expired'?today():u.exp;const d=parseDs(base);d.setMonth(d.getMonth()+n);patchMember(u.id,{exp:dsOf(d)});toast(`Extended to ${fmtD(dsOf(d),{month:'long',day:'numeric',year:'numeric'})} (demo payment)`);render('member')});
  $$('[data-frz]',el).forEach(b=>b.onclick=()=>{patchMember(u.id,{frozen:1,exp:addDs(u.exp,+b.dataset.frz)});toast(`Frozen for ${b.dataset.frz} days`);render('member')});
  $('#unf')?.addEventListener('click',()=>{patchMember(u.id,{frozen:0});toast('Membership unfrozen');render('member')})}}
function bindMember(){const u=me();if(!u){$$('[data-login]').forEach(b=>b.onclick=()=>login(b.dataset.login));$('#lf').onsubmit=e=>{e.preventDefault();const v=$('#li').value.trim().toLowerCase();const m=MEM.find(x=>x.id.toLowerCase()===v||x.e===v);if(!m){$('#lerr').hidden=false;$('#li').classList.add('err');return}login(m.id)};return}
 $('#lo').onclick=()=>{S.sess=null;ls('sess',null);render('member');toast('Logged out')};
 $$('[data-mt]').forEach(b=>b.onclick=()=>{S.mt=b.dataset.mt;$$('[data-mt]').forEach(x=>x.setAttribute('aria-pressed',x===b));drawMemberTab()});drawMemberTab();
 const stats=()=>{const my=visits().filter(v=>v.id===u.id);const T=today();$('#mVm').textContent=my.filter(v=>dsOf(new Date(v.t)).slice(0,7)===T.slice(0,7)).length;const days=new Set(my.map(v=>dsOf(new Date(v.t))));let s=0,d=days.has(T)?T:addDs(T,-1);while(days.has(d)){s++;d=addDs(d,-1)}const wk=new Set(my.filter(v=>Date.now()-v.t<7*DAY).map(v=>dsOf(new Date(v.t)))).size;$('#mStr').textContent=s>1?`${s} days`:`${wk} visit${wk===1?'':'s'} this week`};stats();
 const tick=()=>{const w=win(),p=1-((Date.now()%WIN)/WIN);if(S.lastW!==w){S.lastW=w;$('#mQr').innerHTML=qrSvg(payload(u.id,w));$('#mPin').textContent=code6(u.id,w).replace(/(\d{3})/,'$1 ')}$('#mRing').style.setProperty('--p',p.toFixed(3));$('#mS').textContent=Math.ceil(p*30)+' s'};S.lastW=null;tick();timer(tick,1000);
 S.onStore=()=>{stats();if((S.mt||'visits')==='visits')drawMemberTab()}}
function login(id){S.sess=id;ls('sess',id);S.mt='visits';render('member');toast(`Logged in as ${mem(id).n}`)}

/* ---------- SCANNER ---------- */
function pageScan(){return `<div class="wrap"><div class="k-top"><div><span class="eyebrow" style="color:#AFAFAF">Front desk · FORMA ${CLUBS[S.club].n}</span><h1 style="font-size:clamp(34px,4vw,54px);font-weight:900;margin-top:8px">Scan member card</h1></div><div style="text-align:right"><div class="k-clock num" id="kClock"></div><span style="color:#AFAFAF;font-size:14px" id="kCount"></span></div></div>
 <div class="k-grid"><div class="k-box"><h3>Camera</h3><div class="vf" id="vf"><div style="padding:20px;display:grid;gap:12px;justify-items:center">${ic('cam','width:40px;height:40px')}<span id="camMsg">Point the member’s phone at the camera.</span><button class="btn lime" id="camB">Start camera</button></div></div>
  <h3 style="margin-top:20px">Or enter the code</h3><form class="k-man" id="mf" novalidate><label class="sr" for="mid">Member ID</label><input class="input num" id="mid" placeholder="FM-1001" autocomplete="off"><label class="sr" for="mcode">6-digit code</label><input class="input num" id="mcode" placeholder="6-digit code" inputmode="numeric" maxlength="7" autocomplete="off"><button class="btn lime" type="submit">Check in</button></form></div>
 <div><div class="res" id="res" aria-live="assertive"><div class="hd"><span class="big" style="background:#333;color:#AFAFAF">${ic('scan')}</span><div><h3>Ready</h3><p class="why" style="color:#AFAFAF">Waiting for the next member.</p></div></div></div>
  <div class="k-box" style="margin-top:14px"><h3 style="display:flex;justify-content:space-between">Recent scans <a href="#admin" style="font-size:14px;font-family:var(--f-ui);color:var(--lime)">Admin →</a></h3><div class="k-log" id="klog"></div></div></div></div>
 <div class="sim"><div style="display:flex;justify-content:space-between;gap:12px;flex-wrap:wrap;align-items:center"><div><span class="pill" style="background:var(--lime);color:var(--ink)">Demo tools</span><h3 style="font-size:24px;margin-top:10px">Simulate a member’s phone</h3><p style="color:#AFAFAF;max-width:60ch;margin-top:6px">No second phone? Pick a member, then “scan” their live card, a screenshot or a shared card to see how each rule responds.</p></div>
  <div class="field" style="min-width:260px"><label for="simSel" style="color:#AFAFAF">Member</label><select class="sel" id="simSel">${MEM.map(m=>`<option value="${m.id}" ${m.id===S.simId?'selected':''}>${esc(m.n)} · ${m.id} · ${SLBL[status(m)][1]}${m.plan==='offpeak'?' · Off-Peak':''}</option>`).join('')}</select></div></div>
  <div class="sim-g"><div class="phone" aria-hidden="true"><span class="notch"></span><div class="scr"><div class="mcard" id="simCard"></div><div class="qrbox"><div class="code" id="simQr"></div><div class="t"><span class="ring" id="simRing"></span><span id="simS"></span></div><div class="pin num" id="simPin" style="font-size:18px"></div></div></div></div>
  <div class="sim-btns"><button class="btn" data-sim="live">${ic('scan')}<span>Scan the live card<small>The normal case. Rules for status, plan and duplicates apply.</small></span></button><button class="btn" data-sim="shot">${ic('alert')}<span>Scan a screenshot (2 min old)<small>An old code, e.g. a photo sent to a friend.</small></span></button><button class="btn" data-sim="again">${ic('users')}<span>Scan the same card again<small>Simulates a friend using the member’s card after they entered.</small></span></button><button class="btn" data-sim="type">${ic('list')}<span>Type the code instead<small>Fills the manual form, like a member with a cracked screen.</small></span></button></div></div></div></div>`}
function showResult(r,src){const el=$('#res');const m=r.m;const icon=r.lvl==='ok'?'check':r.lvl==='warn'?'alert':'x';beep(r.lvl!=='bad');
 el.className='res '+r.lvl;el.innerHTML=`<div class="hd"><span class="big">${ic(icon)}</span><div><h3>${r.title}</h3><p class="why">${r.why}</p></div></div>${m?`<div class="pp">${avatar(m).replace('class="av ','class="av ')}<div class="kv"><span>Name</span><b>${esc(m.n)}</b><span>Member ID</span><b>${m.id}</b><span>Plan</span><b>${PLANS[m.plan].n}</b><span>Valid until</span><b>${fmtD(m.exp,{month:'short',day:'numeric',year:'numeric'})}</b><span>Visits (30 days)</span><b>${visits().filter(v=>v.id===m.id&&Date.now()-v.t<30*DAY).length}</b></div></div>`:''}
 ${r.canOverride?`<div style="display:flex;gap:10px;flex-wrap:wrap"><button class="btn lime" id="ovB">Photo matches: allow entry</button><button class="btn white" id="ovN">Deny</button></div>`:''}
 <span style="font-size:13px;color:#AFAFAF">${fmtT(Date.now())} · ${src==='manual'?'Manual code':src==='cam'?'Camera':'Simulated scan'}</span>`;
 $('#ovB')?.addEventListener('click',()=>{const r2=validate(payload(m.id),{override:true});r2.why='Staff override after photo check. Logged for the admin.';const s=record(r2,'override');s.why='Staff override (duplicate entry)';const l=scans();l[l.length-1]=s;ls('scans',l);showResult({...r2,canOverride:false},'override');drawLog()});
 $('#ovN')?.addEventListener('click',()=>{el.className='res';el.innerHTML=`<div class="hd"><span class="big" style="background:#333;color:#AFAFAF">${ic('scan')}</span><div><h3>Ready</h3><p class="why" style="color:#AFAFAF">Entry denied. Waiting for the next member.</p></div></div>`})}
function doScan(input,src){const r=validate(input);record(r,src);showResult(r,src);drawLog();if(S.ci)S.ci()}
function drawLog(){const el=$('#klog');if(!el)return;const l=allScans().filter(s=>!s.seed||dsOf(new Date(s.t))===today()).slice(-14).reverse();el.innerHTML=l.map(s=>{const m=mem(s.id);return `<div><span class="st" style="background:${s.lvl==='ok'?'var(--lime)':s.lvl==='warn'?'var(--warn)':'var(--bad)'}"></span><time>${fmtT(s.t)}</time><b style="flex:1;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">${m?esc(m.n):esc(s.id)}</b><span style="color:#AFAFAF;font-size:12.5px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:45%">${s.ok?(s.lvl==='warn'?'Allowed · expiring':'Allowed'):esc(s.why)}</span></div>`}).join('');$('#kCount').textContent=`${inToday()} members checked in today`}
function bindScan(){const clk=()=>{const e=$('#kClock');if(e)e.textContent=new Date().toLocaleTimeString('en-US',{hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false})};clk();timer(clk,1000);drawLog();
 $('#mf').onsubmit=e=>{e.preventDefault();doScan({id:$('#mid').value,code:$('#mcode').value.replace(/\D/g,'')},'manual');$('#mcode').value=''};
 const simDraw=()=>{const m=mem(S.simId);if(!m)return;const w=win(),p=1-((Date.now()%WIN)/WIN);if(S.simW!==w+S.simId){S.simW=w+S.simId;$('#simQr').innerHTML=qrSvg(payload(m.id,w));$('#simPin').textContent=code6(m.id,w).replace(/(\d{3})/,'$1 ');$('#simCard').innerHTML=`<div class="who">${avatar(m)}<div><b>${esc(m.n)}</b><span>${PLANS[m.plan].n} · ${m.id}</span></div></div>`}$('#simRing').style.setProperty('--p',p.toFixed(3));$('#simS').textContent=Math.ceil(p*30)+' s'};S.simW=null;simDraw();timer(simDraw,1000);
 $('#simSel').onchange=e=>{S.simId=e.target.value;simDraw()};
 $$('[data-sim]').forEach(b=>b.onclick=()=>{const k=b.dataset.sim,id=S.simId;if(k==='live'||k==='again')doScan(payload(id),'sim');if(k==='shot')doScan(payload(id,win()-4),'sim');if(k==='type'){$('#mid').value=id;$('#mcode').value=code6(id,win());$('#mid').scrollIntoView({behavior:'smooth',block:'center'});toast('Code filled in. Press Check in.')}});
 $('#camB').onclick=startCam}
async function startCam(){const msg=$('#camMsg');if(!navigator.mediaDevices?.getUserMedia){msg.textContent='Camera access is not available in this browser. Use the 6-digit code instead.';return}
 if(!('BarcodeDetector' in window)){msg.innerHTML='This browser can’t read QR codes from the camera (try Chrome on Android or macOS). Use the 6-digit code below.';return}
 try{const st=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'}});S.stream=st;const vf=$('#vf');vf.innerHTML='<video playsinline muted></video><div class="fr"></div><span class="scan-line" style="left:22%;right:22%"></span>';const v=$('video',vf);v.srcObject=st;await v.play();
  const det=new BarcodeDetector({formats:['qr_code']});let busy=false,pause=0;const loop=async()=>{if(!S.stream||!document.body.contains(v))return;if(!busy&&Date.now()>pause){busy=true;try{const r=await det.detect(v);if(r[0]){doScan(r[0].rawValue,'cam');pause=Date.now()+2500}}catch(e){}busy=false}requestAnimationFrame(loop)};loop()}
 catch(e){msg.textContent=e&&e.name==='NotAllowedError'?'Camera permission was blocked. Allow the camera, or use the 6-digit code below.':'The camera could not start here (it may be blocked in this preview). Use the 6-digit code below.'}}
function stopCam(){S.stream?.getTracks().forEach(t=>t.stop());S.stream=null}

/* ---------- ADMIN ---------- */
function pageAdmin(){if(ss('adm')!=='1')return `<div class="wrap"><div class="gate"><span class="av" style="width:72px;height:72px;background:var(--lime);margin:0 auto">${ic('lock','width:30px;height:30px')}</span><h1 style="font-size:40px">Admin dashboard</h1><p class="muted">Enter the staff PIN. Demo PIN: <b>2468</b></p><form id="pinF" class="pinrow">${[0,1,2,3].map(i=>`<input inputmode="numeric" maxlength="1" aria-label="PIN digit ${i+1}" data-pin="${i}">`).join('')}</form><p class="err-t" id="pinE" hidden>Wrong PIN. Try 2468.</p></div></div>`;
 const alerts=allScans().filter(s=>!s.ok&&!(ls('rev')||[]).includes(s.sid)).length;
 return `<div class="wrap"><div class="adm"><nav class="side" aria-label="Admin">${[['overview','Overview','grid'],['checkins','Check-ins','list'],['members','Members','users'],['alerts','Alerts','alert']].map(t=>`<button type="button" data-at="${t[0]}" aria-pressed="${S.admTab===t[0]}">${ic(t[2])}${t[1]}${t[0]==='alerts'&&alerts?`<span class="c">${alerts}</span>`:''}</button>`).join('')}<button type="button" id="admOut" style="margin-top:10px">${ic('out')}Lock</button></nav><div id="admB"></div></div></div>`}
function bars(data,h=220,hi){const W=600,max=Math.max(...data.map(d=>d.v),1),bw=(W-40)/data.length;return `<svg class="bars" viewBox="0 0 ${W} ${h}" role="img" aria-label="Bar chart">${[0,.5,1].map(f=>`<line x1="34" x2="${W}" y1="${h-24-(h-44)*f}" y2="${h-24-(h-44)*f}" stroke="var(--line)"/><text x="28" y="${h-20-(h-44)*f}" text-anchor="end">${Math.round(max*f)}</text>`).join('')}${data.map((d,i)=>{const bh=(h-44)*d.v/max;return `<g><rect class="b ${d.hi?'t':''}" x="${40+i*bw+bw*.15}" y="${h-24-bh}" width="${bw*.7}" height="${Math.max(bh,1)}" rx="5"><title>${d.l}: ${d.v}</title></rect>${d.lab!==''?`<text x="${40+i*bw+bw/2}" y="${h-6}" text-anchor="middle">${d.lab??d.l}</text>`:''}</g>`}).join('')}</svg>`}
function drawAdmin(){const el=$('#admB');if(!el)return;const T=today(),V=visits(),A=allScans();const tab=S.admTab;
 const counts={active:0,expiring:0,expired:0,frozen:0};MEM.forEach(m=>counts[status(m)]++);
 if(tab==='overview'){const inT=new Set(V.filter(v=>dsOf(new Date(v.t))===T).map(v=>v.id)).size;const flT=A.filter(s=>!s.ok&&dsOf(new Date(s.t))===T).length;const exp30=MEM.filter(m=>status(m)==='expired'&&diffDays(T,m.exp)<=30).length;
  const d14=[...Array(14)].map((_,i)=>{const ds=addDs(T,i-13);return {l:fmtD(ds),lab:i%2?'':fmtD(ds,{day:'numeric'}),v:V.filter(v=>dsOf(new Date(v.t))===ds).length,hi:ds===T}});
  const hrs=[...Array(17)].map((_,i)=>{const h=6+i;return {l:`${pad(h)}:00`,lab:h%3===0?pad(h):'',v:V.filter(v=>dsOf(new Date(v.t))===T&&new Date(v.t).getHours()===h).length,hi:new Date().getHours()===h}});
  const exp=MEM.filter(m=>status(m)==='expiring').sort((a,b)=>a.exp.localeCompare(b.exp));
  el.innerHTML=`<div style="display:flex;justify-content:space-between;align-items:flex-end;gap:12px;flex-wrap:wrap;margin-bottom:16px"><div><span class="eyebrow">${fmtD(T,{weekday:'long',month:'long',day:'numeric'})}</span><h1 style="font-size:clamp(32px,3.6vw,48px);font-weight:900;margin-top:8px">Good ${new Date().getHours()<12?'morning':new Date().getHours()<18?'afternoon':'evening'}, front desk</h1></div><a class="btn lime" href="#scan">${ic('scan','width:16px;height:16px')}Open scanner</a></div>
  <div class="kpis"><button class="kpi lime" data-go="members:active"><span>Active members</span><b class="num">${counts.active+counts.expiring}</b><small>of ${MEM.length} in demo data</small></button><button class="kpi" data-go="checkins"><span>Checked in today</span><b class="num">${inT}</b><small>unique members</small></button><button class="kpi warn" data-go="members:expiring"><span>Expiring ≤ 7 days</span><b class="num">${counts.expiring}</b><small>send a reminder</small></button><button class="kpi bad" data-go="members:expired"><span>Expired (30 days)</span><b class="num">${exp30}</b><small>blocked at the gate</small></button><button class="kpi bad" data-go="alerts"><span>Flagged today</span><b class="num">${flT}</b><small>denied entries</small></button></div>
  <div class="a-row"><div class="card"><h3>Check-ins, last 14 days<span class="pill">${V.filter(v=>Date.now()-v.t<14*DAY).length} total</span></h3>${bars(d14)}</div><div class="card"><h3>Live feed<span class="pill ok"><i style="animation:pulse 1.6s infinite"></i>Live</span></h3><div class="feed" id="feed"></div></div></div>
  <div class="a-row"><div class="card"><h3>Today by hour</h3>${bars(hrs,190)}</div><div class="card"><h3>Expiring soon<button class="link" data-go="members:expiring">See all</button></h3><div class="hist">${exp.slice(0,6).map(m=>`<div class="hr" style="cursor:pointer" data-mem="${m.id}">${avatar(m).replace('class="av ','class="av " style="width:36px;height:36px;background:var(--lime);font-size:12px"')}<span class="g"><b>${esc(m.n)}</b><br><span class="muted">${PLANS[m.plan].n} · ${CLUBS[m.club].n}</span></span>${sPill(m)}</div>`).join('')||'<p class="muted">Nobody expires this week.</p>'}</div></div></div>`;
  drawFeed()}
 if(tab==='checkins'){const d=S.ciDate||T;el.innerHTML=`<h1 style="font-size:40px;font-weight:900;margin-bottom:16px">Check-ins</h1><div class="card"><div class="tbar"><label class="sr" for="ciD">Date</label><input class="input" type="date" id="ciD" value="${d}" max="${T}" style="max-width:190px"><label class="sr" for="ciQ">Search</label><input class="input" id="ciQ" placeholder="Search member or ID" value="${esc(S.ciQ||'')}"><select class="cur" id="ciC"><option value="">Both clubs</option>${Object.entries(CLUBS).map(([k,c])=>`<option value="${k}" ${S.ciC===k?'selected':''}>${c.n}</option>`).join('')}</select><select class="cur" id="ciR"><option value="">All results</option><option value="ok" ${S.ciR==='ok'?'selected':''}>Allowed</option><option value="bad" ${S.ciR==='bad'?'selected':''}>Denied</option></select><span style="flex:1"></span><button class="btn ink sm" id="csvB">${ic('dl','width:15px;height:15px')}Export CSV</button></div><div class="tw"><table class="tbl"><thead><tr><th>Time</th><th>Member</th><th>Plan</th><th>Club</th><th>Result</th></tr></thead><tbody id="ciBody"></tbody></table></div><p class="muted" id="ciN" style="margin-top:10px;font-size:13.5px"></p></div>`;
  const rows=()=>{const q=(S.ciQ||'').toLowerCase();return A.filter(s=>dsOf(new Date(s.t))===(S.ciDate||T)&&(!S.ciC||s.club===S.ciC)&&(!S.ciR||(S.ciR==='ok'?s.ok:!s.ok))&&(!q||(mem(s.id)?.n||'').toLowerCase().includes(q)||s.id.toLowerCase().includes(q))).reverse()};
  const draw=()=>{const l=rows();$('#ciBody').innerHTML=l.map(s=>{const m=mem(s.id);return `<tr class="cl2" data-mem="${s.id}"><td class="num">${fmtT(s.t)}</td><td><div class="who">${m?avatar(m):''}<div><b>${m?esc(m.n):esc(s.id)}</b><span>${esc(s.id)}</span></div></div></td><td>${m?PLANS[m.plan].n:'–'}</td><td>${CLUBS[s.club]?.n||'–'}</td><td>${s.ok?`<span class="pill ${s.lvl==='warn'?'warn':'ok'}">${s.src==='override'?'Override':'Allowed'}</span>`:`<span class="pill bad">${esc(s.why)}</span>`}</td></tr>`}).join('')||`<tr><td colspan="5" class="muted" style="padding:30px;text-align:center">No scans for this filter.</td></tr>`;$('#ciN').textContent=`${l.filter(s=>s.ok).length} allowed · ${l.filter(s=>!s.ok).length} denied`;bindMemRows(el)};draw();
  $('#ciD').onchange=e=>{S.ciDate=e.target.value||T;draw()};$('#ciQ').oninput=e=>{S.ciQ=e.target.value;draw()};$('#ciC').onchange=e=>{S.ciC=e.target.value;draw()};$('#ciR').onchange=e=>{S.ciR=e.target.value;draw()};
  $('#csvB').onclick=()=>{const q=v=>`"${String(v).replace(/"/g,'""')}"`;const csv=['Date,Time,Member ID,Name,Plan,Club,Result,Reason',...rows().reverse().map(s=>{const m=mem(s.id);return [dsOf(new Date(s.t)),fmtT(s.t),s.id,m?m.n:'',m?PLANS[m.plan].n:'',CLUBS[s.club]?.n||'',s.ok?'Allowed':'Denied',s.why||''].map(q).join(',')})].join('\n');saveFile(`forma-checkins-${S.ciDate||T}.csv`,csv)}}
 if(tab==='members'){el.innerHTML=`<h1 style="font-size:40px;font-weight:900;margin-bottom:16px">Members</h1><div class="card"><div class="tbar"><label class="sr" for="mq">Search</label><input class="input" id="mq" placeholder="Search name, email or ID" value="${esc(S.mq||'')}"><div class="sch-f">${[['all','All',MEM.length],['active','Active',counts.active],['expiring','Expiring',counts.expiring],['expired','Expired',counts.expired],['frozen','Frozen',counts.frozen]].map(f=>`<button class="chip" type="button" data-mf="${f[0]}" aria-pressed="${S.memF===f[0]}" style="height:36px;font-size:12.5px">${f[1]} · ${f[2]}</button>`).join('')}</div></div><div class="tw"><table class="tbl"><thead><tr><th>Member</th><th>Plan</th><th>Club</th><th>Expires</th><th>Status</th><th>Last visit</th><th>Visits 30d</th></tr></thead><tbody id="mBodyT"></tbody></table></div></div>`;
  const draw=()=>{const q=(S.mq||'').toLowerCase();const last={},c30={};V.forEach(v=>{last[v.id]=v.t;if(Date.now()-v.t<30*DAY)c30[v.id]=(c30[v.id]||0)+1});
   const l=MEM.filter(m=>(S.memF==='all'||status(m)===S.memF)&&(!q||m.n.toLowerCase().includes(q)||m.e.includes(q)||m.id.toLowerCase().includes(q))).sort((a,b)=>a.exp.localeCompare(b.exp));
   $('#mBodyT').innerHTML=l.map(m=>`<tr class="cl2" data-mem="${m.id}"><td><div class="who">${avatar(m)}<div><b>${esc(m.n)}</b><span>${m.id}</span></div></div></td><td>${PLANS[m.plan].n}</td><td>${CLUBS[m.club].n}</td><td class="num">${fmtD(m.exp,{month:'short',day:'numeric',year:'2-digit'})}</td><td>${sPill(m)}</td><td class="num">${last[m.id]?fmtD(dsOf(new Date(last[m.id]))):'–'}</td><td class="num">${c30[m.id]||0}</td></tr>`).join('')||`<tr><td colspan="7" class="muted" style="padding:30px;text-align:center">No members match.</td></tr>`;bindMemRows(el)};draw();
  $('#mq').oninput=e=>{S.mq=e.target.value;draw()};$$('[data-mf]',el).forEach(b=>b.onclick=()=>{S.memF=b.dataset.mf;$$('[data-mf]',el).forEach(x=>x.setAttribute('aria-pressed',x===b));draw()})}
 if(tab==='alerts'){const rev=ls('rev')||[];const l=A.filter(s=>!s.ok).reverse();el.innerHTML=`<h1 style="font-size:40px;font-weight:900;margin-bottom:6px">Alerts</h1><p class="muted" style="margin-bottom:16px">Every denied entry is logged here so you can follow up on screenshots, shared cards and expired memberships.</p><div class="card"><div class="hist">${l.map(s=>{const m=mem(s.id);const r=rev.includes(s.sid);return `<div class="hr" style="${r?'opacity:.55':''}"><span class="d" style="width:auto;min-width:70px;text-align:left"><b class="num">${fmtT(s.t)}</b><small>${fmtD(dsOf(new Date(s.t)))}</small></span><span class="g"><b>${m?esc(m.n):esc(s.id)}</b> <span class="muted">${esc(s.id)}</span><br><span class="pill bad" style="margin-top:4px">${ic('alert','width:13px;height:13px')}${esc(s.why)}</span></span>${m?`<button class="btn ghost sm" data-mem="${m.id}">Member</button>`:''}${r?'<span class="pill">Reviewed</span>':`<button class="btn ink sm" data-rev="${s.sid}">Mark reviewed</button>`}</div>`}).join('')||'<p class="muted">No alerts.</p>'}</div></div>`;
  $$('[data-rev]',el).forEach(b=>b.onclick=()=>{const r=ls('rev')||[];r.push(b.dataset.rev);ls('rev',r);render('admin')});bindMemRows(el)}
 $$('[data-go]',el).forEach(b=>b.onclick=()=>{const [t,f]=b.dataset.go.split(':');S.admTab=t;if(f)S.memF=f;$$('[data-at]').forEach(x=>x.setAttribute('aria-pressed',x.dataset.at===t));drawAdmin()});bindMemRows(el)}
function drawFeed(){const el=$('#feed');if(!el)return;el.innerHTML=allScans().slice(-12).reverse().map(s=>{const m=mem(s.id);return `<div data-mem="${s.id}" style="cursor:pointer">${m?avatar(m):''}<span><b>${m?esc(m.n.split(' ')[0]+(m.n.split(' ')[1]?' '+m.n.split(' ')[1][0]+'.':'')):esc(s.id)}</b> ${s.ok?`<span class="muted">checked in · ${CLUBS[s.club]?.n}</span>`:`<span style="color:var(--bad);font-weight:600">denied · ${esc(s.why.split('(')[0])}</span>`}</span><time>${dsOf(new Date(s.t))===today()?fmtT(s.t):fmtD(dsOf(new Date(s.t)))}</time></div>`}).join('');bindMemRows(el)}
function bindMemRows(root){$$('[data-mem]',root).forEach(r=>r.onclick=()=>openMember(r.dataset.mem))}
function openMember(id){const m=mem(id);if(!m)return;closeModal();const V=visits().filter(v=>v.id===id),F=allScans().filter(s=>s.id===id&&!s.ok);const T=today();
 let heat=['M','T','W','T','F','S','S'].map(d=>`<i class="dw">${d}</i>`).join('');const start=addDs(monday(),-28);const by={};V.forEach(v=>{const d=dsOf(new Date(v.t));by[d]=(by[d]||0)+1});for(let i=0;i<35;i++){const ds=addDs(start,i);const n=by[ds]||0;heat+=`<i class="${n>1?'two':n?'on':''} ${ds===T?'td':''}" title="${fmtD(ds)}: ${n}" style="${ds>T?'opacity:.3':''}"></i>`}
 const sc=document.createElement('div');sc.className='scrim';sc.onclick=closeModal;document.body.appendChild(sc);const d=document.createElement('aside');d.className='drawer';d.setAttribute('role','dialog');d.setAttribute('aria-label',m.n);
 d.innerHTML=`<button class="x" style="position:absolute;right:16px;top:16px;width:40px;height:40px;border-radius:50%;border:0;background:var(--mist);display:grid;place-items:center" aria-label="Close">${ic('x')}</button><div class="dr-h">${avatar(m)}<div><b>${esc(m.n)}</b><span class="muted">${m.id} · ${CLUBS[m.club].n}</span><div style="margin-top:6px">${sPill(m)}</div></div></div>
 <div class="kv" style="font-size:14.5px"><span class="muted">Plan</span><b>${PLANS[m.plan].n}</b><span class="muted">Expires</span><b>${fmtD(m.exp,{weekday:'short',month:'short',day:'numeric',year:'numeric'})}</b><span class="muted">Email</span><b style="word-break:break-all">${esc(m.e)}</b><span class="muted">Mobile</span><b>${esc(m.tel)}</b><span class="muted">Member since</span><b>${fmtD(m.joined,{month:'short',year:'numeric'})}</b></div>
 <div><b style="display:block;margin-bottom:8px">Extend membership</b><div class="acts">${[[1,'+1 month'],[3,'+3 months'],[12,'+12 months']].map(x=>`<button class="btn sm ghost" data-ex="${x[0]}">${x[1]}</button>`).join('')}</div></div>
 <div class="acts"><button class="btn sm ${m.frozen?'ink':'ghost'}" id="frz">${ic('snow','width:15px;height:15px')}${m.frozen?'Unfreeze':'Freeze 14 days'}</button><a class="btn sm ghost" href="mailto:${esc(m.e)}?subject=${encodeURIComponent('Your FORMA membership')}&body=${encodeURIComponent(`Hi ${m.n.split(' ')[0]},\n\nYour FORMA ${PLANS[m.plan].n} membership ${status(m)==='expired'?'expired':'expires'} on ${fmtD(m.exp,{month:'long',day:'numeric'})}. Renew in the member area or at the front desk.\n\nSee you soon,\nFORMA ${CLUBS[m.club].n}`)}">${ic('mail','width:15px;height:15px')}Email reminder</a><a class="btn sm ghost" href="https://wa.me/${m.tel.replace(/\D/g,'')}?text=${encodeURIComponent(`Hi ${m.n.split(' ')[0]}, your FORMA membership ${status(m)==='expired'?'expired':'expires'} on ${fmtD(m.exp,{month:'long',day:'numeric'})}. Renew in the app or at the desk.`)}" target="_blank" rel="noopener">WhatsApp</a></div>
 <div><b style="display:block;margin-bottom:8px">Last 5 weeks · ${V.filter(v=>Date.now()-v.t<35*DAY).length} visits</b><div class="heat" style="max-width:none">${heat}</div></div>
 <div><b style="display:block;margin-bottom:8px">Recent activity</b><div class="hist">${allScans().filter(s=>s.id===id).slice(-8).reverse().map(s=>`<div class="hr" style="padding:9px 12px"><span class="g">${fmtDT(s.t)}</span>${s.ok?`<span class="pill ok">Allowed</span>`:`<span class="pill bad" title="${esc(s.why)}">Denied</span>`}</div>`).join('')||'<p class="muted">No visits yet.</p>'}</div>${F.length?`<p class="err-t" style="margin-top:8px">${F.length} denied attempt${F.length>1?'s':''} on record.</p>`:''}</div>`;
 document.body.appendChild(d);d.querySelector('.x').focus();d.querySelector('.x').onclick=closeModal;
 $$('[data-ex]',d).forEach(b=>b.onclick=()=>{const base=status(m)==='expired'?today():m.exp;const x=parseDs(base);x.setMonth(x.getMonth()+ +b.dataset.ex);patchMember(id,{exp:dsOf(x)});toast(`${m.n.split(' ')[0]} extended to ${fmtD(dsOf(x),{month:'short',day:'numeric',year:'numeric'})}`);drawAdmin();openMember(id)});
 $('#frz',d).onclick=()=>{patchMember(id,m.frozen?{frozen:0}:{frozen:1,exp:addDs(m.exp,14)});toast(m.frozen?'Unfrozen':'Frozen for 14 days');drawAdmin();openMember(id)}}
function bindAdmin(){if(ss('adm')!=='1'){const ins=$$('[data-pin]');ins[0].focus();ins.forEach((inp,i)=>{inp.oninput=()=>{inp.value=inp.value.replace(/\D/g,'').slice(-1);if(inp.value&&i<3)ins[i+1].focus();const v=ins.map(x=>x.value).join('');if(v.length===4){if(v==='2468'){ss('adm','1');render('admin')}else{$('#pinF').classList.add('shake');$('#pinE').hidden=false;setTimeout(()=>{$('#pinF').classList.remove('shake');ins.forEach(x=>x.value='');ins[0].focus()},450)}}};inp.onkeydown=e=>{if(e.key==='Backspace'&&!inp.value&&i)ins[i-1].focus()}});return}
 $$('[data-at]').forEach(b=>b.onclick=()=>{S.admTab=b.dataset.at;$$('[data-at]').forEach(x=>x.setAttribute('aria-pressed',x===b));drawAdmin()});
 $('#admOut').onclick=()=>{ss('adm','0');render('admin')};drawAdmin();
 S.onStore=()=>{if(S.admTab==='overview')drawAdmin();else drawFeed()}}

/* ---------- motion ---------- */
let io;
function initReveal(){io?.disconnect();io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');io.unobserve(e.target)}}),{threshold:.12,rootMargin:'0px 0px -5% 0px'});$$('.rv').forEach(el=>RM?el.classList.add('in'):io.observe(el))}
let ticking=false;
function frame(){ticking=false;const y=scrollY,vh=innerHeight;$('#nav')?.classList.toggle('small',y>40);if(RM)return;
 const a=$('.athlete[data-par]');if(a)a.style.transform=`translateY(${(y*+a.dataset.par).toFixed(1)}px)`;
 const ck=$('#checkin');if(ck){const r=ck.getBoundingClientRect();if(r.bottom>0&&r.top<vh){const p=(vh-r.top)/(vh+r.height);$('#big1').style.transform=`translateX(${(-p*40).toFixed(2)}%)`;$('#big2').style.transform=`translateX(${(-30+p*30).toFixed(2)}%)`}}}
addEventListener('scroll',()=>{if(!ticking){ticking=true;requestAnimationFrame(frame)}},{passive:true});
addEventListener('storage',e=>{if(!e.key||!e.key.startsWith('fm_'))return;loadMembers();S.onStore&&S.onStore();if(S.page==='scan')drawLog()});

/* ---------- router ---------- */
const JUMPS=['coaches','plans','recovery','schedule','checkin','faq','programs'];
function route(){let h=(location.hash||'#home').slice(1)||'home';closeModal();$('#mm')?.classList.remove('open');
 if(JUMPS.includes(h)){const was=S.page==='home';if(!was)render('home');document.getElementById(h)?.scrollIntoView({behavior:was?'smooth':'instant',block:'start'});return}
 render(h);scrollTo(0,0)}
function render(h){S.timers.forEach(clearInterval);S.timers=[];S.onStore=null;if(h!=='scan')stopCam();loadMembers();
 let body,bind,cur=h,mode='';
 if(h==='classes'){body=pageClasses();bind=bindClasses}
 else if(h==='join'){body=pageJoin();bind=bindJoin}
 else if(h==='member'){body=pageMember();bind=bindMember}
 else if(h==='scan'){body=pageScan();bind=bindScan;mode='scan'}
 else if(h==='admin'){body=pageAdmin();bind=bindAdmin;mode='admin'}
 else if(h==='journal'){body=pageJournal();bind=bindJournal}
 else if(h.startsWith('article-')&&art(h.slice(8))){const a=art(h.slice(8));body=pageArticle(a);cur='journal'}
 else{h='home';cur='home';body=pageHome();bind=bindHome}
 S.page=h;document.title=({classes:'Classes',join:'Join',member:'Member area',scan:'Front desk',admin:'Admin',journal:'Journal'}[h]||'')+(h==='home'?'FORMA · Fitness & Recovery Club':' · FORMA');
 mount(cur,body,mode);bind&&bind();
 $$('[data-f]').forEach(a=>a.addEventListener('click',()=>{S.fil=a.dataset.f}));
 initReveal();frame()}
addEventListener('hashchange',route);
document.addEventListener('click',e=>{const a=e.target.closest('a[href^="#"]');if(!a)return;const h=a.getAttribute('href').slice(1);if(location.hash==='#'+h){e.preventDefault();route()}});
route();
})();
