(()=>{
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const ic=(n,st='')=>`<svg class="i"${st?` style="${st}"`:''}><use href="#i-${n}"/></svg>`;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ls=(k,v)=>{try{if(v===undefined)return JSON.parse(localStorage.getItem('au_'+k));localStorage.setItem('au_'+k,JSON.stringify(v))}catch(e){return null}};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const hash=s=>{let h=2166136261;for(const c of String(s))h=Math.imul(h^c.charCodeAt(0),16777619);return h>>>0};
const rng=seed=>()=>{seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296};
const ph=(k,alt='',pos='',cls='')=>`<div class="ph ${cls}">${k?`<img src="photos/${k}.jpg" alt="${esc(alt)}" loading="lazy"${pos?` style="object-position:${pos}"`:''} onerror="this.remove()">`:''}</div>`;
const RM=matchMedia('(prefers-reduced-motion:reduce)').matches;
const pad=n=>String(n).padStart(2,'0');
const dsOf=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const addDs=(ds,n)=>{const [y,m,d]=ds.split('-').map(Number);const x=new Date(y,m-1,d);x.setDate(x.getDate()+n);return dsOf(x)};
const fmtD=(ds,o={weekday:'short',month:'short',day:'numeric'})=>{const [y,m,d]=ds.split('-').map(Number);return new Date(y,m-1,d).toLocaleDateString('en-US',o)};

/* ---------- money ---------- */
const TOUSD={USD:1,AUD:.658,EUR:1.087};
const SYM={USD:['en-US','USD'],AUD:['en-US','AUD'],EUR:['en-IE','EUR']};
function price(v,cur,o={}){const to=S.cur==='local'?cur:S.cur;const val=v*TOUSD[cur]/TOUSD[to];return new Intl.NumberFormat(SYM[to][0],{style:'currency',currency:to,maximumFractionDigits:o.compact?1:0,notation:o.compact?'compact':'standard'}).format(val)}
const usd=p=>p.price*TOUSD[p.cur];
const pLabel=(p,o={})=>price(p.price,p.cur,o)+(p.st==='rent'?(o.compact?'/mo':' / month'):'');

/* ---------- data ---------- */
const CITY={syd:{n:'Sydney',cur:'AUD',c:'Australia',areas:{'Elizabeth Bay':[560,200],'Bronte':[860,520],'Paddington':[610,380],'Surry Hills':[470,410],'Pyrmont':[300,260],'Mosman':[640,90]}},
 la:{n:'Los Angeles',cur:'USD',c:'California',areas:{'Hollywood Hills':[560,150],'Venice':[230,520],'Malibu':[110,230],'Silver Lake':[720,260],'Beverly Crest':[420,200],'Downtown':[800,420]}},
 lis:{n:'Lisbon',cur:'EUR',c:'Portugal',areas:{'Chiado':[520,420],'Cascais':[90,520],'Restelo':[330,440],'Parque das Nações':[720,230],'Avenidas Novas':[500,170],'Comporta':[870,610]}}};
const TYPES=['House','Villa','Apartment','Penthouse'];
const L=[
 {id:'harbour-crest',t:'Harbour Crest Penthouse',city:'syd',area:'Elizabeth Bay',type:'Penthouse',st:'sale',price:6850000,bd:3,ba:3,m2:245,yr:2021,img:['a5','l5','b1','t2','k2'],feat:['view','terrace','parking','concierge'],tags:['Harbour view'],d:'A full-floor penthouse with 270° harbour views, a wraparound terrace and a private lift. Oak floors, travertine bathrooms and a chef’s kitchen by Gaggenau.',x:545,y:215,ag:'olivia'},
 {id:'bronte-cliff',t:'Bronte Cliff House',city:'syd',area:'Bronte',type:'House',st:'sale',price:9400000,bd:5,ba:4,m2:480,yr:2019,img:['e10','v2','l4','k2','b3'],feat:['pool','view','garden','parking'],tags:['Ocean view','Pool'],d:'Architect-designed family home stepping down the cliff to an infinity pool above Bronte Beach. Five bedrooms, a cinema and a two-car garage.',x:850,y:505,ag:'james'},
 {id:'paddington-terrace',t:'Paddington Courtyard House',city:'syd',area:'Paddington',type:'House',st:'sale',price:3250000,bd:4,ba:2,m2:210,yr:2018,img:['e8','l1','k1','b2','t1'],feat:['garden','parking'],tags:['Reduced'],d:'A new-build courtyard house behind a brick-and-timber facade, with a north-facing garden, a rooftop study and parking off the lane.',x:600,y:370,ag:'olivia'},
 {id:'surry-loft',t:'Surry Hills Warehouse Loft',city:'syd',area:'Surry Hills',type:'Apartment',st:'rent',price:6200,bd:2,ba:2,m2:118,yr:2012,img:['l6','k3','b5','t1'],feat:['parking','gym'],tags:['Available now'],d:'Converted warehouse loft with 4-metre ceilings, exposed brick and a secure car space. Walk to Crown Street cafés.',x:475,y:420,ag:'james'},
 {id:'solenne-2204',t:'Solenne Residences · 2204',city:'syd',area:'Pyrmont',type:'Apartment',st:'offplan',price:2890000,bd:2,ba:2,m2:128,yr:2027,img:['a1','l3','b4','t3'],feat:['view','concierge','gym','pool'],tags:['Off-plan','Completion 2027'],d:'A 22nd-floor corner residence in Solenne, our new harbourside tower. Floor-to-ceiling glass, a winter garden and resort amenities.',x:300,y:255,ag:'olivia',dev:'solenne'},
 {id:'mosman-garden',t:'Mosman Garden Villa',city:'syd',area:'Mosman',type:'Villa',st:'sale',price:7200000,bd:5,ba:5,m2:520,yr:2016,img:['v6','e11','l7','k4','b1'],feat:['pool','garden','parking','view'],tags:['Pool'],d:'A private villa on 1,100 m² of landscaped gardens with a 20-metre pool, pool house and glimpses of Balmoral Beach.',x:650,y:95,ag:'james'},
 {id:'canyon-glass',t:'Canyon Glass House',city:'la',area:'Hollywood Hills',type:'House',st:'sale',price:8950000,bd:4,ba:5,m2:410,yr:2020,img:['e1','v3','l2','b3','k5'],feat:['pool','view','parking','smart'],tags:['City view','Pool'],d:'A glass-and-steel home cantilevered over the canyon with sunset views to the ocean, a zero-edge pool and a wine room.',x:565,y:160,ag:'mia'},
 {id:'venice-modern',t:'Venice Modern',city:'la',area:'Venice',type:'House',st:'sale',price:4275000,bd:3,ba:3,m2:265,yr:2018,img:['e5','l8','k5','t4','b2'],feat:['garden','smart','parking'],tags:['New'],d:'Three blocks from the beach, a light-filled modern home with a roof deck, pivot doors and a drought-tolerant garden.',x:235,y:510,ag:'ethan'},
 {id:'malibu-point',t:'Malibu Point Villa',city:'la',area:'Malibu',type:'Villa',st:'sale',price:14500000,bd:6,ba:7,m2:720,yr:2017,img:['v1','e9','l5','b1','t2'],feat:['pool','view','garden','parking','smart'],tags:['Ocean view','Pool'],d:'An ocean-front estate on the Point with a 25-metre pool, guest house and private beach access.',x:115,y:235,ag:'mia'},
 {id:'silverlake-studio',t:'Silver Lake Studio House',city:'la',area:'Silver Lake',type:'House',st:'rent',price:9800,bd:3,ba:2,m2:190,yr:2015,img:['e12','l6','k1','b2'],feat:['garden','parking'],tags:['Furnished'],d:'A furnished mid-century-inspired house with a studio above the garage and views over the reservoir.',x:715,y:265,ag:'ethan'},
 {id:'marlowe-7',t:'Marlowe Canyon · Residence 7',city:'la',area:'Beverly Crest',type:'House',st:'offplan',price:3650000,bd:4,ba:4,m2:300,yr:2027,img:['e2','e4','l4','k3'],feat:['pool','garden','smart','parking'],tags:['Off-plan','12 homes'],d:'One of twelve modern homes in Marlowe Canyon, a gated enclave with shared gardens, a clubhouse and 24-hour security.',x:420,y:205,ag:'mia',dev:'marlowe'},
 {id:'dtla-sky',t:'Downtown Sky Apartment',city:'la',area:'Downtown',type:'Apartment',st:'rent',price:7400,bd:2,ba:2,m2:125,yr:2022,img:['a2','l3','b5','t1'],feat:['view','gym','pool','concierge'],tags:['Skyline view'],d:'A 38th-floor apartment with skyline views, a rooftop pool and 24-hour concierge.',x:805,y:425,ag:'ethan'},
 {id:'chiado-atelier',t:'Chiado Atelier',city:'lis',area:'Chiado',type:'Apartment',st:'sale',price:1480000,bd:3,ba:2,m2:165,yr:1910,img:['a6','l1','k2','b4'],feat:['heritage','view','lift'],tags:['River glimpse'],d:'A renovated Pombaline apartment with 4-metre ceilings, azulejo details and a balcony with river glimpses.',x:520,y:430,ag:'ines'},
 {id:'cascais-villa',t:'Cascais Ocean Villa',city:'lis',area:'Cascais',type:'Villa',st:'sale',price:5900000,bd:5,ba:6,m2:560,yr:2020,img:['v4','v5','l7','t2','b3'],feat:['pool','view','garden','parking'],tags:['Ocean view','Pool'],d:'A contemporary villa above the Atlantic with a heated infinity pool, sauna and landscaped terraces.',x:95,y:520,ag:'tomas'},
 {id:'restelo-house',t:'Restelo Pool House',city:'lis',area:'Restelo',type:'House',st:'sale',price:2650000,bd:4,ba:4,m2:290,yr:2019,img:['e7','l2','k4','b3'],feat:['pool','garden','view'],tags:['Pool'],d:'A contemporary family house above Belém with a lap pool, sun terraces and river views from every bedroom.',x:335,y:445,ag:'ines'},
 {id:'nacoes-river',t:'Parque das Nações River Flat',city:'lis',area:'Parque das Nações',type:'Apartment',st:'rent',price:3900,bd:2,ba:1,m2:92,yr:2016,img:['a3','l8','b2','t3'],feat:['view','terrace'],tags:['River view'],d:'A top-floor flat in a white riverside tower, with a terrace over the Tagus and the marina.',x:715,y:240,ag:'tomas'},
 {id:'casa-alba-5b',t:'Casa Alba · 5B',city:'lis',area:'Avenidas Novas',type:'Apartment',st:'offplan',price:1120000,bd:2,ba:2,m2:112,yr:2026,img:['a4','l3','k5','b5'],feat:['terrace','gym','concierge'],tags:['Off-plan','Completion 2026'],d:'A fifth-floor residence in Casa Alba, a boutique building of 36 homes with planted terraces and a rooftop garden.',x:500,y:175,ag:'ines',dev:'alba'},
 {id:'comporta-retreat',t:'Comporta Retreat',city:'lis',area:'Comporta',type:'Villa',st:'sale',price:3400000,bd:4,ba:4,m2:340,yr:2021,img:['v7','e3','l4','k1'],feat:['pool','garden','view'],tags:['Rice-field view'],d:'A timber and lime-rendered retreat among the rice fields, ten minutes from the dunes.',x:870,y:600,ag:'tomas'}];
L.forEach(p=>p.cur=CITY[p.city].cur);
const lst=id=>L.find(x=>x.id===id);
const FEAT={pool:['pool','Pool'],view:['wave','Views'],garden:['leaf','Garden'],parking:['car','Parking'],terrace:['sun','Terrace'],concierge:['bell','Concierge'],gym:['gym','Gym'],smart:['shield','Smart home'],heritage:['key','Heritage'],lift:['key','Lift']};
const AG=[{id:'olivia',n:'Olivia Hart',r:'Director, Sydney',city:'syd',img:'g1',tel:'+61 2 5550 1402',yrs:14},{id:'james',n:'James Cole',r:'Senior agent, Eastern Suburbs',city:'syd',img:'g2',tel:'+61 2 5550 1488',yrs:9},
 {id:'mia',n:'Mia Sanders',r:'Director, Los Angeles',city:'la',img:'g3',tel:'+1 (310) 555-0142',yrs:12},{id:'ethan',n:'Ethan Brooks',r:'Agent, Westside & Downtown',city:'la',img:'g4',tel:'+1 (310) 555-0177',yrs:7},
 {id:'ines',n:'Inês Duarte',r:'Director, Lisbon',city:'lis',img:'g5',tel:'+351 21 555 0192',yrs:11},{id:'tomas',n:'Tomás Reis',r:'Agent, Coast & Comporta',city:'lis',img:'g6',tel:'+351 21 555 0164',yrs:8},
 {id:'sara',n:'Sara Lopes',r:'New developments, Lisbon',city:'lis',img:'g7',tel:'+351 21 555 0133',yrs:6},{id:'daniel',n:'Daniel Whitmore',r:'New developments, Sydney',city:'syd',img:'g8',tel:'+61 2 5550 1455',yrs:10}];
const ag=id=>AG.find(a=>a.id===id);
const DEV=[{s:'solenne',n:'Solenne Residences',city:'syd',area:'Pyrmont',img:['a1','l3','b4','t3','l5'],floors:14,top:26,units:4,from:1650000,done:'Q3 2027',beds:[1,2,2,3],m2:[68,112,128,186],tag:'Harbourside tower · 56 residences',d:'A slender tower on the Pyrmont foreshore with winter gardens, a 25-metre lap pool and a residents’ club overlooking the harbour.',am:['25 m lap pool','Residents’ club','Concierge 24/7','Wellness studio','Winter gardens','EV parking']},
 {s:'marlowe',n:'Marlowe Canyon',city:'la',area:'Beverly Crest',img:['e2','e4','l4','k3','v3'],floors:3,top:3,units:4,from:3150000,done:'Q1 2027',beds:[3,4,4,5],m2:[240,300,310,380],tag:'Gated enclave · 12 homes',d:'Twelve modern homes around shared native gardens, with a clubhouse, fitness pavilion and 24-hour security in the canyon.',am:['Private pools','Clubhouse','Gated & staffed','Native gardens','Solar & batteries','Two-car garages']},
 {s:'alba',n:'Casa Alba',city:'lis',area:'Avenidas Novas',img:['a4','a5','l3','k5','b5'],floors:9,top:9,units:4,from:690000,done:'Q4 2026',beds:[1,2,2,3],m2:[62,98,112,150],tag:'Boutique building · 36 homes',d:'A calm, planted building of 36 homes near Gulbenkian gardens, with deep terraces, a rooftop garden and a residents’ library.',am:['Rooftop garden','Residents’ library','Concierge','Bike storage','Planted terraces','Private parking']}];
const dev=s=>DEV.find(d=>d.s===s);

/* ---------- state ---------- */
const S={cur:ls('cur')||'local',fav:new Set(ls('fav')||[]),cmp:[],page:'',timers:[],
 f:{mode:'buy',city:'all',types:[],beds:0,baths:0,min:0,max:0,feats:[],sort:'feat'},view:'grid',mapCity:'syd',hlId:null,demoOff:0,unitSel:null,bedsF:0};
const saveFav=()=>{ls('fav',[...S.fav]);$$('.favn').forEach(n=>{n.textContent=S.fav.size;n.hidden=!S.fav.size})};
function toast(m,i='check'){const t=document.createElement('div');t.className='toast';t.innerHTML=ic(i)+esc(m);$('#toasts').appendChild(t);setTimeout(()=>{t.style.transition='opacity .3s';t.style.opacity=0;setTimeout(()=>t.remove(),300)},3000)}
const timer=(fn,ms)=>{const t=setInterval(fn,ms);S.timers.push(t);return t};

/* ---------- map ---------- */
function mapSVG(city,dark){const R=rng(hash(city+'map'));const C=dark?{land:'#1B1E24',minor:'#252930',major:'#353B46',water:'#0D1014',park:'#1E2923',lab:'#6E6A63'}:{land:'#EFE8DD',minor:'#FBF8F3',major:'#FFFFFF',water:'#C9DBE3',park:'#DCE4CD',lab:'#A0968A'};
 let s=`<svg viewBox="0 0 1000 700" preserveAspectRatio="none" aria-hidden="true"><rect width="1000" height="700" fill="${C.land}"/>`;
 const ang=R()*30-15;s+=`<g transform="rotate(${ang} 500 350)" stroke="${C.minor}" stroke-width="3">`;for(let i=-200;i<1200;i+=38+R()*14)s+=`<line x1="${i}" y1="-300" x2="${i+R()*40-20}" y2="1000"/>`;for(let j=-300;j<1000;j+=36+R()*14)s+=`<line x1="-300" y1="${j}" x2="1300" y2="${j+R()*40-20}"/>`;s+='</g>';
 for(let i=0;i<6;i++){const x=R()*1000,y=R()*700,w=40+R()*110,h=30+R()*80;s+=`<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="${10+R()*20}" fill="${C.park}" transform="rotate(${R()*40-20} ${x} ${y})"/>`}
 s+=`<g stroke="${C.major}" stroke-width="7" fill="none" stroke-linecap="round">`;for(let i=0;i<7;i++){const y1=R()*700,y2=R()*700;s+=`<path d="M-20 ${y1} C ${300+R()*200} ${y1+R()*200-100}, ${500+R()*200} ${y2+R()*200-100}, 1020 ${y2}"/>`}for(let i=0;i<5;i++){const x1=R()*1000,x2=R()*1000;s+=`<path d="M${x1} -20 C ${x1+R()*160-80} 250, ${x2+R()*160-80} 450, ${x2} 720"/>`}s+='</g>';
 const W={syd:`M0 0H1000V60C900 80 860 120 800 110S700 60 640 140 540 150 480 190 380 170 330 200 240 190 180 160 90 150 0 170Z M930 0H1000V700H960C940 620 900 560 920 480S960 360 940 260 950 120 930 0Z`,
  la:`M0 0H150C120 80 170 160 130 240S60 360 110 440 200 560 180 700H0Z`,
  lis:`M0 700V560C120 520 220 560 330 520S520 470 620 500 820 470 1000 520V700Z`}[city];
 s+=`<path d="${W}" fill="${C.water}"/>`;
 Object.entries(CITY[city].areas).forEach(([n,[x,y]])=>s+=`<text x="${x}" y="${y+46}" text-anchor="middle" fill="${C.lab}" font-size="15" font-family="Instrument Sans,sans-serif" letter-spacing="2" style="text-transform:uppercase">${n.toUpperCase()}</text>`);
 return s+'</svg>'}
function mountMap(el,{city,dark,items,onPin,hover}){const st={z:1,x:0,y:0};el.classList.toggle('lt',!dark);
 el.innerHTML=`<div class="lyr">${mapSVG(city,dark)}${items.map((p,i)=>`<button class="pin" data-pid="${p.id}" style="left:${p.x/10}%;top:${p.y/7}%;--d:${i*.05}s" aria-label="${esc(p.t)}, ${esc(pLabel(p))}">${esc(pLabel(p,{compact:1}))}</button>`).join('')}</div><div class="ctl"><button type="button" data-z="1" aria-label="Zoom in">+</button><button type="button" data-z="-1" aria-label="Zoom out">−</button></div><span class="note">Illustrative map · ${CITY[city].n}</span>`;
 const lyr=$('.lyr',el);const apply=()=>{const W=el.clientWidth,H=el.clientHeight;st.x=clamp(st.x,W-W*st.z,0);st.y=clamp(st.y,H-H*st.z,0);lyr.style.transform=`translate(${st.x}px,${st.y}px) scale(${st.z})`;lyr.style.setProperty('--ps',(1/st.z).toFixed(3));$$('.pin',lyr).forEach(p=>p.style.setProperty('--ps',(1/st.z).toFixed(3)))};
 const zoom=(dz,cx=el.clientWidth/2,cy=el.clientHeight/2)=>{const nz=clamp(st.z*(dz>0?1.35:1/1.35),1,4);st.x=cx-(cx-st.x)*nz/st.z;st.y=cy-(cy-st.y)*nz/st.z;st.z=nz;apply()};
 $$('[data-z]',el).forEach(b=>b.onclick=e=>{e.stopPropagation();zoom(+b.dataset.z)});
 el.onwheel=e=>{if(!e.ctrlKey&&!el.matches(':hover'))return;e.preventDefault();const r=el.getBoundingClientRect();zoom(-e.deltaY,e.clientX-r.left,e.clientY-r.top)};
 let drag=null,moved=0;el.onpointerdown=e=>{if(e.target.closest('.ctl,.mcard'))return;drag={x:e.clientX,y:e.clientY,sx:st.x,sy:st.y};moved=0;el.setPointerCapture(e.pointerId)};
 el.onpointermove=e=>{if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;moved=Math.abs(dx)+Math.abs(dy);st.x=drag.sx+dx;st.y=drag.sy+dy;apply()};
 el.onpointerup=e=>{const d=drag;drag=null;if(d&&moved<5){const pin=document.elementFromPoint(e.clientX,e.clientY)?.closest('.pin');if(pin&&el.contains(pin))onPin&&onPin(lst(pin.dataset.pid),pin);else if(!e.target.closest('.mcard'))$('.mcard',el)?.remove()}};
 if(hover)$$('.pin',el).forEach(p=>{p.onmouseenter=()=>hover(p.dataset.pid,1);p.onmouseleave=()=>hover(p.dataset.pid,0)});
 apply();return {focus(id){const p=lst(id);if(!p)return;st.z=Math.max(st.z,1.6);const W=el.clientWidth,H=el.clientHeight;st.x=W/2-p.x/1000*W*st.z;st.y=H/2-p.y/700*H*st.z;lyr.style.transition='transform .6s cubic-bezier(.2,.8,.2,1)';apply();setTimeout(()=>lyr.style.transition='',650)}}}
function pinCard(el,p,pin){$('.mcard',el)?.remove();const r=el.getBoundingClientRect(),pr=pin.getBoundingClientRect();const c=document.createElement('a');c.className='mcard';c.href='#p-'+p.id;
 c.innerHTML=`<button class="x" type="button" aria-label="Close">${ic('x','width:14px;height:14px')}</button>${ph(p.img[0],p.t)}<div class="b"><b>${esc(p.t)}</b><span>${esc(p.area)} · ${p.bd} bd · ${p.m2} m²</span><div style="font-weight:700;margin-top:4px">${pLabel(p)}</div></div>`;
 let left=pr.left-r.left+pr.width/2-135,top=pr.top-r.top-270;if(top<10)top=pr.bottom-r.top+10;c.style.left=clamp(left,10,r.width-280)+'px';c.style.top=clamp(top,10,r.height-270)+'px';el.appendChild(c);
 $('.x',c).onclick=e=>{e.preventDefault();e.stopPropagation();c.remove()};$$('.pin',el).forEach(x=>x.classList.toggle('on',x===pin))}

/* ---------- shell ---------- */
function nav(cur){const A=(h,t)=>`<a href="#${h}" ${cur===h?'aria-current="page"':''}>${t}</a>`;
 return `<header class="nav ${cur==='home'||/^dev-/.test(location.hash.slice(1))?'onhero':''}" id="nav"><div class="bar"><a class="logo" href="#home" aria-label="Aurelle Estates home"><b>Aurelle</b><i></i></a>
 <nav class="nl" aria-label="Main">${A('buy','Buy')}${A('rent','Rent')}${A('new','New developments')}${A('sell','Sell')}${A('agents','Agents')}</nav><span class="sp"></span>
 <label class="sr" for="curSel">Currency</label><select class="cur" id="curSel">${[['local','Local'],['USD','USD $'],['AUD','AUD A$'],['EUR','EUR €']].map(c=>`<option value="${c[0]}" ${S.cur===c[0]?'selected':''}>${c[1]}</option>`).join('')}</select>
 <a class="ib" href="#saved" aria-label="Saved homes" style="margin-left:6px">${ic('heart')}<span class="n num favn" ${S.fav.size?'':'hidden'}>${S.fav.size}</span></a>
 <a class="btn em bk" href="#buy">Find a home<span class="go">${ic('ne','width:14px;height:14px')}</span></a>
 <button class="ib burger" id="burger" aria-label="Menu" aria-expanded="false" style="margin-left:6px">${ic('menu')}</button></div></header>
 <nav class="mm" id="mm"><a href="#buy">Buy</a><a href="#rent">Rent</a><a href="#new">New developments</a><a href="#sell">Sell / valuation</a><a href="#agents">Agents</a><a href="#saved">Saved</a><select class="sel" id="curSel2" aria-label="Currency">${[['local','Local currency'],['USD','USD $'],['AUD','AUD A$'],['EUR','EUR €']].map(c=>`<option value="${c[0]}" ${S.cur===c[0]?'selected':''}>${c[1]}</option>`).join('')}</select></nav>`}
function footer(){return `<footer class="f"><div class="wrap"><div class="fwm" aria-hidden="true"><span>Aure</span><span class="pl">${ph('e9','','50% 55%').replace('class="ph "','class="ph " style="position:absolute;inset:0"')}</span><span>lle</span></div>
 <div class="fg"><div><p style="color:var(--fg-2);max-width:34ch">Agents and developers of considered homes in Sydney, Los Angeles and Lisbon.</p></div>
 <div><h4>Find</h4><a href="#buy">Buy</a><a href="#rent">Rent</a><a href="#new">New developments</a><a href="#saved">Saved homes</a></div>
 <div><h4>Owners</h4><a href="#sell">Free valuation</a><a href="#agents">Our agents</a><a href="#sell">Sell with us</a></div>
 <div><h4>Developments</h4>${DEV.map(d=>`<a href="#dev-${d.s}">${d.n}</a>`).join('')}</div>
 <div><h4>New listings by email</h4><p style="font-size:14px;color:var(--fg-2)">Off-market homes and launches first.</p><form class="nlf" id="nlf" novalidate><label class="sr" for="nle">Email</label><input class="input" id="nle" type="email" placeholder="you@email.com" autocomplete="email"><button class="btn ink" type="submit">Join</button></form><p class="err-t" id="nlerr" hidden>Enter a valid email.</p></div></div>
 <div class="fbot"><span>© 2026 Aurelle Estates (fictional). Listings, prices and maps are demo content.</span><span>Website by Organoo Studio</span></div></div></footer>`}
function mount(cur,body){$('#root').innerHTML=nav(cur)+`<main id="main">${body}</main>`+footer()+(S.demoOff?'':`<div class="demo" id="demo">Demo<span class="x3">&nbsp;· Organoo Studio</span><button type="button" aria-label="Hide demo label">${ic('x','width:12px;height:12px')}</button></div>`);
 $('#burger').onclick=()=>{const m=$('#mm');m.classList.toggle('open');$('#burger').setAttribute('aria-expanded',m.classList.contains('open'))};$$('#mm a').forEach(a=>a.addEventListener('click',()=>$('#mm').classList.remove('open')));
 [$('#curSel'),$('#curSel2')].forEach(s=>s&&(s.onchange=()=>{S.cur=s.value;ls('cur',S.cur);const y=scrollY;render(S.page,1);scrollTo(0,y)}));
 $('#demo button')?.addEventListener('click',()=>{S.demoOff=1;$('#demo').remove()});
 $('#nlf').onsubmit=e=>{e.preventDefault();const ok=/^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test($('#nle').value.trim());$('#nlerr').hidden=ok;$('#nle').classList.toggle('err',!ok);if(ok){$('#nle').value='';toast('You’re on the list')}}}
function modal(html,cls=''){closeModal();const m=document.createElement('div');m.className='mdl';m.setAttribute('role','dialog');m.setAttribute('aria-modal','true');m.innerHTML=`<div class="bx ${cls}"><button class="x" aria-label="Close">${ic('x')}</button>${html}</div>`;document.body.appendChild(m);S.lastFocus=document.activeElement;m.querySelector('.x').focus();m.onclick=e=>{if(e.target===m)closeModal()};m.querySelector('.x').onclick=closeModal;return m}
function closeModal(){$('.mdl')?.remove();$('.lbx')?.remove();S.lastFocus?.focus?.()}
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal();const lb=$('.lbx');if(lb&&(e.key==='ArrowRight'||e.key==='ArrowLeft'))lb.dispatchEvent(new CustomEvent('nav',{detail:e.key==='ArrowRight'?1:-1}))});
const sh=(lab,h,p='',extra='')=>`<div class="sh"><div><span class="lab p rv">${lab}</span><h2 class="rv" style="--dl:.08s">${h}</h2></div>${p||extra?`<div class="rv" style="--dl:.16s;display:grid;gap:14px;justify-items:start">${p?`<p>${p}</p>`:''}${extra}</div>`:''}</div>`;
const lines=(txt,tag='h2',cls='')=>`<${tag} class="lines ${cls}">${txt.split('|').map((t,i)=>`<span class="l"><span style="--i:${i}">${t}</span></span>`).join('')}</${tag}>`;

/* ---------- listing card ---------- */
function card(p,i=0){const fav=S.fav.has(p.id),cmp=S.cmp.includes(p.id);const tg=p.tags.filter(t=>t!=='Off-plan').slice(0,1);return `<article class="lc" data-card="${p.id}" style="--d:${Math.min(i,8)*.05}s"><div class="img">${ph(p.img[0],p.t)}${ph(p.img[1],'','','b')}<a class="cover" href="#p-${p.id}" aria-label="${esc(p.t)}"></a>
 <div class="tags">${p.st==='offplan'?'<span class="tag em">Off-plan</span>':p.st==='rent'?'<span class="tag dk">For rent</span>':''}${tg.map(t=>`<span class="tag">${t}</span>`).join('')}</div>
 <div class="acts"><button class="circ ${fav?'on':''}" data-fav="${p.id}" aria-label="${fav?'Remove from':'Save to'} favourites" aria-pressed="${fav}">${ic('heart','width:16px;height:16px')}</button><button class="circ ${cmp?'on':''}" data-cmp="${p.id}" aria-label="Compare" aria-pressed="${cmp}">${ic('cmp','width:16px;height:16px')}</button></div>
 <span class="pr num">${pLabel(p)}</span></div>
 <div class="meta"><h3><a href="#p-${p.id}">${esc(p.t)}</a></h3><span class="loc">${esc(p.area)}, ${CITY[p.city].n}</span><div class="facts"><span>${ic('bed','width:15px;height:15px')}${p.bd} bd</span><span>${ic('bath','width:15px;height:15px')}${p.ba} ba</span><span>${ic('area','width:15px;height:15px')}${p.m2} m²</span><span>${p.type}</span></div></div></article>`}
function bindCards(root=document){$$('[data-fav]',root).forEach(b=>b.onclick=e=>{e.preventDefault();e.stopPropagation();const id=b.dataset.fav;S.fav.has(id)?S.fav.delete(id):S.fav.add(id);saveFav();const on=S.fav.has(id);$$(`[data-fav="${id}"]`).forEach(x=>{x.classList.toggle('on',on);x.setAttribute('aria-pressed',on)});toast(on?'Saved to favourites':'Removed from favourites','heart')});
 $$('[data-cmp]',root).forEach(b=>b.onclick=e=>{e.preventDefault();e.stopPropagation();const id=b.dataset.cmp;if(S.cmp.includes(id))S.cmp=S.cmp.filter(x=>x!==id);else{if(S.cmp.length>=3){toast('Compare up to 3 homes','cmp');return}S.cmp.push(id)}$$('[data-cmp]').forEach(x=>{const on=S.cmp.includes(x.dataset.cmp);x.classList.toggle('on',on);x.setAttribute('aria-pressed',on)});drawTray()})}
function drawTray(){$('.cmp-tray')?.remove();if(!S.cmp.length)return;const t=document.createElement('div');t.className='cmp-tray';t.innerHTML=`<span style="display:flex">${S.cmp.map(id=>ph(lst(id).img[0])).join('')}</span><span style="font-weight:600;font-size:14px">${S.cmp.length} to compare</span><button class="btn em sm" id="cmpGo" ${S.cmp.length<2?'disabled':''}>Compare</button><button class="circ" style="width:34px;height:34px;background:transparent;border-color:#555;color:#fff" id="cmpX" aria-label="Clear compare">${ic('x','width:14px;height:14px')}</button>`;document.body.appendChild(t);
 $('#cmpX').onclick=()=>{S.cmp=[];$$('[data-cmp]').forEach(x=>{x.classList.remove('on');x.setAttribute('aria-pressed',false)});drawTray()};$('#cmpGo').onclick=openCompare}
function openCompare(){const ps=S.cmp.map(lst);const ppm=p=>usd(p)/p.m2;const best=(f,dir)=>{const v=ps.map(f);const b=dir>0?Math.max(...v):Math.min(...v);return v.map(x=>x===b)};
 const rows=[['',p=>ph(p.img[0],p.t)],['Home',p=>`<b style="font-family:var(--f-d);font-size:20px;font-weight:400">${esc(p.t)}</b><br><span class="muted">${esc(p.area)}, ${CITY[p.city].n}</span>`],['Price',p=>pLabel(p)],['Price / m²',(p,i,b)=>`<span class="${b[i]?'best':''}">${p.st==='rent'?'–':price(p.price/p.m2,p.cur)}</span>`,ps.every(p=>p.st!=='rent')?best(ppm,-1):[]],['Bedrooms',(p,i,b)=>`<span class="${b[i]?'best':''}">${p.bd}</span>`,best(p=>p.bd,1)],['Bathrooms',p=>p.ba],['Interior',(p,i,b)=>`<span class="${b[i]?'best':''}">${p.m2} m²</span>`,best(p=>p.m2,1)],['Type',p=>p.type],['Built',p=>p.yr>2025?`Completes ${p.yr}`:p.yr],['Features',p=>p.feat.map(f=>FEAT[f][1]).join(', ')],['',p=>`<a class="btn ink sm" href="#p-${p.id}">View home</a>`]];
 const m=modal(`<h3>Compare homes</h3><div style="overflow-x:auto"><table class="cmp"><tbody>${rows.map(r=>`<tr><th>${r[0]}</th>${ps.map((p,i)=>`<td>${r[1](p,i,r[2]||[])}</td>`).join('')}</tr>`).join('')}</tbody></table></div><p class="muted" style="font-size:13px">Green marks the best value in each row. Prices converted at demo rates when a currency is selected.</p>`,'wide');$$('a',m).forEach(a=>a.addEventListener('click',closeModal))}

/* ---------- HOME ---------- */
function pageHome(){const hero=[lst('bronte-cliff'),lst('canyon-glass'),lst('cascais-villa')];
 return `<section class="hero" id="hero"><div class="hero-st"><div class="hero-img" id="heroImg">${ph('e9','Modern white villa with pool','50% 60%')}</div>
  ${[['left:8%;top:28%',hero[0],1.3],['left:52%;top:22%',hero[1],1.5],['right:9%;top:46%',hero[2],1.7]].map(([pos,p,d])=>`<a class="fcard" href="#p-${p.id}" style="${pos};--d:${d}s" data-par="${(d-1.2)*.5}">${ph(p.img[0])}<div><b class="num">${pLabel(p,{compact:1})}</b><span>${esc(p.area)} · ${p.bd} bd</span></div></a>`).join('')}
  <span class="scroll-cue">Scroll</span>
  <div class="hero-in"><div class="wrap"><div class="hero-top"><h1 class="wordmark" aria-label="Aurelle">${[...'Aurelle'].map((c,i)=>`<span style="--i:${i}">${c}</span>`).join('')}</h1><div class="hero-side"><span class="lab p">Est. 2009</span><p>Considered homes, residences and new developments in Sydney, Los Angeles and Lisbon. Buy, rent or reserve off-plan with one team.</p></div></div>
  <form class="srch" id="srch"><div class="tabs" role="group" aria-label="Search type">${[['buy','Buy'],['rent','Rent'],['new','New']].map((m,i)=>`<button type="button" data-sm="${m[0]}" aria-pressed="${!i}">${m[1]}</button>`).join('')}</div>
   <div class="f"><label for="sCity">Location</label><select id="sCity"><option value="all">All cities</option>${Object.entries(CITY).map(([k,c])=>`<option value="${k}">${c.n}, ${c.c}</option>`).join('')}</select></div>
   <div class="f"><label for="sType">Type</label><select id="sType"><option value="">Any type</option>${TYPES.map(t=>`<option>${t}</option>`).join('')}</select></div>
   <div class="f"><label for="sBeds">Bedrooms</label><select id="sBeds"><option value="0">Any</option>${[1,2,3,4,5].map(b=>`<option value="${b}">${b}+</option>`).join('')}</select></div>
   <button class="btn em lg" type="submit" style="margin-left:6px">Search <span class="num" id="sCnt"></span></button></form></div></div></div></section>
 <section class="s wrap"><div class="intro"><div><span class="lab p rv">About</span><p class="big-p rv" style="margin-top:18px">Aurelle brings <b>buying, renting and new developments</b> into one team, so finding a home feels <em>calm, transparent</em> and <b>personal</b>.</p>
  <div class="orbs rv">${ph('l5','Living room','50% 50%')}${ph('e10','House exterior','50% 50%')}<span class="pill">${L.length} homes live now</span></div></div>
  <div class="side rv"><p>One agent from first viewing to keys. Every listing has floor plans, real measurements and a video walkthrough, and our developments show live unit availability.</p><div style="display:flex;gap:10px;margin-top:22px;flex-wrap:wrap"><a class="btn ink" href="#buy">Browse homes</a><a class="btn lt" href="#sell">Get a valuation</a></div></div></div></section>
 <section class="s wrap" id="featured">${sh('Featured','Homes worth <em>seeing</em>','',`<div class="feat-tabs" role="group" aria-label="City">${[['all','All'],...Object.entries(CITY).map(([k,c])=>[k,c.n])].map((c,i)=>`<button class="chip" type="button" data-fc="${c[0]}" aria-pressed="${!i}">${c[1]}</button>`).join('')}</div>`)}<div class="lgrid" id="featG"></div><div style="text-align:center;margin-top:34px"><a class="btn lt lg" href="#buy">View all homes ${ic('arrow','width:16px;height:16px')}</a></div></section>
 <section class="pj" id="pj"><div class="pj-st"><div class="pj-head"><div class="wrap"><span class="lab p">Our developments</span><div class="pj-dots">${DEV.map((d,i)=>`<span data-pjd="${i}">(${i+1})</span>`).join('')}</div></div></div>
  <div class="pj-imgs">${DEV.map((d,i)=>[1,0,2].map((k,j)=>`<div class="ph i${j+1} ${i?'out':''}" data-pji="${i}">${`<img src="photos/${d.img[k]}.jpg" alt="" loading="lazy" onerror="this.remove()">`}</div>`).join('')).join('')}</div>
  <h2 class="pj-title">${DEV.map((d,i)=>`<span class="t ${i?'nx':''}" data-pjt="${i}">${d.n}</span>`).join('')}</h2>
  <div class="pj-foot"><div class="wrap"><p id="pjD">${DEV[0].d}</p><a class="btn wh" id="pjA" href="#dev-${DEV[0].s}">Explore ${DEV[0].n}</a></div></div><i class="pj-bar" id="pjBar"></i></div>
  <div class="pj-mob">${DEV.map(d=>`<a href="#dev-${d.s}">${ph(d.img[0],d.n)}<span class="lab" style="color:#B9B0A3">${d.tag}</span><h3>${d.n}</h3></a>`).join('')}</div></section>
 <section class="s wrap"><div class="stats">${[['1.2','B','in homes sold','$'],['340','','homes launched off-plan'],['3','','cities, one team'],['24','/7','concierge for owners']].map((s,i)=>`<div class="rv" style="--dl:${i*.08}s"><b><span class="num" data-count="${s[0]}" data-pre="${s[3]||''}" data-dec="${s[0].includes('.')?1:0}">0</span>${s[1]?`<sup>${s[1]}</sup>`:''}</b><span>${s[2]}</span></div>`).join('')}</div></section>
 <section class="mapband" id="explore"><div class="wrap">${sh('Explore','Homes near <em>you</em>','Drag to pan, zoom with the buttons and tap a price to preview. Switch cities to explore each market.',`<div class="feat-tabs" role="group" aria-label="Map city">${Object.entries(CITY).map(([k,c])=>`<button class="chip" type="button" data-mc="${k}" aria-pressed="${S.mapCity===k}">${c.n}</button>`).join('')}</div>`)}
  <div class="mb-grid"><div class="map" id="homeMap" style="height:560px"></div><div class="mb-list" id="homeList"></div></div></div></section>
 <section class="s wrap"><div class="jr"><div class="jr-img rv cl">${ph('a2','Residential tower','50% 50%')}
  <div class="jr-card" style="left:6%;top:10%;--r:-4deg" data-par="-.025"><b>Tour from anywhere</b><p>Live video walkthroughs with your agent, then an in-person visit when you’re ready.</p></div>
  <div class="jr-card em" style="right:6%;top:36%;--r:3deg" data-par=".05"><b>One agent, start to keys</b><p>Negotiation, inspections and settlement handled by the same person.</p></div>
  <div class="jr-card" style="left:10%;bottom:8%;--r:2deg" data-par="-.03"><b>Live availability</b><p>See which residences are available, reserved or sold in our developments.</p></div></div>
  <div class="steps"><span class="lab p rv">How it works</span>${lines('Four steps|to the <em style="color:var(--ember)">keys</em>','h2','rv')}${[['Search','Filter by city, price, size and features, or explore on the map.'],['Tour','Book an in-person viewing or a live video walkthrough in two taps.'],['Offer','Your agent prepares comparables, negotiates and manages the paperwork.'],['Move in','Settlement, handover and a concierge for the first 90 days.']].map((s,i)=>`<div class="stp rv" style="--dl:${i*.08}s"><span class="n">0${i+1}</span><div><b>${s[0]}</b><p>${s[1]}</p></div></div>`).join('')}</div></div></section>
 <section class="s wrap"><div class="val rv">${ph('e3','House on a hill','50% 50%')}<div class="in"><span class="lab p">Selling?</span><h2>What is your home <em>worth</em>?</h2><p class="muted">An instant estimate from recent sales near you, then a free appraisal with a local agent.</p><form id="qv" style="display:grid;gap:12px" novalidate><div class="two"><div class="field"><label for="qvC">City</label><select class="sel" id="qvC">${Object.entries(CITY).map(([k,c])=>`<option value="${k}">${c.n}</option>`).join('')}</select></div><div class="field"><label for="qvM">Interior size (m²)</label><input class="input num" id="qvM" inputmode="numeric" placeholder="e.g. 180"></div></div><p class="err-t" id="qvE" hidden>Enter a size between 30 and 2,000 m².</p><button class="btn ink lg" type="submit" style="justify-self:start">Get my estimate</button></form></div></div></section>
 <section class="s wrap">${sh('Agents','People who know <em>the street</em>','',`<a class="btn lt" href="#agents">All agents</a>`)}<div class="ag">${AG.slice(0,4).map((a,i)=>agCard(a,i)).join('')}</div></section>`}
const agCard=(a,i)=>`<button class="agc" type="button" data-ag="${a.id}" style="--d:${i*.06}s">${ph(a.img,a.n,'50% 25%')}<div><b>${a.n}</b><span>${a.r}</span></div></button>`;
function homeMapDraw(){const c=S.mapCity;const items=L.filter(p=>p.city===c);const el=$('#homeMap');if(!el)return;
 const m=mountMap(el,{city:c,dark:1,items,onPin:(p,pin)=>{pinCard(el,p,pin);hl(p.id,1)},hover:(id,on)=>hl(id,on)});
 $('#homeList').innerHTML=items.map(p=>`<a class="mb-it" href="#p-${p.id}" data-li="${p.id}">${ph(p.img[0],p.t)}<div><b>${esc(p.t)}</b><span>${esc(p.area)} · ${p.bd} bd · ${p.m2} m²</span><div style="font-weight:700;font-size:14px;margin-top:2px">${pLabel(p)}</div></div></a>`).join('');
 function hl(id,on){$$('.mb-it').forEach(x=>x.classList.toggle('hl',on&&x.dataset.li===id));$$('#homeMap .pin').forEach(x=>x.classList.toggle('hl',on&&x.dataset.pid===id))}
 $$('.mb-it').forEach(x=>{x.onmouseenter=()=>{hl(x.dataset.li,1)};x.onmouseleave=()=>hl(x.dataset.li,0)})}
function bindHome(){let mode='buy';const cnt=()=>{const f={...S.f,mode,city:$('#sCity').value,types:$('#sType').value?[$('#sType').value]:[],beds:+$('#sBeds').value,min:0,max:0,feats:[]};$('#sCnt').textContent=`(${filtered(f).length})`};
 $$('[data-sm]').forEach(b=>b.onclick=()=>{mode=b.dataset.sm;$$('[data-sm]').forEach(x=>x.setAttribute('aria-pressed',x===b));cnt()});['#sCity','#sType','#sBeds'].forEach(s=>$(s).onchange=cnt);cnt();
 $('#srch').onsubmit=e=>{e.preventDefault();S.f={mode,city:$('#sCity').value,types:$('#sType').value?[$('#sType').value]:[],beds:+$('#sBeds').value,baths:0,min:0,max:0,feats:[],sort:'feat'};location.hash=mode==='rent'?'rent':mode==='new'?'new':'buy';S.keepF=1};
 const drawF=c=>{$('#featG').innerHTML=L.filter(p=>(c==='all'||p.city===c)&&p.st!=='rent').slice(0,6).map(card).join('');bindCards($('#featG'))};drawF('all');
 $$('[data-fc]').forEach(b=>b.onclick=()=>{$$('[data-fc]').forEach(x=>x.setAttribute('aria-pressed',x===b));drawF(b.dataset.fc)});
 homeMapDraw();$$('[data-mc]').forEach(b=>b.onclick=()=>{S.mapCity=b.dataset.mc;$$('[data-mc]').forEach(x=>x.setAttribute('aria-pressed',x===b));homeMapDraw()});
 $('#qv').onsubmit=e=>{e.preventDefault();const m=+$('#qvM').value;if(!(m>=30&&m<=2000)){$('#qvE').hidden=false;$('#qvM').classList.add('err');return}S.val={city:$('#qvC').value,m2:m};location.hash='sell'};
 bindAgents()}
function bindAgents(root=document){$$('[data-ag]',root).forEach(b=>b.onclick=()=>openAgent(b.dataset.ag))}
function openAgent(id){const a=ag(id);const ls2=L.filter(p=>p.ag===id);const m=modal(`<div style="display:grid;grid-template-columns:160px 1fr;gap:20px;align-items:start">${ph(a.img,a.n,'50% 25%').replace('class="ph "','class="ph " style="aspect-ratio:3/4;border-radius:18px"')}<div style="display:grid;gap:8px"><span class="lab">${CITY[a.city].n}</span><h3>${a.n}</h3><span class="muted">${a.r} · ${a.yrs} years</span><div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:6px"><a class="btn ink sm" href="tel:${a.tel.replace(/[^+\d]/g,'')}">${ic('phone','width:15px;height:15px')}${a.tel}</a><a class="btn lt sm" href="mailto:${a.id}@aurelle.example">${ic('mail','width:15px;height:15px')}Email</a></div></div></div>
 <b>Listings (${ls2.length})</b><div style="display:grid;gap:8px">${ls2.map(p=>`<a class="rowi" href="#p-${p.id}" style="text-decoration:none">${ph(p.img[0],p.t)}<div class="g"><b>${esc(p.t)}</b><span class="muted" style="font-size:13px">${esc(p.area)} · ${pLabel(p)}</span></div></a>`).join('')||'<p class="muted">Focused on new developments this season.</p>'}</div>`);$$('a[href^="#p-"]',m).forEach(x=>x.addEventListener('click',closeModal))}

/* ---------- LISTINGS ---------- */
function filtered(f=S.f){return L.filter(p=>(f.mode==='buy'?p.st==='sale'||p.st==='offplan':f.mode==='rent'?p.st==='rent':p.st==='offplan')&&(f.city==='all'||p.city===f.city)&&(!f.types.length||f.types.includes(p.type))&&p.bd>=f.beds&&p.ba>=f.baths&&(!f.min||usd(p)>=f.min)&&(!f.max||usd(p)<=f.max)&&f.feats.every(x=>p.feat.includes(x)))}
const PR={buy:[0,16e6,250e3],rent:[0,12e3,250],new:[0,6e6,100e3]};
function pageList(mode){if(!S.keepF)S.f={...S.f,mode,min:0,max:0};S.f.mode=mode;S.keepF=0;const T={buy:['Homes for <em>sale</em>','Houses, villas and apartments in Sydney, Los Angeles and Lisbon.'],rent:['Homes to <em>rent</em>','Furnished and unfurnished homes on 12-month leases. Prices are per month.'],new:['New <em>developments</em>','Reserve off-plan in our three developments, with live unit availability.']}[mode];
 return `<section class="wrap ph-h"><div class="crumbs"><a href="#home">Home</a>/<span>${mode==='buy'?'Buy':mode==='rent'?'Rent':'New developments'}</span></div><h1 class="rv">${T[0]}</h1><p class="rv" style="--dl:.1s">${T[1]}</p></section>
 ${mode==='new'?`<section class="wrap" style="margin-bottom:40px"><div class="lgrid">${DEV.map((d,i)=>`<a class="lc" href="#dev-${d.s}" style="text-decoration:none;--d:${i*.08}s"><span class="img">${ph(d.img[0],d.n)}${ph(d.img[1],'','','b')}</span><div class="tags"><span class="tag em">${d.done}</span></div><div class="meta"><h3>${d.n}</h3><span class="loc">${d.area}, ${CITY[d.city].n} · ${d.tag}</span><span style="font-weight:700">From ${price(d.from,CITY[d.city].cur)}</span></div></a>`).join('')}</div><h2 style="font-size:40px;margin:60px 0 0">Available residences</h2></section>`:''}
 <section class="wrap"><div class="lp"><aside class="flt closed" id="flt" aria-label="Filters">
  <div><h4>Location</h4><select class="sel" id="fCity"><option value="all">All cities</option>${Object.entries(CITY).map(([k,c])=>`<option value="${k}" ${S.f.city===k?'selected':''}>${c.n}</option>`).join('')}</select></div>
  <div><h4>Property type</h4><div class="chips">${TYPES.map(t=>`<button class="chip" type="button" data-ft="${t}" aria-pressed="${S.f.types.includes(t)}">${t}</button>`).join('')}</div></div>
  <div><h4>Price (USD equiv.)</h4><div class="dual-v num"><span id="pMin"></span><span id="pMax"></span></div><div class="dual"><span class="tr"><i id="pTr"></i></span><input type="range" id="rMin" min="${PR[mode][0]}" max="${PR[mode][1]}" step="${PR[mode][2]}" value="${S.f.min||PR[mode][0]}" aria-label="Minimum price"><input type="range" id="rMax" min="${PR[mode][0]}" max="${PR[mode][1]}" step="${PR[mode][2]}" value="${S.f.max||PR[mode][1]}" aria-label="Maximum price"></div></div>
  <div><h4>Bedrooms</h4><div class="seg full">${[0,1,2,3,4,5].map(b=>`<button type="button" data-fb="${b}" aria-pressed="${S.f.beds===b}">${b?b+'+':'Any'}</button>`).join('')}</div></div>
  <div><h4>Bathrooms</h4><div class="seg full">${[0,1,2,3,4].map(b=>`<button type="button" data-fba="${b}" aria-pressed="${S.f.baths===b}">${b?b+'+':'Any'}</button>`).join('')}</div></div>
  <div><h4>Features</h4>${['pool','view','garden','parking','terrace','gym','concierge'].map(f=>`<label class="ck"><input type="checkbox" data-ff="${f}" ${S.f.feats.includes(f)?'checked':''}>${FEAT[f][1]}</label>`).join('')}</div>
  <div style="display:flex;gap:8px;flex-wrap:wrap"><button class="btn ink sm" type="button" id="svS">${ic('bell','width:15px;height:15px')}Save search</button><button class="link" type="button" id="clr">Reset</button></div></aside>
 <div><div class="rbar"><div style="display:flex;gap:10px;align-items:center"><button class="btn lt sm fbtn" type="button" id="fTog">${ic('filter','width:15px;height:15px')}Filters</button><span class="muted" id="rCnt"></span></div><div style="display:flex;gap:8px;align-items:center;flex-wrap:wrap"><label class="sr" for="sort">Sort</label><select class="sel" id="sort">${[['feat','Featured'],['low','Price: low to high'],['high','Price: high to low'],['size','Largest first'],['new','Newest build']].map(o=>`<option value="${o[0]}" ${S.f.sort===o[0]?'selected':''}>${o[1]}</option>`).join('')}</select><div class="seg" role="group" aria-label="View">${[['grid','grid','Grid'],['split','split','Split'],['map','map','Map']].map(v=>`<button type="button" data-v="${v[0]}" aria-pressed="${S.view===v[0]}" aria-label="${v[2]} view">${ic(v[1],'width:16px;height:16px')}</button>`).join('')}</div></div></div><div id="res"></div></div></div></section>`}
function drawList(){const f=S.f,mode=f.mode;const so={feat:(a,b)=>0,low:(a,b)=>usd(a)-usd(b),high:(a,b)=>usd(b)-usd(a),size:(a,b)=>b.m2-a.m2,new:(a,b)=>b.yr-a.yr}[f.sort];const l=[...filtered()].sort(so);
 $('#rCnt').textContent=`${l.length} home${l.length===1?'':'s'}`;const el=$('#res');
 const fmtU=v=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',notation:'compact',maximumFractionDigits:1}).format(v)+(mode==='rent'?'/mo':'');const mn=+$('#rMin').value,mx=+$('#rMax').value,R=PR[mode];$('#pMin').textContent=fmtU(mn);$('#pMax').textContent=mx>=R[1]?fmtU(mx)+'+':fmtU(mx);$('#pTr').style.left=(mn-R[0])/(R[1]-R[0])*100+'%';$('#pTr').style.right=100-(mx-R[0])/(R[1]-R[0])*100+'%';
 if(!l.length){el.innerHTML=`<div class="empty"><h3 style="font-size:30px">No homes match</h3><p class="muted" style="margin:8px 0 16px">Try widening the price range or removing a feature.</p><button class="btn ink" id="clr2">Reset filters</button></div>`;$('#clr2').onclick=reset;return}
 const cities=[...new Set(l.map(p=>p.city))];const mc=f.city!=='all'?f.city:(cities.includes(S.mapCity)?S.mapCity:cities[0]);
 const grid=`<div class="lgrid" id="lg">${l.map(card).join('')}</div>`;
 const mapHTML=`<div class="mapw"><div style="display:flex;gap:6px;margin-bottom:8px;flex-wrap:wrap" ${f.city!=='all'?'hidden':''}>${cities.map(c=>`<button class="chip" type="button" data-lmc="${c}" aria-pressed="${c===mc}" style="height:32px;font-size:12.5px">${CITY[c].n}</button>`).join('')}</div><div class="map" id="lmap" style="height:${S.view==='map'?'72vh':'calc(100% - 40px)'}"></div></div>`;
 el.innerHTML=S.view==='grid'?grid:S.view==='split'?`<div class="split">${grid}${mapHTML}</div>`:`<div class="onlymap">${mapHTML}</div>`;bindCards(el);
 if(S.view!=='grid'){const items=l.filter(p=>p.city===mc);const mapEl=$('#lmap');const hl=(id,on)=>{$$('.lc').forEach(c=>c.classList.toggle('hl',on&&c.dataset.card===id));$$('#lmap .pin').forEach(x=>x.classList.toggle('hl',on&&x.dataset.pid===id))};
  const M=mountMap(mapEl,{city:mc,dark:0,items,onPin:(p,pin)=>{pinCard(mapEl,p,pin);const c=$(`.lc[data-card="${p.id}"]`);if(c&&S.view==='split'){c.scrollIntoView({behavior:'smooth',block:'center'});hl(p.id,1)}},hover:hl});
  $$('.lc').forEach(c=>{c.onmouseenter=()=>hl(c.dataset.card,1);c.onmouseleave=()=>hl(c.dataset.card,0)});
  $$('[data-lmc]').forEach(b=>b.onclick=()=>{S.mapCity=b.dataset.lmc;drawList()})}}
function reset(){S.f={mode:S.f.mode,city:'all',types:[],beds:0,baths:0,min:0,max:0,feats:[],sort:'feat'};render(S.page,1)}
function bindList(){drawList();const f=S.f,R=PR[f.mode];
 $('#fCity').onchange=e=>{f.city=e.target.value;if(f.city!=='all')S.mapCity=f.city;drawList()};
 $$('[data-ft]').forEach(b=>b.onclick=()=>{const t=b.dataset.ft;f.types=f.types.includes(t)?f.types.filter(x=>x!==t):[...f.types,t];b.setAttribute('aria-pressed',f.types.includes(t));drawList()});
 $$('[data-fb]').forEach(b=>b.onclick=()=>{f.beds=+b.dataset.fb;$$('[data-fb]').forEach(x=>x.setAttribute('aria-pressed',x===b));drawList()});
 $$('[data-fba]').forEach(b=>b.onclick=()=>{f.baths=+b.dataset.fba;$$('[data-fba]').forEach(x=>x.setAttribute('aria-pressed',x===b));drawList()});
 $$('[data-ff]').forEach(c=>c.onchange=()=>{const k=c.dataset.ff;f.feats=c.checked?[...f.feats,k]:f.feats.filter(x=>x!==k);drawList()});
 const rr=()=>{let a=+$('#rMin').value,b=+$('#rMax').value;if(a>b-R[2]){if(document.activeElement===$('#rMin'))a=b-R[2];else b=a+R[2];$('#rMin').value=a;$('#rMax').value=b}f.min=a>R[0]?a:0;f.max=b<R[1]?b:0;drawList()};$('#rMin').oninput=rr;$('#rMax').oninput=rr;
 $('#sort').onchange=e=>{f.sort=e.target.value;drawList()};$$('[data-v]').forEach(b=>b.onclick=()=>{S.view=b.dataset.v;$$('[data-v]').forEach(x=>x.setAttribute('aria-pressed',x===b));drawList()});
 $('#clr').onclick=reset;$('#fTog').onclick=()=>$('#flt').classList.toggle('closed');
 $('#svS').onclick=()=>{const l=ls('searches')||[];const d=[f.mode==='rent'?'Rent':f.mode==='new'?'Off-plan':'Buy',f.city==='all'?'All cities':CITY[f.city].n,f.types.join('/')||'Any type',f.beds?f.beds+'+ bd':'',...f.feats.map(x=>FEAT[x][1])].filter(Boolean).join(' · ');l.unshift({id:Date.now(),d,f:{...f},n:filtered().length});ls('searches',l.slice(0,10));toast('Search saved. Find it under Saved.','bell')}}

/* ---------- PROPERTY ---------- */
function floorPlan(bd,m2){const W=520,H=320,rooms=[];const lw=bd>3?220:250;rooms.push(['Living & dining',0,0,lw,H*.62]);rooms.push(['Kitchen',0,H*.62,lw*.6,H*.38]);rooms.push(['Bath',lw*.6,H*.62,lw*.4,H*.38]);const bw=(W-lw)/Math.min(bd,2),rowsN=Math.ceil(bd/2);for(let i=0;i<bd;i++){const c=i%2,r=Math.floor(i/2);rooms.push([i?`Bedroom ${i+1}`:'Main suite',lw+c*bw,r*H/rowsN,bd===1?W-lw:bw,H/rowsN])}
 const sc=Math.sqrt(m2/(W*H/1e4*1.4));return `<svg viewBox="-10 -10 ${W+20} ${H+56}" role="img" aria-label="Floor plan">${rooms.map(r=>`<rect x="${r[1]}" y="${r[2]}" width="${r[3]}" height="${r[4]}" fill="${r[0].includes('Living')?'#FDE6DC':'#FBF8F3'}" stroke="#1D1A17" stroke-width="2.5"/><text x="${r[1]+r[3]/2}" y="${r[2]+r[4]/2}" text-anchor="middle">${r[0]}</text><text x="${r[1]+r[3]/2}" y="${r[2]+r[4]/2+15}" text-anchor="middle" style="fill:#7A7166;font-size:10px">${(r[3]*r[4]/1e4*1.4*sc*sc/1.4).toFixed(0)} m²</text>`).join('')}<rect x="0" y="${H+8}" width="${W}" height="28" fill="#E8DFD2"/><text x="${W/2}" y="${H+26}" text-anchor="middle">Terrace · indicative plan, not to scale</text></svg>`}
function pageProp(p){const a=ag(p.ag),c=CITY[p.city];const sim=L.filter(x=>x.id!==p.id&&(x.city===p.city||x.type===p.type)&&x.st===p.st).slice(0,3);
 return `<section class="wrap" style="padding-top:100px"><div class="crumbs"><a href="#home">Home</a>/<a href="#${p.st==='rent'?'rent':p.st==='offplan'?'new':'buy'}">${p.st==='rent'?'Rent':p.st==='offplan'?'New developments':'Buy'}</a>/<span>${esc(p.area)}</span></div>
 <div class="gal">${p.img.slice(0,5).map((k,i)=>`<button type="button" data-gi="${i}" aria-label="Open photo ${i+1}">${ph(k,p.t+' photo '+(i+1))}${i===Math.min(4,p.img.length-1)?`<span class="btn wh sm more">${ic('zoom','width:15px;height:15px')}All ${p.img.length} photos</span>`:''}</button>`).join('')}</div>
 <div class="pd"><div><div class="pd-h"><div><span class="lab">${p.type} · ${p.st==='rent'?'For rent':p.st==='offplan'?'Off-plan':'For sale'}</span><h1 style="margin-top:8px">${esc(p.t)}</h1><p class="muted" style="margin-top:6px">${ic('pin','width:15px;height:15px;vertical-align:-2px')} ${esc(p.area)}, ${c.n}, ${c.c}</p></div><div><div class="pr num">${pLabel(p)}</div>${S.cur!=='local'?`<div class="muted" style="text-align:right;font-size:13px">${new Intl.NumberFormat(SYM[p.cur][0],{style:'currency',currency:p.cur,maximumFractionDigits:0}).format(p.price)} local</div>`:''}<div style="display:flex;gap:6px;justify-content:flex-end;margin-top:10px"><button class="circ ${S.fav.has(p.id)?'on':''}" data-fav="${p.id}" aria-label="Save">${ic('heart','width:16px;height:16px')}</button><button class="circ ${S.cmp.includes(p.id)?'on':''}" data-cmp="${p.id}" aria-label="Compare">${ic('cmp','width:16px;height:16px')}</button><button class="circ" id="shr" aria-label="Share">${ic('share','width:16px;height:16px')}</button></div></div></div>
  <div class="kf">${[[p.bd,'Bedrooms'],[p.ba,'Bathrooms'],[p.m2,'m² interior'],[Math.round(p.m2*10.764).toLocaleString(),'sq ft'],[p.yr,p.yr>2025?'Completion':'Built']].map(k=>`<div><b class="num">${k[0]}</b><span>${k[1]}</span></div>`).join('')}</div>
  <div class="body"><p>${esc(p.d)}</p><p>${p.st==='rent'?'Available on a 12-month lease. Pets considered. Bond equal to one month’s rent.':'Inspections by appointment, in person or by live video. Contracts and building reports available from your agent.'}</p></div>
  <h2>Features</h2><div class="amen">${p.feat.map(f=>`<div>${ic(FEAT[f][0])}${FEAT[f][1]}</div>`).join('')}<div>${ic('area')}${p.m2} m² interior</div></div>
  <h2>Floor plan</h2><div class="fp">${floorPlan(p.bd,p.m2)}</div>
  <h2>Location</h2><div class="map" id="pmap" style="height:340px"></div><div class="poi">${[['Café & bakery',4],['Park',6],['Supermarket',8],['School',11],['Transit',9]].map(([n,m])=>`<div><span>${n}</span><b>${m+hash(p.id+n)%6} min walk</b></div>`).join('')}</div>
  ${p.st!=='rent'?`<h2>Mortgage estimate</h2><div class="mort" id="mort"><div class="rows">${[['dep','Deposit',10,50,20,'%'],['rate','Interest rate',2,9,6.1,'%',.1],['yrs','Loan term',10,35,30,' yrs']].map(r=>`<div class="rg"><div class="t"><label for="m-${r[0]}">${r[1]}</label><b id="mv-${r[0]}"></b></div><input class="r" type="range" id="m-${r[0]}" min="${r[2]}" max="${r[3]}" step="${r[6]||1}" value="${r[4]}"></div>`).join('')}<p class="muted" style="font-size:12.5px">Illustrative principal and interest only. Excludes taxes, insurance and fees. Not financial advice.</p></div><div><div class="donut" id="donut"></div><div class="lg2"><span><i style="background:var(--ink)"></i>Principal</span><span><i style="background:var(--ember)"></i>Interest</span></div></div></div>`:''}
  ${sim.length?`<h2>Similar homes</h2><div class="lgrid">${sim.map(card).join('')}</div>`:''}</div>
 <aside class="side"><div class="agent-box"><div class="who">${ph(a.img,a.n,'50% 25%')}<div><b>${a.n}</b><span>${a.r}</span></div></div><div style="display:flex;gap:6px;flex-wrap:wrap"><a class="btn lt sm" href="tel:${a.tel.replace(/[^+\d]/g,'')}">${ic('phone','width:14px;height:14px')}Call</a><a class="btn lt sm" href="mailto:${a.id}@aurelle.example?subject=${encodeURIComponent(p.t)}">${ic('mail','width:14px;height:14px')}Email</a><a class="btn lt sm" href="https://wa.me/${a.tel.replace(/\D/g,'')}?text=${encodeURIComponent('Hi, I’m interested in '+p.t)}" target="_blank" rel="noopener">WhatsApp</a></div></div>
  <div class="agent-box" id="vw"></div></aside></div></section>`}
function drawViewing(p){const el=$('#vw');const V=S.vw||(S.vw={mode:'person',d:null,t:null});const today=dsOf(new Date());const days=[...Array(12)].map((_,i)=>addDs(today,i+1)).filter(d=>new Date(d+'T12:00').getDay()!==0).slice(0,9);if(!V.d)V.d=days[0];
 const slots=['10:00','11:00','12:00','13:00','14:00','15:00','16:00','17:00'];const taken=t=>hash(p.id+V.d+t)%4===0||(ls('viewings')||[]).some(v=>v.pid===p.id&&v.d===V.d&&v.t===t);
 el.innerHTML=`<b style="font-family:var(--f-d);font-size:24px;font-weight:400">Book a viewing</b><div class="seg full">${[['person','In person'],['video','Live video']].map(m=>`<button type="button" data-vm="${m[0]}" aria-pressed="${V.mode===m[0]}">${m[1]}</button>`).join('')}</div>
 <div class="days" role="group" aria-label="Day">${days.map(d=>`<button type="button" data-vd="${d}" aria-pressed="${V.d===d}">${fmtD(d,{weekday:'short'})}<b>${+d.slice(8)}</b>${fmtD(d,{month:'short'})}</button>`).join('')}</div>
 <div class="times">${slots.map(t=>`<button type="button" data-vt="${t}" aria-pressed="${V.t===t}" ${taken(t)?'disabled':''}>${t}</button>`).join('')}</div>
 <form id="vf" novalidate style="display:grid;gap:10px"><input class="input" id="vn" placeholder="Full name" autocomplete="name" aria-label="Full name"><input class="input" id="ve" type="email" placeholder="Email" autocomplete="email" aria-label="Email"><input class="input" id="vp" type="tel" placeholder="Phone (with country code)" autocomplete="tel" aria-label="Phone"><p class="err-t" id="verr" hidden></p><button class="btn em lg" type="submit">${V.t?`Request ${fmtD(V.d,{weekday:'short'})} ${V.t}`:'Choose a time'}</button></form>`;
 $$('[data-vm]',el).forEach(b=>b.onclick=()=>{V.mode=b.dataset.vm;drawViewing(p)});$$('[data-vd]',el).forEach(b=>b.onclick=()=>{V.d=b.dataset.vd;V.t=null;drawViewing(p)});$$('[data-vt]',el).forEach(b=>b.onclick=()=>{V.t=b.dataset.vt;const keep=['vn','ve','vp'].map(i=>$('#'+i).value);drawViewing(p);['vn','ve','vp'].forEach((i,k)=>$('#'+i).value=keep[k])});
 $('#vf').onsubmit=e=>{e.preventDefault();const v=id=>$('#'+id).value.trim();const bad=[];if(v('vn').length<2)bad.push('vn');if(!/^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test(v('ve')))bad.push('ve');const pd=v('vp').replace(/\D/g,'');if(pd.length<8||pd.length>15)bad.push('vp');['vn','ve','vp'].forEach(i=>$('#'+i).classList.toggle('err',bad.includes(i)));const er=$('#verr');
  if(!V.t){er.hidden=false;er.textContent='Please choose a time.';return}if(bad.length){er.hidden=false;er.textContent=bad.includes('ve')?'Please enter a valid email.':bad.includes('vp')?'Please enter a phone number with country code.':'Please enter your name.';return}
  const l=ls('viewings')||[];const rec={id:'AV-'+(hash(p.id+V.d+V.t+v('ve'))%90000+10000),pid:p.id,d:V.d,t:V.t,mode:V.mode,n:v('vn')};l.push(rec);ls('viewings',l);const a=ag(p.ag);
  const st=V.d.replace(/-/g,'')+'T'+V.t.replace(':','')+'00',en=V.d.replace(/-/g,'')+'T'+pad(+V.t.slice(0,2)+1)+'0000';
  modal(`<span class="lab">Viewing requested · ${rec.id}</span><h3>See you ${fmtD(V.d,{weekday:'long'})}, ${esc(rec.n.split(' ')[0])}.</h3><p class="muted">${a.n} will confirm by email within two hours. This is a demo, so no email is sent.</p><div class="rowi">${ph(p.img[0])}<div class="g"><b>${esc(p.t)}</b><span class="muted" style="font-size:13px">${fmtD(V.d,{weekday:'long',month:'long',day:'numeric'})} · ${V.t} local time · ${V.mode==='video'?'Live video':'In person'}</span></div></div><div style="display:flex;gap:10px;flex-wrap:wrap"><a class="btn ink" target="_blank" rel="noopener" href="https://calendar.google.com/calendar/render?action=TEMPLATE&text=${encodeURIComponent('Viewing: '+p.t)}&dates=${st}/${en}&details=${encodeURIComponent('Aurelle demo viewing '+rec.id+' with '+a.n)}&location=${encodeURIComponent(p.area+', '+CITY[p.city].n)}">${ic('cal','width:15px;height:15px')}Add to Google Calendar</a><a class="btn lt" href="#saved">My viewings</a></div>`);V.t=null;drawViewing(p)}}
function bindProp(p){bindCards();drawViewing(p);
 $$('[data-gi]').forEach(b=>b.onclick=()=>lightbox(p,+b.dataset.gi));
 $('#shr').onclick=()=>{(navigator.clipboard?.writeText(location.href)||Promise.reject()).then(()=>toast('Link copied','copy')).catch(()=>toast(location.href,'copy'))};
 const pm=$('#pmap');mountMap(pm,{city:p.city,dark:0,items:[p],onPin:()=>{}});setTimeout(()=>{},0);
 const mo=$('#mort');if(mo){const draw=()=>{const g=id=>+$('#m-'+id).value;['dep','rate','yrs'].forEach(k=>{const el=$('#m-'+k);el.style.setProperty('--p',(el.value-el.min)/(el.max-el.min)*100+'%')});const P=p.price*(1-g('dep')/100),r=g('rate')/1200,n=g('yrs')*12;const pmt=P*r/(1-Math.pow(1+r,-n)),tot=pmt*n,int=tot-P;
  $('#mv-dep').textContent=`${g('dep')}% · ${price(p.price*g('dep')/100,p.cur,{compact:1})}`;$('#mv-rate').textContent=g('rate').toFixed(1)+'%';$('#mv-yrs').textContent=g('yrs')+' years';
  const f=P/tot,C=2*Math.PI*80;$('#donut').innerHTML=`<svg viewBox="0 0 200 200" width="200" height="200"><circle cx="100" cy="100" r="80" fill="none" stroke="var(--ember)" stroke-width="22"/><circle cx="100" cy="100" r="80" fill="none" stroke="var(--ink)" stroke-width="22" stroke-dasharray="${f*C} ${C}" transform="rotate(-90 100 100)" style="transition:stroke-dasharray .4s"/></svg><div class="c"><div><b class="num">${price(pmt,p.cur)}</b><span>per month</span><br><span>interest ${price(int,p.cur,{compact:1})}</span></div></div>`};['dep','rate','yrs'].forEach(k=>$('#m-'+k).oninput=draw);draw()}}
function lightbox(p,i){closeModal();const lb=document.createElement('div');lb.className='lbx';lb.setAttribute('role','dialog');lb.setAttribute('aria-label','Photo gallery');document.body.appendChild(lb);
 const draw=()=>{lb.innerHTML=`<div class="top"><span>${esc(p.t)} · ${i+1} / ${p.img.length}</span><button class="circ" style="background:transparent;color:#fff;border-color:#555" aria-label="Close">${ic('x')}</button></div><div class="stage"><button class="nv p" aria-label="Previous">${ic('left')}</button><img src="photos/${p.img[i]}.jpg" alt="${esc(p.t)} photo ${i+1}"><button class="nv n" aria-label="Next">${ic('arrow')}</button></div><div class="th">${p.img.map((k,j)=>`<button data-j="${j}" aria-current="${i===j}" aria-label="Photo ${j+1}">${ph(k)}</button>`).join('')}</div>`;
  $('.top .circ',lb).onclick=closeModal;$('.nv.p',lb).onclick=()=>go(-1);$('.nv.n',lb).onclick=()=>go(1);$$('[data-j]',lb).forEach(b=>b.onclick=()=>{i=+b.dataset.j;draw()});$('.top .circ',lb).focus()};
 const go=d=>{i=(i+d+p.img.length)%p.img.length;draw()};lb.addEventListener('nav',e=>go(e.detail));let sx=null;lb.addEventListener('pointerdown',e=>sx=e.clientX);lb.addEventListener('pointerup',e=>{if(sx!=null&&Math.abs(e.clientX-sx)>50)go(e.clientX<sx?1:-1);sx=null});draw()}

/* ---------- DEVELOPMENT ---------- */
function units(d){const out=[],res=ls('reserved')||[];for(let f=d.top;f>d.top-d.floors;f--)for(let u=0;u<d.units;u++){const id=d.s==='marlowe'?`R${(d.top-f)*d.units+u+1}`:`${f}${'ABCD'[u]}`;const h=hash(d.s+id)%100;const mine=res.find(r=>r.dev===d.s&&r.u===id);const st=mine?'rs':h<28?'sd':h<42?'rs':'av';const fl=d.top-f;out.push({id,f,u,st,mine:!!mine,bd:d.beds[u],m2:d.m2[u]+(fl%3)*2,price:Math.round(d.from*(d.m2[u]/d.m2[0])*(1+(f-(d.top-d.floors))*.018)/1000)*1000,asp:['North-east','North','North-west','South'][u]})}return out}
function pageDev(d){const c=CITY[d.city],U=units(d),av=U.filter(u=>u.st==='av').length;
 return `<section class="dv-hero">${ph(d.img[0],d.n)}<div class="in"><div class="wrap"><span class="lab p" style="color:#fff">${d.area}, ${c.n} · ${d.tag}</span>${lines(d.n,'h1')}<div class="dv-facts">${[[U.length,'residences'],[av,'available now'],[d.done,'completion'],[price(d.from,c.cur,{compact:1}),'from']].map(f=>`<div><b class="num">${f[0]}</b><span>${f[1]}</span></div>`).join('')}</div></div></div></section>
 <section class="s wrap"><div class="intro"><div><span class="lab p rv">The project</span><p class="big-p rv" style="margin-top:16px;color:var(--ink)">${d.d}</p></div><div class="rv"><div class="amen" style="grid-template-columns:1fr 1fr">${d.am.map(a=>`<div>${ic('check')}${a}</div>`).join('')}</div></div></div></section>
 <section class="s wrap"><div class="dv-gal">${d.img.slice(1,4).map((k,i)=>`<div class="rv cl" style="--dl:${i*.1}s">${ph(k,d.n).replace('class="ph "','class="ph " style="height:100%"')}</div>`).join('')}</div></section>
 <section class="s wrap" id="avail">${sh('Availability','Choose your <em>residence</em>','Live availability. Tap an available residence to see its plan and price, then reserve with a refundable holding deposit.',`<div class="chips" role="group" aria-label="Bedrooms">${[0,...new Set(d.beds)].map(b=>`<button class="chip" type="button" data-ub="${b}" aria-pressed="${S.bedsF===b}">${b?b+' bed':'All'}</button>`).join('')}</div>`)}
 <div class="avail"><div class="stack"><div class="legend" style="margin-bottom:14px"><span><i style="background:var(--ember-soft);border:1px solid #F6C4AE"></i>Available</span><span><i style="background:var(--stone)"></i>Reserved</span><span><i style="background:#EFEAE2"></i>Sold</span><span><i style="background:var(--ink)"></i>Selected</span></div><div class="bld" id="bld"></div></div><div class="ucard" id="ucard"></div></div></section>`}
function drawUnits(d){const U=units(d);const bld=$('#bld');const floors=[...new Set(U.map(u=>u.f))];bld.innerHTML=floors.map(f=>`<div class="fl" style="--u:${d.units}"><span class="lv">${d.s==='marlowe'?'Row '+(d.top-f+1):'L'+f}</span>${U.filter(u=>u.f===f).map(u=>{const dim=S.bedsF&&u.bd!==S.bedsF;return `<button type="button" class="un ${u.st}" data-u="${u.id}" aria-pressed="${S.unitSel===u.id}" ${u.st!=='av'&&!u.mine?'':''} style="${dim?'opacity:.25':''}" aria-label="${u.id}, ${u.bd} bed, ${u.st==='av'?'available':u.st==='rs'?'reserved':'sold'}">${u.id}${u.mine?' ★':''}</button>`}).join('')}</div>`).join('');
 const sel=U.find(u=>u.id===S.unitSel)||U.find(u=>u.st==='av'&&(!S.bedsF||u.bd===S.bedsF));S.unitSel=sel?.id;const cur=CITY[d.city].cur;const uc=$('#ucard');
 uc.innerHTML=sel?`<span class="lab">Residence ${sel.id} · ${d.s==='marlowe'?'Home':'Level '+sel.f}</span><h3>${sel.bd} bedroom${sel.bd>1?'s':''}</h3><div style="font-family:var(--f-d);font-size:36px" class="num">${price(sel.price,cur)}</div><div class="kf" style="grid-template-columns:repeat(3,1fr);margin:6px 0"><div><b class="num">${sel.m2}</b><span>m² interior</span></div><div><b>${sel.asp.split('-').map(x=>x[0]).join('')}</b><span>${sel.asp} aspect</span></div><div style="border:0"><b>${sel.st==='av'?'Open':sel.st==='rs'?'Held':'Sold'}</b><span>status</span></div></div><div class="fp" style="padding:10px">${floorPlan(sel.bd,sel.m2)}</div>
 ${sel.st==='av'?`<button class="btn em lg" id="rsv">Reserve · ${price(sel.price*.05,cur)} deposit</button><button class="btn lt" id="reg">Register interest</button>`:sel.mine?`<span class="tag st" style="justify-self:start">★ Reserved by you</span><button class="btn lt" id="unrsv">Cancel reservation</button>`:`<p class="muted">This residence is ${sel.st==='rs'?'reserved':'sold'}. Choose an orange residence.</p>`}`:`<p class="muted">No residences match this filter.</p>`;
 $$('.un',bld).forEach(b=>b.onclick=()=>{S.unitSel=b.dataset.u;drawUnits(d)});
 $('#rsv')?.addEventListener('click',()=>reserve(d,sel));$('#reg')?.addEventListener('click',()=>{const m=modal(`<h3>Register interest</h3><p class="muted">We’ll send the ${d.n} brochure, price list and floor plans for residence ${sel.id}.</p><form id="rf" novalidate style="display:grid;gap:10px"><input class="input" id="rn" placeholder="Full name" aria-label="Full name"><input class="input" id="re" type="email" placeholder="Email" aria-label="Email"><p class="err-t" id="rerr" hidden>Please enter your name and a valid email.</p><button class="btn ink lg" type="submit">Send me the brochure</button></form>`);$('#rf',m).onsubmit=e=>{e.preventDefault();if($('#rn').value.trim().length<2||!/^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test($('#re').value.trim())){$('#rerr').hidden=false;return}closeModal();toast('Brochure on its way (demo)','mail')}});
 $('#unrsv')?.addEventListener('click',()=>{ls('reserved',(ls('reserved')||[]).filter(r=>!(r.dev===d.s&&r.u===sel.id)));drawUnits(d);toast('Reservation cancelled')})}
function reserve(d,u){const cur=CITY[d.city].cur;const m=modal(`<span class="lab">${d.n} · Residence ${u.id}</span><h3>Reserve this residence</h3><p class="muted">A fully refundable holding deposit of ${price(u.price*.05,cur)} secures ${u.id} for 14 days while contracts are prepared. Demo only, no payment is taken.</p>
 <form id="rs" novalidate style="display:grid;gap:10px"><div class="two"><input class="input" id="rn" placeholder="Full name" autocomplete="name" aria-label="Full name"><input class="input" id="re" type="email" placeholder="Email" autocomplete="email" aria-label="Email"></div><input class="input" id="rp" type="tel" placeholder="Phone with country code" autocomplete="tel" aria-label="Phone"><label style="display:flex;gap:10px;font-size:14px;color:var(--fg-2)"><input type="checkbox" id="rok" style="accent-color:var(--ember);width:17px;height:17px"> I have read the reservation terms.</label><p class="err-t" id="rerr" hidden></p><button class="btn em lg" type="submit">Confirm reservation</button></form>`);
 $('#rs',m).onsubmit=e=>{e.preventDefault();const v=id=>$('#'+id).value.trim();const bad=v('rn').length<2||!/^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test(v('re'))||v('rp').replace(/\D/g,'').length<8;if(bad||!$('#rok').checked){$('#rerr').hidden=false;$('#rerr').textContent=bad?'Please complete your name, email and phone.':'Please accept the reservation terms.';return}
  const nm=v('rn');const l=ls('reserved')||[];l.push({dev:d.s,u:u.id,n:nm,t:Date.now()});ls('reserved',l);closeModal();drawUnits(d);modal(`<span class="lab">Reservation ${d.s.toUpperCase()}-${u.id}</span><h3>${u.id} is held for you.</h3><p class="muted">Our new-homes team will call ${esc(nm.split(' ')[0])} within one business day to arrange contracts. You can view or cancel this under Saved.</p><a class="btn ink" href="#saved">Go to Saved</a>`)}}
function bindDev(d){drawUnits(d);$$('[data-ub]').forEach(b=>b.onclick=()=>{S.bedsF=+b.dataset.ub;S.unitSel=null;$$('[data-ub]').forEach(x=>x.setAttribute('aria-pressed',x===b));drawUnits(d)})}

/* ---------- SELL / valuation ---------- */
const PPM={syd:{'Elizabeth Bay':27000,'Bronte':24000,'Paddington':17000,'Surry Hills':15000,'Pyrmont':19000,'Mosman':16500},la:{'Hollywood Hills':12000,'Venice':15000,'Malibu':19000,'Silver Lake':10500,'Beverly Crest':11500,'Downtown':8500},lis:{'Chiado':9500,'Cascais':8800,'Restelo':8200,'Parque das Nações':7400,'Avenidas Novas':7000,'Comporta':9000}};
function pageSell(){const v=S.val||{city:'syd',m2:''};return `<section class="wrap ph-h"><div class="crumbs"><a href="#home">Home</a>/<span>Sell</span></div><h1 class="rv">What is your home <em>worth</em>?</h1><p class="rv">An instant estimate from recent sales in your neighbourhood. For an exact figure, book a free appraisal.</p></section>
 <section class="wrap"><div class="two" style="gap:24px;align-items:start"><form class="card" id="vf2" novalidate style="display:grid;gap:14px"><div class="two"><div class="field"><label for="vC">City</label><select class="sel" id="vC">${Object.entries(CITY).map(([k,c])=>`<option value="${k}" ${v.city===k?'selected':''}>${c.n}</option>`).join('')}</select></div><div class="field"><label for="vA">Neighbourhood</label><select class="sel" id="vA"></select></div></div>
  <div class="two"><div class="field"><label for="vT">Type</label><select class="sel" id="vT">${TYPES.map(t=>`<option>${t}</option>`).join('')}</select></div><div class="field"><label for="vM">Interior size (m²)</label><input class="input num" id="vM" inputmode="numeric" value="${v.m2||''}" placeholder="e.g. 180"></div></div>
  <div class="two"><div class="field"><span class="fl">Bedrooms</span><div class="seg full">${[1,2,3,4,5].map(b=>`<button type="button" data-vb="${b}" aria-pressed="${b===3}">${b}${b===5?'+':''}</button>`).join('')}</div></div><div class="field"><span class="fl">Condition</span><div class="seg full">${[['0.92','Needs work'],['1','Good'],['1.1','Renovated']].map((c,i)=>`<button type="button" data-vcn="${c[0]}" aria-pressed="${i===1}">${c[1]}</button>`).join('')}</div></div></div>
  <div class="field"><span class="fl">Views</span><div class="seg full">${[['1','None'],['1.06','Partial'],['1.15','Water']].map((c,i)=>`<button type="button" data-vv="${c[0]}" aria-pressed="${i===0}">${c[1]}</button>`).join('')}</div></div><p class="err-t" id="vErr" hidden>Enter a size between 30 and 2,000 m².</p><button class="btn ink lg" type="submit">Estimate my home</button></form><div id="vOut"><div class="est"><span class="lab" style="color:#B9B0A3">Your estimate</span><div class="rng" style="color:#6E6A63">—</div><p style="color:#B9B0A3">Fill in the form to see a range based on comparable homes.</p></div></div></div></section>`}
function bindSell(){let bd=3,cn=1,vw=1;const areas=()=>{$('#vA').innerHTML=Object.keys(CITY[$('#vC').value].areas).map(a=>`<option>${a}</option>`).join('')};areas();$('#vC').onchange=areas;
 const seg=(sel,set)=>$$(sel).forEach(b=>b.onclick=()=>{$$(sel).forEach(x=>x.setAttribute('aria-pressed',x===b));set(b)});seg('[data-vb]',b=>bd=+b.dataset.vb);seg('[data-vcn]',b=>cn=+b.dataset.vcn);seg('[data-vv]',b=>vw=+b.dataset.vv);
 const run=()=>{const m=+$('#vM').value;if(!(m>=30&&m<=2000)){$('#vErr').hidden=false;$('#vM').classList.add('err');return}$('#vErr').hidden=true;$('#vM').classList.remove('err');const c=$('#vC').value,a=$('#vA').value,t=$('#vT').value;const tf={House:1.05,Villa:1.15,Apartment:.95,Penthouse:1.2}[t];const mid=PPM[c][a]*m*tf*cn*vw*(1+(bd-3)*.02);const lo=mid*.92,hi=mid*1.08,cur=CITY[c].cur;
  const comps=L.filter(p=>p.city===c&&p.st!=='rent').sort((x,y)=>Math.abs(x.m2-m)-Math.abs(y.m2-m)).slice(0,3);
  $('#vOut').innerHTML=`<div class="est" style="animation:rise .5s var(--ease)"><span class="lab" style="color:#B9B0A3">Estimated value · ${esc(a)}</span><div class="rng num">${price(lo,cur,{compact:1})} – ${price(hi,cur,{compact:1})}</div><div class="bar"><i style="left:50%"></i></div><p style="color:#C9C1B5;font-size:14px">Mid-point ${price(mid,cur)} · about ${price(PPM[c][a]*tf*cn*vw,cur)} per m². Based on demo comparables; an agent appraisal will refine it.</p><button class="btn em" id="bkA">Book a free appraisal</button></div>
  <h3 style="font-size:24px;margin:24px 0 12px">Comparable homes</h3><div style="display:grid;gap:8px">${comps.map(p=>`<a class="rowi" href="#p-${p.id}" style="text-decoration:none">${ph(p.img[0],p.t)}<div class="g"><b>${esc(p.t)}</b><span class="muted" style="font-size:13px">${p.m2} m² · ${pLabel(p)} · ${price(p.price/p.m2,p.cur)}/m²</span></div></a>`).join('')}</div>`;
  $('#bkA').onclick=()=>{const a2=AG.filter(x=>x.city===c);const md=modal(`<h3>Book a free appraisal</h3><p class="muted">A local agent will visit, measure and give you a written appraisal within 48 hours.</p><form id="af" novalidate style="display:grid;gap:10px"><select class="sel" id="aa" aria-label="Agent">${a2.map(x=>`<option value="${x.id}">${x.n} · ${x.r}</option>`).join('')}</select><input class="input" id="an" placeholder="Full name" aria-label="Full name"><input class="input" id="ae" type="email" placeholder="Email" aria-label="Email"><input class="input" id="aad" placeholder="Property address" aria-label="Property address"><p class="err-t" id="aerr" hidden>Please complete all fields with a valid email.</p><button class="btn em lg" type="submit">Request appraisal</button></form>`);$('#af',md).onsubmit=e=>{e.preventDefault();if($('#an').value.trim().length<2||!/^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test($('#ae').value.trim())||$('#aad').value.trim().length<6){$('#aerr').hidden=false;return}closeModal();toast(`${ag($('#aa').value)?.n||'Your agent'} will be in touch (demo)`,'phone')}}};
 $('#vf2').onsubmit=e=>{e.preventDefault();run()};if(S.val){run();S.val=null}}

/* ---------- AGENTS & SAVED ---------- */
function pageAgents(){return `<section class="wrap ph-h"><div class="crumbs"><a href="#home">Home</a>/<span>Agents</span></div><h1 class="rv">Our <em>agents</em></h1><p class="rv">Local specialists in Sydney, Los Angeles and Lisbon.</p><div class="chips" style="margin-top:22px">${[['all','All cities'],...Object.entries(CITY).map(([k,c])=>[k,c.n])].map((c,i)=>`<button class="chip" type="button" data-ac="${c[0]}" aria-pressed="${!i}">${c[1]}</button>`).join('')}</div></section><section class="wrap"><div class="ag" id="agG">${AG.map(agCard).join('')}</div></section>`}
function bindAgentsPage(){bindAgents();$$('[data-ac]').forEach(b=>b.onclick=()=>{$$('[data-ac]').forEach(x=>x.setAttribute('aria-pressed',x===b));$('#agG').innerHTML=AG.filter(a=>b.dataset.ac==='all'||a.city===b.dataset.ac).map(agCard).join('');bindAgents($('#agG'))})}
function pageSaved(){return `<section class="wrap ph-h"><div class="crumbs"><a href="#home">Home</a>/<span>Saved</span></div><h1 class="rv">Saved</h1><p class="rv">Favourites, searches, viewings and reservations are kept in this browser.</p><div class="chips" style="margin-top:22px">${[['fav','Favourites'],['srch','Searches'],['vw','Viewings'],['rsv','Reservations']].map((t,i)=>`<button class="chip" type="button" data-st="${t[0]}" aria-pressed="${(S.stab||'fav')===t[0]}">${t[1]}</button>`).join('')}</div></section><section class="wrap" id="svB"></section>`}
function drawSaved(){const t=S.stab||'fav',el=$('#svB');
 if(t==='fav'){const l=[...S.fav].map(lst).filter(Boolean);el.innerHTML=l.length?`<div class="lgrid">${l.map(card).join('')}</div>`:`<div class="empty"><h3 style="font-size:28px">No favourites yet</h3><p class="muted" style="margin:8px 0 16px">Tap the heart on any home to save it here.</p><a class="btn ink" href="#buy">Browse homes</a></div>`;bindCards(el)}
 if(t==='srch'){const l=ls('searches')||[];el.innerHTML=l.length?`<div style="display:grid;gap:8px">${l.map(s=>`<div class="rowi"><div class="g"><b>${esc(s.d)}</b><span class="muted" style="font-size:13px">${filtered(s.f).length} homes now · saved ${new Date(s.id).toLocaleDateString('en-US',{month:'short',day:'numeric'})}</span></div><button class="btn ink sm" data-ss="${s.id}">Run search</button><button class="btn lt sm" data-sx="${s.id}">Delete</button></div>`).join('')}</div>`:`<div class="empty"><h3 style="font-size:28px">No saved searches</h3><p class="muted" style="margin:8px 0 16px">Use “Save search” on the listings page to get alerts.</p><a class="btn ink" href="#buy">Start a search</a></div>`;
  $$('[data-ss]',el).forEach(b=>b.onclick=()=>{const s=l.find(x=>x.id==b.dataset.ss);S.f={...s.f};S.keepF=1;location.hash=s.f.mode==='rent'?'rent':s.f.mode==='new'?'new':'buy'});$$('[data-sx]',el).forEach(b=>b.onclick=()=>{ls('searches',l.filter(x=>x.id!=b.dataset.sx));drawSaved()})}
 if(t==='vw'){const l=(ls('viewings')||[]).sort((a,b)=>(a.d+a.t).localeCompare(b.d+b.t));el.innerHTML=l.length?`<div style="display:grid;gap:8px">${l.map(v=>{const p=lst(v.pid);return `<div class="rowi">${ph(p.img[0])}<div class="g"><b>${esc(p.t)}</b><span class="muted" style="font-size:13px">${fmtD(v.d,{weekday:'long',month:'short',day:'numeric'})} · ${v.t} · ${v.mode==='video'?'Live video':'In person'} · ${v.id}</span></div><a class="btn lt sm" href="#p-${p.id}">View home</a><button class="btn lt sm" data-vx="${v.id}" style="color:var(--bad)">Cancel</button></div>`}).join('')}</div>`:`<div class="empty"><h3 style="font-size:28px">No viewings booked</h3><p class="muted" style="margin:8px 0 16px">Book from any listing page.</p><a class="btn ink" href="#buy">Find a home</a></div>`;
  $$('[data-vx]',el).forEach(b=>b.onclick=()=>{ls('viewings',(ls('viewings')||[]).filter(x=>x.id!==b.dataset.vx));drawSaved();toast('Viewing cancelled')})}
 if(t==='rsv'){const l=ls('reserved')||[];el.innerHTML=l.length?`<div style="display:grid;gap:8px">${l.map(r=>{const d=dev(r.dev);const u=units(d).find(x=>x.id===r.u);return `<div class="rowi">${ph(d.img[0])}<div class="g"><b>${d.n} · ${r.u}</b><span class="muted" style="font-size:13px">${u.bd} bed · ${u.m2} m² · ${price(u.price,CITY[d.city].cur)} · held 14 days from ${new Date(r.t).toLocaleDateString('en-US',{month:'short',day:'numeric'})}</span></div><a class="btn lt sm" href="#dev-${d.s}">View</a><button class="btn lt sm" data-rx="${r.dev}|${r.u}" style="color:var(--bad)">Cancel</button></div>`}).join('')}</div>`:`<div class="empty"><h3 style="font-size:28px">No reservations</h3><p class="muted" style="margin:8px 0 16px">Reserve a residence in one of our developments.</p><a class="btn ink" href="#new">New developments</a></div>`;
  $$('[data-rx]',el).forEach(b=>b.onclick=()=>{const [dv,u]=b.dataset.rx.split('|');ls('reserved',(ls('reserved')||[]).filter(r=>!(r.dev===dv&&r.u===u)));drawSaved();toast('Reservation cancelled')})}}
function bindSaved(){$$('[data-st]').forEach(b=>b.onclick=()=>{S.stab=b.dataset.st;$$('[data-st]').forEach(x=>x.setAttribute('aria-pressed',x===b));drawSaved()});drawSaved()}

/* ---------- motion ---------- */
let io;
function initReveal(){io?.disconnect();io=new IntersectionObserver(es=>es.forEach(e=>{if(!e.isIntersecting)return;const t=e.target;t.classList.add('in');io.unobserve(t);$$('[data-count]',t).forEach(countUp);$$('.lines',t).forEach(x=>x.classList.add('in'))}),{threshold:.12,rootMargin:'0px 0px -6% 0px'});$$('.rv,.lines').forEach(el=>RM?(el.classList.add('in'),$$('[data-count]',el).forEach(x=>countUp(x,1))):io.observe(el))}
function countUp(el,now){if(el.dataset.done)return;el.dataset.done=1;const to=+el.dataset.count,dec=+el.dataset.dec||0,pre=el.dataset.pre||'';const f=v=>pre+(dec?v.toFixed(dec):Math.round(v));if(now||RM){el.textContent=f(to);return}const t0=performance.now();const s=t=>{const p=Math.min(1,(t-t0)/1500);el.textContent=f(to*(1-Math.pow(1-p,4)));if(p<1)requestAnimationFrame(s)};requestAnimationFrame(s)}
let tick=false;
function frame(){tick=false;const y=scrollY,vh=innerHeight;const nav=$('#nav');nav?.classList.toggle('small',y>60);if(RM)return;
 const hi=$('#heroImg');if(hi&&innerWidth>980){const p=clamp(y/(vh*.7),0,1);hi.style.transform=`scale(${1-p*.08})`;hi.style.borderRadius=`${p*40}px`;hi.style.inset=`${p*14}px`;$$('.fcard').forEach(c=>c.style.translate=`0 ${(-y*(+c.dataset.par||0)).toFixed(1)}px`);const w=$('.wordmark');if(w)w.style.transform=`translateY(${-p*40}px)`}
 $$('.jr-card[data-par]').forEach(c=>{const r=c.parentElement.getBoundingClientRect();c.style.translate=`0 ${((r.top+r.height/2-vh/2)*+c.dataset.par).toFixed(1)}px`});
 const pj=$('#pj');if(pj&&innerWidth>900){const r=pj.getBoundingClientRect(),p=clamp(-r.top/(pj.offsetHeight-vh),0,1);const i=Math.min(DEV.length-1,Math.floor(p*DEV.length*.999));$('#pjBar').style.transform=`scaleX(${p})`;$('#pjBar').style.width='100%';
  if(S.pjI!==i){S.pjI=i;$$('[data-pjt]').forEach(t=>{const k=+t.dataset.pjt;t.className='t '+(k===i?'':k<i?'out':'nx')});$$('[data-pji]').forEach(t=>t.classList.toggle('out',+t.dataset.pji!==i));$$('[data-pjd]').forEach(t=>t.innerHTML=+t.dataset.pjd===i?`<b>(${i+1})</b>`:`(${+t.dataset.pjd+1})`);$('#pjD').textContent=DEV[i].d;$('#pjA').textContent='Explore '+DEV[i].n;$('#pjA').href='#dev-'+DEV[i].s}
  $$('[data-pji]').forEach(t=>{if(+t.dataset.pji===i){const j=[...t.classList].find(c=>/^i\d$/.test(c));const lp=(p*DEV.length)%1;t.style.transform=`translateY(${(lp-.5)*(j==='i2'?-40:j==='i1'?60:30)}px)`}})}}
addEventListener('scroll',()=>{if(!tick){tick=true;requestAnimationFrame(frame)}},{passive:true});
addEventListener('resize',()=>{sizePj();frame()});
function sizePj(){const pj=$('#pj');if(pj)pj.style.height=innerWidth>900?`${(DEV.length+.6)*100}vh`:''}

/* ---------- router ---------- */
function route(){const h=(location.hash||'#home').slice(1)||'home';closeModal();$('#mm')?.classList.remove('open');if(['explore','featured'].includes(h)){if(S.page!=='home')render('home');document.getElementById(h)?.scrollIntoView({behavior:'smooth'});return}render(h);scrollTo(0,0)}
function render(h,keep){S.timers.forEach(clearInterval);S.timers=[];S.pjI=null;if(!keep)S.vw=null;
 let body,bind,cur=h;
 if(['buy','rent','new'].includes(h)){if(keep)S.keepF=1;body=pageList(h);bind=bindList}
 else if(h.startsWith('p-')&&lst(h.slice(2))){const p=lst(h.slice(2));body=pageProp(p);bind=()=>bindProp(p);cur=p.st==='rent'?'rent':p.st==='offplan'?'new':'buy'}
 else if(h.startsWith('dev-')&&dev(h.slice(4))){const d=dev(h.slice(4));if(!keep){S.unitSel=null;S.bedsF=0}body=pageDev(d);bind=()=>bindDev(d);cur='new'}
 else if(h==='sell'){body=pageSell();bind=bindSell}
 else if(h==='agents'){body=pageAgents();bind=bindAgentsPage}
 else if(h==='saved'){body=pageSaved();bind=bindSaved}
 else{h='home';cur='home';body=pageHome();bind=bindHome}
 S.page=h;document.title=({buy:'Homes for sale',rent:'Homes to rent',new:'New developments',sell:'Valuation',agents:'Agents',saved:'Saved'}[h]||(h.startsWith('p-')?lst(h.slice(2)).t:h.startsWith('dev-')?dev(h.slice(4)).n:''))+(h==='home'?'Aurelle Estates · Homes, Residences & Developments':' · Aurelle Estates');
 mount(cur,body);bind&&bind();bindAgents($('#main'));drawTray();sizePj();initReveal();frame()}
addEventListener('hashchange',route);
document.addEventListener('click',e=>{const a=e.target.closest('a[href^="#"]');if(!a)return;if(location.hash===a.getAttribute('href')){e.preventDefault();route()}});
route();
})();
